### ISSUE TITLE
命令创建实体工具产生多余空字符串

### ISSUE THREAD

**Issue by xemxx** [swoft-cloud/swoft#100]
![image](https://user-images.githubusercontent.com/26523062/35817110-76bb7366-0ad7-11e8-89a6-f9118fda0937.png)
简单的数据表结构
然后产生
![image](https://user-images.githubusercontent.com/26523062/35817186-adf1251a-0ad7-11e8-8c8b-bb7741e4e884.png)
这样的一些空字符串
数据库是
![image](https://user-images.githubusercontent.com/26523062/35817226-c64b2b9c-0ad7-11e8-9cd5-3c62cbde9bc6.png)

**Comment by whiteCcinn** [comment]
@xemxx component-分支已经解决
