### ISSUE TITLE
模型获取别名失败

### ISSUE THREAD

**Issue by ctfang** [swoft-cloud/swoft#1000]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | 2.0.6
| Swoole version      | 4.4.5
| PHP version         | 7.3.8
| Runtime environment | Mac

**Describe the bug**
~~~~
        $data['list'] = mode::where(['use' => 1])->orderBy('order', 'desc')->get(['id', 'use as open']);
~~~~
list数据缺失  open 字段

把mode换成查询器正常

**Comment by sakuraovq** [comment]
不要使用 select 别名 使用  模型的 prop  属性就好 不然无法匹配注解字段
