### ISSUE TITLE
升级到v2.0.6后 ws服务总是会自动将请求返回

### ISSUE THREAD

**Issue by cirvor** [swoft-cloud/swoft#1002]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | v2.0.6
| Swoole version      | 4.4.5
| PHP version         | 7.2.22
| Runtime environment | Mac

```
发送消息 13:34:38

{
  "cmd":"home.ping",
  "data":"he",
  "ext":[
    1,
    2,
    3
  ]
}

收到消息 13:34:38

{
  "status":200,
  "event":"PING",
  "data":"PONG"
}

收到消息 13:34:38

{
  "cmd":"home.ping",
  "data":null,
  "ext":[
  ]
}
```
第二个返回消息是框架自动返回的
且返回的请求数据中 data与ext的值都为空 说明获取到的请求数据并不完整
已回滚到2.0.5 一切正常
服务使用了使用了WsModule
请问有关闭的方法嘛?谢谢

**Comment by cirvor** [comment]
swoft/websocket-server/src/WsMessageDispatcher.php 这个文件

```
// Do send response
$response->send();
```
把这个注释掉就不会自动返回了

**Comment by inhere** [comment]
@cirvor  你在message action 里怎么响应消息的呢？

**Comment by cirvor** [comment]
@inhere 
```
public function ping(): void
{
   Session::mustGet()->push(json_encode([
       'status' => 200,
       'event' => 'PING',
       'data' => 'PONG',
   ]));
}
```

**Comment by inhere** [comment]
@cirvor 谢谢。 

v2.0.6 有这个问题，响应时没有过滤空值。下个版本修复。

你在后面再加一句，防止再自动响应一次可以解决：

```php
context()->getResponse()->setSent(true);
```

**Comment by cirvor** [comment]
@inhere 
好的 不客气呢

**Comment by inhere** [comment]
也可以这样替代现在的使用，就没问题：

```php
return context()->getResponse()->setContent(json_encode([
       'status' => 200,
       'event' => 'PING',
       'data' => 'PONG',
   ]));
```

**Comment by luckart** [comment]
我说怎么会出现错误，老铁搞死我了。

**Comment by landyXU** [comment]
mark
