### ISSUE TITLE
服务注册不成功

### ISSUE THREAD

**Issue by gitwanzx** [swoft-cloud/swoft#1003]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.5-beta
| Swoole version      | 4.4.5
| PHP version         | 7.2.22
| Runtime environment | Ubuntu18.04

**Describe the bug**
根据文档配置好bean.php，监听了SwooleEvent::START事件，但在启动http服务时，服务注册不上consul，有报错。

**Screenshots**
![image](https://user-images.githubusercontent.com/37397718/65568234-9c76f280-df8b-11e9-8d3e-3c2cc0c8e74c.png)

**Details**

> app/bean.php 

```php
'consul' => [
        'host' => '192.168.0.156',
        'port' => 18306
]
```

> App\Listener\ProvinceServiceListener.php

```php
$scheduler = new Scheduler();
$scheduler->add(function () use ($service) {
        $this->agent->registerService($service);
        CLog::info('Swoft http register service success by consul!');
});
$scheduler->start();
```

**Comment by stelin** [comment]
@gitwanzx 你直接写业务，文档已经更新

 $this->agent->registerService($service);
        CLog::info('Swoft http register service success by consul!');

框架底层已经开启Scheduler

**Comment by gitwanzx** [comment]
@stelin 您好，感谢您的回复。

我把代码换成了文档上面的了，如下：
![image](https://user-images.githubusercontent.com/37397718/65649941-321d8b00-e03b-11e9-9ff6-f748260332e1.png)

但是在启动http服务的时候还有错误：
![image](https://user-images.githubusercontent.com/37397718/65649983-61cc9300-e03b-11e9-8b71-7e23fc990499.png)

这个问题该如何解决呢，望赐教，万分感谢！

**Comment by stelin** [comment]
你搞错了，你访问 consul, 怎么访问到 swoft 里面来了，你这里要配置 consul 服务信息

```php
return [
    // ...
    'consul' => [
        'host' => '192.168.4.11'
    ]

    // ...
];
```

**Comment by gitwanzx** [comment]
@stelin 我在app/bean.php配置了

`'consul' => [
        'host' => '192.168.0.156',
    ]`

但是，还是有以下报错：
![image](https://user-images.githubusercontent.com/37397718/65666091-86daf900-e06f-11e9-917c-8f0cb0bff024.png)

我的consul是已经开启了，我用go是可以注册进去的，但是用swoft就不行。
![image](https://user-images.githubusercontent.com/37397718/65665974-47141180-e06f-11e9-8da9-7d8d8cbfdce6.png)
