### ISSUE TITLE
Pool error is Channel consumer is full

### ISSUE THREAD

**Issue by ChangeChe** [swoft-cloud/swoft#1007]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.5
| Swoole version      | 4.4.6
| PHP version         | 7.2.21
| Runtime environment | Docker

**Describe the bug**
在高并发的情况下，使用redis连接池会报Pool error is Channel consumer is full错误。
不知道maxActive/maxWait的大小关系会不会有影响

**配置信息**
```
'redis.pool'      => [
        'class'       => \Swoft\Redis\Pool::class,
        'redisDb'     => bean('redis'),
        'minActive'   => 5,
        'maxActive'   => 10,
        'maxWait'     => 10,
        'maxWaitTime' => 0,
        'maxIdleTime' => 60,
    ],
```
**Details**
错误是在`Swoft\Connection\Pool\AbstractPool->getConnectionByChannel`方法里提示的，打印了下基本信息`$this->channel->isEmpty()`是`false`, 但是`$this->channel->stats()`里的`consumer_num`跟`maxWait`相等。

**Comment by ChangeChe** [comment]
将`maxWaitTime`设置为有意义的值可以防止这个异常的出现，但是本质的原因还没找到。

**Comment by stelin** [comment]
```
if ($this->maxWait > 0 && $stats['consumer_num'] >= $this->maxWait) {
            throw new ConnectionPoolException(
                sprintf('Channel consumer is full, maxActive=%d, maxWait=%d, currentCount=%d',
                    $this->maxActive, $this->maxWaitTime, $this->count)
            );
        }
```

最大的等待数已经到上线了，你可以多开最大等待数
