### ISSUE TITLE
Timer after error！Pool error is Call to undefined method Swoft\Context\TimerAfterContext::getRequest()

### ISSUE THREAD

**Issue by hanks2017** [swoft-cloud/swoft#1008]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       |v2.0.6
| Swoole version      |4.4.4 (by `php --ri swoole`)
| PHP version         | PHP 7.3.8(by `php -v`)
| Runtime environment | Docker etc.

**Describe the bug**
Timer after error！Pool error is Call to undefined method Swoft\Context\TimerAfterContext::getRequest()

**Expected behavior**
能够正常执行mysql数据库操作.

**Screenshots**

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// php7.2
```
2019/09/26-18:31:23 [ERROR] Timer after error！Pool error is Call to undefined method Swoft\Context\TimerAfterContext::getRequest() file=/www/zhongleApi/app/Common/DbSelector.php line=31 /www/zhongleApi/vendor/swoft/db/src/DB.php 81

**Comment by inhere** [comment]
提bug时，请附带上关键的操作使用步骤。能有触发错误的相关代码最好。

**Comment by stelin** [comment]
贴出使用代码，不是没法查问题

**Comment by hanks2017** [comment]
$delay = 15000;
                \Swoft\Timer::after($delay, function ($key, $id, $field) {
                    //获取最新数据
                    $num = $this->redis->get($key);var_dump(333333,$num);
                    //更新数据库

                    $app = AppInfos::where('id',$id)->first();var_dump($id,$field,$app);

                    //$this->appInfosDao->changeNumber($id, $field, (int)$num);
                    //删除此键
                    //$this->redis->del($key);
                    RequestContext::destroy();
                }, $key, $id, $field);

以上是我执行代码报错的部分

**Comment by stelin** [comment]
你把这个文件删除掉，这是一个测试文件 /www/zhongleApi/app/Common/DbSelector.php，删除就好了
