### ISSUE TITLE
RPC 服务有授权功能吗？

### ISSUE THREAD

**Issue by xskit** [swoft-cloud/swoft#1009]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Expected behavior**
希望可以设置授权功能，例如：

```php
// IP 客户端限制
$server->allowHosts(['192.168.0.1', '127.0.0.1']);

// 允许的用户列表
$server->authentication(['user1' => 'password1', 'user2' => 'password2']);

```

**Comment by inhere** [comment]
@xskit  你可以接 rpc server 的 connect 事件，自己拦截下。

**Comment by stelin** [comment]
你可以通过RPC扩展信息传递授权信息，RPC server 使用一个全局中间件，验证权限

**Comment by xskit** [comment]
好的，谢谢
