### ISSUE TITLE
查询器使用value('字段名称')不返回该字段值

### ISSUE THREAD

**Issue by etoup** [swoft-cloud/swoft#1012]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.6
| Swoole version      | 4.4.7
| PHP version         | 7.2.22
| Runtime environment | Ubuntu.

**Describe the bug**
使用查询构造器方法value('字段名称')不是返回该字段值， 而是返回数量1

**Expected behavior**
返回该字段的值

**Details**

> 该ratio字段在数据库中的值是70.0

```php
$ratio = UsersShops::where('user_id', $pid)->value('ratio');
```

**Comment by sakuraovq** [comment]
@etoup  建议看看执行的 sql 喔 我这边是没问题的

**Comment by etoup** [comment]
@sakuraovq 你好！数据库ratio字段类型是decimal，不是varchar等其他类型，我想是不是字段类型的区别导致的

**Comment by sakuraovq** [comment]
@etoup  实体 @var 类型是 float 还是 int 呢

**Comment by sakuraovq** [comment]
用 查询构造器试试

**Comment by sakuraovq** [comment]
value 不行 find 看看结果对不
