### ISSUE TITLE
不能设置下载文件名

### ISSUE THREAD

**Issue by ctfang** [swoft-cloud/swoft#1015]
swoft 2.0.6
使用file（）后无效

`
        return $response->withHeader('Content-Disposition',
            "attachment; filename={$fileName}")->file($path, "application/octet-stream");
`

有效

`        return Context::get()
            ->getResponse()
            ->withContent($json)
            ->withHeader('Content-Type', "application/octet-stream")
            ->withHeader('Content-Disposition', 'attachment; filename=admin-api.json');
`

**Comment by xt1234** [comment]
return Context::get() ->getResponse() ->withContent($json) ->withHeader('Content-Type', "application/octet-stream") ->withHeader('Content-Disposition', 'attachment; filename=admin-api.json');这样设置也无效
