### ISSUE TITLE
http-server testing  MockRequest 不支持 PUT 方法

### ISSUE THREAD

**Issue by cfcvalentine** [swoft-cloud/swoft#1018]
SwoftTest\Http\Server\Testing\MockRequest::new  没有支持PUT 参数

 if ($server['request_method'] === self::POST) {
            $instance->post = $params;
        }

**Comment by stelin** [comment]
感谢反馈，我们新增支持下

**Comment by stelin** [comment]
已修复， 2.0.7 发布

**Comment by stelin** [comment]
已经发布2.0.7，请更新
