### ISSUE TITLE
SwoftTest\Http\Server\Testing\MockResponse ::getHeader 有误

### ISSUE THREAD

**Issue by cfcvalentine** [swoft-cloud/swoft#1019]
SwoftTest\Http\Server\Testing\MockResponse ::getHeader 有误

应为 SwoftTest\Http\Server\Testing\MockResponse ::getHeader($key)

**Comment by stelin** [comment]
感谢反馈，我们调整下

**Comment by stelin** [comment]
已修复，2.0.7 发布

**Comment by stelin** [comment]
已经发布2.0.7，请更新
