### ISSUE TITLE
SwoftTest\Http\Server\Testing\MockResponse::cookie 方法少了一个参数

### ISSUE THREAD

**Issue by cfcvalentine** [swoft-cloud/swoft#1020]
SwoftTest\Http\Server\Testing\MockResponse::cookie 方法与 Swoole\Http\Response 比少了$samesite 参数

会提示

[PHP Warning:  Declaration of AppTest\Testing\MockResponse::cookie($name, $value = NULL, $expires = NULL, $path = NULL, $domain = NULL, $secure = NULL, $httpOnly = NULL) should be compatible with Swoole\Http\Response::cookie($name, $value = NULL, $expires = NULL, $path = NULL, $domain = NULL, $secure = NULL, $httponly = NULL, $samesite = NULL) in testing/MockResponse.php on line 14]

**Comment by stelin** [comment]
感谢反馈，这是swoole 版本升级导致的，我们兼容下

**Comment by stelin** [comment]
已修复， 2.0.7 发布

**Comment by stelin** [comment]
已经发布2.0.7，请更新
