### ISSUE TITLE
日志按时间切割，不会自动切割产生新档案

### ISSUE THREAD

**Issue by andiechang** [swoft-cloud/swoft#1021]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.6
| Swoole version      | 4.4.1 (by `php --ri swoole`)
| PHP version         | 7.2.10 (by `php -v`)
| Runtime environment | Docker

**Describe the bug**
* 在 bean.php 已经设置日志按时间切割，但实际上档案不会自动产生，必须将 swoft restart 后才会产生新的档案。
```php
'noticeHandler'      => [
        'class'     => FileHandler::class,
        'logFile'   => '@runtime/logs/notice-%d{Y-m-d}.log',
        'formatter' => \bean('lineFormatter'),
        'levels'    => 'notice,info,debug,trace',
    ],
```

**Expected behavior**
* 预期设置按时间切割后，会依照时间设置，自动切割档案。
* 例如上述的设置，预期是每天会产生新档案。

**Screenshots**
![image](https://user-images.githubusercontent.com/7233960/66251047-d9a66600-e77d-11e9-9a2a-86b66f4535bc.png)

**Details**
> Describe what you are trying to achieve and what goes wrong.

从上图可以看到，日志档名跟最后写入的时间。
例如：
档案 `notice-2019-09-23.log` ，最后写入时间是 Sep 27 13:59
也就是 log 档案会一直写到 swoft restart ，才会产生下一个档案。
所以下一个档案是 `notice-2019-09-27.log`

**Comment by stelin** [comment]
不会存在你说的问题吧

**Comment by andiechang** [comment]
我有启动定时任务，不知道是否有关，notice log 会一直写入，目前实际的情况，就如上所述，会用同一个档案一直写，不会产生新档案。
附上最新截图
![image](https://user-images.githubusercontent.com/7233960/66363266-49a03080-e9b8-11e9-8521-213dd0098bfd.png)
二分钟后
![image](https://user-images.githubusercontent.com/7233960/66363298-62104b00-e9b8-11e9-80fb-963fa57668cf.png)

**Comment by zfArthur** [comment]
我也遇到了同样的问题，不能按天进行日志切割，日志现在都堆到重启服务的那天了，都不能每天对日志进行压缩处理了.

**Comment by stelin** [comment]
嗯嗯，我复现下，

**Comment by stelin** [comment]
已修复， 2.0.7 发布

**Comment by stelin** [comment]
已经发布2.0.7，请更新
