### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by buzheng95** [swoft-cloud/swoft#1023]
按照官方文档，版本2.x的教程安装，手动安装，composer install提示：
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package swoft/process ~2.0.0 exists as swoft/process[v1.0.4, v1.0.1, v1.0.0, dev-master, v1.0.2, 1.x-dev, v1.0.3, dev-bak] but these are rejected by your constraint.
  Problem 2
    - The requested package swoft/crontab could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

直接composer安装提示：
 [RuntimeException]                                                                                                                               
  Could not scan for classes inside "/home/mzcc/web/learn-note/swoft/vendor/swoft/framework/src/Swoft.php" which does not appear to be a file nor a folder

**Comment by buzheng95** [comment]
composer 镜像 ： https://mirrors.huaweicloud.com/repository/php/

**Comment by inhere** [comment]
不要使用华为的镜像源，有问题很多包都没有更新或者漏文件

**Comment by tqrj** [comment]
我就想弄个目录挂载各种报错，唉 网上所谓的教程在最新的版本完全不行

**Comment by inhere** [comment]
@tqrj  贴一下如何使安装用的
