### ISSUE TITLE
rpc 服务没有请求时的初始化方法

### ISSUE THREAD

**Issue by xskit** [swoft-cloud/swoft#1025]
| Q                   | A
| ------------------- | -----
| Feature request?    | yes
| Swoft version       | 2.0.6
| Swoole version      | 4.4.7-alpha
| PHP version         | 7.2
| Runtime environment | Ubuntu

**Details**

> RPC 服务端 `@Service()` ,每次请求时好像没有公共初始化处理方法，比如我想初始化获取一些自定义的Bean::REQUEST类型的实例
> init() 方法只会在程序启动时调用一次

**Comment by stelin** [comment]
Bean::REQUEST 不需要你初始化，你直接使用请求级别bean, rpc 请求完成，会自动回收的。这样REQUEST 基本 bean init 方法可以做你想做的事情

**Comment by xskit** [comment]
我不是想初始化 Bean::REQUEST ，我是想在每个请求时rpc Service 有个当前请求的初始化方法

**Comment by xskit** [comment]
在当前Service 接口类中有个初始化方法，为供接口中的方法初始化一些公共属性

**Comment by inhere** [comment]
可以监听 `ServiceServerEvent::BEFORE_RECEIVE` 事件。它会在每次收到消息时触发
