### ISSUE TITLE
模型分页 paginate 使用别名后，data没有别名字段的数据

### ISSUE THREAD

**Issue by ctfang** [swoft-cloud/swoft#1027]
模型分页 paginate 使用别名后，data没有别名字段的数据

打印sql正常

2.0.6

**Comment by sakuraovq** [comment]
提供下链式操作 提问需要贴出代码和 可复现操作~

**Comment by ctfang** [comment]
错误的
Model::where(['use' => Used::open])->orderBy('order', 'desc')->paginate($page, $pageNum,
            ['id', 'name', 'thumbnail', 'an_sore as sore', 'an-ma5 as md5', 'limit', 'title']);

使用DB后正常

DB::table('test')->where(['use' => Used::open])->orderBy('order', 'desc')->paginate($page, $pageNum,
            ['id', 'name', 'thumbnail', 'an_sore as sore', 'an-ma5 as md5', 'limit', 'title']);

**Comment by sakuraovq** [comment]
@ctfang  模型返回的只会有 实体定义的字段

**Comment by sakuraovq** [comment]
用了 As 之后就无法匹配实体字段了就会被忽略
