### ISSUE TITLE
redis集群设置prefix无效

### ISSUE THREAD

**Issue by ZxGame00** [swoft-cloud/swoft#1028]
https://github.com/swoft-cloud/swoft-redis/blob/master/src/Connector/PhpRedisConnector.php

查阅代码发现在实例化RedisCluster之后没有setOption相关的逻辑，按swoft官方文档的配置，prefix配置是放在了每个节点配置元素里面，这样设置应该是无效的。建议把prefix放在option里面，在RedisCluster实例化后补充设置逻辑。
```php
public function connectToCluster(array $config, array $option): RedisCluster
{
    ....
    $redisCluster = new RedisCluster($name, $servers, $timeout, $readTimeout, $persistent);
    if (!empty($option['prefix'])) {
        $redisCluster->setOption(Redis::OPT_PREFIX, $option['prefix']);
    }
    ....
}
```

谢谢：）

**Comment by sakuraovq** [comment]
谢谢您的建议, 我们优化下
