### ISSUE TITLE
是否有debug模式？

### ISSUE THREAD

**Issue by lmssky** [swoft-cloud/swoft#103]
开发时更改了代码都需要重启，是否提供开发模式不用每次都重启服务

**Comment by stelin** [comment]
swoft现在支持跨平台热更新，修改app目录下代码，无需重启，自动reload

**Comment by lmssky** [comment]
你好，我已经开启了AUTO_RELOAD，但是更改了app IndexController/index 方法的内容 还是没变化，重启后才有效 是为什么呐

**Comment by lmssky** [comment]
已解决哈，我刚开始swoole是2.0.7  升级到2.1就解决了

**Comment by stelin** [comment]
debug模式正在开发中，这不是一个硬性需求，相对其它稍微晚点才会出来

**Comment by JayenLee** [comment]
热加载是不是没了？还是要配置什么？我这边本地用docker启动，代码更新都没有动静，也没有重新加载
