### ISSUE TITLE
redis-cluster 5.0版本的连接报错

### ISSUE THREAD

**Issue by whistling** [swoft-cloud/swoft#1030]
redis-cluster 官方搭建5.0
bean.php 配置如下
 'redis' => [
        'class'    => RedisDb::class,
        'option'   => [
            'timeout'    => 3,
            'persistent' => true,
        ],
        'clusters' => [
            [
                'host'         => '172.16.0.133',
                'prefix'       => 'swoft-t',
                'read_timeout' => 2,
                'port'         => 6379,
                'database'     => 0,
                'password'     => "******",
            ],
        ]

报错：
Pool error is Create connection error(Couldn't map cluster keyspace using any provided seed) file(/home/vagrant/code/gold-service.2345.com/vendor/swoft/redis/src/Connector/PhpRedisConnector.php) line (74) file=/home/vagrant/code/gold-service.2345.com/vendor/swoft/connection-pool/src/AbstractPool.php line=223 At /home/vagrant/code/gold-service.2345.com/vendor/swoft/redis/src/Redis.php line 158

翻阅代码定位问题：
Swoft\Redis\Connector\PhpRedisConnector.php
 
   public function connectToCluster(array $config, array $option): RedisCluster
    {
        $servers     = array_map([$this, 'buildClusterConnectionString'], $config);
        $servers     = array_values($servers);
        $readTimeout = $option['read_timeout'] ?? 0;
        $timeout     = $option['timeout'] ?? 0;
        $persistent  = $option['persistent'] ?? false;

        $redisCluster = new RedisCluster(null, $servers, $timeout, $readTimeout, $persistent);
        return $redisCluster;
    }

官方 new RedisCluster 会有第六个参数，验证密码

// Connect with cluster using password.
$obj_cluster = new RedisCluster(NULL, Array("host:7000", "host:7001"), 1.5, 1.5, true, "password");

**Comment by sakuraovq** [comment]
好的 我们 2.0.7 优化下 感谢您的建议 ~~
