### ISSUE TITLE
修改Rpc消息协议的结尾符不起作用

### ISSUE THREAD

**Issue by gitwanzx** [swoft-cloud/swoft#1031]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.5-beta
| Swoole version      | 4.4.5
| PHP version         | 7.2.22
| Runtime environment | Ubuntu18.04

**Describe the bug**
rpc默认的结尾是"\r\n\r\n"，我将它改为"\n"，重启服务后，还是照样以"\r\n\r\n"这个结尾来调用服务，在框架外以"\n"调用就会失败，一直转圈圈。

**Screenshots**
![image](https://user-images.githubusercontent.com/37397718/66643200-d49b5800-ec50-11e9-8182-b3f6efe512a8.png)

**Comment by inhere** [comment]
@gitwanzx  找到问题了吗？

**Comment by gitwanzx** [comment]
@inhere 这个是我自己理解错了，这里是客户端，我要在外面调用这个服务在这里配置是没有用的。
'package_eof'  这个配置是没有问题的。另外想问下，如果要改变默认的结尾符要在哪里修改呢，还是说只能修改框架文件了。

**Comment by inhere** [comment]
改 rpc server 的 setting

**Comment by gitwanzx** [comment]
![image](https://user-images.githubusercontent.com/37397718/66822093-235d3080-ef76-11e9-83d8-e24f1e3be192.png)
我这样子改了，行不通啊。
