### ISSUE TITLE
数据库查询selectOne问题

### ISSUE THREAD

**Issue by buzheng95** [swoft-cloud/swoft#1033]
你好，学习过程中，遇到个很奇怪的东西：

$detail = DB::selectOne('select * from `hs_house` where `id`=:house_id', ['house_id' => $id]);

这段代码返回一个数组：

Array
(
    [id] => 3
    [old_id] => 272
    [name] => Renshaw House
    [type_id] => 0
    [company_id] => 28
    [country_id] => 1
    [city_id] => 6
    [address] => 78-82 Renshaw Street
    [house_tag_id] => 17
    [outside_facility_id] => 4
    [postcode] => L1 4EN
    [introduce] => &lt;p&gt;Renshaw House地理位置优越，在四季轩楼上，步行至利物浦大学约10分钟左右，楼下就是四季轩川菜馆，旁边有Tesco和Sainsbury's超市，思达中国超市。距离市中心，火车站步行5分钟。&lt;/p&gt;&lt;p&gt;房间里设施齐全，全新装修，每个房间都配备独立卫浴、WiFi和宽带等。公寓还贴心提供了床褥。可以选择由四季轩提供的学生饭堂式服务优惠，两餐无忧，一站式服务，在家的享受。&lt;/p&gt;&lt;p&gt;&lt;br&gt;&lt;/p&gt;&lt;p&gt;*公寓的起租日期一般为月初的1号或者15号，比较灵活。&lt;br&gt;&lt;/p&gt;
    [lng] => -2.976588487625122
    [lat] => 53.4029541015625
    [status] => 0
    [create_time] => 2018-02-08 15:02:22
    [update_time] => 2019-03-29 10:13:20
    [is_hot] => 0
    [sort] => 0
    [is_empty] => 1
    [min_effect_price] => 115
    [min_origin_price] => 0
    [is_vip] => 0
    [is_sale] => 1
)

但是，如果切换数据库链接：

$detail = DB::query('test_db.pool')->getConnection()->selectOne('select * from `hs_house` where `id`=:house_id', ['house_id' => $id]);

返回的就是stdClass object：

stdClass Object
(
    [id] => 3
    [old_id] => 272
    [name] => Renshaw House
    [type_id] => 0
    [company_id] => 28
    [country_id] => 1
    [city_id] => 6
    [address] => 78-82 Renshaw Street
    [house_tag_id] => 17
    [outside_facility_id] => 4
    [postcode] => L1 4EN
    [introduce] => &lt;p&gt;Renshaw House地理位置优越，在四季轩楼上，步行至利物浦大学约10分钟左右，楼下就是四季轩川菜馆，旁边有Tesco和Sainsbury's超市，思达中国超市。距离市中心，火车站步行5分钟。&lt;/p&gt;&lt;p&gt;房间里设施齐全，全新装修，每个房间都配备独立卫浴、WiFi和宽带等。公寓还贴心提供了床褥。可以选择由四季轩提供的学生饭堂式服务优惠，两餐无忧，一站式服务，在家的享受。&lt;/p&gt;&lt;p&gt;&lt;br&gt;&lt;/p&gt;&lt;p&gt;*公寓的起租日期一般为月初的1号或者15号，比较灵活。&lt;br&gt;&lt;/p&gt;
    [lng] => -2.976588487625122
    [lat] => 53.4029541015625
    [status] => 0
    [create_time] => 2018-02-08 15:02:22
    [update_time] => 2019-03-29 10:13:20
    [is_hot] => 0
    [sort] => 0
    [is_empty] => 1
    [min_effect_price] => 115
    [min_origin_price] => 0
    [is_vip] => 0
    [is_sale] => 1
)

官方文档是这么写的：https://www.swoft.org/docs/2.x/zh-CN/db/origin.html
如果只是查询一条可用 selectOne 结果返回是一个 = Array， 如果没有查询到数据返回是一个空的Array。

如果我想在切换数据库链接后，还要拿到数组，除了获取数据之后，自己用方法进行转换外，框架是否有其它方法提供？

谢谢！！！

**Comment by buzheng95** [comment]
swoft 版本 2.0.6

**Comment by sakuraovq** [comment]
@buzheng95  fetchMode 默认是数组喔 可以改的具体 数据库配置哈  切换了池要看fetchMode 对应配置

**Comment by sakuraovq** [comment]
自己定义数据连接池 默认就是 fetchMode 是对象 需要自己配置下哈

**Comment by sakuraovq** [comment]
默认的连接池 fetchMode 是数组

**Comment by buzheng95** [comment]
> 默认的连接池 fetchMode 是数组

thank you ！ 虽然我也不知道源码是咋回事，但确实解决了。
