### ISSUE TITLE
Bug:批量插入数据报错

### ISSUE THREAD

**Issue by wvfeng** [swoft-cloud/swoft#1034]
SQLSTATE[HY000]: General error: 1390 Prepared statement contains too many placeholders

**Comment by sakuraovq** [comment]
@wvfeng  如何复现呢

**Comment by sakuraovq** [comment]
最近在批量迁移数据写入到mysql表中的时候，出现一下报错。

 SQLSTATE[HY000]: General error: 1390 Prepared statement contains too many placeholders.
        

        

查看mysql官网解释：
Error: 1390 SQLSTATE: HY000 (ER_PS_MANY_PARAM)
Message: Prepared statement contains too many placeholders
参考:https://dev.mysql.com/doc/refman/5.7/en/error-messages-server.html

                

原因分析：
mysql使用PDO进行写入的时候，PDO支持最大占位符为65535。

**Comment by wvfeng** [comment]
@sakuraovq 复现方法就是一次插入很多条数据，超过了PDO限制，之所以出现这个现象是因为Bean默认是单例，我没有手动清空类成员，导致数据一直累加保存

**Comment by sakuraovq** [comment]
使用方法有点问题
