### ISSUE TITLE
自定义配置文件名，和bean.php中key重名，配置无法引用

### ISSUE THREAD

**Issue by phenixsoul** [swoft-cloud/swoft#1036]
遇到的错误：
在config目录创建 dev/httpServer.php，bean.php 中的 httpServer 无法获取配置
bean.php 配置
`    'config'   => [
        'path' => __DIR__ . '/../config',
        'env' => 'dev',
    ],
    'httpServer'        => [
        'class'    => HttpServer::class,
        'port'     => config('httpServer.port'),`

dev/httpServer.php 配置
`return [
        'port'     => 18301,
];`

需要将 httpServer.php改名为其他不存在的key，例如：http.php，使用 config('http.port'), 调用，则正常

**Comment by buzheng95** [comment]
https://www.swoft.org/docs/2.x/zh-CN/config/config.html

看看这个。

**Comment by stelin** [comment]
具体你看下文档，重名会被覆盖
