### ISSUE TITLE
打算用swoft重构公司api项目，但是公司用到mongodb作为数据库，swoft貌似不支持mongodb？

### ISSUE THREAD

**Issue by hisune** [swoft-cloud/swoft#1037]
有没有好的方案可以解决呢？

**Comment by sakuraovq** [comment]
@hisune mongodb 底层已经说了 无法支持 swoole 估计以后也不会支持 

可以单独开一个/多个进程处理 mongodb 哈目前比较好的解决方案就是这个了

详情看 swoft 进程 文档章节哈
