### ISSUE TITLE
tcp event 错误

### ISSUE THREAD

**Issue by first236108** [swoft-cloud/swoft#1039]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.6
| Swoole version      | 4.4.6 (by `php --ri swoole`)
| PHP version         | 7.3.9 (by `php -v`)
| Runtime environment | Ubuntu 18.04.

**错误描述**
(CONSOLE)Swoft\Server\Exception\ServerException: Swoole swoft.tcp.server.connect event is not defined!
At /home/alex/www/im/vendor/swoft/server/src/Server.php line 598

**Expected behavior**
开启http服务器的同时也开启tcp服务器，并对tcp服务器的connect事件进行监听。

**Screenshots**
![image](https://user-images.githubusercontent.com/24523802/66795478-4f0cf600-ef37-11e9-8518-d6019e13345b.png)

**Details**

在app\bean中配置httpServer，增加TCP事件监听，
```php
'httpServer'         => [
        'class'    => HttpServer::class,
        'port'     => 18306,
        'listener' => [
            'tcp' => bean('tcpServer')
        ],
        'on'       => [
            TcpServerEvent::CONNECT => bean(TcpConnectListener::class),
        ],
    ],
```
运行命令：
```bash
php bin/swoft http:start
```
得到报错**(CONSOLE)Swoft\Server\Exception\ServerException: Swoole swoft.tcp.server.connect event is not defined!
**，查找到报错代码位置如下：

![image](https://user-images.githubusercontent.com/24523802/66795780-3b15c400-ef38-11e9-99d5-e059641f638b.png)

这里的**SwooleEvent::LISTENER_MAPPING**并没有包含TCP connect

> 下面附上TcpConnectListener的代码

```php
<?php
/**
 * Created by PhpStorm.
 * User: 85210755@qq.com
 * NickName: 柏宇娜
 * Date: 2019/10/14 上午10:25
 */

namespace App\Listener;

use Swoft\Event\Annotation\Mapping\Listener;
use Swoft\Event\EventHandlerInterface;
use Swoft\Event\EventInterface;
use Swoft\Tcp\Server\TcpServerEvent;
use Swoft\Server\SwooleEvent;

/**
 * Class UserSavingListener
 *
 * @since 2.0
 *
 * @Listener(TcpServerEvent::CONNECT)
 */
class TcpConnectListener implements EventHandlerInterface
{
    /**
     * @param EventInterface $event
     */
    public function handle(EventInterface $event): void
    {

        /* @var \Swoole\Server $server */
        $server = $event->getTarget();
        $pos    = __METHOD__;
        echo "handle the event '{$event->getName()}' on the: $pos\n";
        var_dump(
            $event->getParam(0), // fd
            $event->getParam(1) // reactorId
        );
    }
}

```

**Comment by inhere** [comment]
`TcpServerEvent::CONNECT` 是swoft扩展出来的事件。无需添加到on配置里面。

直接监听就行。
