### ISSUE TITLE
项目需要使用到PostgreSQL不知道是否可以有办法连接？

### ISSUE THREAD

**Issue by lmssky** [swoft-cloud/swoft#104]
项目需要使用到PostgreSQL不知道是否可以有办法连接？或者是连接池？谢谢

**Comment by stelin** [comment]
通过任务实现伪协程

**Comment by gouchaoer** [comment]
因为没有pg的协程客户端，尴尬了，swoole3为了解决这个问题会hook系统调用来编译已有的客户端来得到协程版

**Comment by lmssky** [comment]
好吧有点遗憾.谢谢

**Comment by stelin** [comment]
可以任务里面用同步操作，投递协程任务，实现伪协程，这是完全可以的
