### ISSUE TITLE
期望update返回的值能够区分更新成功、更新失败、没有更新三种情况

### ISSUE THREAD

**Issue by zhezhong17** [swoft-cloud/swoft#1041]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.6

**Describe the bug**
模型中的update返回的是int类型，只有0和数字 (只能区分两种情况)

**Expected behavior**
我需要区分：更新成功、更新失败、没有更新三种情况

例如用户修改一个很复杂的表单，修改了半天，改来改去，最后啥也没改，点击保存。
这个时候如果根据update返回的0，告诉用户操作失败，会令客户产生疑惑的，这不符合业务需求。

建议
&emsp;&emsp;更新成功（int）N条，更新失败（bool）false，无更新内容（int）0条。
或者
&emsp;&emsp;更新失败返回0，无更新返回1，更新成功N

查找了一些相关的资源，暂时不知道怎么解决这个问题。有解决方案吗？

**Comment by sakuraovq** [comment]
只有获取 受影响的行数 判断 如果乐观锁 就判断 ==0 就好了 不会返回 false
