### ISSUE TITLE
建议补充默认错误级别处理的文档说明或配置

### ISSUE THREAD

**Issue by ZxGame00** [swoft-cloud/swoft#1042]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.6
| Swoole version      | 4.4.6 (by `php --ri swoole`)
| PHP version         | 7.2.11 (by `php -v`)
| Runtime environment | CentOS 6

**Details**
在php.ini配置`error_reporting=E_ALL & ~E_NOTICE`，然后在swoft的Http Controller里执行一段会触发notice错误的代码，结果程序抛出异常，输出了notice错误信息，说明error_reporting的设置没生效。查阅代码发现，在`Swoft\Error\DefaultErrorDispatcher`有设置默认错误级别的逻辑，希望这个能有相关文档说明，或者能够做成配置功能，让开放者清楚地知道系统的错误处理级别。

谢谢：）

**Comment by inhere** [comment]
可以配置默认的错误处理级别：

```php
// bean.php

	DefaultErrorDispatcher::class => [
		'errorTypes' => E_ALL | E_STRICT
	],

```

**Comment by ZxGame00** [comment]
OK，这个配置是有效的，谢谢：）

**Comment by ZxGame00** [comment]
> 可以配置默认的错误处理级别：
> 
> ```
> // bean.php
> 
> 	DefaultErrorDispatcher::class => [
> 		'errorTypes' => E_ALL | E_STRICT
> 	],
> ```
Hi, 我在重新安装swoft之后（运行环境与原来一样），发现在`bean.php`里面的配置无法覆盖默认的错误级别，可能之前验证的时候忘了恢复在`Swoft\Error\DefaultErrorDispatcher`的改动，麻烦再次看下为何这个配置没有生效，谢谢：）

**Comment by ZxGame00** [comment]
经过尝试，发现需要调整`scope`为请求注入才能生效：
```php
// bean.php
DefaultErrorDispatcher::class => [
    'errorTypes' => E_ALL & ~E_NOTICE,
    '__option' => [
        'scope' => Bean::REQUEST
    ]
]
```
