### ISSUE TITLE
日志写入失败时Co::writeFile()类型返回限制为int的问题

### ISSUE THREAD

**Issue by guoyoung** [swoft-cloud/swoft#1043]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Describe the bug**
框架Co::writeFile()限制返回只能为int，但该方法下调用的swoole的方法Coroutine::writeFile()在写入失败时会返回bool类型，导致类型不匹配而报致命错误

```php
PHP Fatal error:  Uncaught ErrorException: Uncaught TypeError: Return value of Swoft\Co::writeFile() must be of the type integer, boolean returned in /var/www/swoft/vendor/swoft/framework/src/Co.php:154
```

**Comment by stelin** [comment]
感谢反馈，我们修复下

**Comment by stelin** [comment]
已修复， 20.7 发布

**Comment by stelin** [comment]
已经紧急修复，重新更新2.0.7
