### ISSUE TITLE
swoft2.0.6的验证器为什么不支持GET请求的参数校验的？

### ISSUE THREAD

**Issue by stltd** [swoft-cloud/swoft#1044]

**Comment by stelin** [comment]
你要指定get方式使用，默认是post,具体看文档

**Comment by stltd** [comment]
![image](https://user-images.githubusercontent.com/28774410/66890856-13972800-f01a-11e9-85a4-783abea9774e.png)
是如图，type="ValidateType::GET"吗？是这样的话，还是验证不了

**Comment by stelin** [comment]
你版本

**Comment by stltd** [comment]
> ![image](https://user-images.githubusercontent.com/28774410/66890856-13972800-f01a-11e9-85a4-783abea9774e.png)
> 是如图，type="ValidateType::GET"吗？是这样的话，还是验证不了



> 你版本

swoft2.0.6

**Comment by inhere** [comment]
你这里注解写错了, `ValidateType::GET` 必须引入对应的类，同时这里不能用引号`"`引起来

该这样：

```php
/**
 *@Validate(validator="TestValidator", type=ValidateType::GET)
 */
```

**Comment by stelin** [comment]
你使用方式不正确，亲测没问题

**Comment by stltd** [comment]
可以了，谢谢。
总结一下原因：
1、开始没有引用ValidateType类，这样写：type=ValidateType::GET时，控制器报错，可以就卡在这里；
2、当GET请求验证时，要获取请求参数值时，只能通过方法：$request->getParsedQuery()获取。
3、当POST请求验证时，要获取请求参数值时，只能通过方法：$request->getParsedBody()获取。

提个疑问：为什么POST请求时，验证器不能同时验证Query参数和Body参数？
