### ISSUE TITLE
命令行是否有ErrorHandler？

### ISSUE THREAD

**Issue by hisune** [swoft-cloud/swoft#1046]
console是否有http的这种异常处理呢？https://www.swoft.org/docs/2.x/zh-CN/http-server/exception.html
我看文档里面没有写，然后在`app\Exception\Handler`里面新建`ConsoleExceptionHandler`也没有作用，如何实现console里面的ExceptionHandle呢？

**Comment by inhere** [comment]
console 里也是可以的，跟其他的类似，这里需要继承 `AbstractConsoleErrorHandler`
