### ISSUE TITLE
Redis-cluster 使用 限速redisRateLimiter，报错 RedisCluster::eval(): All keys do not map to the same slot)

### ISSUE THREAD

**Issue by whistling** [swoft-cloud/swoft#1049]
如题，redis 是集群模式，使用redisRateLimiter 报错如下

Redis command reconnect error(RedisCluster::eval(): All keys do not map to the same slot) At /home/vagrant/code/gold-service.2345.com/vendor/swoft/redis/src/Connection/Connection.php line 389

定位原因为： Swoft\Limiter\Rate\RedisRateLimiter类，     getTicket()方法，

使用 redis->eval() 中 使用lua 对多个key 同时操作，但是Redis cluster对多key操作有限，要求命令中所有的key都属于一个slot，才可以被执行。

**Comment by sakuraovq** [comment]
redisRateLimiter 的 lua 暂时不能作为集群使用 后续支持下

**Comment by sakuraovq** [comment]
@whistling  需要使用 到 hashtag 方式 
在 name 限流器名称，默认 swoft:limiter 前加一个  {hashtag:}swoft:limiter  这样子的就可以了

**Comment by KiddoLin** [comment]
@sakuraovq 请问这样的两个 KEY 绝对会被分配在同一个 slot 内吗？例如 {mytag:}swoft:limiter 和 {mytag:}swoft:default

**Comment by chenoh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
