### ISSUE TITLE
建议改进一下，DB的update返回值

### ISSUE THREAD

**Issue by 233cy** [swoft-cloud/swoft#1052]
![图片](https://user-images.githubusercontent.com/29916783/67074868-90620780-f1bc-11e9-9fa0-8901697b5842.png)
DB类，在update后，返回0，或者1。
建议增加false。
原因：
       如我在更新一条数据，0代表数据没有变动无需更新，false代表没有这条数据，无法进行更新（这里我可以知道，是这条数据不存在，而不是数据无变动而已。）。

注：当然我可以通过前面对键值进行一次查询，看这个数据是否存在。只是提个建议，类似TP或者yii

**Comment by inhere** [comment]
refer https://github.com/swoft-cloud/swoft/issues/1041

**Comment by xskit** [comment]
我建议ORM这块跟Laravel保持一致最好用,不接受反驳

**Comment by sakuraovq** [comment]
我看看 能不能加个方法

**Comment by sakuraovq** [comment]
推荐 使用Model save 方法 update 可能会更新多条 改成 bool 不妥
