### ISSUE TITLE
验证规则整型判断 0 值的问题

### ISSUE THREAD

**Issue by xskit** [swoft-cloud/swoft#1058]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Swoft version       | 2.0.6

**Describe the bug**
验证器问题，在验证规则 `@IsInt()`  ，验证值为0时，判断错误，验证不通过，提示：“字段” can not be empty!

**Comment by xskit** [comment]
不是@IsInt ,我加了 @NotEmpty() 导致的，0值比较特殊

**Comment by JasonYH** [comment]
能够提交下当时的验证器注解片段么？ @xskit

**Comment by xskit** [comment]
当时的验证器是这样的：
```php
/**
 * @IsInt()
 * @NotEmpty()
 * @var int
 */
protected $value = 0;
```
我是想，@NotEmpty()不能为空，值传 0 值，是应该可以通过。我看原码是 !empty($value) 做条件判断的，建议规则加个参数严格检查开关，区别一下。

**Comment by JasonYH** [comment]
> 当时的验证器是这样的：
> 
> ```
> /**
>  * @IsInt()
>  * @NotEmpty()
>  * @var int
>  */
> protected $value = 0;
> ```
> 
> 我是想，`@NotEmpty()`不能为空，值传 0 值，是应该可以通过。我看原码是 !empty($value) 做条件判断的，建议规则加个参数严格检查开关，区别一下。
> @JasonYH

好的我这边调整一下

**Comment by JasonYH** [comment]
@xskit @inhere @stelin 问题可以关闭了

**Comment by inhere** [comment]
@JasonYH 你在修复的 PR 里关联下这个issue `fix: swoft-cloud/swoft/issues/1058`

**Comment by xskit** [comment]
明白了，谢谢
