### ISSUE TITLE
redis不支持expireAt

### ISSUE THREAD

**Issue by ZxGame00** [swoft-cloud/swoft#1059]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.6 (by `php bin/swoft -V`)
| Swoole version      | 4.4.7 (by `php --ri swoole`)
| PHP version         | 7.2.11 (by `php -v`)
| Runtime environment | CentOS 6

```php
// app/Http/Controller/HomeController.php
public function hi(): Response
{
    $conn = Swoft\Redis\Redis::connection('redis.pool')
    $conn->set('test', 1);
    $conn->expireAt('test', 3);
    return context()->getResponse->withContent('success');
}
```
捕获到异常信息：
`Redis command reconnect error(Method(expireAt) is not supported!)`

希望能够支持expireAt方法，谢谢：）

**Comment by sakuraovq** [comment]
ok 2.0.7 will support

**Comment by sakuraovq** [comment]
```php
 $conn->set('test', 1 , $expire);
```

**Comment by ZxGame00** [comment]
Sorry，可能示例代码有误导，我想表达的是：
```php
$conn->hMset('test', ['a' => 'foo', 'b' => 'bar']);
$conn->expireAt('test', strtotime(date('20191024')); // will be expired at 2019-10-24 00:00:00, no matter how many times you invoke this
```

**Comment by sakuraovq** [comment]
fixed
