### ISSUE TITLE
是否能提供对 PostgreSQL 数据库的支持

### ISSUE THREAD

**Issue by andy236726493** [swoft-cloud/swoft#1063]
是否能提供对 PostgreSQL 数据库的支持

**Comment by sakuraovq** [comment]
https://www.swoft.org/docs/2.x/zh-CN/extra/postgresql.html

**Comment by andy236726493** [comment]
是否支持PostgreSQL 的事务呢

**Comment by inhere** [comment]
这得问下 https://github.com/curtis18/swoft-pgsql 作者 @curtis18 了

**Comment by curtis18** [comment]
@andy236726493 支持的，事務，進程，協程環境下都可以使用的。留意要安裝 master branch 的 Swoole Postgresql 插件和 Swoole 4.4.7+. 還有是 Variable Binding 現在盡量避免用，因為發現了 Swoole Postgresql 插件有 bug，這已報告給 Swoole Postgresql 插件的作者了。
