### ISSUE TITLE
日志分割问题

### ISSUE THREAD

**Issue by Jason-Wang-Yi** [swoft-cloud/swoft#1066]
swoft v2.0.6
日志分割问题
只有在重启的时候才会产生新的日志文件
否则会一直写入一个文件，并不会按天分割

**Comment by wvfeng** [comment]
我也遇到了类似的问题
![image](https://user-images.githubusercontent.com/33809027/67748043-fffdaf80-fa64-11e9-9830-3fa3c334bf9a.png)

**Comment by stelin** [comment]
2.0.7 已修复 ，后续发不

**Comment by Jason-Wang-Yi** [comment]
2.0.7    预计什么时候发布

**Comment by stelin** [comment]
2.0.7已发布，请更新
