### ISSUE TITLE
Pool error is Create connection error(Dsn(mysql:dbname=pic;host=127.0.0.1:13306)

### ISSUE THREAD

**Issue by XIONGchanghu** [swoft-cloud/swoft#1072]
找了很久的原因，最后发现能通过mysql的容器ip进行连接，但是不能通过局域网127.0.0.1连接，难道是因为没关联网络么，但是我用links关联了呢？麻烦大佬们帮忙看看呢
![image](https://user-images.githubusercontent.com/15356648/67776481-538af000-fa9b-11e9-894f-db17d202691c.png)

**Comment by inhere** [comment]
link 了，可以直接用 `mysql` 作为db的host

**Comment by XIONGchanghu** [comment]
3q
