### ISSUE TITLE
能否创建几个QQ ,wechat，or facebook等技术交流群

### ISSUE THREAD

**Issue by dcdebug** [swoft-cloud/swoft#1073]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z (by `php bin/swoft -V`)
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Describe the bug**

**Expected behavior**

**Screenshots**

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```
能否创建几个QQ ,wechat，or facebook等技术交流群，大家有问题多多交流？

**Comment by inhere** [comment]
qq wechat 都是有的 https://learnku.com/articles/35189
