### ISSUE TITLE
redis 使用进程池读取队列，偶尔会报这个错

### ISSUE THREAD

**Issue by lackoxygen** [swoft-cloud/swoft#1074]
Pool error is Swoft\Connection\Pool\AbstractPool::popByChannel(): send of 5 bytes failed with errno=32 Broken pipe

**Comment by sakuraovq** [comment]
一般是socket已经断开，但是还是去写，就会出现此问题
还有就是通道关闭了

**Comment by lackoxygen** [comment]
有什么解决方法吗@sakuraovq

**Comment by lackoxygen** [comment]
\vendor/swoft/connection-pool/src/AbstractPool.php line=272

**Comment by lackoxygen** [comment]
加这个ini_set('default_socket_timeout', '-1')  能防止这个错误
