### ISSUE TITLE
验证器@Enum枚举数组值只能是数字?

### ISSUE THREAD

**Issue by dogyford** [swoft-cloud/swoft#1075]
不能直接使用枚举数组定义验证器的选项为指定字符串？
![image](https://user-images.githubusercontent.com/25629952/67942225-59efa800-fc12-11e9-94fa-33997800525c.png)

如果按上面设置时会报错，只有将value改成{1,2,3}的时候才可用?非得使用自定义验证器规则才能实现这个效果吗
![image](https://user-images.githubusercontent.com/25629952/67942145-27de4600-fc12-11e9-916f-07741102a176.png)

**Comment by sakuraovq** [comment]
字符串需要加 引号 value={"a","b","c"}

**Comment by sakuraovq** [comment]
hah
