### ISSUE TITLE
RpcProvider->getList两次调用问题

### ISSUE THREAD

**Issue by xiaoproject** [swoft-cloud/swoft#1076]
Swoft\Rpc\Client\Connection

![image](https://user-images.githubusercontent.com/23117484/68009168-32edb080-fcbc-11e9-8e02-2bb5317e4542.png)

这样的话，每次去调用rpc方法的时候，App\Common\RpcProvider -> getList() 方法都会调用两次
可否修改为一下的方式
![image](https://user-images.githubusercontent.com/23117484/68009718-a2b06b00-fcbd-11e9-8a85-663fd1eb7f77.png)

**Comment by inhere** [comment]
@xiaoproject 感谢指出。有兴趣可以直接发 PR 帮助改进。 
如何发PR以及注意，请看：https://github.com/swoft-cloud/swoft/issues/829

**Comment by stelin** [comment]
2.0.7 修复下，感谢支持swoft

**Comment by stelin** [comment]
已修复 2.0.7发布

**Comment by stelin** [comment]
2.0.7已发布，请更新
