### ISSUE TITLE
为什么不把 $request 也传到ExceptionHandle类呢？

### ISSUE THREAD

**Issue by Jamlee** [swoft-cloud/swoft#1078]
/** @var HttpErrorDispatcher $errDispatcher */
            $errDispatcher = Swoft::getSingleton(HttpErrorDispatcher::class);

https://github.com/swoft-cloud/swoft-http-server/blob/9ca8a83884659550f0e1aecdaa10deb024419d36/src/HttpDispatcher.php#L82-L84

![image](https://user-images.githubusercontent.com/5196641/68082247-55670180-fe55-11e9-9673-d0761f5ff5e8.png)
貌似在 hanlde 里面处理所有的http异常更加正规一些呀。虽然通过中间件的最优先的位置的方式可以屏蔽它，好像这里再有个 异常处理类不工作有点奇怪。

**Comment by inhere** [comment]
$request 可以通过上下文获取的。

**Comment by inhere** [comment]
好像这里再有个 异常处理类不工作? 是有啥问题吗？

**Comment by Jamlee** [comment]
@inhere 
![image](https://user-images.githubusercontent.com/5196641/68106844-e0133380-ff1d-11e9-9d6d-9d69923bb332.png)

因为有这一句，异常类不会触发呀。因为我的错误日志写在了 HttpExceptionHandler 里面，就记录不到错误日志了，兄die

**Comment by inhere** [comment]
你可以不用这个中间件方式啊，在 HttpExceptionHandler 里调 whoops。

另外 whoops 本来就是用于本地调试的，功能写的也很简单。你想在中间件里加日志记录，就自己参照这个中间件重新实现一个就行了。

**Comment by Jamlee** [comment]
目前采取在 HttpExceptionHandler 里调 whoops的方式。

**Comment by inhere** [comment]
嗯，是的，都可以。
