### ISSUE TITLE
Timer 定时器，上下文初始化值只能为string问题

### ISSUE THREAD

**Issue by nangge** [swoft-cloud/swoft#1080]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.6
| Swoole version      | 4.4.8
| PHP version         | 7.3.11
| Runtime environment | Docker

`Swoft\Timer`类中有如下方法：
```php
//
private static function initItems(array $items): void
    {
        foreach ($items as $key => $value) {
            context()->set($key, (string)$value);
        }
    }
```
这里的$value是通过`context()->get($item, '')`得到的，但是在这里强制转string，如果上下文设置的值为array就报错了

`ContextInterface`接口`set(string $key, $value)`方法也并没有要求$value为string

这是一个bug，还是有其他考虑？

**Comment by stelin** [comment]
这里不是bug, 这里目的是传递日志扩展参数，扩展参数只支持字符串
