### ISSUE TITLE
swoole 升至 4.4.12 后， websocket 服务的 onOpen 事件报错

### ISSUE THREAD

**Issue by haxqer** [swoft-cloud/swoft#1085]
Swoft version : 2.0.6
Swoole version : 4.4.12
PHP version : 7.2.24
Runtime environment : debian9.9

swoole 升至 4.4.12 后， websocket 服务的 onOpen 事件报错

`[ERROR] Swoole\WebSocket\Server::push() expects parameter 4 to be integer, boolean given /var/www/swoft/vendor/swoft/websocket-server/src/WebSocketServer.php 124`

swoole 回退至 4.4.8 后，该报错消失

**Comment by inhere** [comment]
has been fixed.
