### ISSUE TITLE
通过数据表来映射ORM，生成实体命名可否加个前缀去除

### ISSUE THREAD

**Issue by hhf666feng** [swoft-cloud/swoft#109]
一般建表都会带上特定的前缀，比如表名为lj_users，现生成实体命名为LjUsers，实际希望为Users，希望可以加个命令参数配置去除前缀

**Comment by stelin** [comment]
可以的，新增表前缀和实体字段名前缀选项参数

**Comment by gdc676463** [comment]
提一个小想法：
像symfony中的doctrine定义实体的那样，在实体中指定表名。

**Comment by huangzhhui** [comment]
@gdc676463 本来就是在 Entity 里面通过 @Table() 注解定义表名的

**Comment by stelin** [comment]
db组件更新值1.1.0，已经新增参数
