### ISSUE TITLE
Redis::zRemRangeByScore() expects parameter 2 to be string, float given

### ISSUE THREAD

**Issue by ctfang** [swoft-cloud/swoft#1095]
`Redis::zRemRangeByScore(RedisKey::UserOnline,0.1,time()-30);`

分数int、float都有可能，但是这里限制了string

注释提示 

 * @method static int zRemRangeByScore(string $key, float|string $start, float|string $end)

**Comment by sakuraovq** [comment]
ok

**Comment by sakuraovq** [comment]
我看怎么调整下

**Comment by sakuraovq** [comment]
这个函数是 redis 限制的 zRemRangeByScore  float|string $start, float|string $end 
需要自己手动强转下类型  只支持  float|string
