### ISSUE TITLE
Redis::zadd循环插入 不知道是不是bug

### ISSUE THREAD

**Issue by qidong364482611** [swoft-cloud/swoft#1097]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Swoft version       | 2.0.6
| Swoole version      | 4.4.4
| PHP version         |  7.2.20
| Runtime environment | Mac 10.12

Redis::zadd不支持foreach 循环添加不知道是不是bug？

`
        foreach ($userData as $k=>$v){
            var_dump($v['id']);
//            $coRedis->zAdd('userInfo',$v['id'],json_encode($v));
            Redis::zAdd('userInfo',[json_encode($v),$v['id']]);
        }

`
7000左右数据只成功插入了两条
![2](https://user-images.githubusercontent.com/19990583/68840219-3beb7280-06fd-11ea-9b85-52148528e801.png)

**Comment by sakuraovq** [comment]
使用错误了 

```php

  $data = [
            'scorekey'    => 11.1,
            'scorekey1' => 11.1,
            'scorekey2' => 11.21
        ];
$this->redis->zAdd($key, $data);

```
 key 不能重复的 value 是分数   zAdd 我们封装过了
