### ISSUE TITLE
Clog配置了在Application配置了logFile参数但文件不写入

### ISSUE THREAD

**Issue by kaychem** [swoft-cloud/swoft#1098]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.6
| Swoole version      | 4.3
| PHP version         | 7.2
| Runtime environment | docker

**Describe the bug**
Clog配置了在Application配置了logFile参数但文件不写入，可能功能有遗漏还未实现。

![image](https://user-images.githubusercontent.com/15192564/68841309-5e7e8b00-06ff-11ea-9485-15dd283f39bd.png)
![image](https://user-images.githubusercontent.com/15192564/68841330-6a6a4d00-06ff-11ea-82f0-a92a866cb189.png)
![image](https://user-images.githubusercontent.com/15192564/68841358-73f3b500-06ff-11ea-8b1e-d954040a7052.png)

**Comment by kaychem** [comment]
这个没人看看么

**Comment by stelin** [comment]
CLog 写到文件的还没支持 2.0.8支持下
