### ISSUE TITLE
AnnotationException without install swoft/http-server when I run swoft command

### ISSUE THREAD

**Issue by maxsky** [swoft-cloud/swoft#1099]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.6
| Swoole version      | 4.4.8
| PHP version         | 7.1.33
| Runtime environment | WSL Ubuntu

**Describe the bug**
`AnnotationException` without install `swoft/http-server`

**Expected behavior**
Just remove `swoft/http-server` then run `php ./bin/swoft -h`

**Screenshots**
![TIM20191114171358](https://user-images.githubusercontent.com/7405522/68842944-380e1f00-0702-11ea-81ad-48e7b24d698a.png)

**Details**

> This exception with `swoft/devtool` component. Its about files in `swoft/devtool/src/Http/Controller` and `swoft/devtool/src/Http/Middleware`. Because these files used annotation from `swoft/http-server`. When I remove these files that the command `php ./bin/swoft -h` will be ok.

**Comment by inhere** [comment]
Now, the `devtool` must require `http-server`
