### ISSUE TITLE
ORM可否支持软删除

### ISSUE THREAD

**Issue by hhf666feng** [swoft-cloud/swoft#110]
类似laravel框架Eloquent的SoftDeletes
数据表带时间戳字段deleted_at

顺便是否可支持
数据新增自动填充created_at
数据更新自动更新updated_at

**Comment by huangzhhui** [comment]
嗯，可以的，Eloquent的这个特性还是很实用的

**Comment by GavinZhao8** [comment]
软删除的功能有跟进吗？
