### ISSUE TITLE
Can not use alias colume when create a query

### ISSUE THREAD

**Issue by duythien** [swoft-cloud/swoft#1100]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | ~2.0.0
| Swoole version      | 4.4.7
| PHP version         | 7.2.22
| Runtime environment | Docker

**Describe the bug**
I want to use alias to get query data, below my model and dao

DeviceSettings.php
```
use Swoft\Db\Eloquent\Model;

/**
 *
 * Class DeviceSettings
 *
 * @since 2.0
 *
 * @Entity(table="device_settings")
 */
class DeviceSettings extends Model
{
/**
     *
     *
     * @Column(name="user_id", prop="userId")
     *
     * @var int
     */
    private $userId;

[...]
```
And DeviceSettingsDao.php

```
<?php declare(strict_types=1);


namespace App\Model\Dao;

use App\Model\Entity\Device;
use App\Model\Entity\DeviceSettings;
use Swoft\Db\DB;

class DeviceSettingsDao
{
   
    public function getByUser($id)
    {
        try{
            $deviceSetting = DB::table('device_settings')->where('userId', $id);
            return $deviceSetting->get();
        } catch (\Exception $e) {

        }
    }
}


```

File env

```
# basic
APP_DEBUG=0
SWOFT_DEBUG=0
APP_ENV=dev
TIMEZONE=Asia/Shanghai
# db config
DB_HOST=db:3306
DB_DSN=mysql:dbname=gsviec;host=db
DB_USER=root
DB_PASSWORD=gsviec
DB_NAME=gsviec
# more ...
```

When I try to call function getByUser `var_dump($this->deviceSettingService->getByUser(901));` this will be get the error like this

```
2019/11/14-18:35:05 [INFO] Swoft\Listener\BeforeStartListener:handle(28) Registered swoole events:
 start, shutdown, managerStart, managerStop, workerStart, workerStop, workerError, handshake, message, close, pipeMessage, request
Server start success (Master PID: 135, Manager PID: 138)
2019/11/14-18:35:56 [ERROR] Swoft\Db\Connection\Connection:runQueryCallback(709) Fail sql = select * from `device_settings` where `userId` = 901
NULL
```
If I change the code `DeviceSettings::where('userId', $id)->get()` to `DeviceSettings::where('user_id', $id)->get()` it will be work fine, so this is bug?
Thanks

**Comment by sakuraovq** [comment]
I suggest you use  ```php    DeviceSettings::whereProp('userId', $id)->get() ```

**Comment by sakuraovq** [comment]
See the Prop operation for details.  

https://www.swoft.org/docs/2.x/en/db/model.html#%20prop%20operation

**Comment by duythien** [comment]
Thanks. It work now
