### ISSUE TITLE
会考虑免去 mode 的 set 和 get 方法吗？

### ISSUE THREAD

**Issue by Jamlee** [swoft-cloud/swoft#1103]
经过使用 Swoft 后发现每次需要编写 set 和 get 方法着实比较耗时。能考虑选择性提供这种方式吗。

![image](https://user-images.githubusercontent.com/5196641/69019910-a8ac8880-09ed-11ea-8d93-a392727df21d.png)

也许能为使用者减轻一些负担呀

**Comment by gonghoubin** [comment]
工具生成的

**Comment by sakuraovq** [comment]
后面 兼容 php7.4 是可以的

**Comment by sakuraovq** [comment]
目前可以使用实体生成工具生成实体文件

**Comment by stelin** [comment]
getter/setter 可以时候用phpstrom 快捷生成，或者swoft-devool 是生成，后面php7.4 会考虑放开
