### ISSUE TITLE
Create connection error(Call to a member function getList() on null)

### ISSUE THREAD

**Issue by icyfire** [swoft-cloud/swoft#1105]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.7
| Swoole version      | 4.4.7
| PHP version         | 7.2.24
| Runtime environment | Ubuntu

**Describe the bug**
升级2.0.7版本后，调用RPC时报` Create connection error`错误

```
2019/11/18-11:47:26 [ERROR] App\Exception\Handler\HttpExceptionHandler:handle(44) Create connection error(Call to a member function getList() on null) file(/home/vagrant/workspace/swoft/vendor/swoft/rpc-client/src/Connection.php) line (146)
```

**Comment by stelin** [comment]
已经紧急修复，重新更新2.0.7
