### ISSUE TITLE
BUG 从v2.0.6升级到v2.0.7发现部分文件没有更新

### ISSUE THREAD

**Issue by wvfeng** [swoft-cloud/swoft#1107]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.6
| Swoole version      | 4.4.8
| PHP version         | 7.0.20
| Runtime environment | Docker etc.

**Describe the bug**
通过`composer update`进行升级发现部分文件没有正确升级

**Screenshots**
![image](https://user-images.githubusercontent.com/33809027/69033895-eecc1100-0a1a-11ea-9433-a1c7806f2b98.png)
可以看到版本号显示是对的
![image](https://user-images.githubusercontent.com/33809027/69034004-32267f80-0a1b-11ea-8ad2-549e8d09a708.png)
但是代码却不对
![image](https://user-images.githubusercontent.com/33809027/69034653-bfb69f00-0a1c-11ea-9ed2-77f7902cc5f2.png)

这是正确的代码
![image](https://user-images.githubusercontent.com/33809027/69034803-03a9a400-0a1d-11ea-83ec-b51d3b436db7.png)

**Details**
经过测试，删除掉`composer.lock`文件和`vendor`重新执行`composer install`更新的结果是正确的，至少这个文件恢复了正常

**Comment by stelin** [comment]
这个估计是你本地composer 缓存问题导致
