### ISSUE TITLE
Validator cannot used without annotation

### ISSUE THREAD

**Issue by maxsky** [swoft-cloud/swoft#1111]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.7
| Swoole version      | 4.4.8
| PHP version         | 7.1.33
| Runtime environment | WSL Ubuntu 18.04 LTS

**Describe the bug**
Validator cannot used without annotation, and `Swoft\Validator\Annotation\Mapping\Validator` class cannot used as default validator. Document description error [Use validator without annotation](https://swoft-cn.netlify.com/documents/v2/core-components/validator/#%E9%9D%9E%E6%B3%A8%E8%A7%A3%E9%AA%8C%E8%AF%81%E5%99%A8)

**Expected behavior**
Default validator could be run normal.

**Screenshots**
![20191120014341](https://user-images.githubusercontent.com/7405522/69171609-4364ae80-0b37-11ea-90cc-a54c3055a5ea.png)

**Details**

```php
/**
 * @RequestMapping(route="/test/index", method="post")
 *
 * @param Request $request
 *
 * @return array|Response
 */
public function testIndex(Request $request) {
    try {
        $data = validate($request->post(), "Swoft\Validator\Annotation\Mapping\Validator");
    } catch (ValidatorException $e) {
        return $e->getMessage();
    }
}
```

I found `$validators` has not set default validator when register.

**Comment by stelin** [comment]
你要使用 @Validate 标记类，具体可以看下验证器相关文档

**Comment by stelin** [comment]
你使用方式不对

**Comment by maxsky** [comment]
文档应该是写错了，“非注解验证器” 这一部分
