### ISSUE TITLE
怎么使用session官方文档只讲了安装 没有使用说明

### ISSUE THREAD

**Issue by wike933** [swoft-cloud/swoft#1115]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z (by `php bin/swoft -V`)
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Describe the bug**

**Expected behavior**

**Screenshots**

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
这两天忙。稍后写文档。

可以参考使用示例：
https://github.com/swoft-cloud/swoft/blob/master/app/Http/Controller/SessionController.php

**Comment by inhere** [comment]
文档已经添加
