### ISSUE TITLE
还是上下文丢失！版本2.07

### ISSUE THREAD

**Issue by porsion** [swoft-cloud/swoft#1120]
好久没动过这个项目了，结合上次的上下文丢失问题，官方说要更新至2.06，今天更新了一下，到了2.07了，但还是出现上下文丢失的问题。。。。。
[sam@localhost zoodt]$ php bin/swoft http:stop
2019/11/23-02:54:22 [INFO] Swoft\SwoftApplication:setSystemAlias(494) Project path: @base=/home/sam/www/zoodt
2019/11/23-02:54:22 [INFO] Swoft\SwoftApplication:setSystemAlias(495) Set alias @app=@base/app
2019/11/23-02:54:22 [INFO] Swoft\SwoftApplication:setSystemAlias(496) Set alias @config=@base/config
2019/11/23-02:54:22 [INFO] Swoft\SwoftApplication:setSystemAlias(497) Set alias @runtime=@base/runtime
2019/11/23-02:54:22 [INFO] Swoft\Processor\EnvProcessor:handle(52) Env file(/home/sam/www/zoodt/.env) is loaded
2019/11/23-02:54:22 [INFO] Swoft\Processor\AnnotationProcessor:handle(47) Annotations is scanned(autoloader 22, annotation 355, parser 82)
2019/11/23-02:54:23 [ERROR] InvalidArgumentException(code:500) context information has been lost of the coID: -1
Code Trace:
#0 /home/sam/www/zoodt/vendor/swoft/bean/src/Container.php(436): Swoft\Bean\Container->safeNewBean('config')
#1 /home/sam/www/zoodt/vendor/swoft/framework/src/Swoft.php(119): Swoft\Bean\Container->get('config')
#2 /home/sam/www/zoodt/vendor/swoft/framework/src/BeanHandler.php(130): Swoft::getBean('config')
#3 /home/sam/www/zoodt/vendor/swoft/bean/src/Container.php(1152): Swoft\BeanHandler->getReferenceValue('websocket.autoR...')
#4 /home/sam/www/zoodt/vendor/swoft/bean/src/Container.php(1053): Swoft\Bean\Container->getRefValue('config.websocke...', '')
#5 /home/sam/www/zoodt/vendor/swoft/bean/src/Container.php(923): Swoft\Bean\Container->newProperty(Object(Swoft\WebSocket\Server\Listener\ConnStorageSubscriber), Object(ReflectionClass), Array, '')
#6 /home/sam/www/zoodt/vendor/swoft/bean/src/Container.php(793): Swoft\Bean\Container->newBean('Swoft\\WebSocket...')
#7 /home/sam/www/zoodt/vendor/swoft/bean/src/Container.php(308): Swoft\Bean\Container->initializeBeans()
#8 /home/sam/www/zoodt/vendor/swoft/bean/src/BeanFactory.php(26): Swoft\Bean\Container->init()
#9 /home/sam/www/zoodt/vendor/swoft/framework/src/Processor/BeanProcessor.php(50): Swoft\Bean\BeanFactory::init()
#10 /home/sam/www/zoodt/vendor/swoft/framework/src/Processor/ApplicationProcessor.php(34): Swoft\Processor\BeanProcessor->handle()
#11 /home/sam/www/zoodt/vendor/swoft/framework/src/SwoftApplication.php(221): Swoft\Processor\ApplicationProcessor->handle()
#12 /home/sam/www/zoodt/bin/swoft(12): Swoft\SwoftApplication->run()
#13 {main}
求助

**Comment by stelin** [comment]
感觉反馈我们复现下

**Comment by inhere** [comment]
@porsion 是可以一直复现的吗？操作步骤是怎样的。

**Comment by porsion** [comment]
> @porsion 是可以一直复现的吗？操作步骤是怎样的。

不好意思不好意思。我在配置文件里使用了了request对象。。。我的锅

**Comment by stelin** [comment]
@porsion 请问下怎么复现，我测试没法复现
