### ISSUE TITLE
redis-cluster集群 Redis command reconnect error(Can't communicate with any node in the cluster)

### ISSUE THREAD

**Issue by AridanJohn** [swoft-cloud/swoft#1125]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.7
| Swoole version      | 4.4.7
| PHP version         | 7.2.22
| Runtime environment | Docker etc.

redis-cluster集群配置
![image](https://user-images.githubusercontent.com/29624248/69626785-51a95200-1084-11ea-8f41-6c3c438f4a30.png)

phpredis扩展已经升级5.1.1   redis版本5.0

限流器redis-cluster集群不能使用，报错如下图
![image](https://user-images.githubusercontent.com/29624248/69617907-ec4d6500-1073-11ea-9a3d-39e2b08e133d.png)

去掉限流器：报错如下图
![image](https://user-images.githubusercontent.com/29624248/69626708-1eff5980-1084-11ea-83a7-e77192b376c7.png)

感觉应该是phpredis版本和集群redis的版本不兼容造成的

**Comment by sakuraovq** [comment]
你是的节点无法通行呀 自己本机连接下就知道了 集群问题哈  redis-cluster 使用限流 需要使用 hashtag

**Comment by sakuraovq** [comment]
你是的节点无法通行呀 自己本机连接下就知道了 集群问题哈  redis-cluster 使用限流 需要使用 hashtag

**Comment by AridanJohn** [comment]
> 你是的节点无法通讯呀 自己本机连接下就知道了 集群问题哈 redis-cluster 使用限流 需要使用 hashtag

节点通的，本机也可以访问

**Comment by AridanJohn** [comment]
![image](https://user-images.githubusercontent.com/29624248/69705153-ed43cc80-112f-11ea-999c-3435e6636764.png)

集群这样配置连上了，感觉应该是phpredis版本与redis版本不兼容造成的，但是集群连接池不能配置，配置就被拒绝
