### ISSUE TITLE
websocket 中间件 return  报错 swoole::push 第四个参数为bool

### ISSUE THREAD

**Issue by chenjing0521** [swoft-cloud/swoft#1126]
swoft\websocket-server\src\Message\Response.php在这个文件中的229行
 我不知道怎么改 大佬 麻烦了

**Comment by EthanChenLi** [comment]
更新到2.0.7

**Comment by chenjing0521** [comment]
> 更新到2.0.7

我这个是最新版  框架的其他部分已经修改了（sendTo等 已修改） 这个地方 由于private属性$finished = true 这里还未修改，所以这里需要修改一下

**Comment by inhere** [comment]
是的。这周发个修复版本
