### ISSUE TITLE
error: Swoole\WebSocket\Server::push() expects parameter 4 to be int, bool given

### ISSUE THREAD

**Issue by 233cy** [swoft-cloud/swoft#1127]
PHP: 7.3.8, Swoft: 2.0.7, Swoole: 4.4.12

return context()->getResponse()->setData(wsErr($authUrl['data']['msg'], [], 'close'));

**Comment by 233cy** [comment]
@stelin

**Comment by 233cy** [comment]
@inhere

**Comment by EthanChenLi** [comment]
composer update  v2.0.7

**Comment by 233cy** [comment]
> composer update v2.0.7

已经是2.0.7了啊。上面有写版本啊。

**Comment by 233cy** [comment]
@inhere @EthanChenLi

**Comment by chenjing0521** [comment]
#1126 就是这个问题
