### ISSUE TITLE
error session组件丢失缓存

### ISSUE THREAD

**Issue by EthanChenLi** [swoft-cloud/swoft#1128]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.7
| Swoole version      | 4.4.0
| PHP version         | 7.1.23
| Runtime environment | MACOS

```php
/**
 * Class TestController
 *
 * @since 2.0
 *
 * @Controller(prefix="test")
 */
class TestController
{
    /**
     * @RequestMapping(route="test1")
     *
     * @return string
     */
    public function test()
    {
        HttpSession::current()->set("TEST","hi");
        return  \context()->getResponse()->withContent("test1");
    }

    /**
     * @RequestMapping(route="test2")
     *
     * @return string
     */
    public function test2()
    {
        return \context()->getResponse()->withContent("test2");
    }
    
}
```
访问test1的时候，会在 ```runtime/sessions/```目录下生产一个缓存文件。
但是访问test2的时候，```runtime/sessions/```缓存文件中的缓存内容丢失。
如果把test2改为 ```return HttpSession::current()->get("TEST");``` 则缓存内容不会丢失

**Comment by inhere** [comment]
@EthanChenLi 已经修复

在 `2.0.7` 解决这个问题也很简单。
复制一份 https://github.com/swoft-cloud/swoft-session/blob/master/src/SessionMiddleware.php#L73 session中间件的代码，去掉 `73` 行的代码，配置中间件时用自己的这个就行。
