### ISSUE TITLE
task中调用rpc返回数据长度有限制

### ISSUE THREAD

**Issue by yangtongbing** [swoft-cloud/swoft#1129]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 4.0.3
| PHP version         | 7.2.19
| Runtime environment | Mac

**Describe the bug**

Task中请求rpc

**Expected behavior**

测试过程中发现task中调用接口时数据长度过长也就是两千字节,返回数据报了一段关于json的错误,正常请求rpc是没有问题,而且将数据适当减到一千字节一下,数据就正常返回了,这大概是什么原因呢?

**Details**

json_decode error: Control character error, possibly incorrectly encoded

**Comment by yangtongbing** [comment]
最后没办法,改了一下,把task中执行的内容抽成了一个rpc,也算是绕过了这个问题

**Comment by stelin** [comment]
感谢反馈我们复现下，你是task 中调用rpc服务么

**Comment by yangtongbing** [comment]
> 感谢反馈我们复现下，你是task 中调用rpc服务么
是的,为了验证问题我还特意尝试了多种返回值,在大概等于1000字节的报错了,报了一个上面我发的那个错误,所以我换了一种方式进行调用.

**Comment by stelin** [comment]
我马上测试下，是任务返回大小限制么，协程任务么

**Comment by yangtongbing** [comment]
> 我马上测试下，是任务返回大小限制么，协程任务么

TYPE_ASYNC任务类型,就是请求rpc接口时返回数据长度有限制,长了直接就报错了

**Comment by stelin** [comment]
建议你升级到2.0吧 1.0 很多由于底层限制不好修复

**Comment by yangtongbing** [comment]
> 建议你升级到2.0吧 1.0 很多由于底层限制不好修复

我换了一种方式,把在task中执行的放到了rpc中进行执行,这样也算是巧妙的避开了,改天还是好好看看swoole文档,感觉时swoole的问题.

**Comment by stelin** [comment]
嗯嗯 建议尽快升级到2.0
