### ISSUE TITLE
Swoole\Table::Set: unable to allocate memory

### ISSUE THREAD

**Issue by yuanliang847** [swoft-cloud/swoft#113]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Swoft version    | 0.2.2
| Swoole version   | 2.0.12 
| PHP version      | 7.2.2

> 运行了大概5个小时以上，发现输出了一堆的warning错误，重启之后，错误消失

![image](https://user-images.githubusercontent.com/11944928/36773911-e38eb55e-1c96-11e8-940b-771f01fd6d83.png)

**Comment by yuanliang847** [comment]
开启了crontab和autoload，crontab执行代码是clone下来的默认代码，没有做额外处理
centos7 下

**Comment by whiteCcinn** [comment]
@yuanliang847 无法复现问题，可能是table hash冲突导致的。如果再次发现，请再次提交issue。

**Comment by jianwubayiba** [comment]
同问。
