### ISSUE TITLE
error 进程池设置 workerNum 无效

### ISSUE THREAD

**Issue by Bruce-K** [swoft-cloud/swoft#1130]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.7
| Swoole version      | 4.4.5
| PHP version         | 7.2.22
| Runtime environment | Deepin

**Describe the bug**
比如设置5个worker 实际只能启动3个worker进程

**Screenshots**
![image](https://user-images.githubusercontent.com/15797911/69714109-c772f380-1140-11ea-9fd2-8304eece324a.png)

![image](https://user-images.githubusercontent.com/15797911/69714064-b0cc9c80-1140-11ea-8517-7219713bde99.png)

```php
/**
 * Class Worker1Process
 *
 * @since 2.0
 *
 * @Process(workerId=0)
 */
class Worker1Process implements ProcessInterface
{
    /**
     * @param Pool $pool
     * @param int  $workerId
     */
    public function run(Pool $pool, int $workerId): void
    {
        while (true) {
            CLog::info('test pool worker id '.$workerId);
            Coroutine::sleep(3);
        }
    }
}

/**
 * Class Worker2Process
 *
 * @since 2.0
 *
 * @Process(workerId={1,2})
 */
class Worker2Process implements ProcessInterface
{
    /**
     * @param Pool $pool
     * @param int  $workerId
     *
     * @throws DbException
     */
    public function run(Pool $pool, int $workerId): void
    {
        while (true) {
            CLog::info('test pool worker id '.$workerId);
            Coroutine::sleep(3);
        }
    }
}

/**
 * Class Worker3Process
 *
 * @since 2.0
 *
 * @Process(workerId=3)
 */
class Worker3Process implements ProcessInterface
{
    /**
     * @param Pool $pool
     * @param int  $workerId
     *
     * @throws DbException
     */
    public function run(Pool $pool, int $workerId): void
    {
        while (true) {
            CLog::info('test pool worker id '.$workerId);
            Coroutine::sleep(1);
        }
    }
}
```

**Comment by stelin** [comment]
感谢反馈我们测试下，应为你这里只绑定了几个worker,其它worker进程都没有绑定

**Comment by stelin** [comment]
经过我测试时你配置没有生效，如果有配置生效你会出现 类似这种错误 Run process for process pool fail(Worker process(3) for process pool must be defined

因为你这里只绑定了4个进程，还有其它进程没有绑定

**Comment by stelin** [comment]
你这里开启的还是三个进程，因为底层默认就是三个，你配置未生效问题

**Comment by Bruce-K** [comment]
> 经过我测试时你配置没有生效，如果有配置生效你会�出现 类似这种错误 Run process for process pool fail(Worker process(3) for process pool must be defined
> 
> 因为你这里只绑定了4个进程，还有其它进程没有绑定

你好，在尝试修改 
![image](https://user-images.githubusercontent.com/15797911/69969437-62136e00-1557-11ea-91cb-3dfb868e7ae2.png)
默认进程数量后才出现 了 Worker process(3) for process pool must be defined 类似错误，但是没有弄明白为什么 bean 配置文件 wokerNum 修改后并没有生效出现该错误。

**Comment by stelin** [comment]
你配置的方式不对

**Comment by stelin** [comment]
导致配置未生效
