### ISSUE TITLE
2.0.7在dao无法声明rpc服务

### ISSUE THREAD

**Issue by david2066** [swoft-cloud/swoft#1131]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.7
| Swoole version      | 4.4.12
| PHP version         | 7.3.11
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Describe the bug**
http or websockst 调用dao声明的rpc服务没用

**Expected behavior**
目前只有http请求成功，但无法在dao声明使用，可以直接在http controller声明使用，随同服务.

**Comment by stelin** [comment]
dao 不建议做其它操作也是不支持的，dao 提倡只是数据库操作 如果有调用rpc服务可以在data或logic
