### ISSUE TITLE
单独启动定时任务功能

### ISSUE THREAD

**Issue by icyfire** [swoft-cloud/swoft#1135]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.7
| Swoole version      | 4.4.12
| PHP version         | 7.2.24
| Runtime environment | CentOS 7

**Details**
请问能否单独启动定时任务，而不用在HTTP Server或者RPC Server之中配置。

**Comment by windqyoung** [comment]
这是属于swoole的功能. 可以的.

**Comment by stelin** [comment]
定时任务现在是用用户进程实现，不支持单独启动，如果要单独启动，你可以自己封装下
