### ISSUE TITLE
get和first的toArray()  预期值不一致

### ISSUE THREAD

**Issue by zhezhong17** [swoft-cloud/swoft#1136]
->get()->toArray();   // 没查询到时返回空数组
->first()->toArray(); // 没查询到时报错，这个逻辑和thinkphp一样  // Call to a member function toArray() on null At

这会导致多一次if判断；且代码不连贯。

建议改成 
->first()->toArray(); // 没查询到时返回空数组  // laravel就是这样的
或者->get()->toArray();  // 没有时报错

总之get和first的toArray预期应该是一致的。

**Comment by sakuraovq** [comment]
概念不一样  first 比 get 更加严格

**Comment by sakuraovq** [comment]
不用纠结用 first 方法 可以
 ```php
...->take(1)->get($columns) 
```
first 底层就是基于这样取的第一个

**Comment by sakuraovq** [comment]
我刚刚看了 lv 也一样的 呀

**Comment by zhezhong17** [comment]
get获取的是[[],[],[]]first获取的是[]
这两个东西不一样。不能代替使用
我不是纠结，少一些代码以及toArray操作连贯一点



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "OvO"<notifications@github.com&gt;; 
发送时间: 2019年12月1日(星期天) 中午11:22
收件人: "swoft-cloud/swoft"<swoft@noreply.github.com&gt;; 
抄送: "折中C"<2548551063@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [swoft-cloud/swoft] get和first的toArray()  预期值不一致 (#1136)




不用纠结用 first 方法 可以
 ...-&gt;take(1)-&gt;get($columns) 
 
first 底层就是基于这样取的第一个
