### ISSUE TITLE
v2.0.7这个版本，websocket部分文件没有兼容swoole v4.4.12

### ISSUE THREAD

**Issue by woodost** [swoft-cloud/swoft#1139]
使用websocket，调用push方法时，部分文件的finish参数还没改成int型，没有兼容swoole的4.4.12版本
![image](https://user-images.githubusercontent.com/47843465/70029140-5ec4c480-15e1-11ea-92f7-99b0f7b6f5b0.png)

**Comment by inhere** [comment]
已修复。这周末会发个修复版本。

**Comment by inhere** [comment]
refer https://github.com/swoft-cloud/swoft/issues/1127
