### ISSUE TITLE
文档RPC那块没怎么看明白

### ISSUE THREAD

**Issue by wyz9527** [swoft-cloud/swoft#114]
我看文档里面的RPC列子，服务提供者 和服务消费者是在通一个项目下进行的调用。
实际场景是服务提供者和服务消费者分别在各自的项目里面
我想问的是
服务消费者和服务提供者的项目都用你们的swoft框架 
服务消费者的项目里面要如何配置信息

**Comment by stelin** [comment]
提供服务，其实就是提供的接口服务，接口放在一个公共的lib库里面。定义好接口，服务调用方，首先配置RPC连接信息，框架底层已经实现RPC调用，类似本地函数调用。欢迎加QQ群技术交流，548173319。
