### ISSUE TITLE
使用@View注解 设置视图时 导致响应头异常 导致ie下无法正常显示

### ISSUE THREAD

**Issue by Just-Nothing** [swoft-cloud/swoft#1142]
响应如下内容 Content-Type 错误

Connection: keep-alive
Content-Type: content-type; charset=text/html
Date: Thu, 05 Dec 2019 01:25:39 GMT
Proxy-Connection: keep-alive
Server: nginx/1.16.1
Transfer-Encoding: chunked

**Comment by inhere** [comment]
@Just-Nothing thanks. 已找到问题，这周发个修复版本解决。
