### ISSUE TITLE
并发情况下，相同日志重复输出

### ISSUE THREAD

**Issue by zl00733** [swoft-cloud/swoft#1144]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.7
| Swoole version      | 4.4.8
| PHP version         | 7.2.24
| Runtime environment | Docker etc.

**Describe the bug**
ab 压测的时候，发现Swoft\Log\Helper\Log日志输出会有重复的数据产生

**Expected behavior**
希望不重复

**Screenshots**
app/bean.php
![image](https://user-images.githubusercontent.com/10155850/70290852-45f02500-1814-11ea-8d20-51e15250d993.png)

app/Controller/GatewayController.php
![image](https://user-images.githubusercontent.com/10155850/70292578-8c944e00-1819-11ea-9971-424eaa4f1ffe.png)

日志
![image](https://user-images.githubusercontent.com/10155850/70292497-64a4ea80-1819-11ea-9743-0f69ea3ccd39.png)

ab请求：
![image](https://user-images.githubusercontent.com/10155850/70291130-358c7a00-1815-11ea-9bbf-2d227a99419c.png)

**Details**
![image](https://user-images.githubusercontent.com/10155850/70291212-73899e00-1815-11ea-9a06-920d3b0d7a38.png)

> 怀疑并发情况下，vendor/swoft/log/src/Logger.php写有脏数据，$this->messages第一次flushlog还没有clear，第二个请求把它自己的数据又加入$this->messages里继续flushlog造成的

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by zl00733** [comment]
@stelin hi 这个问题有进度吗？

**Comment by sakuraovq** [comment]
描述下复现场景 清晰点~

**Comment by zl00733** [comment]
@sakuraovq hi 我上面的截图里应该有表达，
1、一个简单的controller里面写了一个Log::info()，记录了时间戳和随机数。
2、ab并发访问这个方法
3、日志里出现了多条“相同的时间戳和随机数”的日志

**Comment by zl00733** [comment]
@sakuraovq 
后来我在vendor/swoft/log/src/Logger.php 用redis记录每次请求产生的$this->messages[]得到结果：
第一次请求：记录日志：a
第二次请求：记录日志：a+b
第三次请求：记录日志：a+b+c
第四次请求：记录日志：d（估计这个时候才清空了$this->message数组）
