### ISSUE TITLE
PHP7.4中使用{} 做偏移会报警告

### ISSUE THREAD

**Issue by LoaderWang** [swoft-cloud/swoft#1145]
![image](https://user-images.githubusercontent.com/34303853/70312738-304c2100-184f-11ea-8857-25ad47f64df2.png)
AbstractInput.php 317行

另外还有vendor\toolkit\cli-utils\src\Flags.php中的135 ，151，313行也出现该问题

**Comment by inhere** [comment]
ok @LoaderWang 我修复下。
