### ISSUE TITLE
SwoftEvent::COROUTINE_COMPLETE 事件有bug

### ISSUE THREAD

**Issue by aslackers** [swoft-cloud/swoft#1146]
swoole文档上写着
> 发生致命错误或者代码中主动调用exit时，Worker/Task进程会退出，管理进程会重新创建新的进程。这可能导致死循环，不停地创建销毁进程

目前已发现的事件`SwoftEvent::COROUTINE_COMPLETE`，未做错误异常捕获，会导致进程不断的被杀死、创建，进入死循环，导致CPU飙升

**Comment by inhere** [comment]
@aslackers 我们检查验证下

**Comment by aslackers** [comment]
项目启动后，将runtime目录下的logs目录删除，发送一个HTTP请求。这种方式必然会出现这个问题。

**Comment by inhere** [comment]
好的

**Comment by herenet** [comment]
我也遇到同样的问题了，我这边不能肯定是否是因为删除Log文件引起的。程序启动后，我有个健康检测1秒钟一次。运行个一天左右，就不返回数据了，只有500错误码，日志也没有，我看notice日志还在打，自定义的记录SQL的日志也正常打印着。。仔细观察发现有一个worker进程的ID一直在变，说明一直在重新创建进程。strace了一个manager进程返回如下：

wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 23484
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23484, si_uid=0, si_status=0, si_utime=1, si_stime=1} ---
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5839709b10) = 23496
@inhere

**Comment by herenet** [comment]
补充：
<img width="458" alt="image" src="https://user-images.githubusercontent.com/568403/74924581-b9660380-540d-11ea-9d8c-b8d0fb41693b.png">
@inhere
