### ISSUE TITLE
超过maxIdleTime的连接没有close导致established状态的连接持续增长

### ISSUE THREAD

**Issue by eyehere** [swoft-cloud/swoft#1147]
已经提交PR，详见：

https://github.com/swoft-cloud/swoft-connection-pool/pull/1

**Comment by inhere** [comment]
不能直接向组件仓库提PR，请提到开发仓库。 参看：https://github.com/swoft-cloud/swoft/issues/829

**Comment by stelin** [comment]
非常好的issue，感觉支持
