### ISSUE TITLE
v2.0.7 ws的消息控制器bug

### ISSUE THREAD

**Issue by Kyourcn** [swoft-cloud/swoft#1152]
在使用Websocket的消息控制器的时候，每当有新客户端消息，都会报WARNING。
`[WARNING] cannot send empty response to websocket client`
swoole版本 最新版
php 7.3
运行的是从composer create 的全新demo
12月9日composer update 后还是有这个情况。

**Comment by tanpeng** [comment]
同样存在~

**Comment by inhere** [comment]
2.0.8 已经发布
