### ISSUE TITLE
crontab增加方法互斥功能

### ISSUE THREAD

**Issue by linjuchen** [swoft-cloud/swoft#1154]
crontab经常用来做异步或者消息处理。如果一个job要消费数据时间比较长，而定时又短，可能造成同时运行多个job的情况，造成数据处理异常，因为希望增加job同时运行的开关。

**Comment by inhere** [comment]
定时任务是不管这些的，它是到了时间并且有任务就执行任务。

你这种有数据先后依赖的可以用MQ，或者自己从逻辑上判断下是否处理过。

**Comment by zhuzhuolong** [comment]
各种锁可以选择。直接加再crontab 上。不合理啊。这种事情应该跟着业务逻辑走

**Comment by stelin** [comment]
锁机制你业务控制吧
