### ISSUE TITLE
期望swoft的redis set命令增加参数支持

### ISSUE THREAD

**Issue by feison** [swoft-cloud/swoft#1155]
redis 2.6.12 版本之后 set命令 能替代setnx和expire 两条命令,   使锁的设置和过期设置原子化,  
希望 swoft/redis 能够支持
官方文档链接 [https://redis.io/commands/set](https://redis.io/commands/set)

**Comment by zl00733** [comment]
@feison 
use Swoft\Redis\Redis;
 $re = Redis::call(function (\Redis $redis) use ($key, $value) {
            return $redis->set($key, $value, array('nx', 'px' => 500));
        });

**Comment by sakuraovq** [comment]
call  就可以了哈 楼上正解

**Comment by feison** [comment]
@sakuraovq @zl00733  eval加lua也能实现,  只是如果能去掉set函数第三个参数的类型限制, 一个set就能解决

**Comment by stelin** [comment]
我们考虑新增一个方法，方便使用

**Comment by sakuraovq** [comment]
@feison  嗯 2.0.8 加上
