### ISSUE TITLE
并发请求,  调用类的函数方法的时候, 函数方法不能正常传递参数

### ISSUE THREAD

**Issue by nilsir** [swoft-cloud/swoft#1156]
[文档链接](http://swoft.org/docs/2.x/zh-CN/common/co.html)
'method'       => [$this, 'requestMethod'],
这样去并发调用的时候, 如果这个函数是需要参数传递的话, 就不能正常调用
PhpHelper::call(...$callback)需要使用可变参数传递, 才能正常调用

**Comment by stelin** [comment]
你要用闭门，文档已经说明，有几种不同的方式，根据不同的场景
