### ISSUE TITLE
swoft定时器 文档无clean  无法清除 

### ISSUE THREAD

**Issue by caojianhui123** [swoft-cloud/swoft#1158]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.7 (by `php bin/swoft -V`)
| Swoole version      | 4.4.4 (by `php --ri swoole`)
| PHP version         | 7.1.31 (by `php -v`)
| Runtime environment | CentOS 7

tick周期性执行 无法清除

**Comment by stelin** [comment]
2.0.8 新增下清除方法封装

**Comment by inhere** [comment]
方法是有的 只是文档上没写。。。
