### ISSUE TITLE
fill触发了两次修改器执行，并且save保存时修改器结果并没有被执行

### ISSUE THREAD

**Issue by zhezhong17** [swoft-cloud/swoft#1167]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | v2.0.7
| Swoole version      | 4.4.5
| PHP version         |  7.2.24
| Runtime environment | Win10/Docker etc.

**Describe the bug**
fill触发了两次setPic方法，并且执行save后，pic字段并没有被setPic修改

```php
// paste code
```

       // 代码
        /** @var User $user */
        $user = $request->user;
        $data = [
            'nickName' => $request->post('nickName'),
            'pic' => $request->post('pic'),
            'backgroundImage' => $request->post('backgroundImage'),
            'sex' => $request->post('sex'),
            'birthdayTime' => $request->post('birthdayTime'),
            'handicap' => $request->post('handicap'),
            'optimum' => $request->post('optimum'),
            'signature' => $request->post('signature'),
            'firstGolfTime' => $request->post('firstGolfTime'),
        ];
        $data['initials'] = getFirstCharter($data['nickName']);

        $user->fill($data);
        $user->save();

      // 修改器
      public function setPic(?string $pic): void
    {
        $this->pic = $this->aliYunOssService->ossArrange($pic, 'user', $this->getId());
    }

   // 修改器执行了两次
   控制台输出  
     ------------------2019-12-17 16:55:33---------------------                                                      
--------------原始image-------------                                                                              
tmp/97ae590d-0b87-41f0-baae-1be437227051.jpg                                                                    
------------------2019-12-17 16:55:33---------------------                                                      
--------------image-------------                                                                                
1984score/user/25/gallery/120365ef9d1f4f8efd6fa77f7988ea9e.jpg                                                  
------------------2019-12-17 16:55:33---------------------                                                      
--------------birthdayTime-------------                                                                         
2019-08-04                                                                                                      
------------------2019-12-17 16:55:33---------------------                                                      
--------------原始image-------------                                                                              
tmp/97ae590d-0b87-41f0-baae-1be437227051.jpg                                                                    
------------------2019-12-17 16:55:33---------------------                                                      
--------------image-------------                                                                                
1984score/user/25/gallery/8e27dc7c192e5d29d8c2b30712676e9b.jpg                                                  
------------------2019-12-17 16:55:33---------------------                                                      
--------------birthdayTime-------------                                                                         
2019-08-04                                                                                                      
2019/12/17-16:56:00 [INFO] App\Task\Crontab\CronTask:minuteTask(52) minute task run: 2019-12-17 16:56:00        
   
     // 实际数据库结果
     pic字段=tmp/97ae590d-0b87-41f0-baae-1be437227051.jpg     // 修改器之前的短

    // 结果就是修改器执行了两次， save保存后还是修改器之前的值

**Comment by stelin** [comment]
感谢反馈，我们查下问题

**Comment by sakuraovq** [comment]
查询会 结果集之后 会调用 setter  
fill 之后也会调用 setter  我试过了没问题 

检查下业务逻辑 开下 DbRanListener 看看执行 sql 是什么样子的

**Comment by zhezhong17** [comment]
场景
    前端设置用户信息，里面含有图片。  要求图片上传到oss


    laravel框架实现，
        保存时： 在修改器里面针对图片字段，进行判断并上传到oss
        查询时： 在获取器里面针对图片字段，进行url组装

    swoft
        查询时： 会调用getXX， 会调用setXXX    ？     
        fill：  会调用setXXX

        查询的时候调用setXXX有什么意义？     

        想上面的场景非常多，不光图片。 其他各种需要转换的字段都可以使用获取器和修改器实现。

        swoft如何实现这样的场景呢？

**Comment by zhezhong17** [comment]
场景
&nbsp;&nbsp;&nbsp;&nbsp;前端设置用户信息，里面含有图片。&nbsp;&nbsp;要求图片上传到oss


&nbsp;&nbsp;&nbsp;&nbsp;laravel框架实现，
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;保存时：&nbsp;在修改器里面针对图片字段，进行判断并上传到oss
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;查询时：&nbsp;在获取器里面针对图片字段，进行url组装

&nbsp;&nbsp;&nbsp;&nbsp;swoft
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;查询时：&nbsp;会调用getXX，&nbsp;会调用setXXX&nbsp;&nbsp;&nbsp;&nbsp;？&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;fill：&nbsp;&nbsp;会调用setXXX

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;查询的时候调用setXXX有什么意义？&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;想上面的场景非常多，不光图片。&nbsp;其他各种需要转换的字段都可以使用获取器和修改器实现。

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;swoft如何实现这样的场景呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"OvO"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 晚上9:33
收件人:&nbsp;"swoft-cloud/swoft"<swoft@noreply.github.com&gt;;
抄送:&nbsp;"折中C"<2548551063@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [swoft-cloud/swoft] fill触发了两次修改器执行，并且save保存时修改器结果并没有被执行 (#1167)




查询会 结果集之后 会调用 setter
 fill 之后也会调用 setter  我试过了没问题
 
检查下业务逻辑 开下 DbRanListener 看看执行 sql 是什么样子的

**Comment by sakuraovq** [comment]
意义不同  业务实现就好了呀  
在 模型事件里面做 不一样嘛
为要在 实体里面写逻辑 
先区分好 分层
