### ISSUE TITLE
crontab 定时任务执行一段时间后，不再执行

### ISSUE THREAD

**Issue by Hetystars** [swoft-cloud/swoft#1168]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.7
| Swoole version      | 4.3.0
| PHP version         | 7.1
| Runtime environment | CentOS 7

**Describe the bug**

1. crontab 定时任务执行一段时间后，不再执行

2. 其中一个work进程cpu占用达到100%[4核8G,开了4个work进程，16个task进程]

**Expected behavior**
   定时任务正常运行

**Screenshots**
   无
**Details**

- 两台机器，其中一台机器上开启了定时任务，cpu占用一直在升高，定时任务已停止；另一台没有开启定时任务，cpu占用也在升高

- http请求中，有大量调用协程任务和异步任务

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
请详细描述下你的问题， 怀疑是投递业务的问题

**Comment by Hetystars** [comment]
-  两台机器，其中一台机器上开启了定时任务，cpu占用一直在升高，定时任务已停止；另一台没有开启定时任务，cpu占用也在升高

- http请求中，有大量调用协程任务和异步任务

**Comment by Hetystars** [comment]
strace 内容:
sudo strace -p 6601 2>&1 | head -n 100
strace: Process 6601 attached

**Comment by stelin** [comment]
你worker开小点，就开和CPU核一样，进程多切换吃CPU

**Comment by inhere** [comment]
@Hetystars  更新版本后，确认下还有问题没
