### ISSUE TITLE
reload不生效

### ISSUE THREAD

**Issue by herenet** [swoft-cloud/swoft#1170]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.7
| Swoole version      | 4.4.12
| PHP version         | 7.2.24
| Runtime environment | Ubuntu

**Describe the bug**

**Expected behavior**

**Screenshots**

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by herenet** [comment]
github 编辑无效。。。
我在这里把问题补充一下：在修改controller或者注解后，reload不会生效。。

**Comment by inhere** [comment]
2.0 reload 不会使代码生效的。 refer https://github.com/swoft-cloud/swoft/issues/1032
