### ISSUE TITLE
work进程falt error，CPU飙高

### ISSUE THREAD

**Issue by webchen** [swoft-cloud/swoft#1172]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.7
| Swoole version      | 4.4.12
| PHP version         | 7.2.25
| Runtime environment | CentOS 7

其实也不能算是BUG吧，可以完善一下

因为是测试服，所以有时会直接用root权限，下面是整个过程

step 1)
sudo php bin/swoft http:start   (success)

step 2)
sudo php bin/swoft http:restart   (success)

step 3)
php bin/swoft http:stop  (fail)

step 4)
sudo kill id

step 5)
php bin/swoft http:restart  (success)

....进程CPU占到80%以上

问题出现了，因为一开始是用sudo启动的，生成的log文件的用户是root权限的，普通用户没有权限（可以衍生为：对日志文件没有权限，再衍生为：对其它资源没有权限）。
因为用的是restart启动的，然后work进程一直报falt error，然后退出，然后master拉起来，然后退出，最后就是CPU飙高。

建议：
1）falt error输出到logs文件里面（现在logs文件里面会有，但不是PHP的原始报错）
2）启动的时候，检查一些必要的文件，资源，权限等，尽量避免出现这样的问题（因为是运行时错误，要启动的时候全部检查出来，也不太可能，只能说尽量吧）
3）master在拉进程的时候，要考虑到CPU，这样出现死循环的拉，对系统不太友好

**Comment by inhere** [comment]
请更新到最新版本，再观察一下，是否还有问题。
