### ISSUE TITLE
SWOFT2.0版本的HTTP CLIENT组件怎么没有了？

### ISSUE THREAD

**Issue by lipengyao2016** [swoft-cloud/swoft#1175]
SWOFT1.0版本的HTTP CLIENT组件有，V2版本为什么去掉了？目前使用Co\Http\Client，经常测试返回statusCode = -2?是什么原因？不是很稳定。有时可以，有时又不行。

**Comment by inhere** [comment]
可以使用 saber 或者 guzzle

**Comment by zl00733** [comment]
saber +1

**Comment by 928799934** [comment]
看到官方文档内开发者注意 里面 写不建议使用 guzzle ,在下面 核心组建里面 http客户端内又建议guzzle 彼此冲突。到底是推荐我们使用还是不让使用

**Comment by inhere** [comment]
> 看到官方文档内开发者注意 里面 写不建议使用 guzzle ,在下面 核心组建里面 http客户端内又建议guzzle 彼此冲突。到底是推荐我们使用还是不让使用

之前swoole没有hook curl时不推荐，后面已经支持curl等功能了。就可以使用了。
