### ISSUE TITLE
内存耗尽

### ISSUE THREAD

**Issue by zhou01** [swoft-cloud/swoft#1176]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0
| Swoole version      | 4.4.10
| PHP version         | 7.2.11
| Runtime environment | CentOS 7

**Describe the bug**
系统运行一段时间后，出现message：
[2019-12-24 15:25:56 *80647.7]	ERROR	php_swoole_server_rshutdown (ERRNO 503): Fatal error: Uncaught ErrorException: Allowed memory size of 134217728 bytes exhausted (tried to allocate 131072 bytes) in /data/wwwroot/api-swoft.mama.cn/vendor/swoft/http-message/src/Response.php:225
Stack trace:
#0 /data/wwwroot/api-swoft.mama.cn/app/Common/ErrorDispatcher.php(62): App\Common\ErrorDispatcher->handleError(1, 'Allowed memory ...', '/data/wwwroot/a...', 225)
#1 [internal function]: App\Common\ErrorDispatcher->App\Common\{closure}()
#2 {main}
  thrown in /data/wwwroot/api-swoft.mama.cn/vendor/swoft/http-message/src/Response.php on line 225
[2019-12-24 15:25:56 $80619.0]	WARNING	swManager_check_exit_status: worker#7[pid=80647] abnormal exit, status=255, signal=0

**Comment by zhou01** [comment]
Swoft version | 2.0.7

**Comment by inhere** [comment]
有啥特殊操作吗？
只用了http-server 还有其他啥吗？

**Comment by zhou01** [comment]
> 只用了http-server

**Comment by zl00733** [comment]
用swoole-tracker 监控内存溢出

**Comment by zhou01** [comment]
在bean.php关闭logger功能之后，用redis（用连接池）的get方法，会导致内存不断增高。（大家可以试试，不知道是不是只有我的才会）

**Comment by liangwhGH** [comment]
好的，加油

**Comment by zhou01** [comment]
> 有啥特殊操作吗？
> 只用了http-server 还有其他啥吗？

在bean.php关闭logger功能之后，用redis（用连接池）的get方法，会导致内存不断增高。

**Comment by zhou01** [comment]
总结问题：使用redis的get方法的时候会调用logger的counting方法，该方法会不断的计数（导致内存泄露的真正原因），一旦把logger设置enable为false，则会导致logger中countting数组不被释放。
Swoft\Redis\Connection\Connection.php
![image](https://user-images.githubusercontent.com/16423689/71608986-daee0000-2bbf-11ea-8ab0-b996680ee21e.png)
Swoft\Log\Logger.php
![image](https://user-images.githubusercontent.com/16423689/71609002-0670ea80-2bc0-11ea-9a48-387b804b061f.png)
![image](https://user-images.githubusercontent.com/16423689/71609009-14267000-2bc0-11ea-8cc5-c09768e31326.png)

**Comment by inhere** [comment]
@zhou01  log 问题已经修复了。等发版
