### ISSUE TITLE
Feature request: Model soft delete and Pagination.

### ISSUE THREAD

**Issue by heshiweij** [swoft-cloud/swoft#1183]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.7
| Swoole version      | 4.4.8
| PHP version         | 7.3.12

**Expected behavior**
用惯了 Laravel，觉得 "软删除" 和 "分页组件" 很好用，希望 Swoft 也可以有。
Soft delete and Pagination are convenient components in Laravel

**Details**

1. Soft delete

软删除让代码更简洁:
If using "soft delete" in laravel, code is very elegant: （有软删除）
```php
User::where('name', 'some')
  ->leftJoin('orders', 'orders.user_id', 'users.id')->get();
```

If no soft delete, we have to go handle "deleted_at"  for every related tables: （无软删除）
```php
User::whereNull('users.deleted_at')
  ->leftJoin('orders', 'orders.user_id', 'users.id')
  ->whereNull('orders.deleted_at')
  ->get();
```

其他原因：
- 自己处理软删除，可能会遗漏，造成不必要的问题
- Migration 组件默认支持 `softDelete()` 方法，那么对应的模型里最好也能支持一下。

Other reasons:
- Let users handle it themselves, it may be missed 
- Blueprint support `softDelete()` method by default, I think It should also be supported in the model.

2. Pagination

Without pagination:

I need a traits 
```php

/**
 * Trait PaginateHelper
 * @package App\Helper
 */
trait PaginateHelper
{

    /**
     * @param Builder $builder
     * @return Builder
     * @throws ApiException
     */
    public function paginate(Builder $builder): Builder
    {
        if (!$builder) {
            throw new ApiException('Builder is null');
        }

        $page = intval(req()->input('page', 1));
        $size = intval(req()->input('size', 10));

        if ($page <= 0) {
            $page = 1;
        }

        if ($size <= 0) {
            $size = 10;
        }

        return $builder->skip(($page - 1) * $size)->limit($size);
    }

    /**
     * @param array $data
     * @param int $total
     * @return array
     */
    public function paginateResponseWrapper(array $data, int $total): array
    {
        $page = intval(req()->input('page', 1));
        $size = intval(req()->input('size', 10));

        return [
            'data' => $data,
            'current_page' => $page,
            'per_page' => $size,
            'total' => $total,
        ];
    }
}

```

and using in controller:

```php
class Controller {
  use PaginateHelper;
  
  public function list(){
       $builder = User::whereNull('deleted_at');
        $total = $builder->count();

        // handle paginate
        $builder = $this->paginate($builder);

        $wrapper = $this->paginateResponseWrapper($this->collect($builder->get(), UserTransformer::class), $total);
        return json_response($wrapper);
  }
}
```

With pagination:
```php
class Controller {
  use PaginateHelper;
  
  public function list(){
       $builder = User::whereNull('deleted_at');
        return json_response($this->collect($builder->paginate(), UserTransformer::class));
  }
}
```

**Comment by sakuraovq** [comment]
`forPage`  Support pagination
![image](https://user-images.githubusercontent.com/30211214/71554500-e07e0580-2a5a-11ea-96b9-3846160a04f7.png) 

`paginate, paginateById` method already support simple paginator.

**Comment by sakuraovq** [comment]
Database design null type, generally not allowed
Soft delete is generally controlled by business design. This makes business more convenient

**Comment by sakuraovq** [comment]
thank you for your advice ~

**Comment by heshiweij** [comment]
Thank you~
