### ISSUE TITLE
db select方法增加fetch_style,fetch_argument参数，以支持pdo控制返回数组的内容的不同方式

### ISSUE THREAD

**Issue by Hetystars** [swoft-cloud/swoft#1186]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.7
| Swoole version      | 4.3.0
| PHP version         | 7.1
| Runtime environment | CentOS 7

**Describe the bug**
db select 不支持传pdo底层获取数据fetch_style， fetch_argument参数
**Expected behavior**
支持传参
**Screenshots**
无
**Details**
  vendor\swoft\db\src\Connection\Connection.php   line 361

> Describe what you are trying to achieve and what goes wrong.

```php
无```

> Provide minimal script to reproduce the issue

```php
    public function select(string $query, array $bindings = [], bool $useReadPdo = true,int $fetch_style = PDO::FETCH_BOTH ): array
    {
        return $this->run($query, $bindings, function ($query, $bindings) use ($useReadPdo, $fetch_style) {
            // For select statements, we'll simply execute the query and return an array
            // of the database result set. Each element in the array will be a single
            // row from the database table, and will either be an array or objects.
            $statement = $this->getPdoForSelect($useReadPdo)->prepare($query);
            $statement = $this->prepared($statement);

            $prepareBindings = $this->prepareBindings($bindings);

            $this->bindValues($statement, $prepareBindings);

            if ($this->fireEvent(DbEvent::SELECTING, $statement, $prepareBindings) === false) {
                return [];
            }

            $statement->execute();

            return $statement->fetchAll($fetch_style);
        });
    }
```

**Comment by Hetystars** [comment]
方便更新的话，麻烦及时更新一下。项目当中存在新老兼容的问题，需统一化处理。仅仅这个问题，重新fork一个db 包，成本太大。新增参数已验证通过
辛苦。

**Comment by sakuraovq** [comment]
我看看~

**Comment by sakuraovq** [comment]
![image](https://user-images.githubusercontent.com/30211214/71554427-d3144b80-2a59-11ea-8bdf-bbf57f42f344.png)
使用改下默认配置就好了呀
![image](https://user-images.githubusercontent.com/30211214/71554436-f7702800-2a59-11ea-847f-39341e17b335.png)

**Comment by sakuraovq** [comment]
默认连接池是使用的数组 可以改的

**Comment by Hetystars** [comment]
一般在一个连接当中，会用到不同的pdo底层fetch_style方式。上面的方式是在不同的连接池当中配置不同的fetchMode，灵活性差一点

**Comment by sakuraovq** [comment]
单独配置一个兼容老项目的连接池 model 指定下连接池就好了呀 这样使用模型更方便 

单独加个方法虽然灵活但是 调用链变长了

**Comment by Hetystars** [comment]
核心原因在FETCH_ASSOC , FETCH_GROUP,FETCH_ASSOC,FETCH_KEY_PAIR,FETCH_CLASSTYPE,FETCH_UNIQUE,FETCH_COLUMN等有若干种组合，单独新配置连接池实现上不可行，且这个参数决定的只是当下获取结果集的返回方式，与连接无关; @sakuraovq

**Comment by Hetystars** [comment]
方便帮更新一下吗，项目急用

**Comment by sakuraovq** [comment]
2.0.8 已经发列
