### ISSUE TITLE
Redis setBit method bug

### ISSUE THREAD

**Issue by kissIce** [swoft-cloud/swoft#1188]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.7
| Swoole version      | 4.4.8
| PHP version         | 7.2.25
| Runtime environment | Mac

**Redis setBit method bug**
The official document show this method expects parameter 3 is int and I give int parameter, But code have Exception,  Exception is Redis command reconnect error(Redis::setBit() expects parameter 3 to be boolean, integer given

**Screenshots**
![image](https://user-images.githubusercontent.com/18099374/71613231-231d1a80-2be0-11ea-8ec5-9b24a8101aa3.png)
![image](https://user-images.githubusercontent.com/18099374/71613236-29ab9200-2be0-11ea-8b46-c37cf62ad6d1.png)

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
    /**
     * 测试服务
     * @RequestMapping(route="test", method=RequestMethod::GET)
     */
    public function test()
    {
        return Redis::setBit('user:sign'.date('ymd'),16,1);
    }
```

**Comment by sakuraovq** [comment]
应该是 redis 版本问题 

看看 redis 文档呢

**Comment by kissIce** [comment]
这应该不是版本的问题， 我在代码里面直接写原生的。然后使用setbit这个方法是可以成功的。
![image](https://user-images.githubusercontent.com/18099374/71650583-dbb69b80-2d51-11ea-90b9-aca29a892f33.png)
redis里面也能查询到该设置的值
![image](https://user-images.githubusercontent.com/18099374/71650614-13254800-2d52-11ea-9acb-ffc08f540f21.png)

**Comment by sakuraovq** [comment]
我查下~

**Comment by sakuraovq** [comment]
注释错了 写 false  / true 就好
