### ISSUE TITLE
事件通过attach闭包注册而非注解引发的问题

### ISSUE THREAD

**Issue by kaychem** [swoft-cloud/swoft#1189]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no

**Details**

因某些业务需要用到动态注册事件名，偶然在源码中找出可以通过 ```bean('eventManager')->attach()``` 的方式注册事件，但操作中发现通过 ```\Swoft::trigger()``` 调用并没有起到任何效果。调用 ```attach```` 注册位置： ```SwooleEvent::START``` 服务启动监听。 ```bean('eventManager')->attach()``` 是一个单例理应可以注册成功的。
```php

<?php declare(strict_types=1);

namespace Jcsp\Cache;

use Jcsp\Cache\Register\CacheRegister;
use Swoft\Bean\BeanFactory;
use Swoft\Event\Annotation\Mapping\Listener;
use Swoft\Event\EventHandlerInterface;
use Swoft\Event\EventInterface;
use Swoft\Event\Manager\EventManager;
use Swoft\Server\SwooleEvent;

/**
 * Class EventRegisterListener
 *
 * @since 2.0
 *
 * @Listener(event=SwooleEvent::START)
 */
class EventRegisterListener implements EventHandlerInterface
{
    /**
     * @param EventInterface $event
     * @throws \ReflectionException
     * @throws \Swoft\Bean\Exception\ContainerException
     * @author kay
     */
    public function handle(EventInterface $event): void
    {
        $datas = CacheRegister::getClearData();
        //添加监听
        /** @var EventManager $eventManager */
        $eventManager = BeanFactory::getBean('eventManager');
        foreach ($datas as $data) {
            if (!($data['data'][3] ?? false)) {
                continue;
            }
            $callable = function (EventInterface $evt) use ($data) {
                $argsMap = func_get_args();
                $key = $data['data'][0] ?? '';
                $prefix = $key ? '' : $data['className'] . '@' . $data['methodName'];
                $key = CacheRegister::formatedKey($prefix, $argsMap, $key);
                Cache::delete($key);
            };
            $eventManager->attach($data['data'][3], $callable);
        }
    }
}

```

**Comment by inhere** [comment]
@kaychem 我测试了下，是可以触发的。

```php
        $em = new EventManager();

        $buffer = '';
        $em->attach('test1', function () use (&$buffer) {
            $buffer = 'data';
        });

        $this->assertSame('', $buffer);
        $em->trigger('test1');
        $this->assertSame('data', $buffer);
```

你注册的时机错了吧，`SwooleEvent::START` 是master进程启动的时候。

**Comment by kaychem** [comment]
> @kaychem 我测试了下，是可以触发的。
> 
> ```
>         $em = new EventManager();
> 
>         $buffer = '';
>         $em->attach('test1', function () use (&$buffer) {
>             $buffer = 'data';
>         });
> 
>         $this->assertSame('', $buffer);
>         $em->trigger('test1');
>         $this->assertSame('data', $buffer);
> ```
> 
> 你注册的时机错了吧，`SwooleEvent::START` 是master进程启动的时候。

你上面是new一个新的```EventManager```，并且在这个新的对象上注册和触发，使用```\ Swoft::trigger()```是无法触发的吧？
我想的是在原bean上注册,这样就能使用```\ Swoft::trigger()```正常触发了？
```SwooleEvent::START```这时候服务启动完毕，应该可以注册呀

**Comment by inhere** [comment]
`SwooleEvent::START` 是master启动时，这时在master进程里，注册了事件有啥用。。。

逻辑执行都在worker进程里啊 😄
