### ISSUE TITLE
rpc调用失败 没有正常走到fallback流程

### ISSUE THREAD

**Issue by yuanliang847** [swoft-cloud/swoft#119]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| Swoft version    | 0.2.2
| Swoole version   | 2.0.12
| PHP version      | 7.2.2

1.  A机器启动RPC服务
2. B机器调用A机器的rpc服务
    使用了fallback
3. A服务关闭
4. B第一次调用失败，有warning报错，并且没有返回fallback的值
![image](https://user-images.githubusercontent.com/11944928/36888491-af8c05f4-1e30-11e8-925c-3232d8403abf.png)

5. B再次调用，走到正常的fallback流程
ps: 只有B调用成功过，然后把A关掉之后的第一次调用会出这个问题，应该是连接被服务端直接关闭了，但是client的那边缓存了导致？

**Comment by stelin** [comment]
已解决，更新版本，要求最新swoole版本
