### ISSUE TITLE
The global middleware can't carry the Http response header when code throws an exception

### ISSUE THREAD

**Issue by heshiweij** [swoft-cloud/swoft#1190]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.7
| Swoole version      | 4.4.8
| PHP version         | 7.3.12
| Runtime environment | CentOS 7

**Details**

全局中间件，在抛出异常的情况下，无法携带已设置的响应头.
The global middleware cannot carry the Http response header when it throws an exception.

这是官方文档提供的跨域中间件示例: [CorsMiddleware](https://www.swoft.org/documents/v2/core-components/http-server/#heading17)
This is an example of cross-domain middleware provided by the official documentation.
```php
/**
     * Process an incoming server request.
     * @param ServerRequestInterface $request
     * @param RequestHandlerInterface $handler
     * @return ResponseInterface
     * @inheritdoc
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        if ('OPTIONS' === $request->getMethod()) {
            $response = Context::mustGet()->getResponse();
            return $this->configResponse($response);
        }
        $response = $handler->handle($request);
        return $this->configResponse($response);
    }

    private function configResponse(ResponseInterface $response)
    {
        return $response
            ->withHeader('Access-Control-Allow-Origin', 'http://mysite')
            ->withHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Accept, Origin, Authorization')
            ->withHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
    }

```

当抛出异常
When we throw an exception in the controller.

```php
/**
     * Test
     * @RequestMapping(route="/test", method={RequestMethod::POST})
     * @return Response
     * @throws \Exception
     */
    public function captcha(): Response
    {
          throw new Exception('foo');
    }
```

然后用 curl 访问该控制器.
Then we access this url.

```shell
curl  beed.zhixiu.vip/api -I
```
Response: 
```
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 02 Jan 2020 09:08:02 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 2214
Connection: keep-alive
**{Missing some headers here!}**  <<<-------
```

虽然可以通过 `nginx.conf` 来解决：
Although it can be solved by `nginx.conf`，Is there a more elegant way？:
```
 # for cors
add_header Access-Control-Allow-Origin *;
add_header Access-Control-Allow-Headers *;
add_header Access-Control-Allow-Methods *;
```

**Comment by inhere** [comment]
你给 `$response = $handler->handle($request);` 用 try catch 包起来，也可以的

**Comment by yumindayu** [comment]
> 你给 `$response = $handler->handle($request);` 用 try catch 包起来，也可以的

这里假如catch捕获到了应该继续怎么处理？$response在catch里是没有的

**Comment by RuizhaoLee** [comment]
我们的实践是：
swoft作为服务提供者，其本身不需要提供跨域CORS的设置，关注好自身业务即可。
关于CORS我们交给nginx（网关）来处理。当需要修改CORS设置时，不需要重启服务

**Comment by inhere** [comment]
> > 你给 `$response = $handler->handle($request);` 用 try catch 包起来，也可以的
> 
> 这里假如catch捕获到了应该继续怎么处理？$response在catch里是没有的

可以 Response::new 或者 从上下文拿个response对象就行。
