### ISSUE TITLE
@controller注解设置了prefix后不生效

### ISSUE THREAD

**Issue by XIONGchanghu** [swoft-cloud/swoft#1191]
![image](https://user-images.githubusercontent.com/15356648/71666806-7f796900-2d9d-11ea-9d24-5f4443883b95.png)

如下截图求大佬帮忙看看

**Comment by XIONGchanghu** [comment]
![image](https://user-images.githubusercontent.com/15356648/71666954-04648280-2d9e-11ea-864b-36af43baf8d2.png)

**Comment by inhere** [comment]
@XIONGchanghu  RequestMapping 设置路由时，以 `/` 开始就会认为这是个完整路由，忽略前缀。

**Comment by XIONGchanghu** [comment]
3Q
