### ISSUE TITLE
How to dynamically change the database connection for the request?

### ISSUE THREAD

**Issue by harishdurga** [swoft-cloud/swoft#1192]
I want to change the database connection parameters like database username,password and database name based on the request parameters. This configuration should be there/available for the current context or request and reset to default once the request is completed.

**Comment by inhere** [comment]
hi @harishdurga  you can refer the https://github.com/swoft-cloud/swoft/blob/master/app/Common/DbSelector.php

**Comment by harishdurga** [comment]
Is it possible to modify the attributes of a database bean dynamically?If yes please provide a reference link

**Comment by inhere** [comment]
Add DbSelector, then config db bean:

```php
'db'        => [
    'class'      => Database::class,
    'dsn'        => 'mysql:dbname=test;host=127.0.0.1',
    'username'   => 'root',
    'password'   => 'swoft123456',
    'dbSelector' => bean(DbSelector::class) // AT HERE
],
'db.pool'   => [
    'class'    => Pool::class,
    'database' => bean('db2')
],
```

Now, When using DB, the db is switched based on the `id` parameter of each request.

please see docs: http://swoft.io/docs/2.x/en/db/selectDb.html

> The data stored in the context is available throughout the request.

**Comment by harishdurga** [comment]
I am checking this framework suitability for a multi tenant application. So basically i will be having n+1 databases for n tenants. based on the sub domain of the incoming request i need to change the database connection for the entire context of the request. I added a global middleware in which i am trying to switch the database connection. Basically i want to use like DB::table('tablename') instead of specifying the database name like DB::table('table_name')->db('database_name'). Please help me how i can handle this scenario

**Comment by harishdurga** [comment]
When i am doing this
`DB::connection('db2.pool')->table('all_crm_users')->select('NAME','PHONE_NUMBER','EMAIL_ID')->get();`
i am getting `[ERROR] App\Exception\Handler\HttpExceptionHandler:handle(40) Call to undefined method Swoft\Db\Connection\MySqlConnection::table()`

**Comment by harishdurga** [comment]
This is my Model file
```
<?php declare(strict_types=1);
/**
 * This file is part of Swoft.
 *
 * @link     https://swoft.org
 * @document https://swoft.org/docs
 * @contact  group@swoft.org
 * @license  https://github.com/swoft-cloud/swoft/blob/master/LICENSE
 */

namespace App\Model\Entity;

use Swoft\Db\Annotation\Mapping\Column;
use Swoft\Db\Annotation\Mapping\Entity;
use Swoft\Db\Annotation\Mapping\Id;
use Swoft\Db\Eloquent\Model;

/**
 *
 * Class CrmUser
 *
 * @since 2.0
 *
 * @Entity(table="all_crm_users",pool="db2.pool")
 */
class CrmUser extends Model
{
    /**
     * @Id()
     * 
     * @Column(name="RUNNING_ID",alias="id")
     *
     * @var int|null
     */
    private $id;

    /**
     * 
     * @Column(name="NAME",alias="name")
     *
     * @var string|null
     */
    private $name;
    
    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }
}

```
And i am fetching data like below but the data is empty in the response
```
$users = CrmUser::where('RUNNING_ID','>',0)->select('RUNNING_ID','NAME','PHONE_NUMBER','EMAIL_ID')->get();
        return context()->getResponse()->withData($users);
```
Output:
```
[
    [],
    [],
    []
]
```

**Comment by harishdurga** [comment]
@inhere please help me with these couple of issues

**Comment by sakuraovq** [comment]
> This is my Model file
> 
> ```
> <?php declare(strict_types=1);
> /**
>  * This file is part of Swoft.
>  *
>  * @link     https://swoft.org
>  * @document https://swoft.org/docs
>  * @contact  group@swoft.org
>  * @license  https://github.com/swoft-cloud/swoft/blob/master/LICENSE
>  */
> 
> namespace App\Model\Entity;
> 
> use Swoft\Db\Annotation\Mapping\Column;
> use Swoft\Db\Annotation\Mapping\Entity;
> use Swoft\Db\Annotation\Mapping\Id;
> use Swoft\Db\Eloquent\Model;
> 
> /**
>  *
>  * Class CrmUser
>  *
>  * @since 2.0
>  *
>  * @Entity(table="all_crm_users",pool="db2.pool")
>  */
> class CrmUser extends Model
> {
>     /**
>      * @Id()
>      * 
>      * @Column(name="RUNNING_ID",alias="id")
>      *
>      * @var int|null
>      */
>     private $id;
> 
>     /**
>      * 
>      * @Column(name="NAME",alias="name")
>      *
>      * @var string|null
>      */
>     private $name;
>     
>     /**
>      * @return int|null
>      */
>     public function getId(): ?int
>     {
>         return $this->id;
>     }
> 
>     /**
>      * @return string|null
>      */
>     public function getName(): ?string
>     {
>         return $this->name;
>     }
> }
> ```
> 
> And i am fetching data like below but the data is empty in the response
> 
> ```
> $users = CrmUser::where('RUNNING_ID','>',0)->select('RUNNING_ID','NAME','PHONE_NUMBER','EMAIL_ID')->get();
>         return context()->getResponse()->withData($users);
> ```
> 
> Output:
> 
> ```
> [
>     [],
>     [],
>     []
> ]
> ```

1. Print the results of the query at that time
2. https://github.com/swoft-cloud/swoft/blob/master/app/Listener/DbRanListener.php  Look at the SQL executed at the time

**Comment by sakuraovq** [comment]
> `DB::connection('db2.pool')->table('all_crm_users')->select('NAME','PHONE_NUMBER','EMAIL_ID')->get();`

use it
    DB::query('db2.pool')->from('all_crm_users')->select('NAME','PHONE_NUMBER','EMAIL_ID')->get();

`DB::connection()` method Already a connection, unable to assemble SQL, Assemble sql using query builder

**Comment by sakuraovq** [comment]
> In that DbSelect class we are setting the database name for the connection. Is it possible to set the username and password as well?

No, DbSelector provides a connection instead of waiting for a connection

Different database username / password, need to use a different connection pool

**Comment by sakuraovq** [comment]
DbSelector uses a different database for the same connection

**Comment by harishdurga** [comment]
@sakuraovq thanks for the reply. i will check with the suggested methods.
