### ISSUE TITLE
 Message sending for specify client

### ISSUE THREAD

**Issue by duythien** [swoft-cloud/swoft#1195]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | ~2.0.0
| Swoole version      | 4.4.7
| PHP version         | 7.2.22
| Runtime environment | Docker

**Describe the bug**
Hello Team
I have a question about function sendToSome, as I know from docs

```
public function sendToSome(string $data, array $receivers = [], array $excluded = [], int $sender = 0, int $pageSize = 50): int
```
My case here: I have a lot of devices IOT(for example I have five devices) connecting via websocket server, then I want to send message for device two. If the device to connect the first time to web socket server, then the $fd=1, so I can send exactly this device.
But maybe we can not detected detect value $fd, so that I can not send message for the device two(device-02)

How would the swoft server know which connection does  device-02 have ?

Any suggestions. Thanks

**Comment by inhere** [comment]
You should store the fd to device relationship to redis (recommended) or db, for example:

device | fd
--------|-----------
 `device-01` | `0`
 `device-02` | `1`

Usage:

```php
$fd = $redis->get('devices:device-02'); // 1

$wsserver->sendTo($fd, 'message');
```

**Comment by duythien** [comment]
@inhere Thank your quick comment. I will try this
