### ISSUE TITLE
请问如何在框架内如何实现http与ws之间的通信呢？比如http处理完之后会主动给某个ws客户端发送消息通知？还是会像swoole官方解释的哪样通过tcp做监听么？求大佬指点

### ISSUE THREAD

**Issue by XIONGchanghu** [swoft-cloud/swoft#1196]
请问如何在框架内如何实现http与ws之间的通信呢？比如http处理完之后会主动给某个ws客户端发送消息通知？还是会像swoole官方解释的哪样通过tcp做监听么？求大佬指点

**Comment by sakuraovq** [comment]
启动 ws 服务的同时 监听 http 就可以了 swoole 有 demo 配置下就好

**Comment by XIONGchanghu** [comment]
@sakuraovq  3Q

**Comment by inhere** [comment]
refer https://github.com/swoft-cloud/swoft/issues/1203
