### ISSUE TITLE
启动的时候一直报内存超出限制，请问什么情况下会这样？

### ISSUE THREAD

**Issue by ronylee** [swoft-cloud/swoft#1201]
![image](https://user-images.githubusercontent.com/3433344/72076550-a51fe880-3330-11ea-8c08-fcd805ffd9e8.png)

**Comment by inhere** [comment]
看下有没有错误 trace。有可能是互相注入，循环依赖导致。

**Comment by ronylee** [comment]
这个项目我在本地，运行正常的，部署到测试环境才会，由于pod启动不了，我无法进入容器查看日志，在本地又无法复现。有好几个项目，都是用swoft只有这个会这样，其它部署上去之后都能正常运行

**Comment by ronylee** [comment]
![image](https://user-images.githubusercontent.com/3433344/72079707-5ecd8800-3336-11ea-9b02-0473a3c63f2c.png)

我好像在本地复现到，可能是这种情况下递归调用

**Comment by inhere** [comment]
你用一样的容器，挂载代码启动试试看

**Comment by ronylee** [comment]
我试过了，在本地用的是，和线上一样的dockerfile构建出来的镜像，是没问题的

**Comment by inhere** [comment]
可以查下具体是哪个bean创建时出问题了？

**Comment by ronylee** [comment]
![image](https://user-images.githubusercontent.com/3433344/72126934-e5bb4880-33a8-11ea-8ce7-49bdd75d5794.png)

找到问题了，这一行，导致的，但是不知道为什么在本地(win10)同样的镜像，运行却可以启动

**Comment by ronylee** [comment]
谢谢！ @inhere
