### ISSUE TITLE
系统无法运行，代码有报错

### ISSUE THREAD

**Issue by cooly-me** [swoft-cloud/swoft#1208]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.8
| Swoole version      | x.y.z 
| PHP version         | 7.3.1 
| Runtime environment | Mac

**Describe the bug**
2020/01/18-17:25:57 [INFO] Swoft\Processor\EnvProcessor:handle(60) Env file(/Users/mazheng/Documents/Projects/PhpProjects/swoft/.env) is loaded
PHP Fatal error:  Declaration of App\Validator\Rule\AlphaDashRule::validate(array $data, string $propertyName, $item, $default = NULL): array must be compatible with Swoft\Validator\Contract\RuleInterface::validate(array $data, string $propertyName, $item, $default = NULL, $strict = false): array in /Users/mazheng/Documents/Projects/PhpProjects/swoft/app/Validator/Rule/AlphaDashRule.php on line 23

**Expected behavior**
框架无法运行

**Screenshots**
<img width="841" alt="Screen Shot 2020-01-18 at 5 27 09 PM" src="https://user-images.githubusercontent.com/24238335/72661666-e8a4e180-3a17-11ea-8dc0-14f320bf4963.png">

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
public function validate(array $data, string $propertyName, $item, $default = null): array
```

> 解决方案

```php
  public function validate(array $data, string $propertyName, $item, $default = null,$strict = false): array
```

**Comment by inhere** [comment]
en, 还没发主项目的版本的。之前的有这个问题。
