### ISSUE TITLE
redis管道传入的回调函数似乎并不执行

### ISSUE THREAD

**Issue by xuanyingcool** [swoft-cloud/swoft#1210]
**swoft 版本是2.0.7**
**回调函数没有执行**
![TIM图片20200120141156](https://user-images.githubusercontent.com/28334148/72702870-12344900-3b8f-11ea-9632-c118bea4c3b1.png)
![TIM图片20200120141214](https://user-images.githubusercontent.com/28334148/72702871-12ccdf80-3b8f-11ea-8654-b092bf6bfb26.png)
![TIM图片20200120141217](https://user-images.githubusercontent.com/28334148/72702873-13657600-3b8f-11ea-90d0-b366fb107cbe.png)

**Comment by sakuraovq** [comment]
不可能的 你看 profile 日志都有是不是 写错了
