### ISSUE TITLE
[suggestion] 执行 migrate 指令，可以指定 db pool

### ISSUE THREAD

**Issue by andiechang** [swoft-cloud/swoft#1212]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.8 (by `php bin/swoft -V`)
| Swoole version      | 4.4.13 (by `php --ri swoole`)
| PHP version         | 7.4.2 (by `php -v`)
| Runtime environment | CentOS 7 in Docker

**Describe the Feature request**
基于多个数据库的 host 或帐密不同，在执行 migrate 指令时，希望可以透过指定 db pool 的方式，连线到指定的数据库连接池。 

数据库设定如下：（host 与 帐密皆不同）
![image](https://user-images.githubusercontent.com/7233960/73511752-d49eae00-4421-11ea-9b19-b0e05a21fda8.png)

**Expected behavior**
增加指定 --pool 的参数，如下：
`php bin/swoft migrate:up --pool db2`

**附注说明**
目前可以透过 --db 参数指定数据库，但是只会使用预设的 db.pool 连接池进行数据库切换。
当 host 或 帐密不同时，会造成 migrate 失败。

**Comment by sakuraovq** [comment]
@Migration(time=20190913234407,pool="db1.pool")
 注解有参数可以指定 pool 不能执行的时候在选择

**Comment by andiechang** [comment]
抱歉没说明清楚。
需求是同一个 migration 档案，需要在不同的数据库都执行一样的迁移行为。
如果使用注解参数指定 pool ，就变成要开很多个相同的档案来处理。

**Comment by sakuraovq** [comment]
http://swoft.io/docs/2.x/zh-CN/tool/devtool/migrations.html  看看文档呢 可以指定不同的数据库运行

**Comment by andiechang** [comment]
> http://swoft.io/docs/2.x/zh-CN/tool/devtool/migrations.html 看看文档呢 可以指定不同的数据库运行

我在 Issue 的附注说明有写了
```
附注说明
目前可以透过 --db 参数指定数据库，但是只会使用预设的 db.pool 连接池进行数据库切换。
当 host 或 帐密不同时，会造成 migrate 失败。
```

**Comment by sakuraovq** [comment]
我们讨论下 没问题会在 2.0.9 支持, 感谢您的建议 ~~~

**Comment by sakuraovq** [comment]
我们支持 一个迁移支持 多个 连接池就可以解决了

**Comment by sakuraovq** [comment]
https://github.com/swoft-cloud/swoft-ext/pull/68
