### ISSUE TITLE
请问哪里可以找到连接池的使用说明

### ISSUE THREAD

**Issue by MrCJJW** [swoft-cloud/swoft#1213]
https://www.swoft.org/documents/v1/framework-core/connection-pool/
v1的版本
所框该链接无效
![image](https://user-images.githubusercontent.com/15009827/74002799-5014d800-49ab-11ea-9e07-748741e42b0e.png)
v2的版本
![微信截图_20200207131636](https://user-images.githubusercontent.com/15009827/74003080-52c3fd00-49ac-11ea-8bda-b8241deaa385.png)

**Comment by inhere** [comment]
http://swoft.io/docs/2.x/zh-CN/db/setting.html
