### ISSUE TITLE
复合主键更新数据出现主键冲突

### ISSUE THREAD

**Issue by wvfeng** [swoft-cloud/swoft#1218]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.8
| Swoole version      |4.4.8
| PHP version         |7.2.20
| Runtime environment | Docker etc.

**Details**

由于实体类中@Id注解只能使用一次，若使用多次最后一次剩下，导致复合主键实体在执行update的过程中只会使用一个主键作为条件，没有作为条件的主键存在的情况下会出现主键冲突错误，另一个主键不存在的情况下可能回导致更新数据条数比预期多的问题

**Comment by sakuraovq** [comment]
符合主键不建议使用 建议都使用自增主键  符合组件 需要手动指定 where 就好了

**Comment by wvfeng** [comment]
现在就是用手动指定 where 解决的，但是为什么不建议使用呢？

**Comment by sakuraovq** [comment]
mysql 用的 innodb B+ 数据结构 适合自增  联合主键其实效果并不是那么好
