### ISSUE TITLE
websocket无法进入中间件

### ISSUE THREAD

**Issue by shuqiangzhou** [swoft-cloud/swoft#1219]
版本信息
![2020-02-15 18-39-29 的屏幕截图](https://user-images.githubusercontent.com/26402118/74586462-880ec180-5022-11ea-810c-78f65aa0cef7.png)
配置信息
![2020-02-15 18-42-48 的屏幕截图](https://user-images.githubusercontent.com/26402118/74586507-fb183800-5022-11ea-8a78-2750d5f976ac.png)
代码
![2020-02-15 18-40-41 的屏幕截图](https://user-images.githubusercontent.com/26402118/74586480-b096bb80-5022-11ea-80f3-efa984659774.png)

调试信息
![2020-02-15 18-41-44 的屏幕截图](https://user-images.githubusercontent.com/26402118/74586497-dcb23c80-5022-11ea-86b7-91aa46901d29.png)

**Comment by inhere** [comment]
@shuqiangzhou  嗯，发现了。当命令上没有中间件时，会导致 配置里的 `middlewares` 失效。

你可以改为 `preMiddlewares` 来避免这个问题。 修复的下个版本发布。

**Comment by yumindayu** [comment]
preMiddlewares 貌似也不行
