### ISSUE TITLE
App::$server return null

### ISSUE THREAD

**Issue by jianhuihi** [swoft-cloud/swoft#122]
App::$server return null

**Comment by inhere** [comment]
能提供更多的相关信息吗？
怎么出现的？
运行环境？

**Comment by jianhuihi** [comment]
sudo php bin/swoft rpc:start
                    Information Panel                     
**********************************************************
* tcp | Host: 0.0.0.0, port: 8099, Model: 3, type: 1
**********************************************************


然后我在app/commands
`<?php
namespace App\Commands;
use Swoft\App;
use Swoft\Console\Bean\Annotation\Command;
use Swoft\Console\Bean\Annotation\Mapping;
use Swoft\Console\Input\Input;
use Swoft\Console\Output\Output;
use Swoft\Core\Coroutine;
use Swoft\Log\Log;
use Swoft\Task\Task;

/**
 * Testdo command
 *
 * @Command(coroutine=true)
 */
class TestCommand {
	/**
	 * this test command
	 *
	 * @Usage
	 * test:{command} [arguments] [options]
	 *
	 * @Options
	 * -o,--o this is command option
	 *
	 * @Arguments
	 * arg this is argument
	 *
	 * @Example
	 * php swoft test:test arg=stelin -o opt
	 *
	 * @param Input  $input
	 * @param Output $output
	 *
	 * @Mapping("test")
	 */
	public function test(Input $input, Output $output) {
        var_dump(App::$server;exit;`

然后命令行模式执行 sudo php bin/swoft test:test

**Comment by jianhuihi** [comment]
____                __ _
/ ___|_      _____  / _| |_
\___ \ \ /\ / / _ \| |_| __|
 ___) \ V  V / (_) |  _| |_
|____/ \_/\_/ \___/|_|  \__|

swoft: 0.2.2, php: 7.1.14, swoole: 2.1.0

**Comment by jianhuihi** [comment]
想在命令行投递task
能在console启动初始化App::$server么？

**Comment by stelin** [comment]
可以这样投递任务，暂时还没有封装 https://wiki.swoole.com/wiki/page/212.html

**Comment by huangzhhui** [comment]
@jianhuihi 你是想通过Command往正在运行的Server里面投递Task给TaskWorker消费吗？

**Comment by stelin** [comment]
@jianhuihi 已支持，任务投递，https://doc.swoft.org/master/zh-CN/console/task.html
