### ISSUE TITLE
版本2.08验证器有问题

### ISSUE THREAD

**Issue by chenglh** [swoft-cloud/swoft#1220]
文档中【验证项】   属性的默认值就是参数的默认值，如果属性没有定义默认值，代表参数没有定义默认值且必须传递。

bug  ： 版本swoft 2.08 中如果key没有传递就没有校验，只有value传错了才抛出验证异常，PHP 7.4，swoole 4.4

**Comment by dongqibin** [comment]
![image](https://user-images.githubusercontent.com/26727769/75218380-16c6cf80-57d5-11ea-9306-9462dda7d92d.png)
我确定都是月亮惹的祸...

**Comment by wcaqrl** [comment]
同样找到了这个问题，也是这段源码，目前只能手动打补丁，蛋疼
https://github.com/swoft-cloud/swoft/issues/1226

**Comment by chenglh** [comment]
需要 打上注解了
@Required()
