### ISSUE TITLE
websocket在setting添加“open_websocket_close_frame”后 关闭websocket报错

### ISSUE THREAD

**Issue by zengzhichao** [swoft-cloud/swoft#1222]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.8 (by `php bin/swoft -V`)
| Swoole version      | 4.4.14 (by `php --ri swoole`)
| PHP version         | 7.3.0 (by `php -v`)
| Runtime environment | Ubuntu

**Describe the bug**
在bean.php wsServer setting添加“'open_websocket_close_frame' => true”后 客户端主动关闭连接后报错

**Screenshots**
![image](https://user-images.githubusercontent.com/30308070/75016520-23da7a80-54c6-11ea-99f8-4c33ded09060.png)
![image](https://user-images.githubusercontent.com/30308070/75016570-440a3980-54c6-11ea-9004-4f83a9acbb4a.png)

**Details**
错误信息：{"messages":"trace[WsMessageExceptionHandler.php:38] Ws server error(parse message error 'json_decode error: Syntax error At \/mnt\/hgfs\/share\/websocket\/vendor\/swoft\/websocket-server\/src\/WsMessageDispatcher.php line 97)","context":[],"level":400,"level_name":"error","channel":"swoft","datetime":"2020-02-21 16:12:30","event":null,"tid":8,"cid":8,"traceid":"","spanid":"","parentid":""}

**Comment by inhere** [comment]
OK 我兼容下

**Comment by zengzhichao** [comment]
> OK 我兼容下

好的 感谢
