### ISSUE TITLE
运行一段时间后work进程中有一个一直不停的重启，请求返回500没有任何日志记录

### ISSUE THREAD

**Issue by herenet** [swoft-cloud/swoft#1224]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.7
| Swoole version      | 4.4.13
| PHP version         | 7.2.15
| Runtime environment | CentOS 7

**Describe the bug**
基本描述如题。具体情况：程序启动后，我有个健康检测1秒钟一次。运行一段时间（一般几天），就不返回数据了，只有500错误码，日志也没有，我看notice日志还在打，自定义的记录SQL的日志也正常打印着。。仔细观察发现有一个worker进程的ID一直在变，说明一直在重新创建进程。strace了一个manager进程返回如下：

wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 23484
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23484, si_uid=0, si_status=0, si_utime=1, si_stime=1} ---
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f5839709b10) = 23496

**Comment by herenet** [comment]
bean.php详细：
`<?php

use App\Process\SqlMonitorProcess;
use Swoft\Db\Database;
use Swoft\Db\Pool;
use Swoft\Http\Server\HttpServer;
use Swoft\Rpc\Server\ServiceServer;
use Swoft\Redis\RedisDb;
use Swoft\Server\SwooleEvent;
use Swoft\Task\Swoole\TaskListener;
use Swoft\Task\Swoole\FinishListener;

return [
    'noticeHandler'      => [
        'logFile' => '@runtime/logs/notice-%d{Y-m-d}.log',
    ],
    'applicationHandler' => [
        'logFile' => '@runtime/logs/error-%d{Y-m-d}.log',
    ],
    'logger'     => [
        'flushRequest' => false,
        'enable'       => true,
        'json'         => false,
    ],
    'httpServer' => [
        'class'   => HttpServer::class,
        'port'    => 18306,
        'listener'  => [
            'rpc'   => bean(ServiceServer::class),
        ],
        'process' => [
            'sqlMonitor' => bean(SqlMonitorProcess::class),
        ],
//        'processPool' => [
//            'class' => \Swoft\Process\ProcessPool::class,
//            'workerNum' => 3
//        ],
        'on'       => [
//            SwooleEvent::TASK   => bean(SyncTaskListener::class),  // Enable sync task
            SwooleEvent::TASK   => bean(TaskListener::class),  // Enable task must task and finish event
            SwooleEvent::FINISH => bean(FinishListener::class)
        ],
        /* @see HttpServer::$setting */
        'setting' => [
            'task_worker_num'       => 4,
            'task_enable_coroutine' => true,
            'worker_num'            => 6
        ]
    ],
    'rpcServer' => [
        'class' => ServiceServer::class,
        'port'  => 18307,
        'setting' => [
            'worker_num' => 8,
        ],
    ],
    'httpDispatcher'    => [
        // Add global http middleware
        'middlewares'      => [

        ],
        'afterMiddlewares' => [
            \Swoft\Http\Server\Middleware\ValidatorMiddleware::class
        ]
    ],
    'db'  => [
        'class'  => Database::class,
        'charset'  => 'utf8mb4',
        'options'  => [],
        'config'   => [
            'collation' => 'utf8mb4_general_ci',
            'strict'    => false,
            'timezone'  => '+8:00',
            'modes'     => 'NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES',
        ],
        'writes' => [
            [
                'dsn'      => 'mysql:dbname=kkb_cloud_passport;host=192.168.100.54',
                'username' => 'test',
                'password' => 'Meihao100@bfbd',
            ],
        ],
        'reads'  => [
            [
                'dsn'      => 'mysql:dbname=kkb_cloud_passport;host=192.168.100.42',
                'username' => 'testread',
                'password' => 'kkbtestread',
            ],
        ],
    ],
    'db.pool' => [
        'class'       => Pool::class,
        'database'    => bean('db'),
        'minActive'   => 10,
        'maxActive'   => 20,
        'maxWait'     => 0,
        'maxWaitTime' => 0,
        'maxIdleTime' => 60,
    ],
    'redis'             => [
        'class'    => RedisDb::class,
        'host'     => '192.168.56.2',
        'port'     => 6379,
        'database' => 0,
        'retryInterval' => 10,
        'readTimeout'   => 0,
        'timeout'       => 0,
        'option'   => [
            'prefix' => 'swoft:',
            'serializer' => 1
        ]
    ],
    'redis.pool'     => [
        'class'   => \Swoft\Redis\Pool::class,
        'redisDb' => \bean('redis'),
        'minActive'   => 10,
        'maxActive'   => 20,
        'maxWait'     => 0,
        'maxWaitTime' => 0,
        'maxIdleTime' => 60,
    ],
    'consul' => [
        'host' => '192.168.100.15',
        'port'  => 8500,
        'timeout' => 2,
    ]
];
`
@stelin @inhere

**Comment by inhere** [comment]
是你这个自定义进程一直在重启吗？

**Comment by herenet** [comment]
> 是你这个自定义进程一直在重启吗？

不是，自定义的进程设置了名字，是可以区分开的。现在因为这个问题，也找不到原因，项目一直不敢上线，真心不想换掉swoft。

**Comment by inhere** [comment]
没有明显的错误日志？ 就是运行一段时间就卡死，worker重启?

**Comment by inhere** [comment]
只有500错误码? 是哪里看到的呢

**Comment by herenet** [comment]
> 只有500错误码? 是哪里看到的呢

请求端，浏览器，httpcode

**Comment by herenet** [comment]
> 没有明显的错误日志？ 就是运行一段时间就卡死，worker重启?

没有日志，我是开了debug的，但是就是没有日志。确认是worker一直在重启，就一个。

**Comment by inhere** [comment]
@herenet 你拉下新版本的组件看看呢
