### ISSUE TITLE
swoft 2.0.8 Validator有问题，验证规则 required 无效。并且不支持batch()批量验证

### ISSUE THREAD

**Issue by wcaqrl** [swoft-cloud/swoft#1226]
![image](https://user-images.githubusercontent.com/31134400/75310084-e3944700-588d-11ea-9d33-c6360f3d7e09.png)
![image](https://user-images.githubusercontent.com/31134400/75310091-edb64580-588d-11ea-9945-64c10693152f.png)
![image](https://user-images.githubusercontent.com/31134400/75310100-f3ac2680-588d-11ea-83c3-1faa5dcc7b2f.png)
![image](https://user-images.githubusercontent.com/31134400/75310110-fb6bcb00-588d-11ea-92ac-7eefaca12f13.png)

**Comment by JasonYH** [comment]
你好我根据你的使用场景仔细检查了一下，并没有发现你说的问题，下面是我的测试截图
<img width="458" alt="issues1" src="https://user-images.githubusercontent.com/18589230/77670087-aa501380-6fc0-11ea-8945-5d9fd6245018.png">
<img width="551" alt="issues2" src="https://user-images.githubusercontent.com/18589230/77670095-ac19d700-6fc0-11ea-950a-73449bd0f180.png">
<img width="691" alt="issues3" src="https://user-images.githubusercontent.com/18589230/77670099-acb26d80-6fc0-11ea-919b-49b76f951f00.png">

**Comment by JasonYH** [comment]
@stelin 关闭一下
