### ISSUE TITLE
全局验证无法使用

### ISSUE THREAD

**Issue by ren-jimmy** [swoft-cloud/swoft#1228]
1.我使用swoft2的validate函数
![image](https://user-images.githubusercontent.com/25098996/75420937-1e70aa80-5974-11ea-9e30-81830b984419.png)
![image](https://user-images.githubusercontent.com/25098996/75420951-2597b880-5974-11ea-8b9f-b9f87e6c5341.png)
![image](https://user-images.githubusercontent.com/25098996/75420966-2d575d00-5974-11ea-8fb6-ebfd29fe12dd.png)

**Comment by JasonYH** [comment]
@stelin 可以关闭了
