### ISSUE TITLE
pgsql组件下载之后少了这个Swoole\Coroutine\PostgreSQL类

### ISSUE THREAD

**Issue by Dexter0215** [swoft-cloud/swoft#1229]
下载了pgsql第三方组件，使用的时候发现Coroutine少了关于postgresql的类，是因为我的swoole出问题了吗

**Comment by inhere** [comment]
这个要自己安装下对应扩展。

**Comment by Dexter0215** [comment]
我也发现这个问题了，可是安装一直不成功

**Comment by Dexter0215** [comment]
> 这个要自己安装下对应扩展。
![image](https://user-images.githubusercontent.com/48578704/75737673-53497c80-5d3b-11ea-8c3b-fa7ac2629ed2.png)
这个扩展的意思是安装在php里吗

**Comment by sakuraovq** [comment]
看看 swoole 文档

**Comment by sakuraovq** [comment]
PostgreSQL swoole 不维护了 不建议使用

**Comment by sakuraovq** [comment]
PostgreSQL swoole 不维护了 不建议使用
