### ISSUE TITLE
Controller想调用Service怎么办？

### ISSUE THREAD

**Issue by jianhuihi** [swoft-cloud/swoft#123]
使用最新1.0的demo代码 想在demoController 直接调用Service
```
        /**
	 * @Reference("user")
	 *
	 * @var \App\Lib\DemoInterface
	 */
	private $demoService;
```

报错
[Semantical Error] The annotation "@Reference" in property App\Controllers\DemoController::$demoService was never imported. Did you maybe forget to add a "use" statement for this annotation

**Comment by huangzhhui** [comment]
请 use 对应的注解的命名空间，参考
https://github.com/swoft-cloud/swoft/blob/master/app/Controllers/RpcController.php
