### ISSUE TITLE
One question about get the data after verification In 2.0.8

### ISSUE THREAD

**Issue by RuizhaoLee** [swoft-cloud/swoft#1230]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.8
| Swoole version      | 4.4.6
| PHP version         | 7.2.24
| Runtime environment | Mac

**Describe the bug**
When I try to use the validator to verify the submitted data in the form of annotation in the controller, like http://swoft.io/docs/2.x/en/validator/controller-validator.html。
Then I got the data after passing the verification through 
```php
$request->getparsedbody(),
```
 I find that the difference with the previous version is that there is an additional subscript [0].

The detailed code is as follows：

```php
  /**
     *  Create permission routing method. 
     * @RequestMapping(route="routing", method={RequestMethod::POST})
     * @Validate(validator=PermissionRoutingDto::class)
     * @param Request $request
     * @return Wrapper
     */
    public function createRouting(Request $request):Wrapper
    {
        $dto = ObjectHelper::init(new PermissionRoutingDto(), $request->getParsedBody()[0]);
        return Wrapper::new()
            ->setData($this->service->createRoutingProvider($dto));
    }
```

When I try to use ***var_dump*** to output some information, I find the results are as follows:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/35215628/76000407-a0e20700-5f3e-11ea-81af-01ff7b2746f2.png">

> I want to know if this is a bug?

**Comment by JasonYH** [comment]
Hello, according to your description, we re-checked the test again and did not find this problem. Please check whether there is a problem with the data you submitted, or you can inform the detailed reproduction steps. Thank you
<img width="458" alt="issues1" src="https://user-images.githubusercontent.com/18589230/77671851-20ee1080-6fc3-11ea-8147-f53016bd62e7.png">
![image](https://user-images.githubusercontent.com/18589230/77671839-1d5a8980-6fc3-11ea-91ee-b6829104f684.png)
![image](https://user-images.githubusercontent.com/18589230/77671897-319e8680-6fc3-11ea-80e7-ed53294c17a2.png)

**Comment by JasonYH** [comment]
@stelin close question
