### ISSUE TITLE
Entity设置默认值后，虽然select没有取出该字段，在返回结果时也会把这个字段给返回

### ISSUE THREAD

**Issue by ChangeChe** [swoft-cloud/swoft#1234]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.7
| Swoole version      | 4.4.6
| PHP version         | 7.4.1
| Runtime environment | Docker

**Describe the bug**
Entity设置某个column的默认值后，在get/first操作时，没有设置取出该字段，但在结果里还是有这个字段

**Expected behavior**
返回的字段应该要按传入的照样返回，不期望加入其他元素

**Comment by RuizhaoLee** [comment]
是在Entity类中设置了默认值，但是数据库里面是空值吗？

**Comment by ChangeChe** [comment]
Entity类中设置的默认值是空(0或者空字符串)。数据库是空值是什么意思？指的是这个字段的默认值吗？

**Comment by ChangeChe** [comment]
> Entity类中设置的默认值是空(0或者空字符串)。数据库是空值是什么意思？指的是这个字段的默认值吗？

我并没有取出这个字段，所以跟数据库里是什么没有关系

**Comment by sakuraovq** [comment]
这个实体属性设置默认值无效 别设置默认值 这是和数据库一一对应的

**Comment by sakuraovq** [comment]
查询只会查询出 指定了字段的

**Comment by ChangeChe** [comment]
> 查询只会查询出 指定了字段的

查询只查出了指定字段，但是newFromBuilder/toArray时把entity里有默认值的又给同步进去了。
