### ISSUE TITLE
swoft 内存占用很大如何优化

### ISSUE THREAD

**Issue by ronylee** [swoft-cloud/swoft#1235]
swoft 项目上线后，发现占用内存太大，work_num = 30，max_request = 10 , 程序一启动就占了1.3 G的内存，检查代码没发现有什么，内存泄漏的不合理的写法， 请问可以怎么优化么？

**Comment by RuizhaoLee** [comment]
建议采用内存分析工具查看下进程的使用情况，另外swoole版本与PHP版本也有一定关系，可以尝试把更详细的配置、参数等贴上来。大家一起分析问题。

**Comment by ronylee** [comment]
版本：PHP: 7.2.28, Swoft: 2.0.8, Swoole: 4.4.16

配置：

# http server
task_worker_num=2
worker_num=20
task_max_request=10
max_request=10

# db pool
'db.pool' => [
    'class'       => \Swoft\Db\Pool::class,
    'database'    => \bean('db'),
    'minActive'   => 2,
    'maxActive'   => 5,
    'maxWait'     => 0,
    'maxWaitTime' => 0,
    'maxIdleTime' => 60,
 ]

**Comment by RuizhaoLee** [comment]
检查下是否有进程任务，我按照你的配置跑了一个空的Swoft项目，占用情况如下：

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/35215628/76704709-d2fd2100-6715-11ea-8d1a-0727cd3bbbea.png">
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/35215628/76704821-8fef7d80-6716-11ea-8506-ed122730f39c.png">

**Comment by RuizhaoLee** [comment]
用一个生成环境的系统配置了你的参数后，占用情况如下：
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/35215628/76705052-1fe1f700-6718-11ea-8c1f-57c1a98f9a24.png">

**Comment by ronylee** [comment]
> 用一个生产环境的系统配置了你的参数后，占用情况如下：
> <img alt="image" width="1132" src="https://user-images.githubusercontent.com/35215628/76705085-75b69f00-6718-11ea-8932-3a59b9eda0fe.png">

你这是不是开了30个进程，只用了80MB的内存，我程序里面跑 http 接口的逻辑，还有使用了 RPC , 就是集成在一起开了两个端口

**Comment by ronylee** [comment]
我们用k8s上去之后发现整个pod的内存居然跑到3g，一个日志notice没有关掉，一直在写，还有控制台的日志输出，开了max_request 进程释放内存控制台就一直有日志，磁盘io较高，导致缓冲区占用了比较多的内存

**Comment by ronylee** [comment]
@RuizhaoLee  谢谢 ！

**Comment by 583128870** [comment]
> > 用一个生产环境的系统配置了你的参数后，占用情况如下：
> > <img alt="图片" width="1132" src="https://user-images.githubusercontent.com/35215628/76705085-75b69f00-6718-11ea-8932-3a59b9eda0fe.png">
> 
> 你这是不是开了30个进程，只用了80MB的内存，我程序里面跑http接口的逻辑，还有使用了RPC，就是集成在一起开了两个端口
> 
> task进程虽然有开了2个进程，但几乎就没有用到到



> 我们用k8s上去之后发现整个pod的内存居然跑到3g，注意没有关掉，一直在写，还有控制台的日志输出，开了max_request进程释放内存控制台就一直一直有日志，磁盘io较旧高，导致罚款占用了比较多的内存

大佬能提供一份k8s部署swoft的yaml文件写法吗
