### ISSUE TITLE
Swoft框架实体模型查询加入到容器后，查询出数据不对，出现BUG

### ISSUE THREAD

**Issue by huangshunyang** [swoft-cloud/swoft#1240]
swoft框架我将entity实体模型加上@Bean注解后，然后用实体查询出来的数据全部是最后一条，只要把实体的@Bean注解去掉，查询出来的数据又出现正常！

**Comment by sakuraovq** [comment]
实体不需要加 bean 喔

**Comment by sakuraovq** [comment]
实体是原型类型的 每次 clone 出来的不需要 用户去干预
