### ISSUE TITLE
Mysql表主键id是int类型 insertGetId方法返回的主键是string类型

### ISSUE THREAD

**Issue by landyXU** [swoft-cloud/swoft#1243]
![image](https://user-images.githubusercontent.com/20528643/77621302-24f44100-6f77-11ea-8718-5942230c348a.png)

**Comment by sakuraovq** [comment]
pdo 返回就是 string 的 可以用模型 会转义的

**Comment by landyXU** [comment]
还有一个问题就是,websocket自动关闭报错session丢失,错误码:1006
![image](https://user-images.githubusercontent.com/20528643/77867449-d5a95b80-7269-11ea-82c6-f4cb8c1c3382.png)
