### ISSUE TITLE
Validator空判断BUG，以及引用BUG

### ISSUE THREAD

**Issue by herenet** [swoft-cloud/swoft#1244]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.8
| Swoole version      | 4.4.13
| PHP version         | 7.2.15
| Runtime environment | CentOS 7

**Describe the bug**
1、在配置validator时，设制了NotEmpty，判断不生效，除非设置一个空字符串的默认值。
2、在Controller中使用Validator时，不能使用类名称的方式传参，必须使用字符串（validator声明的名称），否则提示找不到对应的validator类。

**Screenshots**
<img width="613" alt="image" src="https://user-images.githubusercontent.com/568403/77820197-66bdec80-711b-11ea-97f9-78285886e775.png">
<img width="590" alt="image" src="https://user-images.githubusercontent.com/568403/77820217-92d96d80-711b-11ea-8fd8-3e3f60a7df1b.png">

**Comment by JasonYH** [comment]
您好，底层原理是因为，如果你设置了一个验证字段，并且没有使用 @Rrequired 属性的时候，如果在请求的参数中没有这个字段，则会自动忽略，并不会拦截，可是如果你设置了默认值为 ‘’空字符串，那么如果在你的请求参数中没有这个字段，那么框架会自动根据你的默认值构建一个参数，然后再进行验证，正好你的默认值是 ‘’ 空字符串，命中了 @NotEmpty 规则所以会被拦截。
你可以添加一个@Required 的规则，这样如果您的请求中不包含此字段，将会被强制拦截。

**Comment by JasonYH** [comment]
@stelin 关一下issues

**Comment by herenet** [comment]
> @stelin 关一下issues

加required一样。。
<img width="624" alt="image" src="https://user-images.githubusercontent.com/568403/77820738-590a6600-711f-11ea-9267-9253de72e97f.png">

**Comment by herenet** [comment]
> @stelin 关一下issues

第二个问题，确认解决了，是我这边使用的问题。

**Comment by herenet** [comment]
这个requried就是一个空类
<img width="461" alt="image" src="https://user-images.githubusercontent.com/568403/77820820-27de6580-7120-11ea-9c50-a850d132fb58.png">

**Comment by JasonYH** [comment]
你好我这边并不会这样，加了required 后会强制检查必须请求中有这个参数，当请求中有这个参数时，如果给了空，就会触发 notempt 的规则
![image](https://user-images.githubusercontent.com/18589230/77824323-ddb7ad00-713c-11ea-9c7f-b6d654066dda.png)
![image](https://user-images.githubusercontent.com/18589230/77824342-017af300-713d-11ea-9aa2-254a7b09ca39.png)

![image](https://user-images.githubusercontent.com/18589230/77824364-23747580-713d-11ea-9816-bf3d4ec28d61.png)

**Comment by JasonYH** [comment]
close #1244

**Comment by gaobinzhan** [comment]
我这边也是对应的问题 我觉得你们调试的时候 应该用IsInt 别用IsString

**Comment by gaobinzhan** [comment]
解决了 注解写错了 写成双引号了

**Comment by gaobinzhan** [comment]
不应该写引号的
