### ISSUE TITLE
v2.0.8，MySQL数据库连接池错误：Pool error is Create connection error(SQLSTATE[HY000] [2006] MySQL server has gone away)

### ISSUE THREAD

**Issue by ennm** [swoft-cloud/swoft#1248]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.8
| Swoole version      | 4.4.1
| PHP version         | 7.3.8
| Runtime environment | centos

**Describe the bug**

MySQL连接池错误：Pool error is Create connection error(SQLSTATE[HY000] [2006] MySQL server has gone away)  导致应用被卡住
这时候使用Navicat客户端是可以访问数据库的，并且在项目里去掉了连接池之后就可以正常访问

这是我的连接池配置，希望得到您的回复
'db' => [
        'class' => Database::class,
        'dsn' => sprintf('mysql:dbname=%s;host=%s', env('DB_NAME'), env('DB_HOST')),
        'username' => env('DB_USER'),
        'password' => env('DB_PWD'),
        'prefix' => env('DB_PREFIX'),
        'charset' => 'utf8mb4',
    ],
'db.pool' => [
        'class' => Pool::class,
        'database' => bean('db'),
        'minActive' => 1,
        'maxActive' => 20,
        'maxWait' => 0,
        'maxWaitTime' => 0,
        'maxIdleTime' => 90,
        'timeout' => 10,
    ]

**Comment by sakuraovq** [comment]
造成这样的原因最常见的就是采集或者新旧数据转化——也就是一般说sql操作的时间过长，或者是传送的数据太大(例如使用insert ... values的语句过长， 这种情况可以通过修改max_allowed_packed的配置参数来避免，也可以在程序中将数据分批插入(使用mysql limit进行分页，循环分批处理数据))；

应用程序（比如PHP）长时间的执行批量的MYSQL语句。执行一个SQL，但SQL语句过大或者语句中含有BLOB或者longblob字段。比如，图片数据的处理。都容易引起MySQL server has gone away。
