### ISSUE TITLE
websocket自动关闭报错session丢失,错误码:1006

### ISSUE THREAD

**Issue by inhere** [swoft-cloud/swoft#1249]
还有一个问题就是,websocket自动关闭报错session丢失,错误码:1006
![image](https://user-images.githubusercontent.com/20528643/77867449-d5a95b80-7269-11ea-82c6-f4cb8c1c3382.png)

_Originally posted by @landyXU in https://github.com/swoft-cloud/swoft/issues/1243#issuecomment-605738241_

**Comment by inhere** [comment]
@landyXU 自动关闭指的是？

**Comment by landyXU** [comment]
经常报出session丢失的错误,感觉是框架里实现的Session类的问题

**Comment by inhere** [comment]
如果worker重启了，相关数据就会丢失

**Comment by inhere** [comment]
在 2.0.8 后，已经提供了自定义存储session的功能。你可以将这些信息存储到 swoole table 或者 redis 中去。 reload worker 后 session 信息会自动恢复。

**Comment by inhere** [comment]
@landyXU  http://swoft.io/docs/2.x/zh-CN/websocket-server/config.html#%E8%BF%9E%E6%8E%A5%E6%95%B0%E6%8D%AE%E5%AD%98%E5%82%A8
