### ISSUE TITLE
bean.php的db配置中writes与reads使用config无法获取正确的配置参数

### ISSUE THREAD

**Issue by herenet** [swoft-cloud/swoft#1253]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.8
| Swoole version      | 4.4.13
| PHP version         | 7.2.15
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Describe the bug**
<img width="518" alt="image" src="https://user-images.githubusercontent.com/568403/79101495-32912f80-7d9b-11ea-9523-7cda2497c79d.png">

2020/04/13-15:22:58 [ERROR] App\Exception\Handler\HttpExceptionHandler:handle(52) Pool error is Create connection error(Dsn(${.config.mysql.write.dsn}) format error, please check Dsn) file(/data/app/swoft-im/vendor/swoft/db/src/Connection/Connection.php) line (1144) file=/data/app/swoft-im/vendor/swoft/connection-pool/src/AbstractPool.php line=250

其它配置项没有问。

**Comment by inhere** [comment]
@herenet  你说 `mysql.write.user` 这些都获取正确,但dsn这个错了?

**Comment by herenet** [comment]
全部都是错了。只要是数组的第三层，就不能解析配置的变量

**Comment by herenet** [comment]
@inhere 我看了源代码，配置文件只支持两层数组，再多就不再解析$(.config.*)了。

**Comment by herenet** [comment]
@inhere 
<img width="549" alt="image" src="https://user-images.githubusercontent.com/568403/79104511-535c8380-7da1-11ea-9cca-8bb83a5a4891.png">
改成这样就可以了。

**Comment by sakuraovq** [comment]
👍
