### ISSUE TITLE
Swoft2.0.9 RPC组件的依赖问题

### ISSUE THREAD

**Issue by RuizhaoLee** [swoft-cloud/swoft#1254]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.9
| Swoole version      | 4.4.16
| PHP version         | 7.4.4
| Runtime environment | Mac 

**Describe the bug**
在2.0.9中只使用RPC服务，不加在其他多余composer依赖时：

<img width="418" alt="image" src="https://user-images.githubusercontent.com/35215628/79107596-3925a400-7da7-11ea-8223-2c20e7a72048.png">

无法启动。报错内容如下：

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/35215628/79107666-66725200-7da7-11ea-9e56-ea60b34164ab.png">

需要加上
"swoft/http-server": "~2.0.0" 
依赖才能正常启动

**Comment by inhere** [comment]
@RuizhaoLee  应该是 devtool 里面使用了http中间件。
