### ISSUE TITLE
在@cron定时任务中 无法使用guzzle发送一个http post请求

### ISSUE THREAD

**Issue by zengzhichao** [swoft-cloud/swoft#1256]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 2.0.8 (by `php bin/swoft -V`)
| Swoole version      | 4.4.14 (by `php --ri swoole`)
| PHP version         | 7.4 (by `php -v`)
| Runtime environment | Ubuntu

**Describe the bug**
在 `@cron` 定时任务中 无法使用guzzle发送一个http post请求，并且日志没有报错

**Screenshots**
![image](https://user-images.githubusercontent.com/30308070/79216982-a0635700-7e80-11ea-8b76-bc62e5e41b87.png)

**Details**
想在定时任务中在某个条件下 使用guzzle向后台服务器发送一个post请求 但是没有成功，日志没有错误记录。

**Comment by pkdog** [comment]
可以尝试用bean去调用一下相关cron下的方法，先验证下是不是有问题。例如
$crontab = BeanFactory::getBean("crontab");
$crontab->execute("任务bean名称", "方法名");

**Comment by zengzhichao** [comment]
> 可以尝试用bean去调用一下相关cron下的方法，先验证下是不是有问题。例如
> $crontab = BeanFactory::getBean("crontab");
> $crontab->execute("任务bean名称", "方法名");

方法应该是没问题的
因为我在websocket的module文件下 @onClose()都是可以正常使用
![image](https://user-images.githubusercontent.com/30308070/79228345-d78f3380-7e93-11ea-88ed-bca434c212a0.png)

只是把这个方法复制过去到@Scheduled定时任务下

**Comment by inhere** [comment]
确认下 cron 是否按预期执行了的。

**Comment by zengzhichao** [comment]
> 确认下 cron 是否按预期执行了的。

是的 按照预期执行了 我先调用了
Log::info(xxxxx);
$this->httpFun();
// 删除redis数据
Redis::del(xxx);
redis都按照预期清空了 但是log没有打印出来 而且http请求也没有执行

**Comment by zengzhichao** [comment]
抱歉 是我这边的问题 http请求地址没有写好。
