### ISSUE TITLE
匿名函数声明为static及collection的使用会造成内存泄漏或者其他问题吗?

### ISSUE THREAD

**Issue by lzylyd** [swoft-cloud/swoft#1263]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 2
| Swoole version      |
| PHP version         | 7.4
| Runtime environment |

我看到 Swoft\Stdlib\Collection中声明返回了很多static修饰的值,请问诸如 `$bar =static function($foo){}`这种的函数会带来副作用吗

**Comment by inhere** [comment]
:) 暂时没有发现有啥副作用

**Comment by lzylyd** [comment]
:) 谢谢
