### ISSUE TITLE
第一次请求比较慢 macOs 2017 MBP

### ISSUE THREAD

**Issue by jianhuihi** [swoft-cloud/swoft#127]
`
'worker_num' => env('WORKER_NUM', 5),
'task_worker_num' => env('TASK_WORKER_NUM', 100),
`

最后测试发现是由于这两个参数引起的,将近10秒左右 负载也在攀升

若按照默认配置 则不会出现这个问题
`
'worker_num' => env('WORKER_NUM', 1),
'task_worker_num' => env('TASK_WORKER_NUM', 1),
`
swoft: 1.0.0, php: 7.1.14, swoole: 2.1.0

![image](https://user-images.githubusercontent.com/4176545/37143131-2bd8be18-22f5-11e8-808d-011dd62bd1a2.png)

**Comment by huangzhhui** [comment]
Docker 环境 还是 本机环境？

**Comment by jianhuihi** [comment]
本机环境

**Comment by huangzhhui** [comment]
![tim 20180309131731](https://user-images.githubusercontent.com/12077148/37191718-570abc9c-239c-11e8-899d-b80473607158.png)
Worker在初始化过程中是没法响应请求的，请在看到"Server started."后再发起请求，该提示语需执行`composer update`后才会出现
