### ISSUE TITLE
mysql decimal 小数点超过14位，生成实体的时候会变成科学计算法

### ISSUE THREAD

**Issue by yiqunhaitun** [swoft-cloud/swoft#1270]
mysql decimal 小数点超过10位，生成实体的时候会变成科学计算法

**Comment by sakuraovq** [comment]
转成 浮点型了 应该是双精度吧?

**Comment by yiqunhaitun** [comment]
@sakuraovq decimal 是不应该转成 浮点型，应该是 string

**Comment by sakuraovq** [comment]
把 @var 注释改成 string 就好

**Comment by sakuraovq** [comment]
模型会根据 @column 字段下 的 @var 注释转义类型
