### ISSUE TITLE
2.0.9中路由匹配问题

### ISSUE THREAD

**Issue by RuizhaoLee** [swoft-cloud/swoft#1281]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.9
| Swoole version      | 4.4.15
| PHP version         | 7.2
| Runtime environment | Mac

![image](https://user-images.githubusercontent.com/35215628/81490348-e6f77600-92b3-11ea-9c31-68ad4ca3b87f.png)

**Comment by inhere** [comment]
你这样的两个路由很明显会冲突啊！上面的匹配已经包含了下面的了

**Comment by lizhichao** [comment]
@RuizhaoLee 这是一个路由优先级问题，市面上的路由大部分都有这个缺陷。

**Comment by lizhichao** [comment]
可以看这个 https://github.com/lizhichao/one-doc/blob/master/%E8%B7%AF%E7%94%B1.md

**Comment by inhere** [comment]
@RuizhaoLee  你第一个路由的匹配规则设置的太宽泛了 `"uuid"="\S+"` 

- 你不加这个，默认的规则是匹配非 `/` 字符，不会包含第二个
- 或者匹配写严格点

**Comment by RuizhaoLee** [comment]
> @RuizhaoLee 你第一个路由的匹配规则设置的太宽泛了 `"uuid"="\S+"` (匹配任何非空白字符)
> 
> * 你不加这个，默认的规则是匹配非 `/` 字符，不会包含第二个
> * 或者匹配写严格点

感谢提醒，已经采用更加严格的正则来处理了。
