### ISSUE TITLE
验证器 Mobile方法 报错

### ISSUE THREAD

**Issue by first236108** [swoft-cloud/swoft#1283]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.9
| Swoole version      | 4.4.1
| PHP version         | 7.2.6
| Runtime environment | CentOS 7.4.

**Describe the bug**
我新写的验证器，包含@Mobile()，但报错，无法启动服务

**验证器代码如下**
```php
<?php declare(strict_types=1);

namespace App\Validator;

use Swoft\Validator\Annotation\Mapping\Mobile;
use Swoft\Validator\Annotation\Mapping\Length;
use Swoft\Validator\Annotation\Mapping\Validator;

/**
 * Class CommonValidator
 *
 * @since 2.0
 *
 * @Validator(name="CommonValidator")
 */
class CommonValidator
{

    /**
     * @Mobile(message="手机号错误")
     *
     * @var string
     */
    protected $mobile;
    
    /**
     * @Length(min=1,message="请填写收货人")
     *
     * @var string
     */
    protected $consignee;
}

```

**报错**
`Swoft\Validator\Exception\ValidatorException(code:0) Property(CommonValidator->consignee) must be define `@XxxType``

> 试了共它@IsInt，@IsString都没有问题，请问，这是bug吗？ 实在没找到如何验证手机号的示例，希望增加几个验证示例。

感谢swoole、swoft团队

**Comment by inhere** [comment]
报这个错误，应该是必须加类型：

```php
 	/**
     * @IsString()
     * @Mobile(message="手机号错误")
     *
     * @var string
     */
    protected $mobile;
```

**Comment by JasonYH** [comment]
你自定义的是条件规则，验证器必须要有个基础类型 @Isxxx() 这样的注解
