### ISSUE TITLE
百度移动版蜘蛛访问网站时会报rpc调用异常

### ISSUE THREAD

**Issue by linjuchen** [swoft-cloud/swoft#1288]
百度移动版蜘蛛访问网站时会报rpc调用异常。
源码：
![图片](https://user-images.githubusercontent.com/33847736/81761710-3a103980-94fd-11ea-9d83-17ccfdef8cfe.png)
输出结果：
![图片](https://user-images.githubusercontent.com/33847736/81761732-472d2880-94fd-11ea-8895-a6051423c8be.png)

可以看出来  json_encode没有输出结果

100% 随时都可以复现。

**Comment by inhere** [comment]
是蜘蛛请求到了rpc的端口导致的？ 还是内部http使用了这个 `user-agent` 带过去请求rpc 导致的

**Comment by linjuchen** [comment]
是蜘蛛访问了http接口都会这样。测试只有一个百度的移动蜘蛛agent才会，其他都正常。
