### ISSUE TITLE
 缺少一个实体到数据表的映射工具

### ISSUE THREAD

**Issue by JiankangMai** [swoft-cloud/swoft#129]
当前有一个用于数据表转换成实体的entity:create工具，缺少一个实体生成数据表的工具用于初始化数据库。

**Comment by patrickkh7788** [comment]
数据迁移以及数据库升级的支持

**Comment by stelin** [comment]
@JiankangMai  2.0 已经正式发布，建议升级到2.0 2.0 数据库提供迁移、实体生成。
