### ISSUE TITLE
怎么在command里获取websocket连接并发送

### ISSUE THREAD

**Issue by yumindayu** [swoft-cloud/swoft#1304]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z (by `php bin/swoft -V`)
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Describe the bug**

**Expected behavior**

**Screenshots**

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
command 是一个新的进程。无法跟server直接联系的，可以发http请求到ws server里再处理
