### ISSUE TITLE
TCP服务 无法接受到消息

### ISSUE THREAD

**Issue by 982865723** [swoft-cloud/swoft#1305]
onConnect 和 onClose 可以出发  onReceive 无法收到消息

RECEIVE 和 RECEIVE_BEFORE 都无效

配置

```php
  /** @see \Swoft\Tcp\Server\TcpServer */
    'tcpServer'   => [
        'class'   => TcpServer::class,
        'port' => 18307,
        'debug' => env('SWOFT_DEBUG', 0),
        /* @see TcpServer::$setting */
        'setting' => [
            'log_file' => alias('@runtime/swoole.log'),
        ],
    ],
    /** @see \Swoft\Tcp\Protocol */
    'tcpServerProtocol'  => [
        'type' => \Swoft\Tcp\Packer\SimpleTokenPacker::TYPE,
    ],
    /** @see \Swoft\Tcp\Server\TcpDispatcher */
    'tcpDispatcher'      => [
        'enable' => false,
        'middlewares' => [
            \App\Tcp\Middleware\GlobalTcpMiddleware::class
        ],
    ],
```

Listener 监听

```php
<?php declare(strict_types=1);
/**
 * This file is part of Swoft.
 *
 * @link     https://swoft.org
 * @document https://swoft.org/docs
 * @contact  group@swoft.org
 * @license  https://github.com/swoft-cloud/swoft/blob/master/LICENSE
 */

namespace App\Listener\Test;

use Swoft\Event\Annotation\Mapping\Listener;
use Swoft\Event\EventHandlerInterface;
use Swoft\Event\EventInterface;
use Swoft\Log\Helper\CLog;
use Swoft\Server\ServerEvent;
use Swoft\Tcp\Server\TcpServerEvent;

/**
 * Class TaskProcessListener
 *
 * @since 2.0
 *
 * @Listener(TcpServerEvent::RECEIVE)
 */
class TestListener implements EventHandlerInterface
{
    /**
     * @param EventInterface $event
     */
    public function handle(EventInterface $event): void
    {
        vdump ('RECEIVE');
    }
}
```

**Comment by xutao123777** [comment]
我的一样
2020/07/17 15:27:26 [DEBUG] [WID:0, PID:521, TID:3, CID:3] Receive: conn#1 received client request, begin init context 
2020/07/17-15:27:26 [INFO] Tcp protocol data packer is Swoft\Tcp\Packer\SimpleTokenPacker
2020/07/17 15:27:26 [ERROR] [WID:0, PID:521, TID:3, CID:3] Receive: conn#1 error: request command '{"cmd":"demo.index","data":"i' is not found of the tcp server 
2020/07/17-15:27:26 [ERROR] Swoft\Tcp\Server\TcpErrorDispatcher:defaultHandle(100) Tcp Receive Error(no handler, Swoft\Tcp\Server\Exception\CommandNotFoundException): request command '{"cmd":"demo.index","data":"i' is not found of the tcp server
At File /data/Swoft/vendor/swoft/tcp-server/src/TcpDispatcher.php line 129
Trace:
#0 /data/Swoft/vendor/swoft/tcp-server/src/Swoole/ReceiveListener.php(70): Swoft\Tcp\Server\TcpDispatcher->dispatch(Object(Swoft\Tcp\Server\Request), Object(Swoft\Tcp\Server\Response))
#1 {main}
2020/07/17 15:27:26 [DEBUG] [WID:0, PID:521, TID:4, CID:4] Close: conn#1 has been closed. server conn count 0 
2020/07/17 15:27:26 [DEBUG] [WID:0, PID:521, TID:4, CID:4] Close: conn#1 meta info: 
{
    "fd": 1,
    "ip": "192.168.199.1",
    "port": 57729,
    "connectTime": 1594970846,
    "connectFtime": 1594970846.192475
}

**Comment by inhere** [comment]
请求的数据跟打包协议 `Swoft\Tcp\Packer\SimpleTokenPacker` 不匹配

**Comment by zhongjie19** [comment]
@inhere 尝试了用了json，也是不行
{"cmd":"echo","data":"i an client","ext":[]}
