### ISSUE TITLE
开发组件的文档没有了,旧版和新版的文档里面都找不到了,能否提供一下,顺带收录一下他人写的组件,方便使用swoft开发

### ISSUE THREAD

**Issue by nanyounanyounan** [swoft-cloud/swoft#1306]
开发组件的文档没有了,旧版和新版的文档里面都找不到了,能否提供一下,顺带收录一下他人写的组件,方便使用swoft开发,
我记得以前是有的,有展示如何开发组件,
我现在需要开发一个rabbitmq的组件和rpc负载均衡组件,能否提供一下开发组件文档
如何使用swoft的连接池做rabbitmq的连接池,

**Comment by phpwei** [comment]
撕逼事件后 就没用swoft 开发新项目了,只是旧项目维护,新项目换成goleng

**Comment by nanyounanyounan** [comment]
> 撕逼事件后 就没用swoft 开发新项目了,只是旧项目维护,新项目换成goleng

好的,谢谢

**Comment by inhere** [comment]
http://swoft.io/docs/2.x/zh-CN/component/structure.html @nanyounanyounan  文档在的

**Comment by ekk0** [comment]
> 撕逼事件后 就没用swoft 开发新项目了,只是旧项目维护,新项目换成goleng

请问一下开发组件是不是要制作composer包，我看文档没有写，我根据文档来总是找不到class

**Comment by inhere** [comment]
组件就是一个 `composer` 包，只是里面会包含一个swoft会自动识别的 `AutoLoader.php` 文件
