### ISSUE TITLE
模型的firstOrCreate和firstOrNew没有效果

### ISSUE THREAD

**Issue by first236108** [swoft-cloud/swoft#1311]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.9 (by `php bin/swoft -V`)
| Swoole version      | 4.4.1 (by `php --ri swoole`)
| PHP version         | 7.2.6 (by `php -v`)
| Runtime environment | CentOS 7

**使用模型的更新或插入功能没有效果**
代码如下：
```php
//bad, as same problem with the method of firstOrNew 
$goods = Goods::firstOrCreate(['id' => $goods['id']], $goods);
$goods->save();

// good
$goods = Goods::updateOrCreate(['id' => $goods['id']], $goods);

```

**Comment by sakuraovq** [comment]
/**
     * Get the first record matching the attributes or create it.
     *
     * @param array $attributes
     * @param array $values
     *
     * @return Model
     * @throws DbException
     */
    public function firstOrCreate(array $attributes, array $values = []): Model
    {
        if (!is_null($instance = $this->where($attributes)->first())) {
            return $instance;
        }

        $instance = $this->newModelInstance($attributes + $values);
        $instance->save();

        return $instance;
    }

// firstOrCreate 会执行 sql 并返回 model

    /**
     * Get the first record matching the attributes or instantiate it.
     *
     * @param array $attributes
     * @param array $values
     *
     * @return object|Builder|Model
     * @throws DbException
     */
    public function firstOrNew(array $attributes, array $values = [])
    {
        if (!is_null($instance = $this->where($attributes)->first())) {
            return $instance;
        }

        return $this->newModelInstance($attributes + $values);
    }
// 只会返回 model
