### ISSUE TITLE
swoft redis组件不支持select命令

### ISSUE THREAD

**Issue by studyzhanglei** [swoft-cloud/swoft#1312]
看了一下源码，在vendor/swoft/redis/src/Connection/Connection.php 的$supportedMethods数组变量里面加上select命令就好了，官方能否加一下呢？

之前老业务一个redis实例里面用了很多的db，如果不支持select命令的话，需要写非常多的redis配置

**Comment by sakuraovq** [comment]
redis->call( function( $redis) { $redis->select() });

**Comment by sakuraovq** [comment]
@studyzhanglei 先用下这样的呢

**Comment by studyzhanglei** [comment]
> redis->call( function( $redis) { $redis->select() });

好的，多谢～

**Comment by studyzhanglei** [comment]
> @studyzhanglei 先用下这样的呢

这样不行，只有在匿名函数内redis db才会变化，比如在匿名函数内部使用了select(10)，外部还是默认的db

**Comment by sakuraovq** [comment]
@studyzhanglei redis 每次执行都会 从连接池获取连接 select 需要保证在同一连接 

用完了需要自己重置才行喔

**Comment by sakuraovq** [comment]
每次 redis 操作可能用的不是一个连接
