### ISSUE TITLE
rpc连接有时候连接失败，再连一次就成功了

### ISSUE THREAD

**Issue by yumindayu** [swoft-cloud/swoft#1314]
Create connection error

file(/var/www/swoft/vendor/swoft/rpc-client/src/Connection.php) line (76)

项目已部署在生产，大概什么原因会造成这种现象？不太可能是服务间网络问题，日志如上，谢谢

**Comment by inhere** [comment]
`Create connection error` 后面的错误消息是啥

**Comment by yumindayu** [comment]
@inhere Connect failed host=xxxxxxxxxx port=8099  xxxxx是我的内网ip

**Comment by 583128870** [comment]
老哥 你这个问题解决了吗
