### ISSUE TITLE
rpc-client 连接池bug 

### ISSUE THREAD

**Issue by lengfengbyit** [swoft-cloud/swoft#1315]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.9
| Swoole version      | 4.4.18
| PHP version         | 7.3.17
| Runtime environment | Docker etc.

**Describe the bug**
rpc-client ServiceTrait 调用sendAndRecv抛出异常后没有回收连接，导致连接耗尽

**Expected behavior**

**Screenshots**

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by yumindayu** [comment]
我也遇到这个问题了

**Comment by lengfengbyit** [comment]
我们现在是暂时在源代码里，抛出异常之前手动回收了连接？
请问你们是怎么解决这个问题的？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yumindayu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月16日(星期二) 下午2:44
收件人:&nbsp;"swoft-cloud/swoft"<swoft@noreply.github.com&gt;;
抄送:&nbsp;"冷锋"<1348207308@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [swoft-cloud/swoft] rpc-client 连接池bug  (#1315)





 
我也遇到这个问题了

**Comment by yumindayu** [comment]
> 我们现在是暂时在源代码里，抛出异常之前手动回收了连接？ 请问你们是怎么解决这个问题的？ ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"yumindayu"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月16日(星期二) 下午2:44 收件人:&nbsp;"swoft-cloud/swoft"<swoft@noreply.github.com&gt;; 抄送:&nbsp;"冷锋"<1348207308@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [swoft-cloud/swoft] rpc-client 连接池bug (#1315) 我也遇到这个问题了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

还没解决
