### ISSUE TITLE
validator内置验证规则Required仍然有Bug，并且 源码中的Rule 全都不支持多语种。期待改进。

### ISSUE THREAD

**Issue by wcaqrl** [swoft-cloud/swoft#1317]
内置验证规则Required仍然有Bug，不支持message传入。

希望 Rule 中的 sprintf 结合 \Swoft::t( )实现扩展支持多语种。只需要在每个Rule里 修改sprintf这一行；并在resource文件夹下添加相应的validator相关message的语种文件。

>

**Comment by JasonYH** [comment]
验证器在2.8版本的时候就已经支持了 i18n 多语言提示了
https://github.com/swoft-cloud/swoft-component/pull/545/commits/bcc58a41c26cff106c5f4b64678483b6a1cbf012

**Comment by JasonYH** [comment]
@wcaqrl         https://github.com/JasonYH/swoft-component/blob/bcc58a41c26cff106c5f4b64678483b6a1cbf012/src/validator/src/Validator.php#L229
