### ISSUE TITLE
wesocket 中间件

### ISSUE THREAD

**Issue by MonkWang** [swoft-cloud/swoft#1319]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.9
| Swoole version      | 4.4.16
| PHP version         | 7.4.7,
| Runtime environment | Mac

**Describe the bug**
关于swoft的websocket的全局中间件问题

**Expected behavior**
在处理ws全局中间件时，无法获取到当前request的内容，接口只提供了一个getFd()的函数

**Screenshots**

**Details**

> Describe what you are trying to achieve and what goes wrong.
中间件的代码应该能处理业务逻辑，譬如判断token是否有效等，但此处无法获取到请求过来到参数，导致无法在中间件层来过滤处理一些请求
```php
    /**
     * @param RequestInterface        $request
     * @param MessageHandlerInterface $handler
     *
     * @return ResponseInterface
     */
    public function process(RequestInterface $request, MessageHandlerInterface $handler): ResponseInterface
    {
        $start = '>before ';
        CLog::info('before handle');
        $resp = $handler->handle($request);//中间件的代码应该能处理业务逻辑，譬如判断token是否有效等，但此处无法获取到请求过来到参数，导致无法在中间件层来过滤处理一些请求。而且文档也没有关于ws中间件到详细文档，导致在该处无法正确处理全局到业务逻辑
        $resp->setData($start . $resp->getData() . ' after>');
        CLog::info('after handle');
        \server()->log(__METHOD__, [], 'error');
        return $resp;
    }
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
@MonkWang  发起请求的信息存在连接里面，消息阶段也是能拿到请求对象的：

```php
use Swoft\Session\Session;

/** @var \Swoft\Http\Message\Request $psr7req */
$psr7req = Session::current()->getRequest();
```
