### ISSUE TITLE
简单的 swoft 的使用教程，使用 swoole-docker 启动 swoft

### ISSUE THREAD

**Issue by gdc676463** [swoft-cloud/swoft#132]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      | 2.1.1
| PHP version         | 7.2.3
| Runtime environment | swoole-docker

**Details**

> 我想要展示一个最小化使用 swoft 的方法

### 第一步 构建一个本地 swoole-docker 镜像

此镜像是包含有 swoole 扩展的 php-cli 运行环境，参见 https://github.com/gdc676463/swoole-docker 。

### 第二步 拉取 swoft 项目并安装依赖

```bash
$ git clone https://github.com/swoft-cloud/swoft
```

然后进到 `swoft` 项目目录，安装依赖

```bash
$ composer install
```

### 第三步，利用 `swoole-docker` 启动 swoft 项目

```bash
$ docker run --rm -it -p 8000:80 -v $(pwd):/app php:swoole php /app/swoft/bin/swoft start
```

现在访问 http://localhost:8000 查看吧

**Comment by daydaygo** [comment]
可以参考项目下的 dockerfile 和 docker-compose.yml

**Comment by daydaygo** [comment]
@gdc676463 swoft 的教程正在制作中(文章&视频), 会包括 php/swoole/swoft  等等相关技术知识, 欢迎参与进来
