### ISSUE TITLE
Use swoft-db package out of the Swoft framework

### ISSUE THREAD

**Issue by ljfreelancer88** [swoft-cloud/swoft#1321]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no

Hi! I'm planing to use `https://github.com/swoft-cloud/swoft-db` package out the Swoft framework. My question is how and where can I set the configuration? Because right now it uses the `app/bean.php` when you use the Swoft framework.

Thanks in advance.

**Comment by inhere** [comment]
hi @ljfreelancer88  `swoft-db` Maybe it doesn't work correctly from the outside, it depends on swoft's container. Need you to do some renovation
