### ISSUE TITLE
Tcp模块DemoMiddleware继承的MiddlewareInterface类没有

### ISSUE THREAD

**Issue by taoshaoye** [swoft-cloud/swoft#1323]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | v2.0.9 
| Swoole version      | v4.4.18
| PHP version         | v7.2.31
| Runtime environment | Mac-Docker

**Describe the bug**
Tcp模块DemoMiddleware继承的MiddlewareInterface类没有

**Expected behavior**
`Fatal error: Interface 'Swoft\Tcp\Server\Contract\MiddlewareInterface' not found in /var/www/swoft/app/Tcp/Middleware/DemoMiddleware.php on line 25`

**Screenshots**
![image](https://user-images.githubusercontent.com/16772742/86320257-0d5ce080-bc69-11ea-9ebc-d3d94c4aaeba.png)

**Details**

> Tcp模块DemoMiddleware继承的MiddlewareInterface类没有

```php
2020/07/02-13:35:30 [INFO] Swoft\SwoftApplication:setSystemAlias(417) Project path: @base=/var/www/swoft
2020/07/02-13:35:30 [INFO] Swoft\SwoftApplication:setSystemAlias(418) Set alias @app=@base/app
2020/07/02-13:35:30 [INFO] Swoft\SwoftApplication:setSystemAlias(419) Set alias @config=@base/config
2020/07/02-13:35:30 [INFO] Swoft\SwoftApplication:setSystemAlias(420) Set alias @runtime=@base/runtime
2020/07/02-13:35:31 [INFO] Swoft\Processor\EnvProcessor:handle(60) Env file(/var/www/swoft/.env) is loaded

Fatal error: Interface 'Swoft\Tcp\Server\Contract\MiddlewareInterface' not found in /var/www/swoft/app/Tcp/Middleware/DemoMiddleware.php on line 25
```

> Provide minimal script to reproduce the issue

```php
<?php declare(strict_types=1);
/**
 * This file is part of Swoft.
 *
 * @link     https://swoft.org
 * @document https://swoft.org/docs
 * @contact  group@swoft.org
 * @license  https://github.com/swoft-cloud/swoft/blob/master/LICENSE
 */

namespace App\Tcp\Middleware;

use Swoft\Bean\Annotation\Mapping\Bean;
use Swoft\Log\Helper\CLog;
use Swoft\Tcp\Server\Contract\MiddlewareInterface;
use Swoft\Tcp\Server\Contract\RequestHandlerInterface;
use Swoft\Tcp\Server\Contract\RequestInterface;
use Swoft\Tcp\Server\Contract\ResponseInterface;

/**
 * Class DemoMiddleware
 *
 * @Bean()
 */
class DemoMiddleware implements MiddlewareInterface
{
    /**
     * @param RequestInterface        $request
     * @param RequestHandlerInterface $handler
     *
     * @return ResponseInterface
     */
    public function process(RequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $start = '>before ';

        CLog::info('before handle');

        $resp = $handler->handle($request);

        $resp->setData($start . $resp->getData() . ' after>');

        CLog::info('after handle');

        return $resp;
    }
}

```

**Comment by inhere** [comment]
是不是没有安装 tcp 组件啊

**Comment by taoshaoye** [comment]
现在已经好了，准确来说是没安装tcp-server组件



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2020年7月2日(星期四) 下午2:58
收件人: "swoft-cloud/swoft"<swoft@noreply.github.com&gt;; 
抄送: "Mreden"<913057891@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [swoft-cloud/swoft] Tcp模块DemoMiddleware继承的MiddlewareInterface类没有 (#1323)





 
是不是没有安装 tcp 组件啊

**Comment by inhere** [comment]
ok
