### ISSUE TITLE
我在RPC，service中如何调用其他服务

### ISSUE THREAD

**Issue by 233cy** [swoft-cloud/swoft#1324]
![P(XH54GD`2JX4N)NF}W9ELN](https://user-images.githubusercontent.com/29916783/86341215-92a3bd80-bc88-11ea-8ed2-734aedadec8f.png)
。类似这样，我如何在RPC里调用其他服务，因为可能会有一些公共服务。一些业务服务会用到这些公共服务。 @inhere

**Comment by inhere** [comment]
这里没法调用成功吗？

**Comment by 233cy** [comment]
> 这里没法调用成功吗？

...打扰了。。。刚又试了一下，可以的。之前也发起过一次，问怎么调用，那次可能是因为我那里写的有问题。刚测试了可以的。谢谢。~！~
