### ISSUE TITLE
swoft调用链问题

### ISSUE THREAD

**Issue by Huangsh17** [swoft-cloud/swoft#1330]
swoft这边边调用go这边用grpc写的微服务，golang这边的链路追踪数据怎么上报给swoft那边

**Comment by inhere** [comment]
为啥要上报给swoft这里的服务

**Comment by Huangsh17** [comment]
> 为啥要上报给swoft这里的服务
可视化出来啊，还是说golang这边可以用jaeger来做的

**Comment by inhere** [comment]
jager 是可以的
