### ISSUE TITLE
swoft http 服务如何在浏览器中访问图片

### ISSUE THREAD

**Issue by leablogs** [swoft-cloud/swoft#1335]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 2.0.9
| Swoole version      | 4.4.14
| PHP version         | 7.2.24
| Runtime environment | CentOS 7

在swoft http服务的目录下的public中放一个图片,如何可以访问这个图片    
nginx 服务器可以通过ip/imageurl在 swoft http服务中如何访问

**Comment by yinjiajiu** [comment]
enable_static_handler 设置为true ，就可以向nginx 一样访问了，高版本的swoole不需要设置enable_static_handler

**Comment by leablogs** [comment]
开启enable_static_handler 之后通过ip+图片路径  提示Route not found(path /aaa.png)这个是我请求方式不正确还是需要配置什么参数

**Comment by leablogs** [comment]
访问 public/image目录也是提示 路由错误

**Comment by yinjiajiu** [comment]
这个你要在中间件里做处理了

**Comment by inhere** [comment]
http://swoft.io/docs/2.x/zh-CN/extra/view.html#%E5%8A%A0%E8%BD%BD%E9%9D%99%E6%80%81%E6%96%87%E4%BB%B6
