### ISSUE TITLE
实体管理类,建议添加实体更新方法

### ISSUE THREAD

**Issue by aprchen** [swoft-cloud/swoft#134]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

目前只有实体的添加和删除

**Comment by daydaygo** [comment]
麻烦提供一下现有实体使用的代码示例, 以及你期望的代码示例. 我们会综合考虑 功能 + 代码风格 2个方面

**Comment by huangzhhui** [comment]
$entity->update();
有Update方法的

**Comment by aprchen** [comment]
@huangzhhui 我说的是EntityManager,有save和delete方法,却没有update 方法
