### ISSUE TITLE
数据库批量更新数据时发现的BUG

### ISSUE THREAD

**Issue by longjianghu** [swoft-cloud/swoft#1340]
swoft版本2.0.9

**Comment by sakuraovq** [comment]
提供下具体的 代码呢

**Comment by longjianghu** [comment]
> 提供下具体的 代码呢

这个是必出的BUG,只要你更新的数据包含json数据就可以。

**Comment by longjianghu** [comment]
目前测试主来应该是生成的SQL主键的值加了一个单引号导致的问题，能不能紧急修复一下？

**Comment by longjianghu** [comment]
![WechatIMG417](https://user-images.githubusercontent.com/1303264/92566295-94a08300-f2ae-11ea-856f-9303f6eca77b.jpeg)
