### ISSUE TITLE
如何控制异步任务并发数？

### ISSUE THREAD

**Issue by zarte** [swoft-cloud/swoft#1346]
文档中没看到有相关配置。 
c#有线程池，golang有通道不知道swoft可以用什么实现。

**Comment by inhere** [comment]
你的task进程数就是相当于在控制task并发数据

**Comment by zarte** [comment]
> 你的task进程数就是相当于在控制task并发数据

task_worker_num这个？
想要实现的是控制单个异步任务的并发数  
例如并发数3个
待处理1，2，3.。。。100
先投递3个完成一个后有个回调的地方接收完成然后继续投递下一个 这样的。

**Comment by inhere** [comment]
投递都是不限制的啊，只需限制并发处理。
go channel 通常也是在消费端做并发限制，限制投递那不是影响逻辑了。

**Comment by zarte** [comment]
@inhere chan
go可以建立固定长度的channel，启动n个协程来消费，channel满了就无法投递会卡住等待。  
swoft中应该没类似东西吧？要通过外部redis来实现么？

**Comment by zarte** [comment]
@inhere 
此外有异步任务完成必定执行的方法吗？针对某种任务的，finish是所有任务都会调用不是太符合。

**Comment by inhere** [comment]
finish 里面做筛选吧 不想处理的忽略掉就行
