### ISSUE TITLE
下载swoft最新版本，注解无效，bena配置端口修改无效，新添加的控制器不能根据路由找到对应的方法

### ISSUE THREAD

**Issue by zqtop** [swoft-cloud/swoft#1348]
![image](https://user-images.githubusercontent.com/41433704/91444733-bf024180-e8a7-11ea-9b95-e9d9a19dda9d.png)
![image](https://user-images.githubusercontent.com/41433704/91444790-d6412f00-e8a7-11ea-8d49-bb01cf7d0a1c.png)

**Comment by zqtop** [comment]
what mean?

**Comment by zqtop** [comment]
版本 swoft v2.0.9

**Comment by inhere** [comment]
路由是 `/index`

**Comment by inhere** [comment]
可以通过执行 `php bin/swoft app:httproutes ` 查看注册的路由信息

**Comment by zqtop** [comment]
![image](https://user-images.githubusercontent.com/41433704/91518081-eb5aa400-e921-11ea-9107-848a21d48c68.png)
执行这条命令后，发现新写的控制器的路由没有注册进去

**Comment by zqtop** [comment]
查看这条命令后，发现路由没有注册进去




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Inhere"<notifications@github.com&gt;; 
发送时间: 2020年8月28日(星期五) 中午11:20
收件人: "swoft-cloud/swoft"<swoft@noreply.github.com&gt;; 
抄送: "zq"<820780348@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [swoft-cloud/swoft] 下载swoft最新版本，注解无效，bena配置端口修改无效，新添加的控制器不能根据路由找到对应的方法 (#1348)





 
可以通过执行 php bin/swoft app:httproutes  查看注册的路由信息

**Comment by inhere** [comment]
第一个不就是吗

**Comment by zqtop** [comment]
swoft 2.x系列官方文档注解的用法并未详细的说明/的拼接，实际上，我很早之前的index路由是注册进去，但是当我修改它的路由更改为其他的，我重新把swoft 重新启动，并重新访问这个路由，这个路由并不能生效，似乎一直在内存里，swoft是常驻内存框架，理应重启服务后，路由应当生效，我不知道这是为什么，文档没有给出详细的解释

**Comment by inhere** [comment]
![image](https://user-images.githubusercontent.com/5302062/91528399-3da7bf00-e93a-11ea-97c7-bab8e04c9764.png)
