### ISSUE TITLE
为什么swoft官方要把登录信息放到Request对象里面啊

### ISSUE THREAD

**Issue by studyzhanglei** [swoft-cloud/swoft#1352]
从1.0开始用swoole框架，之前还是有标准的auth类的，现在把登录信息直接放到request里面了，我觉得好难受啊，有点接受不了，觉得很不符合规范，request 和用户信息是完全不搭嘎的东西啊

官方示例代码：https://www.swoft.org/documents/v2/core-components/http-server/

![image](https://user-images.githubusercontent.com/43992249/92089445-befec600-ee00-11ea-8973-ea2520195961.png)

希望官方能给个解释 本人有点强迫症 但绝对不是找茬

**Comment by yinjiajiu** [comment]
我感觉你也可以将这些放在requestBean里面，官方的例子放在request对象里面，也只是一个例子而已，

**Comment by studyzhanglei** [comment]
> 我感觉你也可以将这些放在requestBean里面，官方的例子放在request对象里面，也只是一个例子而已，

现在我们开发团队就把这个抄过来了 我实在是受不了 官方的代码总是会起到带头作用的 我知道代码这样写不会有任何问题 只是个人觉得不规范

**Comment by inhere** [comment]
放到 context 上下文里也是可以的
