### ISSUE TITLE
rpcClientExtender没有正常传递

### ISSUE THREAD

**Issue by Ederth** [swoft-cloud/swoft#1355]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.9
| Swoole version      | 4.5.2
| PHP version         | 7.3.21
| Runtime environment | Docker

**Describe the bug**
rpcClientExtender 没有正常传递
请求 http 控制器
设置`traceid`后调用 rpc 服务
rpc 请求日志没有打印出`traceid`（空字符串）

**Expected behavior**
rpc 请求日志应该要打印 http 控制器设置的 `traceid`

**Screenshots**
![image-20200907093312185](https://user-images.githubusercontent.com/18107297/92341190-835d4800-f0ef-11ea-9cdd-18aeaed80cf2.png)
![image-20200907093443360](https://user-images.githubusercontent.com/18107297/92341199-8e17dd00-f0ef-11ea-8283-1cf5db88facb.png)

**Details**

> Describe what you are trying to achieve and what goes wrong.
应该是 rpc-client 获取 extender 的时候没有设置数组的 key，rpc-server 无法根据对应的 key 拿到数据

![image-20200907093616987](https://user-images.githubusercontent.com/18107297/92341315-e2bb5800-f0ef-11ea-937f-888f2f53a284.png)
![image-20200907093717499](https://user-images.githubusercontent.com/18107297/92341317-e51db200-f0ef-11ea-8f4d-934b83649853.png)

**Comment by inhere** [comment]
嗯 修复过，没有发布新版本 :(
