### ISSUE TITLE
框架中能否使用defer

### ISSUE THREAD

**Issue by Ederth** [swoft-cloud/swoft#1357]
| Q                   | A |
| ------------------- | ----- |
| Bug report?         | yes |
| Feature request?    | no |
| Swoft version       | 2.0.9 |
| Swoole version      | 4.5.3 |
| PHP version         | 7.3.21 |
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc. |

**Describe the bug**

进程组件中，运行以下代码进程会一直崩溃重启

http 控制器中运行以下代码，只会打印一个 defer，另一个 defer 没有执行，导致 WaitGroup 一直等待

```php
$wg = new WaitGroup();
$wg->add();
sgo(function () use ($wg) {
    Co::defer(function () use ($wg) {
        vdump('defer1');
        $wg->done();
    });
    vdump('hello');
});

$wg->add();
sgo(function () use ($wg) {
    Co::defer(function () use ($wg) {
        vdump('defer2');
        $wg->done();
    });
    vdump('hello');
});

$wg->wait();
```

**Comment by sakuraovq** [comment]
sgo 底层也是 WaitGroup 相互等待 wait 这段代码无效

**Comment by sakuraovq** [comment]
$wg = new WaitGroup();
        $wg->add();
        sgo(function () use ($wg) {
                vdump('defer1');
                $wg->done();
            vdump('hello');
        },false);

        $wg->add();
        sgo(function () use ($wg) {
                vdump('defer2');
                $wg->done();
            vdump('hello');
        },false);

        $wg->wait();

**Comment by sakuraovq** [comment]
除非 sgo不进入等待就可以执行

**Comment by sakuraovq** [comment]
默认 sgo 会进行等待不用 使用者自己在 wait 等待 框架底层已经实现了

**Comment by sakuraovq** [comment]
```php
 $wg = new WaitGroup();
        $wg->add();
        sgo(function () use ($wg) {
                vdump('defer1');
                $wg->done();
            vdump('hello');
        },false);

        $wg->add();
        sgo(function () use ($wg) {
                vdump('defer2');
                $wg->done();
            vdump('hello');
        },false);

        $wg->wait();


```
