### ISSUE TITLE
RedisSessionHandler unserialize

### ISSUE THREAD

**Issue by xiongchao123** [swoft-cloud/swoft#136]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Swoft version       | master
| Swoole version      | 2.0.13
| PHP version         | 7.0.25
| Runtime environment | CentOS 7 
 
**Details**

> PHP Warning:  unserialize() expects parameter 2 to be array, null given in /var/www/php/swoft/vendor/swoft/session/src/Handler/RedisSessionHandler.php on line 128

```php

protected function unserialize($value)
    {
        return is_numeric($value) ? $value : unserialize($value,null);
    }

```

mixed unserialize ( string $str )    
unserialize() 应该没有第二个参数的吧

**Comment by inhere** [comment]
有的 高版本就有了 可以这样加 `['allowed_classes' => false]`

**Comment by xiongchao123** [comment]
那这第二个参数应该是个数组类型吧
return is_numeric($value) ? $value : unserialize($value,null); 
是不是要改成
return is_numeric($value) ? $value : unserialize($value,[]);

**Comment by huangzhhui** [comment]
已修复，请更新 swoft/session 至 v1.0.2 版本以上
