### ISSUE TITLE
[question] 请问如何支持 protobuf 协议？

### ISSUE THREAD

**Issue by Sun-FreePort** [swoft-cloud/swoft#1363]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no

组了个团队做游戏，但我是纯粹的“长连接萌新”，请问框架中的 WebSocket 是否支持 PB 协议？

如果不支持，有没有比较专业的入门教程？求个链接，谢谢。

**Comment by inhere** [comment]
内置的解析器没有支持。可以参考

https://github.com/swoft-cloud/swoft-component/blob/master/src/websocket-server/src/MessageParser/JsonParser.php

实现接口 Swoft\WebSocket\Server\Contract\MessageParserInterface 即可。

**Comment by Sun-FreePort** [comment]
> 内置的解析器没有支持。可以参考
> 
> https://github.com/swoft-cloud/swoft-component/blob/master/src/websocket-server/src/MessageParser/JsonParser.php
> 
> 实现接口 `Swoft\WebSocket\Server\Contract\MessageParserInterface` 即可。

感谢，很专业~
