### ISSUE TITLE
Swoole\Coroutine\Channel::isEmpty(): you must call Channel constructor first in

### ISSUE THREAD

**Issue by simpleKalvin** [swoft-cloud/swoft#1366]
需求： 
1. 我在Process中启动3个协程并包上waitgroup 对队列信息进行处理。
2. 协程中有可能RPC服务不稳定

代码如下
![image](https://user-images.githubusercontent.com/18275521/93425898-888b7580-f8ed-11ea-93ae-356b585416c4.png)

**Comment by Ederth** [comment]
sgo底层已经使用了WaitGroup，和外层的WaitGoup会有冲突
去掉外层的WaitGoup，或者sgo的第二个参数传入false

**Comment by simpleKalvin** [comment]
感谢🙏
