### ISSUE TITLE
Model insert 数据库字段 date 类型插入时将 null 转换为 '' 空字符串

### ISSUE THREAD

**Issue by imzyf** [swoft-cloud/swoft#1385]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| version       | PHP: 7.1.33-17+ubuntu18.04.1+deb.sury.org+1, Swoft: 2.0.10, Swoole: 4.5.4
| Runtime environment | Mac

**Describe the bug**

MySQL 5.7，table result，列 posted_date 类型 date，可以为 null，没有默认值

```
Result::new(['posted_date' => null])->save();
```

insert 数据库字段 date 类型插入时将 null 转换为 '' 空字符串

```
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect date value: '' for column 'posted_date' at row 1 sql=insert into `result` (`posted_date`, `updated_at`, `created_at`) values ('', '2020-10-22 21:10:19', '2020-10-22 21:10:19')
```

预期是：

```
insert into `result` (`posted_date`, `updated_at`, `created_at`) values (null, '2020-10-22 21:10:19', '2020-10-22 21:10:19')
```

**Comment by imzyf** [comment]
select date 类型的列 null 也会被转为 ''

**Comment by sakuraovq** [comment]
![image](https://user-images.githubusercontent.com/30211214/104798083-a961ca00-57fe-11eb-9705-8db98cddf67e.png)
![image](https://user-images.githubusercontent.com/30211214/104798089-ba124000-57fe-11eb-834c-c104e88e7c74.png)
属性值无法区分 null  所以用模型无法实现 带 null 的插入

**Comment by sakuraovq** [comment]
/* @var User $user */
        $user = User::new();

        // Save result
        $result = $user->newModelQuery()->insert(['a'=>null]);

**Comment by sakuraovq** [comment]
直接用 Db 里面的方法就不会转义了

**Comment by frank0v0** [comment]
> 直接用 Db 里面的方法就不会转义了

请问解决了吗？好像insert update 这些都不能赋予null

**Comment by imzyf** [comment]
![image](https://user-images.githubusercontent.com/9289792/154055424-c3bb08f7-9a08-4260-9da9-606e6698db64.png)


![image](https://user-images.githubusercontent.com/9289792/154055187-b218d490-c3fb-4a21-9be0-cd97ea4fada4.png)


原因应该是这个方法导致的，就是说 ?string 会被当成 string 处理，null 时 被转换为了 ''

@sakuraovq 这里可以进行改造吗
