### ISSUE TITLE
启动rpc服务就报错

### ISSUE THREAD

**Issue by michael23-24** [swoft-cloud/swoft#1392]
环境win10，docker
启动rpc就报错，如下：

**(CONSOLE)Swoft\Server\Exception\ServerException: Swoole task event listener is not Swoft\Server\Contract\SyncTaskInterface**
At /var/www/html/swoft/vendor/swoft/server/src/Server.php line 636
Code Trace:
#0 /var/www/html/swoft/vendor/swoft/server/src/Server.php(601): Swoft\Server\Server->addTaskEvent(Object(Swoole\Server\Port), Object(Swoft\Task\Swoole\TaskListener), 'task')
#1 /var/www/html/swoft/vendor/swoft/server/src/Server.php(574): Swoft\Server\Server->addEvent(Object(Swoole\Server\Port), Array)
#2 /var/www/html/swoft/vendor/swoft/server/src/Server.php(526): Swoft\Server\Server->addListener()
#3 /var/www/html/swoft/vendor/swoft/rpc-server/src/ServiceServer.php(63): Swoft\Server\Server->startSwoole()
#4 /var/www/html/swoft/vendor/swoft/rpc-server/src/Command/ServiceServerCommand.php(56): Swoft\Rpc\Server\ServiceServer->start()
#5 /var/www/html/swoft/vendor/swoft/console/src/ConsoleDispatcher.php(53): Swoft\Rpc\Server\Command\ServiceServerCommand->start()
#6 /var/www/html/swoft/vendor/swoft/console/src/Application.php(221): Swoft\Console\ConsoleDispatcher->dispatch(Array)
#7 /var/www/html/swoft/vendor/swoft/console/src/Application.php(151): Swoft\Console\Application->doRun('rpc:start')
#8 /var/www/html/swoft/vendor/swoft/framework/src/Processor/ConsoleProcessor.php(48): Swoft\Console\Application->run()
#9 /var/www/html/swoft/vendor/swoft/framework/src/Processor/ApplicationProcessor.php(43): Swoft\Processor\ConsoleProcessor->handle()
#10 /var/www/html/swoft/vendor/swoft/framework/src/SwoftApplication.php(198): Swoft\Processor\ApplicationProcessor->handle()
#11 /var/www/html/swoft/bin/swoft(12): Swoft\SwoftApplication->run()
#12 {main}

**Comment by liuxingyuxia** [comment]
你怎么解决的啊

**Comment by djfzqq** [comment]
找到swoft/vendor/swoft/server/src/SwooleEvent.php类，发现Task监听映射了两个类，SyncTaskInterface::class 与TaskInterface::class，注释SyncTaskInterface::class 后，重启ws:start 完美启动
疑问：请问这里的SyncTaskInterface::class 是什么用途
