### ISSUE TITLE
swoft-db 抛出异常参数错误

### ISSUE THREAD

**Issue by ronylee** [swoft-cloud/swoft#1409]
![image](https://user-images.githubusercontent.com/3433344/104764217-0aa78000-57a2-11eb-9adb-8433646d8af5.png)

![image](https://user-images.githubusercontent.com/3433344/104764472-68d46300-57a2-11eb-9545-e262b5afc1a3.png)

更新到 2.0.10 就报这个错误， 2.0.9 是正常的。（int)$e->getCode()

**Comment by sakuraovq** [comment]
已修复 v2.0.11  发布

**Comment by sakuraovq** [comment]
master 已修复
