### ISSUE TITLE
swoft DB 报错

### ISSUE THREAD

**Issue by jiancixiuxian** [swoft-cloud/swoft#1416]
![image](https://user-images.githubusercontent.com/63960265/111073944-ce7f6a00-851b-11eb-9817-d54e26325961.png)
swoft 版本  2.0.10  

服务开启一段时间就偶尔  会报这个错误
HttpExceptionHandler.php:39] Wrong parameters for Swoft\\Db\\Exception\\DbException([string $message [, long $code [, Throwable $previous = NULL]]])

这是什么原因呢

**Comment by sakuraovq** [comment]
@jiancixiuxian  是因为 code 不是 int , 之前有强转的 2.10 搞掉了
