### ISSUE TITLE
swoft rpc启动报错

### ISSUE THREAD

**Issue by cwp6** [swoft-cloud/swoft#1419]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z (by `php bin/swoft -V`)
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Describe the bug**

**Expected behavior**

**Screenshots**

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```
rpc启动报错
> Provide minimal script to reproduce the issue

```php
// paste code
```
![QQ图片20210406225115](https://user-images.githubusercontent.com/33923881/113730601-9c33e780-972a-11eb-95f4-e0071227505c.png)

**Comment by XuanYi2018** [comment]
您好，①您没有设置.env配置文件 ②报错提示您可能配置了 task_worker，但是没有实现 swoole task 事件回调。

**Comment by cwp6** [comment]
谢谢
