### ISSUE TITLE
数据库entity继承的model，希望能支持批量设置属性的功能

### ISSUE THREAD

**Issue by yuanliang847** [swoft-cloud/swoft#142]
| Q                   | A
| ------------------- | -----
| Bug report?         | NO
| Feature request?    | YES
| Swoft version       | 1.0.0
| Swoole version      | 2.1.1-alpha
| PHP version         | 7.2.2
| Runtime environment | Centos 7

entity设置方法，希望能增加一个匹配设置属性的方法，类似
set({
   name: value
})
这样子，不然更新或者插入代码都会写的很麻烦

**Comment by stelin** [comment]
更新最新版本

**Comment by huangzhhui** [comment]
fill()方法
