### ISSUE TITLE
【文档校验】v2.x 基础组件 - 容器，示例代码部分

### ISSUE THREAD

**Issue by FebruaryZhang** [swoft-cloud/swoft#1420]
![image](https://user-images.githubusercontent.com/32325152/114495951-96219780-9c51-11eb-8174-9abc1fcfb659.png)

**Comment by FebruaryZhang** [comment]
该专题最后的示例演示代码是否未上传？

**Comment by JasonYH** [comment]
@FebruaryZhang 这些代码只是教学演示容器概念用的，你对着文档就能写出来，并不是框架的功能。
