### ISSUE TITLE
[question] 请问可否发布 2.0.11?

### ISSUE THREAD

**Issue by andiechang** [swoft-cloud/swoft#1422]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no

您好，我手上有个案子已在生产环境。
 2.0.11 已修正的问题，请问是否可以先发布一个版本？

谢谢

**Comment by inhere** [comment]
我周末找个时间发布下

**Comment by andiechang** [comment]
> 我周末找个时间发布下

麻烦了，谢谢！

**Comment by andiechang** [comment]
> 我周末找个时间发布下

@inhere 
再请帮忙抽空发布下，感谢！

**Comment by inhere** [comment]
各个组件昨晚都发了

**Comment by andiechang** [comment]
Thanks a lot!!!
