### ISSUE TITLE
reids 缺一个方法提示 sismember

### ISSUE THREAD

**Issue by aprchen** [swoft-cloud/swoft#147]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
![image](https://user-images.githubusercontent.com/13740363/37512568-7cac4d3e-293d-11e8-89d9-f9321f7f7775.png)
如图

**Comment by huangzhhui** [comment]
已添加，非紧急bug修复问题请等待下一次版本(v1.0.3)发布时一起发布
