### ISSUE TITLE
用这个框架的phper 得有多倒霉

### ISSUE THREAD

**Issue by liubangde** [swoft-cloud/swoft#1479]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z (by `php bin/swoft -V`)
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Describe the bug**

**Expected behavior**

**Screenshots**

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by chunpat** [comment]
已经很久没怎么维护拉，已经不爱了

**Comment by FlameMida** [comment]
Archive 了算了

**Comment by zwfengwu** [comment]
比之前公司自研的好一些.....
