### ISSUE TITLE
请求支持可以动态选择数据库，以支持MyCat

### ISSUE THREAD

**Issue by DeivaLiang** [swoft-cloud/swoft#149]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 1.0
| Swoole version      | 2.0
| PHP version         | 7.0
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

>  场景：在一些多租户的系统中，每个租户的数据库是完全隔离，即张三使用的张三的数据库，李四使用的是李四的数据。
> 每个库的表和每个表的结构都是一样的，仅是具体的业务数据不一样的。

>  关键：是在用户登录后才知道使用哪个库。

初步建议，仅供参数
```php
        $result = User::findById(720)->useDB('张三的库名')->getResult();
```

**Comment by stelin** [comment]
新增一个驱动的方式，已解决。
