### ISSUE TITLE
自定义进程,怎么调用task::async呢？2.0.11

### ISSUE THREAD

**Issue by kjlixx** [swoft-cloud/swoft#1498]
我想开一个进程，然后调用task异步来操作，请问swoft怎么实现

**Comment by kjlixx** [comment]
自定义用户进程，报错信息：
             WARNING Server::reply_task_result(): Server::finish() can only be used in the worker process

**Comment by LGFModel** [comment]
一模一样：我想定时处理一些任务
定时异步处理，结果和你出现了一模一样的问题

**Comment by kjlixx** [comment]
@LGFModel 换了hyperf了😅
