### ISSUE TITLE
分组情况下，希望@Controller() 为空时，路由地址能自动加上分组的名称

### ISSUE THREAD

**Issue by yourphp** [swoft-cloud/swoft#153]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes/no
| Swoft version       | 1.0.0
| Swoole version      | 2.1.1-alpha
| PHP version         | 7.2.2
| Runtime environment | CentOS 7

分组情况下，希望@Controller() 为空时，路由地址能自动加上分组的名称.

**Comment by huangzhhui** [comment]
分组是指文件夹吗

**Comment by yourphp** [comment]
是的

**Comment by stelin** [comment]
@yourphp  2.0 已经正式发布，建议升级到2.0
