### ISSUE TITLE
.env 缺少时区设置

### ISSUE THREAD

**Issue by longhtml** [swoft-cloud/swoft#154]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 1.0.4
| Swoole version      | 2.1.1
| PHP version         | 7.1 (by `php -v`)
| Runtime environment | CentOS 7

**Details**

缺少“时区”设置。

**Comment by daydaygo** [comment]
推荐以下 2 种方式: @huangzhhui  @longhtml 
1. 设置 `php.ini` 文件, 文件地址通过 `php --ini` 查看
2. 在 `bin/swoft` 中使用 `ini_set('date.timezone', 'PRC');` 设置

**Comment by huangzhhui** [comment]
通过.env的TIME_ZONE属性来设置时区
