### ISSUE TITLE
无法在命令模式下使用TASK任务投递。

### ISSUE THREAD

**Issue by yangshen1987** [swoft-cloud/swoft#155]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 2.1.2-alpha
| PHP version         | 7.2.3
| Runtime environment |Ubuntu

**Details**
Fatal error: Uncaught Error: Call to a member function getServer() on null in /home/alex/workspace/codes/swoft/vendor/swoft/task/src/Task.php:39
Stack trace:

> Provide minimal script to reproduce the issue

```php
  public function taskTest(){
        $result  = Task::deliver('sync', 'deliverCo', ['p', 'p2'], Task::TYPE_ASYNC);
        echo $result;
    }
```

**Comment by stelin** [comment]
@yangshen1987 已支持，https://doc.swoft.org/master/zh-CN/console/task.html?refresh=1
