### ISSUE TITLE
官方docker镜像缺少pdo扩展

### ISSUE THREAD

**Issue by yuanliang847** [swoft-cloud/swoft#157]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

task投递任务处理的时候，使用的mysql扩展是pdo，官方docker镜像里没有安装该扩展，处理会报错

**Comment by huangzhhui** [comment]
最新的Docker镜像已经增加
