### ISSUE TITLE
使用内存数据库GET方法时不传第二个参数返回FALSE

### ISSUE THREAD

**Issue by yangshen1987** [swoft-cloud/swoft#159]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 2.1.1
| PHP version         | 7.2.23
| Runtime environment | Ubuntu.

**Details**

> Describe what you are trying to achieve and what goes wrong.
我做一个TABLE的DEMO的时候发现GET时不传第二参数返回的是一个FALSE，传第二个参数时返回结果
```php
// paste output here
```
        $struct = [
            'rule'       => [Table::TYPE_STRING, 100],
            'taskClass'  => [Table::TYPE_STRING, 255],
            'taskMethod' => [Table::TYPE_STRING, 255],
            'add_time'   => [Table::TYPE_STRING, 11],
        ];
        $swoftTable = new Table('shareTable', 1024, $struct);
        $swoftTable->create();
        var_dump($swoftTable->set('yangshen',['rule'=>1,'taskClass'=>1221]));
        var_dump($swoftTable->exist('yangshen'));
        var_dump($swoftTable->get('yangshen',null));
> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by huangzhhui** [comment]
请更新 swoft-memory 组件至 1.0.1 版本以上修复此问题

**Comment by yangshen1987** [comment]
更到DEV-MASTER依然没有解决该问题的说
