### ISSUE TITLE
getResult 传入实体后,数据异常

### ISSUE THREAD

**Issue by aprchen** [swoft-cloud/swoft#160]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | master
| Swoole version      | 2.1.1
| PHP version         | 7.1.4
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
数据库为msql5.6
不传入实体的话,数据是正常的
传入实体的话,目前发现俩个错误,
1是使用工具生成的实体,tinyint 类型识别为了bool,导致查询的数据不符合预期
2是其中有个varchar字段里存的数据为json串,结果查出的数据为空字符串

![image](https://user-images.githubusercontent.com/13740363/37701943-e4aebcb8-2d2b-11e8-87ba-d56d9d1b5483.png)

**Comment by stelin** [comment]
已经修复，db组件更新到1.1.0
