### ISSUE TITLE
使用php bin/swoft entity:create -d命令生成Entity后，页面无法访问，报504错误

### ISSUE THREAD

**Issue by uhonliu** [swoft-cloud/swoft#165]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 2.1.1
| PHP version         | 7.1.15
| Runtime environment | CentOS 7

**Details**
使用php bin/swoft entity:create -d命令生成Entity后，页面无法访问，报504错误

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
[2018-03-23 17:17:54 $27718.0]	WARNING	swManager_check_exit_status: worker#3 abnormal exit, status=255, signal=0
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by huangzhhui** [comment]
不使用此命令能访问？

**Comment by huangzhhui** [comment]
请确认此问题后重新开启此issue
