### ISSUE TITLE
关于使用Swoft搭建我的网站

### ISSUE THREAD

**Issue by alexsunnysun** [swoft-cloud/swoft#17]
看了swoft的文档发现没有直接的方法直接输出网页模板是吗？  是能使用response->setResponseContent是吗？

**Comment by stelin** [comment]
这个方法可以，目前没有提供显示网页模板的方法。下个版本会增加一个简单的显示模板。

**Comment by alexsunnysun** [comment]
收到，你们的框架很赞 就差一个网页模板直接使用了。 👍    : )

**Comment by inhere** [comment]
是有简单的模板渲染支持的， 稍后我给个示例

**Comment by alexsunnysun** [comment]
坐等 :)

**Comment by inhere** [comment]
已经添加了.  查看使用文档 和 源码里的使用示例
https://doc.swoft.org/view-render.html

**Comment by alexsunnysun** [comment]
666 双击  老铁  👍 :)

**Comment by stelin** [comment]
@inhere 👍👍

**Comment by jonny77** [comment]
swoft不是自带http服务器吗 ,如果没有nginx. 怎么设置虚拟主机实现和nginx一样的效果呢?

**Comment by huangzhhui** [comment]
可以使用 $response->view()

**Comment by huangzhhui** [comment]
但是，并不建议直接输出网页模板，具体请查阅文档 控制器 章节

**Comment by jonny77** [comment]
我的意思是 是否可以绑定域名
