### ISSUE TITLE
docker运行，有几次出现不断增加这样的文件

### ISSUE THREAD

**Issue by sunyang3721** [swoft-cloud/swoft#174]
我这是直接从docker pull 下来的

docker-compose up -d   运行之后，一个星期有那么3、4次出现这样的状态，这是什么问题？
我已经删了很多次，还是不断增加。

![360 20180328144621435](https://user-images.githubusercontent.com/8475109/38013188-d0221f2c-3296-11e8-9c08-936a2022a5b4.jpg)

**Comment by whiteCcinn** [comment]
@sunyang3721 昨天修复了一个process的bug，不知道你的coredump文件是不是由于这个bug导致的，请更新swoft/process v1.0.2版本再次尝试，如果修复了，麻烦帮忙close issue。

**Comment by sunyang3721** [comment]
这个bug 把我的服务器搞得开不了机，我晚上update 再观察下

**Comment by huangzhhui** [comment]
coredump文件不会影响服务器

**Comment by sunyang3721** [comment]
更新之后正常了，服务器重新开机的时候，发现根目录满，文件占容量百分40多，  composer update  之后 不会再出现问题了，观察一晚上都正常了。
