### ISSUE TITLE
cron任务阻塞问题

### ISSUE THREAD

**Issue by jianhuihi** [swoft-cloud/swoft#175]
myTask内有  两个cron 任务  一个每分钟执行一次  另外一个10秒执行一次 

目前测试发现1分钟的任务会阻塞10秒的那个任务

跟白菜沟通，后续这里可以优化迭代，记录一下。

**Comment by stelin** [comment]
@jianhuihi 你任务开启的那种模式

**Comment by jianhuihi** [comment]
task_ipc_mode=1

**Comment by stelin** [comment]
@jianhuihi  2.0 已经正式发布，建议升级到2.0， 更简单完善
