### ISSUE TITLE
[Validator] 关于HTTP验证器 Validator 建议

### ISSUE THREAD

**Issue by lu8533783** [swoft-cloud/swoft#176]
HTTP验证器 Validator 需要完善下。
建议增加以下内容：
1、增加可自定义错误返回格式和内容
2、增加可自定义验证规则

**Comment by stelin** [comment]
我们尽快完善！

**Comment by stelin** [comment]
@lu8533783  2.0 已经正式发布，建议升级到2.0 2.0验证器更简单灵活
