### ISSUE TITLE
[view]view是否可以支持静态文件发布功能

### ISSUE THREAD

**Issue by puwei3402023** [swoft-cloud/swoft#181]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by puwei3402023** [comment]
这个怎么说呢,比如一个CSS文件修改了,就会和上一次不一样,就不会去加载上一次的css了,是不是叫静态文件版本控制

**Comment by inhere** [comment]
欧 。。 这个只有你自己控制了，我们咋帮你

比如 link 的css 后面跟个参数 `some.css?v=123` 改动后把参数变动下

**Comment by puwei3402023** [comment]
我现在的做法是写了个函数,内容用MD5加密,在复制到assets下面去,就会每次加载最新的

**Comment by inhere** [comment]
这只是用于开发时吧
