### ISSUE TITLE
[console]php bin/swoft ss 命令输入错误

### ISSUE THREAD

**Issue by puwei3402023** [swoft-cloud/swoft#184]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```
命令输入错误应该友好的提示,不应该是报错

**Comment by inhere** [comment]
console `v1.0.7` 已经调整
