### ISSUE TITLE
[process]自定义Process启动后没有自动回收

### ISSUE THREAD

**Issue by ycy0312** [swoft-cloud/swoft#185]
1、使用官方提供的自定义Process
2、在Control中调用，成功启动
3、再次调用Control出现notice，提示进程已被启动了
     `PHP Warning:  Swoole\Process::start(): process has already been started.`
4、查看机器进程列表，发现第一次启动的进程常驻在那里
![image](https://user-images.githubusercontent.com/22163837/38553040-97773446-3cf0-11e8-92d9-56c76e8fd252.png)

**Comment by inhere** [comment]
正在修复中

**Comment by zhangxuanru** [comment]
请教一下， 自定义Process如何启动 ？

**Comment by limingxinleo** [comment]
@zhangxuanru https://doc.swoft.org/master/zh-CN/process/course.html
