### ISSUE TITLE
[db]当用AR快速查询findOne 并限制获取字段时会报错

### ISSUE THREAD

**Issue by xemxx** [swoft-cloud/swoft#190]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 2.1.1
| PHP version         | 7.2.4
| Runtime environment | Mac

**Details**

> 当用AR快速查询findOne 并限制获取字段时会报某个字段返回类型错误，但去掉限制条件无错误

```php
$user=Users::findOne(['id'=>1],['fields'=>['username','password']])->getResult();
 return $user;
```
报错如下：
>["\/Users\/xem\/code\/own\/yoyoapi\/app\/Models\/Entity\/Users.php Return value of App\\Models\\Entity\\Users::getOpenid() must be of the type string, null returned 203"]

数据库：
![image](https://user-images.githubusercontent.com/26523062/38737277-4eea1dce-3f61-11e8-92ea-ca68ceaf94e9.png)

**Comment by stelin** [comment]
这是实体语法错误

**Comment by xemxx** [comment]
@stelin 实体我用工具生成的:relieved:

**Comment by stelin** [comment]
已修复，db组件请更新至v1.1.4

**Comment by AaronWB** [comment]
使用findOne添加fields参数查询后使用rpc调用会报错，本地服务能查询到结果，调用方提示响应状态无效
