### ISSUE TITLE
[db]Swoft\Db\Model的fill方法与数据库实体的set方法不兼容

### ISSUE THREAD

**Issue by heavenqq** [swoft-cloud/swoft#191]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
当数据库存在下划线字段时，如:add_time，实体会生成 setAddTime方法，然后用Swoft\Db\Model的fill方法向数据库写入内容时，会与实体生成setAddTime方法不兼容，无法更新add_time字段

```php
// paste output here
$data =[
     'add_time'=>time()
]
$member = new EwgMember();
$member->fill($data)->save()->getResult();
```

> Provide minimal script to reproduce the issue

```php
// paste code
实体的setAddTime方法
public function setAddTime(int $value): self
    {
        $this->add_time = $value;

        return $this;
    }
//Swoft\Db\Model的fill方法
public function fill(array $attributes): self
    {
        foreach ($attributes as $name => $value) {
            $methodName = sprintf('set%s', ucfirst($name));
            if (method_exists($this, $methodName)) {
                $this->$methodName($value);
            }
        }

        return $this;
    }

```

**Comment by stelin** [comment]
建议属性名称，统一定义成驼峰，再映射数据库字段，

**Comment by inhere** [comment]
他这是 命令根据表生成的
