### ISSUE TITLE
-d swoft.pid文件不会更新

### ISSUE THREAD

**Issue by zibber2015** [swoft-cloud/swoft#194]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       |  1 .0
| Swoole version      | 2.10
| PHP version         | 7.1
| Runtime environment | Ubuntu16

**Details**

> php bin/swoft ws:start/restart -d 启动swoft.pid不会变化, 前台启动就没问题, 目前只有一个项目

**Comment by stelin** [comment]
@zibber2015 2.0 已经正式发布，建议升级到2.0
