### ISSUE TITLE
[doc]adding english documentation

### ISSUE THREAD

**Issue by masihfathi** [swoft-cloud/swoft#195]
hi, it is really good to create english documentation as soon as possible and make the documentation like yii2 documentation which list properties and methods and base class and example for some usable parts and separate guide from api describing

**Comment by Jurigag** [comment]
Up

**Comment by inhere** [comment]
@Jurigag If you can help us translate the document, we will thank you very much!

**Comment by Jurigag** [comment]
Well i don't know chinese at all, It would be easier to use some collaborating tool for it - i recommend using crowdin. It's free for open source projects.

**Comment by inhere** [comment]
@Jurigag @masihfathi Now, swoft v2 version already has the English version of the document.
Please see https://swoft.org/docs/2.x/en
