### ISSUE TITLE
“trace[Executor.php:427,Swoft\Db\Executor::validate] 验证器不存在，beanName=ValidatorInt” in file runtime/error.log 

### ISSUE THREAD

**Issue by dormscript** [swoft-cloud/swoft#197]
重现：
1：打开错误提示, config/beands/log.php ,  logger.enable = true

2：数据库进行save操作，runtime/error.log中报错如下：

Swoft\Db\Executor::validate] 验证器不存在，beanName=ValidatorString
Swoft\Db\Executor::validate] 验证器不存在，beanName=ValidatorInt

**Comment by huangzhhui** [comment]
目前所有组件均使用 [swoft-cloud/swoft-component](https://github.com/swoft-cloud/swoft-component) 仓库来管理再分发到各个组件去，请将此 pr 的修改提到 component 仓库的 db 组件相关的代码去
