### ISSUE TITLE
新增文件配置路由后需要重启的问题，这个时候热更新就没用了

### ISSUE THREAD

**Issue by q495265366** [swoft-cloud/swoft#201]
新增了一个控制器然后写好了对应的路由再不重启的情况下一直无法访问。
手动重启一下swoft就好了，可以访问了

**Comment by inhere** [comment]
这种情况是可能出现的，检查到这样的情况后，记得尝试重启 :)

**Comment by stelin** [comment]
配置文件没有加入热更新里面
