### ISSUE TITLE
数据库的实体类，AR操作无法查询到数据问题

### ISSUE THREAD

**Issue by q495265366** [swoft-cloud/swoft#202]
`$rs = WfAdmin::findById(1)->getResult();`
无法直接打印$rs，只能单个调用某个字段如$rs->getName();这样才可以。。。如果你直接打印$rs会是空。。。。

**Comment by inhere** [comment]
直接 var_dump 是有效的，你那是嵌套到了一个 array 里，就出问题了

**Comment by stelin** [comment]
rs返回的是一个实体对象，如果需要数组就toArray
