### ISSUE TITLE
[redis]异步redis  问题

### ISSUE THREAD

**Issue by webphplove** [swoft-cloud/swoft#210]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> 异步redis的sRem()和sCard()方法无效

```php
    /**
     * @Inject()
     * @var Redis
     */
    private $redis;

    public function testFd(){
          $this->redis->sRem($key, $fd);
          $this->redis->sCard($key);
   }
    
```

**Comment by stelin** [comment]
redis组件更新至1.0.7，已经修复
