### ISSUE TITLE
[db]关于实体类，字段类型支持不完整问题，如不支持bigint字段类型

### ISSUE THREAD

**Issue by q495265366** [swoft-cloud/swoft#214]
对于数据库类型支持不完整，比如bigint无法识别，其他的还没有尝试过
![default](https://user-images.githubusercontent.com/10863909/39103151-a97083ce-46db-11e8-84c5-8f9a6126348e.png)

**Comment by stelin** [comment]
@q495265366 从代码没看出那里需要有问题，具体点！

**Comment by stelin** [comment]
已修复，db组件更新值1.1.8
