### ISSUE TITLE
SESSION会话配置完毕后，配置参数不起作用

### ISSUE THREAD

**Issue by q495265366** [swoft-cloud/swoft#215]
不知道这个代码加位置对不对，但目前看来就是配置参数没有被加载或者赋值。
目前我自己是以下修改 `vendor\swoft\session\src\Middleware\SessionMiddleware.php`

文件再process方法内第一行加入 `$this->config = bean('sessionManager')->getConfig();`

```php
public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $this->config = bean('sessionManager')->getConfig();
        $this->sessionHandled = true;
    }
```

但是发现只有ID什么的起作用但是其他的貌似都没有生效

**Comment by huangzhhui** [comment]
https://github.com/swoft-cloud/swoft-session/releases/tag/v1.0.3
