### ISSUE TITLE
前置进程中无法调Logic

### ISSUE THREAD

**Issue by ycy0312** [swoft-cloud/swoft#216]
这个Logic是可以正常使用的，在controller中调用正常。

前置进程：

![image](https://user-images.githubusercontent.com/22163837/39109697-912056bc-4700-11e8-85ea-0027973fa83f.png)

logic定义：

![image](https://user-images.githubusercontent.com/22163837/39109678-77baa268-4700-11e8-8825-6cca254220be.png)

执行结果：
![image](https://user-images.githubusercontent.com/22163837/39109703-98363548-4700-11e8-971e-ca67ebc5f407.png)

**Comment by huangzhhui** [comment]
并没有看到此bean有定义你用于获取的别名

**Comment by ycy0312** [comment]
@huangzhhui 定义不对？第二张图类开头不是定义吗？

**Comment by inhere** [comment]
`@Bean()` 不设置名称，默认使用类名称。 这个类名称是**完整的类名称**

**Comment by ycy0312** [comment]
![image](https://user-images.githubusercontent.com/22163837/39112320-affe82ca-470a-11e8-9c3e-719d502a3583.png)

用了别名还是不行 @inhere

**Comment by inhere** [comment]
@ycy0312  怎么关了

**Comment by ycy0312** [comment]
找到可行的调用方式了，使用别名会报错，目前可行的调用方式：
1、将文件加入扫描
2、use文件命名空间
3、App::getBean(XXX::class)
 @inhere

**Comment by inhere** [comment]
我看你最后一张设置的别名，跟前面调用那里 对不上啊 

第一个字符，一个大写一个小写的

**Comment by ycy0312** [comment]
都试过的，不行 @inhere
