### ISSUE TITLE
怎么给swoft开发个插件？

### ISSUE THREAD

**Issue by wuchuguang** [swoft-cloud/swoft#217]
如题，要给swoft加个队列。
如何下手？

**Comment by huangzhhui** [comment]
这个可参考Swoft的各个组件，如果不需要嵌入到框架的一下机制上，正常的PHP包开发即可，通过Composer加载

**Comment by stelin** [comment]
先熟悉下swoft框架加载和初始化流程

**Comment by wuchuguang** [comment]
文档有些少，要看源码了。。

**Comment by limingxinleo** [comment]
@wuchuguang 
给你几个例子：
[Aop 缓存](https://github.com/limingxinleo/swoft-aop-cacheable)
[加密/签名组件](https://github.com/zcmzc/swoft-encrypt)

你可以用这个脚本初始化swoft组件仓库
[Swoft组件脚本](https://github.com/limingxinleo/swoft-component-creater)
