### ISSUE TITLE
定时任务在docker环境无法运行

### ISSUE THREAD

**Issue by ycy0312** [swoft-cloud/swoft#219]
1、非docker环境下直接运行正常
2、docker环境下运行报错如下：
![image](https://user-images.githubusercontent.com/22163837/39168511-c30765aa-47c6-11e8-8231-e7ebcef1f606.png)

已与开发组 【白菜】反馈，希望尽快修复。

**Comment by whiteCcinn** [comment]
该问题初步定位为swoole_table在docker下的bug，等待swoole解决

**Comment by jianhuihi** [comment]
官方说的很清楚 需要pcre支持  镜像加入pcre即可
