### ISSUE TITLE
打开项目中默认的前置进程，命令行一直afterProcess,beforeProcess但PS -aux中没有进程名

### ISSUE THREAD

**Issue by zhangxuanru** [swoft-cloud/swoft#220]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

   1. 修改项目中  app/Boot/MyProcess.php。

/**
 * Custom process
 *
 * @Process(boot=true)
 */
class MyProcess implements ProcessInterface
{
  ¦ public function run(SwoftProcess $process)
  ¦ { 
  ¦ ¦ ¦ $pname = App::$server->getPname();
  ¦ ¦ ¦ $processName = "$pname myProcess process";
  ¦ ¦ ¦ $process->name($processName); 
  ¦ ¦ ¦ ProcessBuilder::create('customProcess')->start();
  ¦ } 

2.修改app/Process/MyProcess.php
/**
 * Custom process
 *
 * @Process(name="customProcess", coroutine=true)
 */
class MyProcess implements ProcessInterface
{
  ¦ public function run(SwoftProcess $process)
  ¦ { 
  ¦ ¦ ¦ $pname = App::$server->getPname();
  ¦ ¦ ¦ $processName = "$pname myProcess process";
  ¦ ¦ ¦ $process->name($processName); 
  ¦ } 

3.运行 bin/swoft start, 效果如下:
2018/04/24 18:22:36 [DEBUG] [Application] [WorkerId:0] Trigger the event afterProcess 
2018/04/24 18:22:36 [DEBUG] [Application] [WorkerId:0] Trigger the event beforeProcess 
2018/04/24 18:22:36 [DEBUG] [Application] [WorkerId:0] Trigger the event afterProcess 
2018/04/24 18:22:36 [DEBUG] [Application] [WorkerId:0] Trigger the event applicationLoader 
2018/04/24 18:22:36 [DEBUG] [Application] [WorkerId:0] Trigger the event beforeProcess 
2018/04/24 18:22:36 [DEBUG] [Application] [WorkerId:0] Trigger the event afterProcess 
2018/04/24 18:22:36 [DEBUG] [Application] [WorkerId:0] Trigger the event beforeProcess 
2018/04/24 18:22:36 [DEBUG] [Application] [WorkerId:0] Trigger the event afterProcess 
2018/04/24 18:22:36 [DEBUG] [Application] [WorkerId:0] Trigger the event applicationLoader 
2018/04/24 18:22:36 [DEBUG] [Application] [WorkerId:0] Trigger the event beforeProcess 
2018/04/24 18:22:36 [DEBUG] [Application] [WorkerId:0] Trigger the event afterProcess 
2018/04/24 18:22:36 [DEBUG] [Application] [WorkerId:0] Trigger the event beforeProcess 
2018/04/24 18:22:36 [DEBUG] [Application] [WorkerId:0] Trigger the event afterProcess 
2018/04/24 18:22:37 [DEBUG] [Application] [WorkerId:0] Trigger the event applicationLoader 
2018/04/24 18:22:37 [DEBUG] [Application] [WorkerId:0] Trigger the event beforeProcess 
2018/04/24 18:22:37 [DEBUG] [Application] [WorkerId:0] Trigger the event afterProcess 
2018/04/24 18:22:37 [DEBUG] [Application] [WorkerId:0] Trigger the event beforeProcess 
2018/04/24 18:22:37 [DEBUG] [Application] [WorkerId:0] Trigger the event afterProcess 
2018/04/24 18:22:37 [DEBUG] [Application] [WorkerId:0] Trigger the event applicationLoader 
2018/04/24 18:22:37 [DEBUG] [Application] [WorkerId:0] Trigger the event beforeProcess 
2018/04/24 18:22:37 [DEBUG] [Application] [WorkerId:0] Trigger the event afterProcess 
2018/04/24 18:22:37 [DEBUG] [Application] [WorkerId:0] Trigger the event beforeProcess 
2018/04/24 18:22:37 [DEBUG] [Application] [WorkerId:0] Trigger the event afterProcess 
 

[root@iZ2ze6yh0lvepn9x5kgs8xZ ~]# ps -aux |grep process
Warning: bad syntax, perhaps a bogus '-'? See /usr/share/doc/procps-3.2.8/FAQ
root      4669  0.0  0.4 263704  4648 ?        Ss   Apr17   0:13 php-fpm: master process (/usr/local/php/etc/php-fpm.conf)
root      4719  0.0  0.2  37408  2056 ?        Ss   Apr17   0:00 nginx: master process /usr/local/nginx/sbin/nginx
www       4750  0.0  2.3  61984 24136 ?        S    Apr17   0:00 nginx: worker process      
root     23133  0.5  4.0 371032 41528 pts/2    Sl+  18:22   0:00 php-swoft master process (../bin/swoft)
root     23134  0.0  0.8 295020  8968 pts/2    S+   18:22   0:00 php-swoft manager process
root     23136  1.4  1.8 302480 18644 pts/2    S+   18:22   0:00 php-swoft task process
root     23137  1.4  1.8 302876 18880 pts/2    S+   18:22   0:00 php-swoft worker process
root     23139  1.4  1.8 304664 18656 pts/2    S+   18:22   0:00 php-swoft reload process
root     23263  6.0  1.1 297292 11792 pts/2    R+   18:22   0:00 php-swoft manager process

运行结果：
   命令行一直出现 afterProcess, beforeProcess。 但ps -aux 中没有出现进程名。。

    我才刚接触这个框架， 不知道出现这种情况是否是正常的 ？ 

 
> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by cirvor** [comment]
运行环境是否为mac？
目前swoole的`swoole_process->name`方法在mac上存在问题
因此会导致上述问题
>https://wiki.swoole.com/wiki/page/364.html

**Comment by stelin** [comment]
@cirvor  2.0 已经正式发布，建议升级到2.0
