### ISSUE TITLE
自定义Process如何启动

### ISSUE THREAD

**Issue by zhangxuanru** [swoft-cloud/swoft#222]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
 
请教一下， 自定义Process如何启动 ？

app/Boot/MyProcess.php

/**

Custom process
@process(boot=false)
*/
class MyProcess implements ProcessInterface
{
  ¦ public function run(SwoftProcess $process)
  ¦ { 
  ¦ ¦ ¦ $pname = App::$server->getPname();
  ¦ ¦ ¦ $processName = "$pname myProcess process";
  ¦ ¦ ¦ $process->name($processName); 
  ¦ ¦ ¦ ProcessBuilder::create('customProcess')->start();
  ¦ }

  ¦ public function check(): bool
  ¦ {
  ¦ ¦ ¦ return true;
  ¦ }
}

如果这里设置的不是 前置进程， 是不是 就没法启动这个进程呢 ？

如果我再定义其它进程，都必须设置成前置进程才可以运行吗? 没法在Controllers中去手动启动自定义的进程吗? 

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by whiteCcinn** [comment]
@zhangxuanru 有问题群交流，有bug，反馈issue。

**Comment by stelin** [comment]
非前置进程，需要手动create使用

**Comment by stelin** [comment]
Process::create(xxx)
