### ISSUE TITLE
[db]查询器左右联查报错

### ISSUE THREAD

**Issue by q495265366** [swoft-cloud/swoft#225]
![default](https://user-images.githubusercontent.com/10863909/39281805-1a9f9ecc-4939-11e8-8da1-b2c1ff1411d5.png)
![default](https://user-images.githubusercontent.com/10863909/39281814-27c4846e-4939-11e8-8a22-9e763da78df1.png)

**Comment by stelin** [comment]
已修复，db组件请更新至 v1.1.4
