### ISSUE TITLE
多task,worker进程下getBean得来的单例，有价值吗？感觉有缺陷

### ISSUE THREAD

**Issue by wuchuguang** [swoft-cloud/swoft#227]
getBean是从容器拿bean,如果这个bean定义为一个单例 ，以为一直是单例，会有哪些缺陷！

**Comment by inhere** [comment]
- 大多数情况下使用单例对象是没有问题的。 
- 有需要的可以在使用 Bean tag 时注明不使用单例，而使用工厂方式，每次获取新的对象。

这些都是支持，文档上面也是说了的。
