### ISSUE TITLE
DB组件leftJoin查询强制指定前缀。导致某些查询或者情况无法使用

### ISSUE THREAD

**Issue by q495265366** [swoft-cloud/swoft#229]
```
$data = Query::table('wf_admin'， ‘a')
            ->leftJoin('wf_admin_nexus_role',['b.admin_id' => 'a.id'], 'b')
            ->condition($where)
            ->one()
            ->getResult();
```
类似这样会强制给leftJoin的ON条件加上前缀，这让人很恶心。
建议能不能赶紧完善DB操作，或者移植TP,YII,medoo

![_qviagm hz567xuuju8h5 8](https://user-images.githubusercontent.com/10863909/39393874-2cd152fa-4afd-11e8-810d-fcdb35a00ff1.png)

**Comment by stelin** [comment]
这是一个bug，不是强制性的，我们尽快修复！

**Comment by stelin** [comment]
你语法使用不对，正确方式是

$data = Query::table('wf_admin'， ‘a')
            ->leftJoin('wf_admin_nexus_role',['b.admin_id=a.id'], 'b')
            ->condition($where)
            ->one()
            ->getResult();
