### ISSUE TITLE
session()方法不能使用

### ISSUE THREAD

**Issue by xiao872380658** [swoft-cloud/swoft#233]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

![image](https://user-images.githubusercontent.com/6781698/39659070-e043ebfe-5052-11e8-80b4-6f6733b62add.png)

> Provide minimal script to reproduce the issue

```php
$sess =  session(); //->put(['uid' => $user2['id']]);
$sess->put(['uid' => $user2['id']]);
```

Return value of Swoft\Session\SessionManager::getSession() must implement interface Swoft\Session\SessionInterface, null returned"

**Comment by huangzhhui** [comment]
请检查是否正确配置Session组件，尤其是相关的中间件是否已经加入全局中间件配置内，请参考[文档](https://doc.swoft.org/master/zh-CN/session/quickstart.html#%E5%AE%89%E8%A3%85%E5%B9%B6%E5%90%AF%E7%94%A8)

**Comment by carpcai** [comment]
Your usage is wrong. Put method needs to pass the second parameter.
中文：put方法需要传两个参数
```php
$sess =  session(); //->put(['uid' => $user2['id']]);
$sess->put('uid', $user2['id']);
```

**Comment by donglf681** [comment]
我也遇到同样的错误了，请问是如何解决的？
报错如下
`PHP Fatal error:  Uncaught TypeError: Return value of Swoft\Session\SessionManager::getSession() must implement interface Swoft\Session\SessionInterface, null returned in /var/www/vendor/swoft/session/src/SessionManager.php:99
Stack trace:
#0 /var/www/vendor/swoft/session/src/Helper/Functions.php(12): Swoft\Session\SessionManager->getSession()
#1 /var/www/app/Commands/TestCommand.php(39): session()
#2 /var/www/vendor/swoft/framework/src/Helper/PhpHelper.php(47): App\Commands\TestCommand->debug()
#3 /var/www/vendor/swoft/console/src/Router/HandlerAdapter.php(96): Swoft\Helper\PhpHelper::call(Array, Array)
#4 /var/www/vendor/swoft/framework/src/Helper/PhpHelper.php(44): Swoft\Console\Router\HandlerAdapter->Swoft\Console\Router\{closure}()
#5 /var/www/vendor/swoft/framework/src/Core/Coroutine.php(73): Swoft\Helper\PhpHelper::call(Object(Closure))
#6 {main}
  thrown in /var/www/vendor/swoft/session/src/SessionManager.php on line 99
`
配置文件：
`'serverDispatcher' => [
        'middlewares' => array_filter([
            env('MIDDLEWARE_DEV_TOOL'),
            env('MIDDLEWARE_SIGN'),
            \Swoft\Auth\Middleware\AuthMiddleware::class,
            \App\Middlewares\CorsMiddleware::class,
            \Swoft\Session\Middleware\SessionMiddleware::class,
        ])
    ],
    // 注意Bean大小写
    'sessionManager' => [
        'class' => \Swoft\Session\SessionManager::class,
        'config' => [
            'driver' => 'redis',
            'name' => 'SWOFT_SESSION_ID',
            'lifetime' => 1800,
            'expire_on_close' => false,
            'encrypt' => false,
            'storage' => '@runtime/sessions',
        ],
    ],`
使用方式：
`session()->put('CODE_SESSION_ID', '12de');
 session()->get('CODE_SESSION_ID');
`
