### ISSUE TITLE
docker-compose up这个命令在docker-tools下不能正常启动container

### ISSUE THREAD

**Issue by sowork** [swoft-cloud/swoft#234]
系统：win7

**Details**

$ docker-compose up
Creating network "swoft_default" with the default driver
Pulling swoft (swoft/swoft:latest)...
latest: Pulling from swoft/swoft
Digest: sha256:9ebac540ea7506e7d1871b94ad546df0e86e9d08338e1c57a75462caea0a0b00
Status: Downloaded newer image for swoft/swoft:latest
Creating swoft ... done
Attaching to swoft
swoft    | Could not open input file: /var/www/swoft/bin/swoft
swoft exited with code 1

**Comment by inhere** [comment]
使用 `docker-compose up` 你要先确认 `docker-compose.yml` 里配置的文件夹挂载路径是否正确
