### ISSUE TITLE
Notice: Undefined index: spanid in 

### ISSUE THREAD

**Issue by zibber2015** [swoft-cloud/swoft#236]
| Q                   | A
| ------------------- | -----
| Bug report?         |yes
| Feature request?  |  no
| Swoft version       | 1.0
| Swoole version      | 2.1.0 (by `php --ri swoole`)
| PHP version         | 7.2 (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
```
Notice: Undefined index: spanid in /Users/*/Code/swoft/vendor/swoft/framework/src/Core/RequestContext.php on line 191
```

> Describe what you are trying to achieve and what goes wrong.
ws 启动报这个错

**Comment by inhere** [comment]
这应该是调用记录日志导致的， log 时要收集上下文信息 - spanid (从 RequestContext  去拿的)
但是 ws 流程里 RequestContext 是空的

**Comment by stelin** [comment]
@inhere ws那边做一个默认值。

**Comment by inhere** [comment]
是 RequestContext 获取 spanid 那有问题，应该向 logid 那样 没有返回 0

**Comment by stelin** [comment]
是的，那优化

**Comment by huangzhhui** [comment]
看了下 SpanId 的获取是有先判断 isset 的，理应不会出现此 notice @inhere @stelin

**Comment by inhere** [comment]
是后面改了的

**Comment by huangzhhui** [comment]
那这个issue就close掉了
