### ISSUE TITLE
[sg]希望可以修改 ConsulProvider 类中的 discoveryTag

### ISSUE THREAD

**Issue by scmforever** [swoft-cloud/swoft#239]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | x.y.z
| Swoole version      | 2.1.1
| PHP version         | 7.1.15

**Details**

> 希望 `swoft/Sg/Provider/ConsulProvider` 类可以提供函数对类中的 `$discoveryTag` 进行修改，这样就可以在不同 rpc 服务的连接池中提供不同的 tag，来过滤 consul 返回的 url 列表

```php
class BaseServicePool extends ServicePool
{
    /**
     * @var MyConsulProvider
     * @Inject()
     */
    protected $provider;

    /**
     * @var BasePoolConfig
     */
    protected $poolConfig;

    protected function getServiceList()
    {
        $name = $this->poolConfig->getName();
        $tag = $this->poolConfig->getTag();

        return $this->provider->setTag($tag)->getServiceList($name);
    }
}
```

**Comment by scmforever** [comment]
可以与 issues 198 合并一起做

**Comment by stelin** [comment]
服务发现tag支持的文档没有写

/**
     * Specifies the tag to filter the list. This is specifies as part of the URL as a query parameter.
     *
     * @Value(name="${config.provider.consul.discovery.tag}", env="${CONSUL_DISCOVERY_TAG}")
     * @var string
     */
    private $discoveryTag = "";

**Comment by scmforever** [comment]
明白，但是如果一个服务调用方需要调用多个服务，每个服务的 Tag 不一样，这就用不了了。
我的意思是，看看能不能对 ConsulProvider 公开一个方法可以从外部修改 $discoverTag，然后每个进程池的 poolConfig 中配置该服务的 Tag

**Comment by scmforever** [comment]
![image](https://user-images.githubusercontent.com/13246984/39853845-3e292b00-5457-11e8-9398-58dea5f780a5.png)

**Comment by stelin** [comment]
这个考虑优化下。

**Comment by stelin** [comment]
@scmforever  2.0 已经正式发布，建议升级到2.0，服务治理更简单
