### ISSUE TITLE
db组件sql未加转义

### ISSUE THREAD

**Issue by ycy0312** [swoft-cloud/swoft#245]
如果sql插入的字段中带英文引号，sql执行将失败，sql打印如下：
1、先用的db v1.0.9
![image](https://user-images.githubusercontent.com/22163837/40214744-13578a96-5a8f-11e8-8f6f-84e88f61c027.png)

2、后使用db v1.1.11 报错
![image](https://user-images.githubusercontent.com/22163837/40214817-7e4c6cc2-5a8f-11e8-807c-b1a082c83318.png)
![image](https://user-images.githubusercontent.com/22163837/40214808-75dd8602-5a8f-11e8-9297-2e3df7da236b.png)

因此推测未对sql进行转义。

**Comment by stelin** [comment]
@ycy0312 2.0 已经正式发布，建议升级到2.0
