### ISSUE TITLE
[http-server]服务端无法获取ajax post请求参数

### ISSUE THREAD

**Issue by 769835303** [swoft-cloud/swoft#246]
在发ajax post请求是，request header如下所示：
![default](https://user-images.githubusercontent.com/12715467/40224470-d4e89cbc-5ab8-11e8-864a-df06b163770b.png)
swoft通过Swoft\Http\Server\Parser\RequestParser解析请求时，无法正确调用RequestJsonParser来处理请求，如下图所示：
![3](https://user-images.githubusercontent.com/12715467/40224635-5466da44-5ab9-11e8-8361-139f72793dce.png)

手动将$contentType改为application/json时，可以正常解析post数据，但数据是保存在Request的bodyParams属性中，Request对象的post方法是从Request的parseBody属性中获取数据的，从而导致通过post和input都获取不到post请求中的参数

**Comment by Littlesqx** [comment]
Content-Type 为 `application/json` 的 POST 请求可使用 `$request->json()`获取请求内容，`$request->post()` 不能获取，严格来说这种方式发的是发的 json 而不是键值对，简单的`$request->post()` 或 `$request->input()` 是很难拿的（因为不是一维的键值对）。Swoole 底层的 API 也是 rawContent 获取后再 decode。

RequestJsonParser 的问题（application/json 可以，application/json;chartset=UTF-8）可能是 bug，其他都不是。

**Comment by limingxinleo** [comment]
@inhere 

application/json;chartset=UTF-8 通过$request->json()获取不到的问题已经改过了。

但是，是否要支持input也能拿到json的数据呢？

**Comment by stelin** [comment]
@769835303 2.0 已经正式发布， 建议升级到2.0
