### ISSUE TITLE
多文件上传502

### ISSUE THREAD

**Issue by cpj555** [swoft-cloud/swoft#247]
![1](https://user-images.githubusercontent.com/19289096/40299400-bb4d4908-5d18-11e8-90de-0756fa188836.png)
![2](https://user-images.githubusercontent.com/19289096/40299401-bba1cc44-5d18-11e8-8be5-8204ca2eacdc.png)
![3](https://user-images.githubusercontent.com/19289096/40299402-bbf2bfa0-5d18-11e8-9ea6-21121bd06e41.png)
单文件没问题。
多文件一个能接受,多个会502。
还有多文件toArray的问题

**Comment by huangzhhui** [comment]
@cpj555 相关的代码也提供一下

**Comment by cpj555** [comment]
![1](https://user-images.githubusercontent.com/19289096/40304313-e9a36ed0-5d28-11e8-8200-ff59acbddeeb.png)
@inhere

**Comment by huangzhhui** [comment]
测试是没有问题的，无法重现此 issue   
![image](https://user-images.githubusercontent.com/12077148/41192947-9b70f2cc-6c38-11e8-8e53-6a4386be87a3.png)
![image](https://user-images.githubusercontent.com/12077148/41192951-ac42d016-6c38-11e8-8849-36c34e4c3880.png)
