### ISSUE TITLE
[redis] 配置认证密码无法正常连接

### ISSUE THREAD

**Issue by guanzhao** [swoft-cloud/swoft#249]
redis 配置认证密码无法正常连接
![1](https://user-images.githubusercontent.com/4636457/40400987-1d79bd32-5e77-11e8-9cb7-b16c0e8fb79f.png)
![2](https://user-images.githubusercontent.com/4636457/40400991-1e2fc71c-5e77-11e8-98b2-14bbc686f0ac.png)

**Comment by daydaygo** [comment]
`            $error = sprintf('Redis Connection format is incorrect uri=%s, eg:tcp://127.0.0.1:6379/1?auth=password', $uri);
`

**Comment by guanzhao** [comment]
`namespace Swoft\Redis;

RedisConnection.php
到这个方法这里过不去了getConnectRedis 
`
$error = sprintf('Redis connection failure host=%s port=%d', $host, $port);

CLI 和工具都可以正常连接

**Comment by guanzhao** [comment]
没有特殊字符就是字母和数字

**Comment by guanzhao** [comment]
@inhere 没有特殊字符只要字母和数字

**Comment by inhere** [comment]
但是其他人也有用密码的呀，没有这个问题

你用 Swoole 的 协程redis 客户端连接试下呢

**Comment by guanzhao** [comment]
@inhere Swoole  协程redis 客户端连 也是一样不行

**Comment by guanzhao** [comment]
@inhere tcp://127.0.0.1:6379/1?auth=123456abc  127.0.0.1:6379?auth=123456abc
tcp://127.0.0.1:6379/?auth=123456abc  127.0.0.1:6379/?auth=123456abc
我把这几种写法都测试了

**Comment by inhere** [comment]
是不是你没有启用 协程 ？
安装hiredis,启用异步redis 没 ？

运行： `php bin/swoft app:check` 看下

**Comment by guanzhao** [comment]
@inhere 全部是YES
PHP version is greater than 7?                Yes (current is 7.1.14)
  Swoole extension is installed?                Yes
  Swoole version is greater than 2.1?           Yes (current is 2.1.3)
  Swoole async redis is enabled?                Yes
  Swoole coroutine is enabled?                  Yes

Extensions that conflict with 'swoole'

   - zend                                       Yes
   - xdebug                                     Yes
   - xhprof                                     Yes
   - blackfire                                  Yes

**Comment by inhere** [comment]
如果用 Swoole 的协程redis 客户端连接都不行

- 你的环境有问题
- redis 配置有问题
- swoole 内部问题(版本低了？)

**Comment by guanzhao** [comment]
我升级下试试~  我把环境从新在搭建下.

**Comment by guanzhao** [comment]
从新安装了下环境之后,就好了
