### ISSUE TITLE
redis 认证密码中含有 & 符号时无法正常连接

### ISSUE THREAD

**Issue by EdenChan** [swoft-cloud/swoft#251]
例如 redis 连接为 tcp://127.0.0.1:6379?auth=W&AAA，auth 部分无法得到完整 password，

会被 parse_str 截断成：

['auth' => 'W', 'AAA' => '']

导致认证失败

**Comment by EdenChan** [comment]
同样的问题也出现在 mysql 的连接配置中，建议还是显式配置这部分比较好，直接解析连接 uri 可能还会出现别的因为特殊符号导致的问题

**Comment by inhere** [comment]
需要自己先将参数url encode 下

**Comment by EdenChan** [comment]
@inhere urlencode 后会提示连接格式有误，parse_url 貌似会拿不到连接里的信息

**Comment by inhere** [comment]
只编码 参数值 

`tcp://127.0.0.1:6379?auth=W&AAA` to `tcp://127.0.0.1:6379?auth=W%26AAA`

```php
$info = parse_url('tcp://127.0.0.1:6379?auth=W%26AAA');
parse_str($info['query'], $args);

var_dump(
    $info, $args
);
```

output:

```text
array(4) {
  ["scheme"]=>
  string(3) "tcp"
  ["host"]=>
  string(9) "127.0.0.1"
  ["port"]=>
  int(6379)
  ["query"]=>
  string(12) "auth=W%26AAA"
}
array(1) {
  ["auth"]=>
  string(5) "W&AAA"
}
```

**Comment by EdenChan** [comment]
这样可以，多谢
