### ISSUE TITLE
WAMP - The Web Application Messaging Protocol Implementation

### ISSUE THREAD

**Issue by mhf-ir** [swoft-cloud/swoft#252]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | any
| Swoole version      | 2.2.0
| PHP version         | 7.2.5
| Runtime environment | Docker (Ubuntu 18.04)

Request feature: WAMP 2 server implementation for websocket ... client is optional but server requirement.

Implementation of WAMP protocol version 2
https://wamp-proto.org/
https://wamp-proto.org/why/index.html

JavaScript implementation of client wamp
https://github.com/crossbario/autobahn-js

Server Implementation:
WAMP1 (legacy)
http://socketo.me/docs/wamp

**Comment by stelin** [comment]
@mhf-ir You can update to swoft 2.0, It will be better!
