### ISSUE TITLE
Commands执行命令里面，获取全局变量或者通过config获取配置属性无效

### ISSUE THREAD

**Issue by huazaili** [swoft-cloud/swoft#253]
/**
     * @Value(name="${config.rabbitmq.queueName}", env="${RABBITMQ_QUEUE_NAME}")
     * @var string
     */
    protected $queueName = '';   //获取为空

   env('UDP_LOG_URI')  //获取为空

**Comment by stelin** [comment]
@huazaili 2.0 已经正式发布， 建议升级到2.0
