### ISSUE TITLE
Command下注解无法自动注入,需要用bean来获取

### ISSUE THREAD

**Issue by CodeMonkeyLuffy** [swoft-cloud/swoft#257]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | x.y.z
| Swoole version      | 2.2.0
| PHP version         | 7.1.12
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> 找不到redis方法报错

```php
class TestCommand
{
    /**
     * @Inject()
     * @var \Swoft\Redis\Redis
     */
    private $redis;
    
    /**
     * this test command
     */
    public function test(Input $input, Output $output)
    {
        $result = $this->redis->set('name', 'swoft');
        var_dump($result);
    }
```

**Comment by huangzhhui** [comment]
Command 是实现不了的，会影响 Reload 功能

**Comment by jianhuihi** [comment]
command  process 不能使用service? 只能使用logic？

**Comment by stelin** [comment]
这个是两个不同的生命周期，暂时不好实现，后续想下有没有好办法！
