### ISSUE TITLE
redis list方法缺rpoplpush,brpoplpush,lpushx

### ISSUE THREAD

**Issue by CodeMonkeyLuffy** [swoft-cloud/swoft#258]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | 最新
| Swoole version      |2.2.0
| PHP version         | 7.1.12
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> redis方法 建议跟随redis版本走,不需要框架定义直接传值调用原生的方法

**Comment by stelin** [comment]
问题已经了解，我们会尽快调整，感谢支持 swoft!

**Comment by stelin** [comment]
@CodeMonkeyLuffy 2.0 已经正式发布， 建议升级到2.0  2.0 已经支持原生redis 更稳定强大
