### ISSUE TITLE
[db]AR查询时数据表中的type字段被忽略

### ISSUE THREAD

**Issue by 769835303** [swoft-cloud/swoft#260]
AR查询时，数据表中的type字段被忽略，但插入和更新都正常，如下：
代码：
![qq 20180530114917](https://user-images.githubusercontent.com/12715467/40698059-d0f0bc3e-63ff-11e8-80e5-ee8b0aa0c757.png)
查询结果：
![qq 20180530114948](https://user-images.githubusercontent.com/12715467/40698068-daceef0a-63ff-11e8-9651-99f86e854685.png)
SQL语句：
![qq 20180530115003](https://user-images.githubusercontent.com/12715467/40698074-e4ce6c06-63ff-11e8-8853-5b35ff091aa8.png)

**Comment by wujunze** [comment]
```php  
        $data = User::findById(1, ['fields' => ['id', 'type']]);
        var_dump(get_last_sql());
        return $data->getResult();
```

![image](https://user-images.githubusercontent.com/12997869/40953342-ea8c2118-68b1-11e8-9d41-f509f35e072f.png)
![image](https://user-images.githubusercontent.com/12997869/40953368-05a6d092-68b2-11e8-9c0c-60eb6d43f937.png)

可以查询到type字段 @769835303

**Comment by stelin** [comment]
贴下你的实体代码和表结构
