### ISSUE TITLE
[db]记录日志时期望能记录完整的SQL语句

### ISSUE THREAD

**Issue by zhangxuanru** [swoft-cloud/swoft#268]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
   在日志记录SQL语句时， 现在日志中记录的是占位符， 像以下这条SQL：
![image](https://user-images.githubusercontent.com/11569114/41022753-195459a2-699d-11e8-9c10-b333f35c6db1.png)

这样的SQL在排查日志时，不太好排查问题， 希望能记录完整的SQL语句。

                                                                        非常感谢！！！

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
这个优化，我们会尽快加上！感谢支持swoft!

**Comment by stelin** [comment]
@zhangxuanru 建议升级到2.0 2.0 已经正式发布，数据库高度兼容laravel
