### ISSUE TITLE
协程客户端抛出的异常无法被捕获

### ISSUE THREAD

**Issue by EdenChan** [swoft-cloud/swoft#269]
以 MySql 为例，向数据库执行 **任意一条语法有问题的 sql** 都会导致 \Swoft\Db\Driver\Mysql\MysqlConnection::receive 方法抛出异常

```php
    public function receive()
    {
        $result = $this->connection->recv();
        if ($result === false) {
            throw new MysqlException('Mysql recv error，connectError=' . $this->connection->connect_error . ' error=' . $this->connection->error);
        }
        $this->connection->setDefer(false);

        $this->recv   = true;
        $this->result = $result;

        return $result;
    }
```

此时抛出的异常会走到事件监听器 \Swoft\Event\Listeners\ResourceReleaseListener 中，这里面的 handle 方法是没有进行 try catch 处理的，导致当前 worker 进程直接退出

```
[2018-06-06 16:41:05 *200.0]    ERROR   zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Exception: connection recv error in /var/www/swoft/vendor/swoft/framework/src/Event/Listeners/ResourceReleaseListener.php:48
Stack trace:
#0 /var/www/swoft/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Event\Listeners\ResourceReleaseListener->handle(Object(Swoft\Event\Event))
#1 /var/www/swoft/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Event\Listeners\ResourceReleaseListener), 'handle', Array)

[2018-06-06 16:41:05 $195.0]    WARNING swManager_check_exit_status: worker#0 abnormal exit, status=255, signal=0
```

这样应该会产生比较严重的问题，现在疑问是在这些协程客户端中抛出异常是正确的做法吗？
问题参考：https://github.com/swoole/swoole-src/issues/1598

稍微看了下 SwooleDistributed 框架，它在协程客户端中貌似是通过 return Exception 的方式去处理异常，而不是直接 throw 的。

有尝试过在 \Swoft\Db\Driver\Mysql\MysqlConnection::receive 方法中返回异常，这样在 \Swoft\Core\AbstractResult::recv 方法中能拿到 return 的 Exception，进行另外的处理。

**Comment by huangzhhui** [comment]
首先异常只有抛出一种做法，没有return的做法，然后这个问题应该是 ResourceReleaseListener  在进行连接自动回收时没处理妥善导致的，但是收包动作应当存在于业务代码中的，你的业务代码是怎样的呢？

**Comment by EdenChan** [comment]
@huangzhhui 现在我的测试代码就是 Db::query("selectttttt * from table"); 

往 query 方法传了一条错误的sql，没有做收包之类的动作，文档里似乎也没有提到需要自行收包？

这样执行之后 worker 直接退出了，我自己定义的 ExceptionHandler 也没有拿到 query 里面报出来的异常。

**Comment by stelin** [comment]
@EdenChan 问题已经了解到了，我们修复下。

**Comment by EdenChan** [comment]
@stelin @huangzhhui  请问下这个问题有计划什么时候可以修复吗？

使用 http client 的 co 协程客户端的时候也出现了类似的问题，当请求执行超过了 client 的超时时间的时候，并没有捕获到异常，而是直接返回了空结果，这样处理起来比较麻烦了。

**Comment by huangzhhui** [comment]
https://github.com/swoft-cloud/swoft-db/releases/tag/v1.1.21
