### ISSUE TITLE
memory  命名空间找不到

### ISSUE THREAD

**Issue by yanwuguangjun** [swoft-cloud/swoft#272]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | 1.0.0
| Swoole version      | 2.2.0 (by `php --ri swoole`)
| PHP version         | 7.2 (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
信息能完整的吗? 咋用的 报了啥错

**Comment by stelin** [comment]
有具体信息么
