### ISSUE TITLE
在前置进程中无法循环创建一个子进程的多个实例

### ISSUE THREAD

**Issue by aprchen** [swoft-cloud/swoft#274]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
 public function createProcess(string $name,int $num =4){
        for ($i = 0;$i<$num;$i++){
            ProcessBuilder::create($name)->start();
        }
    }
```

> Provide minimal script to reproduce the issue

```php
PHP Warning:  Swoole\Process::start(): process has already been started. in /Volumes/Work/service/vendor/swoft/process/src/Process.php on line 36

```

**Comment by carolkey** [comment]
这个问题在swoft 1.0.0复现，php7.2.12 ，swoole4.2.9

```
/**
 * Custom process
 *
 * @Process(boot=true)
 */
class MyProcess implements ProcessInterface
{
    public function run(SwoftProcess $process)
    {
        $pname = App::$server->getPname();
        $processName = "$pname myProcess process";
        $process->name($processName);
        
        for ($i = 0; $i <2; $i++) {
            ProcessBuilder::create('customProcess')->start();
        }
    }

    public function check(): bool
    {
        return true;
    }
}
```

出现：

> PHP Warning:  Swoole\Process::start(): process has already been started. in /data/www/swoft/vendor/swoft/process/src/Process.php on line 36

**Comment by inhere** [comment]
自定义进程数量是在 注解上配置的 默认是 1 个

```text
@Process(name="customProcess", num=1, coroutine=true)
```

**Comment by carolkey** [comment]
注解 `num=1` 在非boot进程实际上并没有生效，仅仅在boot=true的时候生效

**Comment by inhere** [comment]
@carolkey 

```php
 public function createProcess(string $name,int $num =4){
 	for ($i = 0;$i<$num;$i++){
        ProcessBuilder::create($name)->start();
    }
 }       
```

发现这里有点问题 `$name` 不能一样。 

- 内部根据 `$name` 标注进程的。一样的就会报上面的错误。你可改下 `$name . $i` 看看

**Comment by lragon** [comment]
$name和注解的不一样也会报错

`Uncaught Swoft\Process\Exception\ProcessException: The xxx process is not exist`

所以其实不支持启动多个自定义进程？

**Comment by carolkey** [comment]
> $name和注解的不一样也会报错
> 
> `Uncaught Swoft\Process\Exception\ProcessException: The xxx process is not exist`
> 
> 所以其实不支持启动多个自定义进程？

是的，我看了代码，目前是不支持的，貌似swoole原生用法也是不支持的。已经不纠结这个问题了

**Comment by lragon** [comment]
我觉得还是swoft本身不支持，如果我把Process的代码拷贝一份，修改注解`name`，应该还是可以启动的

**Comment by carolkey** [comment]
> 我觉得还是swoft本身不支持，如果我把Process的代码拷贝一份，修改注解`name`，应该还是可以启动的

这个和swoole是一致的，swoole同一份前置进程也是只能跑一份，除非你复制一份前置进程的代码。所以swoft设计成这样其实是没毛病的

**Comment by inhere** [comment]
创建多个进程是没有支持完善的。有需要可以自己实现，现在swoole 有 process\pool 很方便了

**Comment by carolkey** [comment]
但是进程池好像不能当做前置进程， `$serv->addProcess()` 只能添加单个进程

**Comment by lragon** [comment]
可以通过在前置进程里启动多个子进程来实现

**Comment by lragon** [comment]
swoole不支持在server中创建`Process\Pool`，这条路行不通，看来只能自己用`Swoole\Process`实现，或者等swoft 2.0了

```
 PHP Fatal error:  Swoole\Process\Pool::__construct(): swoole_process_pool cannot use in server process. in /var/www/app/Boot/BootProcess.php on line 30
```
