### ISSUE TITLE
使用AR插入数据后，新记录ID没有保存到实体对象中

### ISSUE THREAD

**Issue by 769835303** [swoft-cloud/swoft#277]
使用AR方式插入数据成功后，并没有把最新记录的ID保存在实体对象中:
![qq 20180611121626](https://user-images.githubusercontent.com/12715467/41212548-6168c43a-6d71-11e8-9c00-2eaaddd7baac.png)

**Comment by huangzhhui** [comment]
Please upgrade the components below to latest version
https://github.com/swoft-cloud/swoft-framework/releases/tag/v1.0.20
https://github.com/swoft-cloud/swoft-db/releases/tag/v1.1.13
