### ISSUE TITLE
RPC EOF封包问题

### ISSUE THREAD

**Issue by songweihang** [swoft-cloud/swoft#283]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | 1.0.0
| Swoole version      | 2.1.3
| PHP version         | 7.1.18
| Runtime environment Docker.

>RPC 调用中有个配置参数 TCP_OPEN_EOF_CHECK 当这个配置成 true的时候，整个RPC封包将会有问题，因为缺少swoole的package_eof配置以及封包添加相对应的EOF，如果不配置EOF会不会因为单个数据包过大而无法接受完全数据导致解包失败？

>缺少对EOF的封装
![image](https://user-images.githubusercontent.com/4744532/41386657-211d83de-6fb5-11e8-8119-ac520a12e198.png)

>缺少package_eof的配置
![image](https://user-images.githubusercontent.com/4744532/41386669-36416fd2-6fb5-11e8-9370-e757387bbd48.png)

**Comment by inhere** [comment]
update on https://github.com/swoft-cloud/swoft/pull/286
