### ISSUE TITLE
建议服务发现可以支持获取本地IP地址

### ISSUE THREAD

**Issue by songweihang** [swoft-cloud/swoft#284]
建议服务发现可以支持根据服务器本地获取IP地址来减少部署运维难度比如说 
`return exec("ip -4 addr show eth0 | grep inet | awk '{print $2}' | cut -d / -f 1");`

**Comment by huangzhhui** [comment]
获取本地IP地址主要用于何处或何种场景？

**Comment by songweihang** [comment]
@huangzhhui 
> 获取本地IP地址主要用于何处或何种场景？

主要是 .env 配置问题，配置RPC  consul 的时候每次都要进行IP绑定这样导致每次部署一台服务器都要重新配置一个不同的.env , 这样不利于做快速伸缩扩容

**Comment by songweihang** [comment]
@huangzhhui 

![image](https://user-images.githubusercontent.com/4744532/41395013-bb9d2b48-6fde-11e8-8c75-c0f719919517.png)

一般来说Consul 连接的可能是本地consul client 并且就算链接 Consul Server 是固定的但是服务发现的检测地址也是需要动态配置
![image](https://user-images.githubusercontent.com/4744532/41395122-229c2a56-6fdf-11e8-8715-7d7a3eb60a88.png)

**Comment by songweihang** [comment]
@huangzhhui 
非常感谢！ 已经解决了，确实也不需要必须配置根据本地地址，可以全部设置成127.0.0.1
只需要每一个微服务里面安装一个 consul client， 然后地址由于 consul client 去自动绑定。
