### ISSUE TITLE
auth   无法 使用composer  下载

### ISSUE THREAD

**Issue by yanwuguangjun** [swoft-cloud/swoft#288]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | 1.0
| Swoole version      | 2.2
| PHP version         | 7.2
| Runtime environment | Win10

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by wujunze** [comment]
composer 包已经发布 https://packagist.org/packages/swoft/auth    欢迎使用 @yanwuguangjun
