### ISSUE TITLE
希望 RPC长链接可以支持多数据中心配置

### ISSUE THREAD

**Issue by songweihang** [swoft-cloud/swoft#289]
![image](https://user-images.githubusercontent.com/4744532/41494514-735dd9d6-7146-11e8-9695-5b6047dced8b.png)
因为有些RPC接口可能在另外一个数据中心中，希望swoft配置长链接的时候指定Consul的数据中心

**Comment by stelin** [comment]
@songweihang 2.0正式发布，可以升级到2.0
