### ISSUE TITLE
单独启动rpc server,提示找不到ServiceDispatcher

### ISSUE THREAD

**Issue by highwayliu** [swoft-cloud/swoft#290]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0
| Swoole version      | 2.1.3
| PHP version         | 7.1
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.
CentOS
**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```
Stack trace:
#0 /usr/local/services/rpc/vendor/swoft/framework/src/Bean/BeanFactory.php(76): Swoft\Bean\Container->get('ServiceDispatch...')
#1 /usr/local/services/rpc/vendor/swoft/framework/src/Core/ApplicationContext.php(86): Swoft\Bean\BeanFactory::getBean('ServiceDispatch...')
#2 /usr/local/services/rpc/vendor/swoft/framework/src/App.php(124): Swoft\Core\ApplicationContext::getBean('ServiceDispatch...')
#3 /usr/local/services/rpc/vendor/swoft/rpc-server/src/Bootstrap/Listeners/RpcEventListener.php(36): Swoft\App::getBean('ServiceDispatch...')
#4 /usr/local/services/rpc/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Rpc\Server\Bootstrap\Listeners\RpcEventListener->onReceive(Object(Swoole\Server), 1, 4, '\x00\x0FBA-\x04dJ\x00\x00\x00\x01\x00\x00\x00...')
#5 /usr/local/services/rpc/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute in /usr/local/services/rpc/vendor/swoft/framework/src/Bean/Container.php on line 74
[18-Jun-2018 18:01:32 PRC] PHP Warning:  Swoole\Client::recv(): recv() failed. Error: Resource temporarily unavailable [11] in /data/www/yoyo/rpc/class/SimpleClient.class.php on line 78

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by huangzhhui** [comment]
无法重现，请重新克隆 swoft-cloud/swoft 项目并执行 composer update 后重试
