### ISSUE TITLE
rpc 端口修改不生效

### ISSUE THREAD

**Issue by CodeMonkeyLuffy** [swoft-cloud/swoft#292]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.5
| Swoole version      |2.2.0
| PHP version         | 7.2.1
| Runtime environment | Mac

**Details**
> TCP端口估计是写死了
![61421f65-c4e7-4d65-845e-19749889e5b0](https://user-images.githubusercontent.com/4016890/41815525-7821a19a-77a0-11e8-9a53-a5fb11031f56.png)

**Comment by inhere** [comment]
不可能吧 你咋个改的

**Comment by CodeMonkeyLuffy** [comment]
env 里面改的 只能是8099正常的 试了很多次 换啥都不行

**Comment by wujunze** [comment]
Mac Docker下测试修改TCP端口正常

swoft服务 
![image](https://user-images.githubusercontent.com/12997869/41820480-0bd530aa-7805-11e8-98e2-a93a86ef3d23.png)

测试curl 请求:
![image](https://user-images.githubusercontent.com/12997869/41820484-20dba6e6-7805-11e8-8997-a0c6fa6950e7.png)


.env配置:

![image](https://user-images.githubusercontent.com/12997869/41820487-33958d56-7805-11e8-81d4-918e110d8bc6.png)


请告知你的开发环境  和 swoft版本   配置文件   检查一下配置文件的有没有问题  Thanks   @CodeMonkeyLuffy

**Comment by huangzhhui** [comment]
实测修改项目根目录的 `.env` 文件内的 `TCP_PORT` 为 8098 成功
![image](https://user-images.githubusercontent.com/12077148/43444837-5bff506c-94d7-11e8-8367-c96fd0c28541.png)

![image](https://user-images.githubusercontent.com/12077148/43444826-5653acee-94d7-11e8-9871-ba1724042d38.png)
