### ISSUE TITLE
Listener 事件管理如同鸡肋 只是通知过程  却获取不到事件对应的名称和结果

### ISSUE THREAD

**Issue by CodeMonkeyLuffy** [swoft-cloud/swoft#293]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.5
| Swoole version      | 2.2.0
| PHP version         | 7.2.1
| Runtime environment | Mac

**Details**

>监听器  返回结果获取不到，任务名称获取不到，任务参数的参数获取不到，这个事情监听器可以做什么？

```php
<?php
/**
 * This file is part of Swoft.
 *
 * @link https://swoft.org
 * @document https://doc.swoft.org
 * @contact group@swoft.org
 * @license https://github.com/swoft-cloud/swoft/blob/master/LICENSE
 */

namespace App\Listener;

use Swoft\Bean\Annotation\Listener;
use Swoft\Event\EventHandlerInterface;
use Swoft\Event\EventInterface;
use Swoft\Task\Event\TaskEvent;
/**
 * 任务处理之后 监听处理器
 *
 * @Listener(TaskEvent::AFTER_TASK)
 */
class AfterTask implements EventHandlerInterface
{
    /**
     * @param \Swoft\Event\EventInterface $event
     */
    public function handle(EventInterface $event)
    {
        var_dump($event->getName());
        var_dump($event->getParams());
        var_dump($event->getTarget());
        var_dump($event);
        //任务返回结果获取不到，任务名称获取不到，任务参数的参数获取不到，这个事情监听器可以做什么？
//        var_dump('任务处理之后', $event->getTarget());
    }
}
```

**Comment by louvxiao** [comment]
建议增加 onFinish 回调的 Event 对象增加 `$worker_id` 和 `$task_id`。

Swoole 本身的回调 `function onTask(swoole_server $serv, int $task_id, int $src_worker_id, mixed $data);` 是有的，这里没有让人感觉很奇怪。

另外就是，啥时候能支持在 `Swoole\Server->task()` 里增加 finish 回调？这样就不需要去 `TaskEvent::FINISH_TASK` 回调里对各种任务做分流处理了。
