### ISSUE TITLE
model fill 优化

### ISSUE THREAD

**Issue by hujinhuaP** [swoft-cloud/swoft#297]
/**
     * @param array $attributes
     *
     * $attributes = [
     *     'name' => $value
     * ]
     *
     * @return \Swoft\Db\Model
     */
    public function fill(array $attributes): self
    {
        foreach ($attributes as $name => $value) {
            $methodName = sprintf('set%s', ucfirst($name));
            if (method_exists($this, $methodName)) {
                $this->$methodName($value);
            }
        }

        return $this;
    }

ucfirst建议优化和生成实体类规则一致。字段很多下划线的

**Comment by limingxinleo** [comment]
这个其实没啥问题，Entity中的私有变量已经是驼峰命名了，所有只需要用ucfirst就可以了

**Comment by huangzhhui** [comment]
这里涉及到一个问题是fill方法是提供以属性名传参还是字段名传参的问题，我觉得大家可以探讨一下

**Comment by hujinhuaP** [comment]
如果全传驼峰的进去肯定没问题得，如果传递原字段就有问题了！
输出是驼峰，防君子不防小人吧

**Comment by limingxinleo** [comment]
@hujinhuaP 这里我越来越觉得，fill应该也是小写比较好。。

驼峰命名只让他活在toArray()里吧。

**Comment by huangzhhui** [comment]
@limingxinleo 如果驼峰只活在`toArray()`里面的话，那接收参数的时候也会有问题，前端获取的数据模型不一致，应当从参数接收，Entity设置，返回结果整个流程使用的都是一致的
