### ISSUE TITLE
rpc service出现数据库异常不会返回给客户端 $server->send($fd,$data);不会执行到

### ISSUE THREAD

**Issue by 12black** [swoft-cloud/swoft#298]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | 1.0.0
| Swoole version      | 4.0.0 (by `php --ri swoole`)
| PHP version         | 7.1.14 (by `php -v`)
| Runtime environment | centos7

**Details**
> rpc service出现数据库异常不会返回给客户端 $server->send($fd,$data);不会执行到
![b86cu3g1a21txdn s5yiw9](https://user-images.githubusercontent.com/8529526/42120723-bd0e99b4-7c52-11e8-9f4d-48ed307fb996.png)
![k de f aa mlb3a5ghl w2](https://user-images.githubusercontent.com/8529526/42120744-fb11a21a-7c52-11e8-9f8d-46d19dba8a4a.jpg)
![zf 5rb5 6 _ bso7jfcfgy](https://user-images.githubusercontent.com/8529526/42120718-ad916674-7c52-11e8-8eda-45e8da3da54c.png)
![5t nh xkccu d fi l so](https://user-images.githubusercontent.com/8529526/42120719-b07d6fae-7c52-11e8-86eb-beb17c448852.png)

**Comment by limingxinleo** [comment]
$data 后面跟上\r\n 试试

**Comment by stelin** [comment]
@12black 升级到2.0， 2.0已经从底层解决了就很多1.0问题
