### ISSUE TITLE
session自动丢失

### ISSUE THREAD

**Issue by hujinhuaP** [swoft-cloud/swoft#299]
存储到session的数据，会自动丢失，多个异步请求得时候会丢失，如果全部为同步请求就不会丢失

**Comment by huangzhhui** [comment]
请提供请求方法，并注意请求是否提供了SessionId

**Comment by hujinhuaP** [comment]
![image](https://user-images.githubusercontent.com/20160039/42122999-042bcc16-7c7d-11e8-8dd0-756aa73ea318.png)
请求提供的sessionid
![image](https://user-images.githubusercontent.com/20160039/42123000-13b1aed0-7c7d-11e8-8c7f-ebe021a61505.png)
redis该session存储的数据

![image](https://user-images.githubusercontent.com/20160039/42123008-4afe3854-7c7d-11e8-9427-cd4175196a55.png)
调用中间件

![image](https://user-images.githubusercontent.com/20160039/42123018-597c24c2-7c7d-11e8-8d9c-6f134bd3b79e.png)
中间件代码

其它就没有地方调用session了，就剩下登录和注销调用了session了


如果页面加载时触发多个请求，使用默认异步的方式，就会把session给清掉，如果页面加载时多个请求采用sync同步的方式，就不会清掉session了

环境配置：nginx+swoft的dockerfile + mysql +redis
使用虚拟机里面的docker

**Comment by huangzhhui** [comment]
请注意如果使用fetch作为异步请求时是默认不带cookies的

**Comment by hujinhuaP** [comment]
前端要手工传递？异步请求是这样子的
![image](https://user-images.githubusercontent.com/20160039/42141300-e6510440-7dda-11e8-8d98-162ca04c68fb.png)
![image](https://user-images.githubusercontent.com/20160039/42141302-e878b09c-7dda-11e8-93c5-4d5996998228.png)
![image](https://user-images.githubusercontent.com/20160039/42141313-f749e8f2-7dda-11e8-964b-08de363c8366.png)

**Comment by huangzhhui** [comment]
axios默认是不会带上cookies的，axios.defaults.withCredentials = true 开启
