### ISSUE TITLE
能否统一命令行和Debug日志的日志输出格式

### ISSUE THREAD

**Issue by guoyahao** [swoft-cloud/swoft#305]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 最新
| Swoole version      | 4.0.0 (by `php --ri swoole`)
| PHP version         | 7.1 (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.
Centos7

**Details**
> Describe what you are trying to achieve and what goes wrong.

```php
命令行：    \output()->writeln(implode("\n", $lines));
writeln()
 // 输出文字
 echo $messages;
 if ($newline) {
     echo "\n";
  }

日志：addRecord（)  
    $record = array(
            'message' => (string) $message,
            'context' => $context,
            'level' => $level,
            'level_name' => $levelName,
            'channel' => $this->name,
            'datetime' => $ts,
            'extra' => array(),
        );

```
consloe 的命令行输出的是 字符串，仅仅是echo。

APP::debug 输出的是格式化数组之后的字符串。(包含很多的信息记录)

能否统一一下

**Comment by louvxiao** [comment]
楼上的大佬都干了些啥……差点笑出声// 哈哈哈哈哈哈

**Comment by stelin** [comment]
@guoyahao 2.0 已经发布，可以升级到2.0， 2.0 日志更为规范、更稳定和简单
