### ISSUE TITLE
建议优化两个地方。

### ISSUE THREAD

**Issue by 233cy** [swoft-cloud/swoft#317]
1、中间件中无法去掉内置的header头，建议优化一下
![default](https://user-images.githubusercontent.com/29916783/42790449-a036d1a0-899d-11e8-984d-580b20e49b6b.png)
2、cache缓存中，redis的keys获取所有键带前缀，导致没有办法直接取到用于get，delete等操作（好像get，delete这些方法都是处理过的，自带前缀的），希望swoft重载一个获取所有key的方法，不带前缀，或者可以通过参数指明，这样方便操作，不然开发人员还得自行做一次处理好像没必要
![default](https://user-images.githubusercontent.com/29916783/42790479-e3a0c216-899d-11e8-8a46-47bfce69e8c4.png)

**Comment by stelin** [comment]
@233cy 2.0 已经发布，建议升级。更简单稳定，底层全协程化
