### ISSUE TITLE
rcp服务端抛错优化

### ISSUE THREAD

**Issue by yunxi177** [swoft-cloud/swoft#318]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
```php
namespace App\Exception;

class OrderException extends BaseRpcException
{
    public $code = 400;

    public  $errCode=10020;

    public $message = "订单错误";

}
```
我服务端用自己写的OrderException抛错,到了 ServiceDispatcher->dispatch 经过下面代码被统一格式化
```php
 $message = sprintf('%s %s %s', $t->getMessage(), $t->getFile(), $t->getLine());
 $data = ResponseHelper::formatData('', $message, $t->getCode());
 $data = service_packer()->pack($data);
```

这样一来我在rpc客户端捕获异常的时候就无法获取到封装的 errCode的信息

**Comment by allenbin** [comment]
我是重写了dispatch把已知的错误做友好处理，其他的都500，看看是否可行

**Comment by herojhc** [comment]
支持修改...

**Comment by stelin** [comment]
@yunxi177 2.0 已经发布，建议升级。更简单稳定，底层全协程化，2.0 rpc 更为规范和简单。
