### ISSUE TITLE
rpc-client插件缺少EOF封装导致TCP粘包异常

### ISSUE THREAD

**Issue by songweihang** [swoft-cloud/swoft#326]
![image](https://user-images.githubusercontent.com/4744532/43362657-93738164-9322-11e8-840c-dfe150167d09.png)

如果单个包过大导致数据被截断，然后出现数据异常

**Comment by huangzhhui** [comment]
ref https://github.com/swoft-cloud/swoft-component/pull/152

**Comment by huangzhhui** [comment]
https://github.com/swoft-cloud/swoft-rpc-client/releases/tag/v1.0.5
