### ISSUE TITLE
rpc:reload不会自动更新app\Service的改动

### ISSUE THREAD

**Issue by highwayliu** [swoft-cloud/swoft#327]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0.1
| Swoole version      | 2.1.3
| PHP version         | 7.1.1
| Runtime environment | centos 

**Details**

> Describe what you are trying to achieve and what goes wrong.
rpc:reload不会自动更新app\Service的改动
rpc:restart则会更新改动

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by sakuraovq** [comment]
@highwayliu  2.0已经正式发布，建议升级到2.0
