### ISSUE TITLE
不能切换数据库

### ISSUE THREAD

**Issue by webphplove** [swoft-cloud/swoft#331]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | v1.0.21
| Swoole version      | 4.0.0 
| PHP version         | php7.20
| Runtime environment | deepin
| Swoft-db       | v1.1.18

> 使用selectInstance不能切换数据库

```
$result = Query::table('sms_recv')->selectInstance('spcard')->get()->getResult();
```
错误返回的是
```
{
    "msg": "the pool of spcard.master is not exist!",
    "file": "/media/project/swoft/vendor/swoft/framework/src/App.php",
    "line": 197,
    "code": 0
}
```
我在.env已经配置了spcard的链接

**Comment by huangzhhui** [comment]
如Pool配置配置正确后仍旧重现再开启此issue，先关掉了
