### ISSUE TITLE
中间件修改request, RequestContext 中需要手动修改

### ISSUE THREAD

**Issue by zcmzc** [swoft-cloud/swoft#332]
建议保持相同
HandlerAdapter->doHandler 里

        // execute handler
        $params   = $this->bindParams($request, $handler, $matches);
        $response = PhpHelper::call($handler, $params);

改为

        // execute handler
        $params   = $this->bindParams($request, $handler, $matches);
        \Swoft\Core\RequestContext::setRequest($request);
        $response = PhpHelper::call($handler, $params);

**Comment by huangzhhui** [comment]
根据PSR7标准应该保持Request和Response的不可变性，这样改的理由是什么？

**Comment by zcmzc** [comment]
比如我做的加解密 , 中间件解密后修改Request 传递给后续中间件, 在控制器中的话发现获取的又是没解密前的Request了 , 需要手动修改上下文中的Request
既然能修改 , 并当做参数传递给后续中间件 , 觉得不如默认修改上下文中的Request 了
只是个人这样以为的

**Comment by huangzhhui** [comment]
在控制器中的话发现获取的又是没解密前的Request

为什么会是没解密前的Request？

**Comment by inhere** [comment]
@zcmzc 应该是想保证在 action或者其他方法里，能拿到最新的 req

**Comment by zcmzc** [comment]
```php
    public function test(Request $request)
    {
        // 注入的$request 是解密后的
       // request() 是解密前的
    }
```
就是没修改RequestContext 上下文里的Request 啦

**Comment by huangzhhui** [comment]
按设计是 RequestContext 是请求的原始 Request 对象，后续的更改都是依赖中间件的机制来传递的

**Comment by zcmzc** [comment]
好的明白了 , 那就参数注入的形式获取
