### ISSUE TITLE
.env配置信息没有覆盖默认配置信息/bug

### ISSUE THREAD

**Issue by touch888** [swoft-cloud/swoft#336]
swoft: 1.0.0, php: 7.2.6, swoole: 4.0.3
.env文件配置信息没有覆盖swoft的默认配置信息,.env文件可写可读,和PHP脚本用户组一致
只有数据库信息没覆盖

**Comment by huangzhhui** [comment]
请提供更细致的信息

**Comment by touch888** [comment]
config/properties/db.php 里的默认数据库配置信息不会被.env的数据库配置信息覆盖

**Comment by huangzhhui** [comment]
无法还原你说的情况，请具体说明

**Comment by huangzhhui** [comment]
没反，env优先级是最高的，你先把你的问题描述清楚吧……

**Comment by touch888** [comment]
我想我描述的很清楚了数据库配置必须得在config/properties/db.php这里改,在env文件里改不生效,这样够清楚了吧截图是env数据库配置项
![image](https://user-images.githubusercontent.com/20635217/43874594-3812c26c-9bbf-11e8-9488-c5b09dc12bc5.png)
问过别人了上个小版本没问题就这个最新的1.0.0有问题

**Comment by huangzhhui** [comment]
请执行 `composer update` 确保你的所有组件为最新版后再测试此问题 ，如问题依旧，最好提供一个可以复现的 Demo

**Comment by touch888** [comment]
[swoft.zip](https://github.com/swoft-cloud/swoft/files/2273020/swoft.zip)
这是demo表结构你们自己随意好了

**Comment by beatwade** [comment]
遇到相同的情况
![image](https://user-images.githubusercontent.com/6858148/43890820-5fcacaf8-9bfa-11e8-975c-2b380caa5572.png)
env　配置dbSlave
![image](https://user-images.githubusercontent.com/6858148/43890855-71ab8fc8-9bfa-11e8-8504-4bea32757738.png)
devtool 信息
![image](https://user-images.githubusercontent.com/6858148/43890893-8a5d68fc-9bfa-11e8-8d8f-1f89ddb30bba.png)

**Comment by touch888** [comment]
@limingxinleo 你这是db.php里的配置信息,不是env里的配置信息,看清楚了,这是不正常的,你们文档上写明env的优先级高于db.php现在正好相反

**Comment by limingxinleo** [comment]
@touch888 
![image](https://user-images.githubusercontent.com/16648551/43934076-fcbd8398-9c7f-11e8-89f9-e42e15daa629.png)
![image](https://user-images.githubusercontent.com/16648551/43934093-1903a14a-9c80-11e8-9cf8-7ec6b7e3233c.png)

你在仔细看看，各项参数都是env优先，为什么只有URI用的是db.php的！！！

**Comment by limingxinleo** [comment]
@touch888 看明白了，就把issue关掉吧。。。

**Comment by limingxinleo** [comment]
@beatwade 你的问题就有趣了。。。我现在严重怀疑，你看的是.env.example里的，而不是.env里的 😄

**Comment by touch888** [comment]
![image](https://user-images.githubusercontent.com/20635217/43935789-256499d2-9c88-11e8-9f75-df445c7f6437.png)
@ @limingxinleo

**Comment by beatwade** [comment]
@limingxinleo  由于是才使用swoft 框架，再次检查了下
![image](https://user-images.githubusercontent.com/6858148/43938566-dfe50aa4-9c96-11e8-8476-7e7f0152b5b4.png)
的确是这样的,
原因是写一些测试demo熟悉框架发现不能联通数据库
![image](https://user-images.githubusercontent.com/6858148/43938593-08ef1da4-9c97-11e8-8069-a3739d5aab3a.png)
手动改config/properties/db.php
里slave项为env相同配置后可以联通。
我再想办法调试看下加载的生命周期吧，这里的确遇到问题了

**Comment by limingxinleo** [comment]
@touch888 还得非让人给你指出来。。。你.env里根本没有配置DB_SLAVE_URI

**Comment by limingxinleo** [comment]
@beatwade 你要不再看下。。。因为你上面给我的连接池信息，dbSlave的名字也不和你.env里配置的一样。。你是否一直没有重启服务？或者你把全部的.env贴出来，我在帮你检查检查，另外就是我看看你 swoft/db 的版本
![image](https://user-images.githubusercontent.com/16648551/43939764-9d77a692-9c9e-11e8-9009-3963c583ab58.png)

**Comment by touch888** [comment]
@limingxinleo 我的配置项完全是在.env.example默认项的基础上改的,这是默认配置文件就有问题

**Comment by beatwade** [comment]
@limingxinleo 
有点疑惑，这边是clone　repo　安装的在master 分支
![image](https://user-images.githubusercontent.com/6858148/43941350-57fa9216-9ca6-11e8-908f-885007a357bc.png)
发现安装完的swoft/db和你贴出来的不一样,版本v1.1.18
.env 全部内容
```
# Application
TIME_ZONE=Asia/Shanghai
LOG_ENABLE=false
APP_DEBUG=false

# Server
PFILE=/tmp/swoft.pid
PNAME=php-swoft
TCPABLE=true
CRONABLE=false
AUTO_RELOAD=true
AUTO_REGISTER=false

# HTTP
HTTP_HOST=0.0.0.0
HTTP_PORT=80
HTTP_MODE=SWOOLE_PROCESS
HTTP_TYPE=SWOOLE_SOCK_TCP

# WebSocket
WS_ENABLE_HTTP=true

# TCP
TCP_HOST=0.0.0.0
TCP_PORT=8099
TCP_MODE=SWOOLE_PROCESS
TCP_TYPE=SWOOLE_SOCK_TCP
TCP_PACKAGE_MAX_LENGTH=2048
TCP_OPEN_EOF_CHECK=false

# Crontab
CRONTAB_TASK_COUNT=1024
CRONTAB_TASK_QUEUE=2048

# Swoole Settings
WORKER_NUM=1
MAX_REQUEST=100000
DAEMONIZE=0
DISPATCH_MODE=2
TASK_IPC_MODE=1
MESSAGE_QUEUE_KEY=1879052289
TASK_TMPDIR=/tmp/
LOG_FILE=@runtime/logs/swoole.log
TASK_WORKER_NUM=1
PACKAGE_MAX_LENGTH=2048
OPEN_HTTP2_PROTOCOL=false
SSL_CERT_FILE=/path/to/ssl_cert_file
SSL_KEY_FILE=/path/to/ssl_key_file

# Database Master nodes
DB_NAME=dbMaster
DB_URI=mysql:3306/dbMaster?user=root&password=secret&charset=utf8,mysql:3306/dbMaster?user=root&password=secret&charset=utf8
DB_MIN_ACTIVE=5
DB_MAX_ACTIVE=10
DB_MAX_WAIT=20
DB_MAX_WAIT_TIME=3
DB_MAX_IDLE_TIME=60
DB_TIMEOUT=2

# Database Slave nodes
DB_SLAVE_NAME=dbSlave
DB_SLAVE_URI=mysql:3306/dbMaster?user=root&password=secret&charset=utf8,mysql:3306/dbMaster?user=root&password=secret&charset=utf8
DB_SLAVE_MIN_ACTIVE=5
DB_SLAVE_MAX_ACTIVE=10
DB_SLAVE_MAX_WAIT=20
DB_SLAVE_MAX_WAIT_TIME=3
DB_SLAVE_MAX_IDLE_TIME=60
DB_SLAVE_TIMEOUT=3

# Redis
REDIS_NAME=redis
REDIS_DB=2
REDIS_URI=127.0.0.1:6379,127.0.0.1:6379
REDIS_MIN_ACTIVE=5
REDIS_MAX_ACTIVE=10
REDIS_MAX_WAIT=20
REDIS_MAX_WAIT_TIME=3
REDIS_MAX_IDLE_TIME=60
REDIS_TIMEOUT=3
REDIS_SERIALIZE=1

# other redis node
REDIS_DEMO_REDIS_DB=6
REDIS_DEMO_REDIS_PREFIX=demo_redis_

# User service (demo service)
USER_POOL_NAME=user
USER_POOL_URI=127.0.0.1:8099,127.0.0.1:8099
USER_POOL_MIN_ACTIVE=5
USER_POOL_MAX_ACTIVE=10
USER_POOL_MAX_WAIT=20
USER_POOL_TIMEOUT=200
USER_POOL_MAX_WAIT_TIME=3
USER_POOL_MAX_IDLE_TIME=60
USER_POOL_USE_PROVIDER=false
USER_POOL_BALANCER=random
USER_POOL_PROVIDER=consul

# User service breaker (demo service)
USER_BREAKER_FAIL_COUNT = 3
USER_BREAKER_SUCCESS_COUNT = 6
USER_BREAKER_DELAY_TIME = 5000

# Consul
CONSUL_ADDRESS=http://127.0.0.1
CONSUL_PORT=8500
CONSUL_REGISTER_NAME=user
CONSUL_REGISTER_ETO=false
CONSUL_REGISTER_SERVICE_ADDRESS=127.0.0.1
CONSUL_REGISTER_SERVICE_PORT=8099
CONSUL_REGISTER_CHECK_NAME=user
CONSUL_REGISTER_CHECK_TCP=127.0.0.1:8099
CONSUL_REGISTER_CHECK_INTERVAL=10
CONSUL_REGISTER_CHECK_TIMEOUT=1
```

**Comment by beatwade** [comment]
@limingxinleo　原因找打了，感谢！   @touch888 也可以参考下看是否原因相同
1. swoft　composer repositories 使用的是
![image](https://user-images.githubusercontent.com/6858148/43942076-3b52617c-9ca9-11e8-9ca6-85aad94db02d.png)
2. 而中国镜像出现bug很久没跟新了
![image](https://user-images.githubusercontent.com/6858148/43942108-4f83ecce-9ca9-11e8-8ad0-78f33406b290.png)
3. 换了一个镜像(https://packagist.laravel-china.org/) ‘国区还是选择国内镜像’后可以顺利upgrade
![image](https://user-images.githubusercontent.com/6858148/43942132-628151d6-9ca9-11e8-9c45-5ddcf6f037ac.png)
4.正常工作了
![image](https://user-images.githubusercontent.com/6858148/43942253-cdc9ccfc-9ca9-11e8-9093-5d83d4722f4f.png)

**Comment by limingxinleo** [comment]
@beatwade 嗯到问题了就好，他的问题不是这个，他的问题是.env里没有配置DB_SLAVE_URI，他下面那个也是DB_URI

**Comment by limingxinleo** [comment]
@beatwade 嗯，找到问题了就好，他的问题不是这个，他的问题是.env里没有配置DB_SLAVE_URI，他下面那个也是DB_URI

**Comment by touch888** [comment]
我的错,已经发现问题了

**Comment by zhuwei913** [comment]
> @limingxinleo
> 有点疑惑，这边是clone　repo　安装的在master 分支
> ![image](https://user-images.githubusercontent.com/6858148/43941350-57fa9216-9ca6-11e8-908f-885007a357bc.png)
> 发现安装完的swoft/db和你贴出来的不一样,版本v1.1.18
> .env 全部内容
> 
> ```
> # Application
> TIME_ZONE=Asia/Shanghai
> LOG_ENABLE=false
> APP_DEBUG=false
> 
> # Server
> PFILE=/tmp/swoft.pid
> PNAME=php-swoft
> TCPABLE=true
> CRONABLE=false
> AUTO_RELOAD=true
> AUTO_REGISTER=false
> 
> # HTTP
> HTTP_HOST=0.0.0.0
> HTTP_PORT=80
> HTTP_MODE=SWOOLE_PROCESS
> HTTP_TYPE=SWOOLE_SOCK_TCP
> 
> # WebSocket
> WS_ENABLE_HTTP=true
> 
> # TCP
> TCP_HOST=0.0.0.0
> TCP_PORT=8099
> TCP_MODE=SWOOLE_PROCESS
> TCP_TYPE=SWOOLE_SOCK_TCP
> TCP_PACKAGE_MAX_LENGTH=2048
> TCP_OPEN_EOF_CHECK=false
> 
> # Crontab
> CRONTAB_TASK_COUNT=1024
> CRONTAB_TASK_QUEUE=2048
> 
> # Swoole Settings
> WORKER_NUM=1
> MAX_REQUEST=100000
> DAEMONIZE=0
> DISPATCH_MODE=2
> TASK_IPC_MODE=1
> MESSAGE_QUEUE_KEY=1879052289
> TASK_TMPDIR=/tmp/
> LOG_FILE=@runtime/logs/swoole.log
> TASK_WORKER_NUM=1
> PACKAGE_MAX_LENGTH=2048
> OPEN_HTTP2_PROTOCOL=false
> SSL_CERT_FILE=/path/to/ssl_cert_file
> SSL_KEY_FILE=/path/to/ssl_key_file
> 
> # Database Master nodes
> DB_NAME=dbMaster
> DB_URI=mysql:3306/dbMaster?user=root&password=secret&charset=utf8,mysql:3306/dbMaster?user=root&password=secret&charset=utf8
> DB_MIN_ACTIVE=5
> DB_MAX_ACTIVE=10
> DB_MAX_WAIT=20
> DB_MAX_WAIT_TIME=3
> DB_MAX_IDLE_TIME=60
> DB_TIMEOUT=2
> 
> # Database Slave nodes
> DB_SLAVE_NAME=dbSlave
> DB_SLAVE_URI=mysql:3306/dbMaster?user=root&password=secret&charset=utf8,mysql:3306/dbMaster?user=root&password=secret&charset=utf8
> DB_SLAVE_MIN_ACTIVE=5
> DB_SLAVE_MAX_ACTIVE=10
> DB_SLAVE_MAX_WAIT=20
> DB_SLAVE_MAX_WAIT_TIME=3
> DB_SLAVE_MAX_IDLE_TIME=60
> DB_SLAVE_TIMEOUT=3
> 
> # Redis
> REDIS_NAME=redis
> REDIS_DB=2
> REDIS_URI=127.0.0.1:6379,127.0.0.1:6379
> REDIS_MIN_ACTIVE=5
> REDIS_MAX_ACTIVE=10
> REDIS_MAX_WAIT=20
> REDIS_MAX_WAIT_TIME=3
> REDIS_MAX_IDLE_TIME=60
> REDIS_TIMEOUT=3
> REDIS_SERIALIZE=1
> 
> # other redis node
> REDIS_DEMO_REDIS_DB=6
> REDIS_DEMO_REDIS_PREFIX=demo_redis_
> 
> # User service (demo service)
> USER_POOL_NAME=user
> USER_POOL_URI=127.0.0.1:8099,127.0.0.1:8099
> USER_POOL_MIN_ACTIVE=5
> USER_POOL_MAX_ACTIVE=10
> USER_POOL_MAX_WAIT=20
> USER_POOL_TIMEOUT=200
> USER_POOL_MAX_WAIT_TIME=3
> USER_POOL_MAX_IDLE_TIME=60
> USER_POOL_USE_PROVIDER=false
> USER_POOL_BALANCER=random
> USER_POOL_PROVIDER=consul
> 
> # User service breaker (demo service)
> USER_BREAKER_FAIL_COUNT = 3
> USER_BREAKER_SUCCESS_COUNT = 6
> USER_BREAKER_DELAY_TIME = 5000
> 
> # Consul
> CONSUL_ADDRESS=http://127.0.0.1
> CONSUL_PORT=8500
> CONSUL_REGISTER_NAME=user
> CONSUL_REGISTER_ETO=false
> CONSUL_REGISTER_SERVICE_ADDRESS=127.0.0.1
> CONSUL_REGISTER_SERVICE_PORT=8099
> CONSUL_REGISTER_CHECK_NAME=user
> CONSUL_REGISTER_CHECK_TCP=127.0.0.1:8099
> CONSUL_REGISTER_CHECK_INTERVAL=10
> CONSUL_REGISTER_CHECK_TIMEOUT=1
> ```

为啥我按照你的设置 .env 无效呢？
默认HTTP端口还是启动的18306
