### ISSUE TITLE
Request->json() 调用报错

### ISSUE THREAD

**Issue by ITdashu** [swoft-cloud/swoft#339]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.6-beta
| Swoole version      | 4.0.3
| PHP version         | 7.2.8
| Runtime environment | debian

> PHP Warning:  stripos() expects parameter 1 to be string, array given in /home/www-data/Project/swoft/vendor/swoft/http-message/src/Server/Concerns/InteractsWithInput.php on line 140

json方法中 stripos 调用 InteractsWithInput->getHeader 返回的数据，此方法返回数组

**Comment by limingxinleo** [comment]
这个BUG早就修了吧

**Comment by limingxinleo** [comment]
你更新一下依赖，如果更新不到，可以更换一下composer源试试

**Comment by huangzhhui** [comment]
请更新你的 swoft/http-message 组件
https://github.com/swoft-cloud/swoft-http-message/releases/tag/v1.0.2
