### ISSUE TITLE
建议增加几层docker layer 来处理僵尸进程

### ISSUE THREAD

**Issue by beatwade** [swoft-cloud/swoft#341]
本地编排用的docker-compose version 3.3

发现每次ctrl+c 后不能自动回收swoft 进程，
建议在dockerfile中加入
```
# Add Tini
ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

ENTRYPOINT ["/tini", "--", "docker-php-entrypoint"]

CMD ["php", "-a"]
```
来辅助手动结束的进程，由于不是硬性的，就不建pull request 了

**Comment by huangzhhui** [comment]
感谢建议，我这边没能重现你说的情况，该issue可以作为同类问题的解决方案参考，官方的Dockerfile仅作为基础镜像和试用而存在，就不做调整了，或者对 https://github.com/swoft-cloud/swoft-docker 项目发起探讨
