### ISSUE TITLE
php bin/swoft start 启动Swoft时出错

### ISSUE THREAD

**Issue by feikoo** [swoft-cloud/swoft#342]
![image](https://user-images.githubusercontent.com/6971028/43947367-7a558d20-9cba-11e8-8962-65ee3fb20891.png)

PHP Warning:  require_once(/usr/share/nginx/html/swoft/vendor/autoload.php)
提示加载不到vendor/autoload.php文件，手动查看文件列表也找不到vendor文件夹和autoload.php文件。
why？？
注：swoft项目通过composer下载的1.0.7最新版本

**Comment by huangzhhui** [comment]
`composer install` ，仔细看文档，这个也太基础了点吧
