### ISSUE TITLE
建议在AR内 增加下 json 类型的数据操做

### ISSUE THREAD

**Issue by yanwuguangjun** [swoft-cloud/swoft#343]
建议在AR内 增加下 json 类型的数据操做 毕竟 都是MySQL8了嘛

**Comment by huangzhhui** [comment]
事实上非 MySQL 8 也有 json 类型的实现，具体可参考 Doctrine 的实现

**Comment by sakuraovq** [comment]
2.0已经正式发布，建议升级到2.0 @yanwuguangjun  和 lv 一样的使用方法哦
