### ISSUE TITLE
redis set return null

### ISSUE THREAD

**Issue by highwayliu** [swoft-cloud/swoft#346]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | 1.0.0
| Swoole version      | 4.0.3
| PHP version         | 7.1.1
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.
CentOs
**Details**
redis set return null
> Describe what you are trying to achieve and what goes wrong.
![image](https://user-images.githubusercontent.com/39515014/44186566-c933c600-a14c-11e8-880e-8f4af790e11e.png)

```php
// paste output here

Return value of Swoft\Redis\Redis::set() must be of the type boolean, null returned
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by huangzhhui** [comment]
@highwayliu 其它的Redis操作是否正常？

**Comment by huangzhhui** [comment]
@highwayliu 如果问题依旧，请重新开启此issue
