### ISSUE TITLE
服务长时间开启，restart时报Swoft bin/swoft stop fail，进程假死无法访问

### ISSUE THREAD

**Issue by jqhph** [swoft-cloud/swoft#347]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.7
| Swoole version      | 4.0.3
| PHP version         | 7.1
| Runtime environment | CentOS 7

**Details**

> 服务长时间开启，restart时报Swoft bin/swoft stop fail，进程假死服务无法访问

```php
[root@TB-WEB easysale-yxb]# php bin/swoft restart
Swoft bin/swoft is stopping ...
Swoft bin/swoft stop fail

[root@TB-WEB easysale-yxb]# ps aux|grep swoft
root      2707  0.0  0.4 607292 11996 ?        Ssl  09:59   0:00 php-swoft master process (bin/swoft)
root      2708  0.0  0.3 531312 11012 ?        S    09:59   0:00 php-swoft manager process
root      2721  0.2  0.7 541488 22464 ?        S    09:59   0:02 php-swoft reload process
root      2887  0.0  0.7 539404 22176 ?        S    10:05   0:00 php-swoft worker process
```

**Comment by huangzhhui** [comment]
请更新 swoft/framework 到最新版后再试

**Comment by jqhph** [comment]
剛剛重新更新了，什麼也沒有，現在是1.0.26版本。
下週再試試

**Comment by huangzhhui** [comment]
那就是最新版的了，能100%复现吗？

**Comment by jqhph** [comment]
明天试试就知道了，昨天拉代码的时候清除了文件夹，把日志也删掉了。明天测试如果问题重现会把日志也贴出来

**Comment by limingxinleo** [comment]
以前我也碰到过，不过最新版的framework几天来都正常。。

**Comment by jqhph** [comment]
先关了这个issue吧。我在想可能是因为开启了服务自动reload，而我拉代码的脚本更新代码时会先把所有文件先删除，再restart，可能是因为这个原因吧。今天我直接restart没有先删除文件，然后就正常了
