### ISSUE TITLE
不支持多个函数返回值类型的解析

### ISSUE THREAD

**Issue by adotpeng** [swoft-cloud/swoft#349]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.1.0
| Swoole version      | 3.0.0
| PHP version         | 7.2.5
| Runtime environment | CentOS 7

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
class ConfigDao {

    /**
     * @param string $name
     * @return null|string
     */
    public function getValueByName( string $name ): ?string {}
}
```

> Provide minimal script to reproduce the issue

```php
Return value of ConfigDao_5b7a96772d198::getValueByName() must be of the type string, null returned
```

**Comment by huangzhhui** [comment]
PHP7语法问题

**Comment by adotpeng** [comment]
我测试了下，`eval` 是支持解析 `?string` 这种返回值类型的，在 `swoft` 中就不行了。

**Comment by huangzhhui** [comment]
你的问题是什么？你描述清楚一点

**Comment by adotpeng** [comment]
`swoft` 没解析 `?string`
