### ISSUE TITLE
不能连接websocket: during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by tgl123** [swoft-cloud/swoft#350]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
1.按官方教程，通过docker 安装的swoft，并启动swoft
2.  js连接websocket，在一个html文件中

               // 创建一个Socket实例
            var socket = new WebSocket('ws://192.168.2.185/echo');

            // 打开Socket 
            socket.onopen = function (event) {
                console.log("starting ...........");
                // 发送一个初始化消息
                socket.send('I am the client and I\'m listening!');

                // 监听消息
                socket.onmessage = function (event) {
                    console.log('Client received a message', event);
                };

                // 监听Socket的关闭
                socket.onclose = function (event) {
                    console.log('Client notified socket has closed', event);
                };

                // 关闭Socket.... 
                //socket.close() 
            };

3. 出现错误
 websocket.html:18 WebSocket connection to 'ws://192.168.2.185/' failed: Error during WebSocket handshake: Unexpected response code: 200

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
默认是只启动了http server的。 你是怎么启动的

**Comment by inhere** [comment]
你要直接运行的话 要修改下dockerfile 最后的命令。 直接用 docker run 不方便挂载文件等使用，只能当做运行个测试容器

推荐使用docker compose 运行，你可以找下文档上 相关使用。

**Comment by tgl123** [comment]
（1）我修改了Dockerfile 自己  docker build生成的了一个新的镜像。官方Dockerfile中我只修改了最后一句为
CMD ["php", "/var/www/swoft/bin/swoft", "ws:start"]  然后，根本不起动不了。
（2）其中的Dockerfile中的  EXPOSE 80这个端口在分别在修改为9088和保持默认没有修改，均不能启动

**Comment by inhere** [comment]
CMD 命令必须启动一个前台程序 不能加 `-d`

**Comment by tgl123** [comment]
去掉了 -d 也不行呢

**Comment by inhere** [comment]
... 那你最好使用docker-compose 启动容器，然后进入容器里 调用swoft启动命令。方便调试

https://doc.swoft.org/master/zh-CN/quickstart/development.html

查看 - 推荐使用 docker 作为开发环境

**Comment by tgl123** [comment]
docker-compose 感觉也不行
（1）配置文件地址https://github.com/swoft-cloud/swoft/blob/master/docker-compose.yml
（2）docker-compse up 启动后报错：swoft_1  | Could not open input file: /var/www/swoft/bin/swoft

**Comment by inhere** [comment]
你先大概看下docker文档使用呀

```yaml
        ports: # 端口映射: 本地端口 -> 容器内端口
            - "80:80"
        volumes: # 文件挂载: 本地文件路径 -> 容器内文件路径
            - /usr/swoft:/var/www
```

注释都写了。。。

**Comment by tgl123** [comment]
上面这个我也试了，能启来，但是没有什么用 进去了  bin/swoft 命令都没有
所以我才又按github上的来

**Comment by huangzhhui** [comment]
Docker使用问题，请参考 https://segmentfault.com/a/1190000015759752
