### ISSUE TITLE
启动docker的swoft镜像后，在xshell中  Ctrl + C 不能退出

### ISSUE THREAD

**Issue by tgl123** [swoft-cloud/swoft#351]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
1.xshell 连接到linjux
2. docker run --name=swoft  -p 80:80 swoft/swoft
3. 显示成功启动的信息，提示按ctrl+c退出，使用后，没有效果，无法退出

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
通过docker容器运行是有一定的机会出现这样的情况。 ctrl+c 未成功时，可以使用 docker stop NAME 来结束
