### ISSUE TITLE
默认配置文件中.env.example ,REDIS_URI格式配置错误,缺少tcp://

### ISSUE THREAD

**Issue by tgl123** [swoft-cloud/swoft#355]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      |4.0.4
| PHP version         | 7.2.9
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
1.使用 cache()->set("name",'brifht')
2.系统日志报错：
Redis Connection format is incorrect uri=120.78.68.11:6379, eg:tcp://127.0.0.1:6379/1?auth=password

3.建议.env.example中的加上tcp://
REDIS_URI=tcp://127.0.0.1:6379,tcp://127.0.0.1:6379

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by huangzhhui** [comment]
@tgl123 无论是 \Redis 还是 \Swoole\Coroutine\Redis 均没有要求前面加上 tcp:// ，如仍然无法使用最好提供一个可复现的 Demo
