### ISSUE TITLE
在定时任务中全局函数cache()不能使用

### ISSUE THREAD

**Issue by tgl123** [swoft-cloud/swoft#356]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      | 4.0.4(by `php --ri swoole`)
| PHP version         | 7.2.9(by `php -v`)
| Runtime environment  CentOS 7

**Details**

代码是项目中的默认代码  app/Tasks/SyncTask.php  只是在定时任务中加了redis操作代码

1.我在websocket中使用cache()进行操作redis是正常的
2.在定时任务可以执行，且运行，但cache()操作无效，error.log中报错：
trace[TaskEventListener.php:45,Swoft\Task\Bootstrap\Listeners\TaskEventListener->onTask] TaskExecutor->run Class 'Redis' not found file=/var/www/swoft/vendor/swoft/redis/src/SyncRedisConnection.php line=64

3.定时任务代码如下：
    /**
     * crontab定时任务
     * 每一秒执行一次
     *
     * @Scheduled(cron="*\/5 * * * * *")
     */
    public function cronTask()
    {
        echo time() . "每一秒执行一次  \n";
        $time=cache()->rpop("name");
        //$cache = \Swoft\App::getBean(Redis::class);
        //$time=$cache->deferCall('rpop', ['name']);
        App::info("from task".$time."=====");
        //cache()->lpush("name",time());
        //echo "cache value is :". cache()->rpop("name");
        return 'cron';
    }

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by huangzhhui** [comment]
Task进程内所有协程客户端会退化为同步客户端，也就是会使用 `\Redis`，请确保 PHP 环境已正确安装 Redis 扩展
