### ISSUE TITLE
热更新, 原sokect连接会断开,必须重连

### ISSUE THREAD

**Issue by dearlin** [swoft-cloud/swoft#357]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 4.1.0-alpha
| PHP version         | 7.0.30
| Runtime environment | Ubuntu

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by huangzhhui** [comment]
@dearlin 请描述一个详细的场景

**Comment by dearlin** [comment]
@huangzhhui  开启 AUTO_RELOAD, 通过 php bin/swoft ws:start 启动websocket, 用客户端连接上, 在程序中随意改个代码(例如输入个回车), 脚本会自动reload, 此时客户端会掉线, 必须重连,  不能像GatewayWorker一样保持客户端不掉线

**Comment by inhere** [comment]
是会这样子。 后面可能会加上自动恢复，现在的话，暂时不会变动这个逻辑，需要你client自动重连下。

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
