### ISSUE TITLE
如何配置或者启用 wss

### ISSUE THREAD

**Issue by tgl123** [swoft-cloud/swoft#359]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
1.公司的官网是https的，在使用ws这个协议就会被阻止
2.在配置文件.env中有看到以下2个选项
SSL_CERT_FILE=/path/to/ssl_cert_file
SSL_KEY_FILE=/path/to/ssl_key_file

请问这2个项目的文件是怎么来的，是公司的官网申请的ssl相关证书吗？

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by huangzhhui** [comment]
是的

**Comment by tgl123** [comment]
公司官网用是apache作为web服务器，web服务器有三个证书配置项，页swoft中只有两个，我试着配置上去了，但是显示如下错误：
WebSocket connection to 'wss://www.xxx.com:8080/order' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR

（1）用的是阿里的免费证书三个证书分别为
214424817190294.pem   214424817190294.key     chain.pem

(2)我对.env中的配置项时行设置
SSL_CERT_FILE=/var/www/swoft/cert/214424817190294.pem
SSL_KEY_FILE=/var/www/swoft/cert/214424817190294.key

(3)我还注意到感觉还有加密的算法SSLCipherSuite，不知道有没有影响，apache中的配置项如下：
    SSLEngine On
    SSLCertificateFile /etc/letsencrypt/live/www.mhupro.com/214424817190294.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/www.mhupro.com/214424817190294.key
    SSLCertificateChainFile /etc/letsencrypt/live/www.mhupro.com/chain.pem
    SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH   
    SSLProtocol All -SSLv2 -SSLv3
    SSLHonorCipherOrder On
