### ISSUE TITLE
wss 启动报错：Fatal error: Swoole\Http\Server::start(): cannot use http2 protocol 

### ISSUE THREAD

**Issue by tgl123** [swoft-cloud/swoft#360]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 4.0.4 (by `php --ri swoole`)
| PHP version         | 7.2.9(by `php -v`)
| Runtime environment  CentOS 7.4

**Details**
1.  使用官方的Dockerfile文件 ，用docker 创建的镜像，默认启用httpserver的 ssl功能也是正常的，但是如果Dockerfile中的启动项成成  ws:start 启动镜像就会报错：

Fatal error: Swoole\Http\Server::start(): cannot use http2 protocol in websocket server in /var/www/swoft/vendor/swoft/websocket-server/src/WebSocketServer.php on line 89
> Describe what you are trying to achieve and what goes wrong.

2.我使用composer的方式安装，然后启用OPEN_HTTP2_PROTOCOL=true,设置好相关证书
php  bin/swoft ws:start   一样报上面的错误：
Fatal error: Swoole\Http\Server::start(): cannot use http2 protocol in websocket server in /var/www/swoft/vendor/swoft/websocket-server/src/WebSocketServer.php on line 89

如果php  bin/swoft  start 就是正常的，https的方式访问站点也正常

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
@tgl123 2.0已发布，建议升级到2.0
