### ISSUE TITLE
关于文档中docker-compose描述错误

### ISSUE THREAD

**Issue by lu8533783** [swoft-cloud/swoft#361]
文档地址：https://doc.swoft.org/master/zh-CN/quickstart/docker-installation.html
## docker-compose

> 运行之前需要先clone swoft项目代码到本机，再进入到swoft项目目录运行下面的命令

```bash
// 运行容器
docker-compose up -d swoft
```
## 由于clone的项目没有vendoer。导致启动失败。固文档描述有误

**Comment by inhere** [comment]
已调整

**Comment by lu8533783** [comment]
还是有问题，docker-compose.yml 中 command 改为bash ，应该是改变不了dockerfile中ENTRYPOINT 命令启动后还是执行了 php /var/www/swoft/bin/swoft start 报错。

**Comment by inhere** [comment]
😄 大概意思 这些事docker的基础知识了，我不能把情况都写完撒。。。
你发现doc问题，可以直接点右上角的编辑 修正 然后提交

**Comment by trowa8509** [comment]
> 还是有问题，docker-compose.yml 中 command 改为bash ，应该是改变不了dockerfile中ENTRYPOINT 命令启动后还是执行了 php /var/www/swoft/bin/swoft start 报错。

这个坑我昨天也遇到了，改变不了dockerfile中的ENTRYPOINT命令，那就修改 docker-compose.yml 的command 为 ENTRYPOINT，然后exec -it进容器，composer install安装完依赖之后退出docker-compose up就行了，文档确实有个坑，希望官方也修改下，昨天在这里卡了不少时间。
