### ISSUE TITLE
写在task里面的redis和controller里面的redis表现不一样，例如zrange/zrangebyscore

### ISSUE THREAD

**Issue by allovine** [swoft-cloud/swoft#365]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Swoft version       | 1.0.0
| Swoole version      | 4.0.3
| PHP version         | 7.1.20
| Runtime environment | Mac

**Details**
分别在task下面，和controller下面写一段redis的代码，结果输出是不一样的，在controller下面的redis类处理ZSET数据有问题，而且不能使用 zrangebyscore 的 withscores => true，会报warning，说是第四个参数不对
> Describe what you are trying to achieve and what goes wrong.
$this_redis = new \Swoft\Redis\Redis();
$this_redis->select(6);
var_dump($this_redis->zRange("round_start_queue",0,-1,true));
这段代码的输出，task里面执行为：
array(1) {
  ["a"]=>
  float(1)
}

如果在controller里面，输出为：
array(2) {
  [0]=>
  string(1) "a"
  [1]=>
  string(1) "1"
}

，并且在controller里面使用
$this_redis->zRangeByScore("round_start_queue",1,10,["withscores" => true]);
会提示：
PHP Warning:  Swoole\Coroutine\Redis::zRangeByScore() expects parameter 4 to be array, string given in ...../vendor/swoft/framework/src/Helper/PhpHelper.php on line 47

无论是在controller采用注入的方式引用redis，还是在函数里面new都一样

**Comment by allovine** [comment]
redis 组件更新后可以了。不过请老大能否告诉一下怎么才能安装最新的组件？
我不太会用composer、git之类的命令，我是下载了代码，然后覆盖了redis目录，好用了。

**Comment by limingxinleo** [comment]
新版本都改了，你把compoesr.json里的仓库改一下。。

https://packagist.laravel-china.org

然后composer update -o 就行了

**Comment by allovine** [comment]
compoesr.json要怎么修改呢？把版本号从 1.0 修改成 1.0.7 ？

**Comment by allovine** [comment]
git上面的compoesr.json里面都是1.0，也不知道最新的compoesr.json是个什么样子
