### ISSUE TITLE
v1.0.6 能用于生产环境吗？

### ISSUE THREAD

**Issue by louvxiao** [swoft-cloud/swoft#367]
现在 V1 正式版 只有百分之六十二的完成进度。最近两周要上线项目，担心的有两个问题：
1. 现在 1.0.6 版本还是 beta 版本，主要功能稳定了吗？附加功能不完善倒没什么关系，例如 DevTool；
2. 等正式版发布之后，会提供升级方法吗？现在发布的版本都没有完整的升级文档。

**Comment by huangzhhui** [comment]
可稳定用于生产环境，已经有很多大量应用生产环境的案例了
