### ISSUE TITLE
mysql密码配置出错的时候，返回错误显示容易让人误解

### ISSUE THREAD

**Issue by CodeMonkeyLuffy** [swoft-cloud/swoft#369]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.7
| Swoole version      | 2.2.0
| PHP version         | 7.1
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
```
数据库密码配置错误 但是swoft打印的信息容易让人误解  数据库ip不是配置的 第一反应谁让人觉得是数据库ip配置错了

SQLSTATE[HY000] [1045] Access denied for user 'ceshi'@'120.199.31.162' (using password: YES)

swoft 截取客户端请求IP

```
![image](https://user-images.githubusercontent.com/4016890/44978632-c551d180-af9d-11e8-8435-656743c7b353.png)

**Comment by huangzhhui** [comment]
这是标准的MySQL错误返回信息
