### ISSUE TITLE
文档缺少 @ServerListener 的阐述

### ISSUE THREAD

**Issue by huangzhhui** [swoft-cloud/swoft#370]
文档缺少对 @ServerListener 事件监听使用的阐述，以及使用的生命周期 
Ref: https://github.com/swoft-cloud/swoft/issues/368#issuecomment-418053077

**Comment by inhere** [comment]
fixed: https://doc.swoft.org/master/zh-CN/core/event-manager.html#swoft%20server%20%E4%BA%8B%E4%BB%B6
