### ISSUE TITLE
Swoole\Table::Set: unable to allocate memory

### ISSUE THREAD

**Issue by allovine** [swoft-cloud/swoft#371]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      | 4.0.3
| PHP version         | 7.1.2
| Runtime environment | CentOS 7

启用了 crontab 任务，在任务里每 1 秒执行一次，扫描redis队列，然后处理队列数据
在运行了一段时间（大概1晚上）之后，出现
PHP Warning:  Swoole\Table::set(): unable to allocate memory. in /var/www/games/putaoGames/vendor/swoft/task/src/Crontab/Crontab.php on line 245
的错误。

<img width="845" alt="set" src="https://user-images.githubusercontent.com/15407088/44994187-0a8ef700-afd0-11e8-84b5-9b478f27ee36.png">

不知道有没有什么思路，能提供下，以便怎么定位问题。
看之前的一个issue，从回答上，也没看出什么来。

谢谢

**Comment by huangzhhui** [comment]
Ref #371

**Comment by huangzhhui** [comment]
#371

**Comment by stelin** [comment]
@allovine 2.0已发布，建议升级到2.0
