### ISSUE TITLE
Swoole\\Table::set(): unable to allocate memory

### ISSUE THREAD

**Issue by tgl123** [swoft-cloud/swoft#372]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment Docker etc.

**Details**

1.项目中有做定时任务：利用websockert clients 10秒发送一次数据给websocket server

2.运行几天后，websocket连接正常连接，但就是收不到信息，日志中报很多如下错误：

{"log":"Warning: Swoole\\Table::set(): unable to allocate memory. in /var/www/swoft/vendor/swoft/task/src/Crontab/Crontab.php on line 245\n","stream":"stdout","time":"2018-09-03T23:12:00.848825852Z"}

3.定时任务代码：

    /**
     * crontab定时任务
     * 每10秒执行一次
     *
     * @Scheduled(cron="*\/10 * * * * *")
     */
    public function cronOrderTask() {
        $data = array('type' => 'to_all', 'info' => ''); //标志type为to_all表示群发
        $socket = new \Swoole\Client\WebSocket(env("HOST_NAME"), env("HTTP_PORT"), '/order');
        $keyFile = env('SSL_KEY_FILE');
        $certFile = env('SSL_CERT_FILE');
        if (env('OPEN_HTTP2_PROTOCOL')) {
            //如果是开启ssl，就时行加密传输
            $socket->enableCrypto($keyFile, $certFile);
        }
        $s = $socket->connect(5);
        if ($s) {
            $info=$this->get_info();//循环获取订单信息
            $data['info'] = $info;
            if (!empty($info)) {
                //有数据时才发送给websocket
                $socket->send(json_encode($data));
            }
        } else {
            App::info(__CLASS__ . '中的方法' . __FUNCTION__ . ": websocket 连接异常！");
        }
        App::info('===from task===');
        return 'cron';
    }

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by huangzhhui** [comment]
#371

**Comment by limingxinleo** [comment]
swoole 版本是多少

**Comment by tgl123** [comment]
swoole版本  4.04

**Comment by tgl123** [comment]
这个bug有计划何时解决呢，现在感觉都没发用在生产环境，不太稳定哦

**Comment by huangzhhui** [comment]
你可以先不使用计划任务，通过其它方案解决实现

**Comment by lion1120lion** [comment]
请问这个bug修复了？我的定时任务也出现“不能分配内存”问题

**Comment by jianwubayiba** [comment]
一堆
xxx@docker01 Warning: Swoole\Table::set(): unable to allocate memory. in /var/www/swoft/vendor/swoft/task/src/Crontab/Crontab.php on line 245
xxx@docker01
xxx@docker01 Warning: Swoole\Table::set(): unable to allocate memory. in /var/www/swoft/vendor/swoft/task/src/Crontab/Crontab.php on line 245

**Comment by zhana0** [comment]
我也遇到了，现在结局了吗？

**Comment by kyleliwotian** [comment]
我也遇见了，2677031999 qq

**Comment by inhere** [comment]
task 发了新版本 各位观察下还有问题吗？

**Comment by tgl123** [comment]
请问要怎么升级呢

**Comment by stelin** [comment]
@tgl123 2.0已发布，建议升级到2.0
