### ISSUE TITLE
Command 中无法使用 Reference 注入服务

### ISSUE THREAD

**Issue by zhwei** [swoft-cloud/swoft#373]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | v1.0.21
| Swoole version      | 4.0.3 (by `php --ri swoole`)
| PHP version         | 7.0.31 (by `php -v`)
| Runtime environment | Mac

**Details**

Command 中无法使用 `@Reference` 注入服务，添加 `\Swoft\Rpc\Client\Bean\Wrapper\Extend\CommandExtend` 后，仍会提示 `Bean App_Lib_DemoInterface_99f389e5535a70d1431bf84474c20723 not exist`

**Comment by huangzhhui** [comment]
Command 是启动生命周期的第一步，ServerStart 和 WorkerStart 是两个生命周期，服务属于 WorkerStart 生命周期，不能混用
