### ISSUE TITLE
如何自定义RpcEventListener类？

### ISSUE THREAD

**Issue by im050** [swoft-cloud/swoft#374]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | latest
| Swoole version      | latest
| PHP version         | 7.1.20
| Runtime environment | CentOS7

**Details**

> 如何用自己编写的RpcEventListener取代官方的swoft/rpc-server/src/Bootstrap/Listeners/RpcEventListener.php

> 在文档中没有找到相关说明

**Comment by huangzhhui** [comment]
暂时无法取代已存在的Listener，可直接fork组件改造后直接引入自己的组件

**Comment by inhere** [comment]
@im050  你用 SwooleListener 监听  SwooleEvent::ON_CONNECT 事件试过没
