### ISSUE TITLE
SoapClient如何调用SOWFT的RPC服务呢

### ISSUE THREAD

**Issue by QiiSyhx** [swoft-cloud/swoft#376]
| Q                   | A
| ------------------- | -----
| Bug report?         |no
| Feature request?    | no
| Swoft version       | master
| Swoole version      | 4.1.0
| PHP version         | 7.2
| Runtime environment Ubuntu16

使用swoole_client调用是没有问题的，但是这个和其他的rpc调用方式完全不一样，使用其他的rpc方式该如何使用呢？
$client = new \swoole_client(SWOOLE_SOCK_TCP);
if (! $client->connect('192.168.8.129', 8099, 0.5))
{
    echo "connect failed. Error: {$client->errCode}\n";
}
$client->send(json_encode([
    "interface" => "App\Lib\DemoInterface",
    "version" => "0",
    "method" => "getUser",
    "params" => [1],
])."\r\n");
$result = $client->recv();
$client->close();
var_dump($result);

**Comment by huangzhhui** [comment]
Swoft RPC 服务暂无 Soap Server 实现
