### ISSUE TITLE
添加新事件,trigger时报错

### ISSUE THREAD

**Issue by alukaa** [swoft-cloud/swoft#377]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      | 4.0.1
| PHP version         | 7.2.8
| Runtime environment | Docker

**Details**

> 添加事件定义如下:
```
 $show = new TestShow();
 App::getBean('eventManager')->attach('demo:showCase',[$show, 'test2'], 1);
 App::trigger('demo:showCase', null, [1,2,3,4]);

class TestShow
{ 
  public function test2(...$params)
    {
        var_dump($params);
        var_dump('test2');
        //App::error(__FUNCTION__);
    }
}
```

```php
{"msg":"Argument 2 passed to Swoft\\Helper\\PhpHelper::call() must be of the type array, object given, called in \/var\/www\/swoft-research\/vendor\/swoft\/framework\/src\/Event\/LazyListener.php on line 30","file":"\/var\/www\/swoft-research\/vendor\/swoft\/framework\/src\/Helper\/PhpHelper.php","line":40,"code":0}
```

> Provide minimal script to reproduce the issue

原因分析:
```
App::getBean('eventManager')->attach('demo:showCase',[$show, 'test2'], 1);
```
会调用```LazyListener```
![image](https://user-images.githubusercontent.com/8164389/45083197-b863e800-b12d-11e8-9e90-0d7c32477143.png),
但是LazyListener在调用handle方法时传递的参数是```EventInterface $event```,而```\Swoft\Helper\PhpHelper::call```接受的是```array```
这里应该接收```event$->getParams()```?

```php
// paste code
```

**Comment by alukaa** [comment]
@inhere 效率

**Comment by huangzhhui** [comment]
@alukaa 可以按PR内容改一下看看是否解决了你的问题并反馈一下

**Comment by inhere** [comment]
@alukaa 你参照PR修改试试看呢。

trigger时始终会传递 event 对象给用户处理的。 params 需自己从event对象中拿取

**Comment by alukaa** [comment]
![image](https://user-images.githubusercontent.com/8164389/45085395-2c54bf00-b133-11e8-80e6-7bd957ca847f.png)
![image](https://user-images.githubusercontent.com/8164389/45085414-38d91780-b133-11e8-8dea-ff5d2310c849.png)
按照PR进行修改得到了以下结果，可以得到event object

**Comment by inhere** [comment]
😄 行，感谢反馈  👍

**Comment by alukaa** [comment]
@inhere 效率真高，给个star,哈哈

**Comment by huangzhhui** [comment]
Released https://github.com/swoft-cloud/swoft-framework/releases/tag/v1.0.27
