### ISSUE TITLE
Class 'Swoole\Coroutine\Redis' not found 

### ISSUE THREAD

**Issue by QiiSyhx** [swoft-cloud/swoft#380]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | master
| Swoole version      | 4.1.0-beta.2
| PHP version         | 7.2
| Runtime environment | Ubuntu16.4

**Details**
使用rpc调用的时候，出现错误
Class 'Swoole\Coroutine\Redis' not found /home/xikk/vendor/swoft/redis/src/RedisConnection.php 94

请问这是什么原因？

**Comment by huangzhhui** [comment]
请确保安装了 Hiredis 和编译 Swoole 时附加了 `--enable-async-redis` 参数

**Comment by QiiSyhx** [comment]
已经安装hiredis并且编译时加入./configure --enable-async-redis，错误还是存在

**Comment by huangzhhui** [comment]
请输入  php --ri swoole 查看异步Redis是否成功安装

**Comment by QiiSyhx** [comment]
redis client => enabled
显示redis是可用的

**Comment by QiiSyhx** [comment]
这是完整的信息：
swoole

swoole support => enabled
Version => 4.1.2
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu affinity => enabled
spinlock => enabled
rwlock => enabled
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
redis client => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608
