### ISSUE TITLE
http表单验证

### ISSUE THREAD

**Issue by alukaa** [swoft-cloud/swoft#381]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 4.0.1
| PHP version         | 7.2.8
| Runtime environment | Docker

**Details**

> Describe what you are trying to achieve and what goes wrong.

![image](https://user-images.githubusercontent.com/8164389/45204610-58e31500-b2b2-11e8-9c63-a173b6c6668f.png)
```php
表单验证问题:
多字段的表单验证代码不能返回表单的全部字段错误，当莫一个字段验证失败过后，直接throw exception了，
能否实现当表单验证完全后一次性的返回全部错误?
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by huangzhhui** [comment]
一次性返回多个不符合参数验证本身的目的吧？从参数验证的角度来说，一旦有不通过我就应该直接断掉不再执行了，你要的是参数检查，是为了帮助用户检查参数都有哪些问题，不一样的吧

**Comment by alukaa** [comment]
参数验证和参数检查是同一回事吧，校验表单参数的合法性。
如果前端表单验证没做好，后台一个字段一个字段的验证返回用户体验不会很好吧我觉得。

**Comment by huangzhhui** [comment]
那你的需求是为Web表单提供参数检查，这你单独提供参数检查的接口和方法就好了，这是两个业务场景

**Comment by alukaa** [comment]
我忽然有点懵逼了，有点不知道你们实现这个功能的初衷是什么了

**Comment by huangzhhui** [comment]
从参数验证的角度来说，一旦有参数验证不通过就应该直接断掉不再执行了，绝大部分的参数验证器都是如此的

**Comment by alukaa** [comment]
个人看法:我觉得swoft的参数验证适合在数据插入数据库的时候进行验证。
如果验证form,symfony validator或许是个更好的选择
@huangzhhui 你觉得呢？

**Comment by huangzhhui** [comment]
参数验证同样适用于数据库字段验证，这是共用的

**Comment by alukaa** [comment]
好吧，我抉择一下
