### ISSUE TITLE
集成laravel框架Eloquent

### ISSUE THREAD

**Issue by wydhit** [swoft-cloud/swoft#382]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes

laravel框架Eloquent的作为ORM很强大，能否把Eloquent集成进来，底层可能需要修改下

**Comment by iyueshang** [comment]
支持

**Comment by wydhit** [comment]
集成到核心中应该是不妥的，可以单独形成组件，传统的orm在常驻内存及协成下有很多问题，解决协成问题然后封装成组件，应该是比较好的选择

**Comment by huangzhhui** [comment]
Eloquent 本身并没有作为一个单独的包发布，设计上跟 Laravel 耦合比较严重，并不能很好的剥离并享受后续的升级修复，官方暂不考虑此组件，有兴趣的小伙伴可以弄一下
