### ISSUE TITLE
db pool maxActive 问题

### ISSUE THREAD

**Issue by alukaa** [swoft-cloud/swoft#388]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      | 4.0.1
| PHP version         | 7.2.8
| Runtime environment | Docker

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
当数据库并发超过了我们设置的最大连接后，有没有其他更好的解决方式，求指教
```
![image](https://user-images.githubusercontent.com/8164389/45527049-5af62800-b80c-11e8-8c1c-28437a430198.png)

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by wujunze** [comment]
连接数调大一点?       根据业务压力分不同的数据库 不同的连接池?

**Comment by alukaa** [comment]
像这样的效果可否: 
当并发已经达到了设置的最大连接数，那么新来的请求排队等待，如果有连接使用完成释放出来，就给排队的请求使用。
只是一个想法，不知道怎么搞或者可不可以搞

**Comment by alukaa** [comment]
@wujunze 你说的这种就是类似拆分子系统嘛，子系统要是拆无可拆了呢，不好意思，我好想有点钻牛角尖

**Comment by huangzhhui** [comment]
@alukaa Channel 有你说的这样的等待机制的，`$channel->pop($timeout)`，`$timeout` 就是等待时长

**Comment by alukaa** [comment]
@huangzhhui 这是swoole协程的东西，我自己写了个mongo的连接池，但是swoole底层并不支持mongo协程，那么蛋疼的问题就是我现在只能当达到最大连接数的时候throw exception

**Comment by alukaa** [comment]
那基本就是这么回事了
