### ISSUE TITLE
rpc验证器未通过客户端异常捕捉到的异常无法使用

### ISSUE THREAD

**Issue by Mrzhengyixuan** [swoft-cloud/swoft#391]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes

**Details**
rpc客户端数据传输未通过rpc服务端验证，客户端不能得到正确的异常 信息，getMessage返回的信息不准确，建议反馈异常数据

**Comment by huangzhhui** [comment]
能否带上详细的案例描述一下？

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
