### ISSUE TITLE
查询器 selects join 方法不存在

### ISSUE THREAD

**Issue by vatezj** [swoft-cloud/swoft#392]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | dev-master (d7a44f3)
| Swoole version      | 4.0.3
| PHP version         | 7.1.2
| Runtime environment | Docker 

**Details**

查询器 selects join 方法不存在

![image](https://user-images.githubusercontent.com/16894578/45798275-df98e880-bcdb-11e8-86a4-4ecd1524309c.png)
![image](https://user-images.githubusercontent.com/16894578/45798287-eb84aa80-bcdb-11e8-90c9-391e120847b1.png)

**Comment by huangzhhui** [comment]
事实上 `selects` 是不存在的，仅存在于旧版的 DB 组件，文档已做对应的更新
