### ISSUE TITLE
swoole 版本兼容问题

### ISSUE THREAD

**Issue by touch888** [swoft-cloud/swoft#393]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 4.1.0 +
| PHP version         | 7.2.6
| Runtime environment | CentOS 7

**Details**

> 在大于swoole 4.0.4 的版本上swoft进程停止后 （PHP bin/swoft stop） ,会出现table刷日志的情况
![image](https://user-images.githubusercontent.com/20635217/45857851-45917880-bd8d-11e8-82ac-4dd2eb8259f3.png)
ps aux|grep bin/swoft  之后发现work进程和master 和manger进程还在，继续PHP bin/swoft stop没用，切回swoole 4.04 版本后一切正常

**Comment by sakuraovq** [comment]
2.0已经正式发布，建议升级到2.0 @touch888
