### ISSUE TITLE
建议增加配置让用户自己决定是否把QueryBuilder查出的数据的字段名称转化为驼峰命名

### ISSUE THREAD

**Issue by jqhph** [swoft-cloud/swoft#394]
**Details**

> swoft的实体使用是要逼死强迫症，查出来的字段下划线命名强制转化为驼峰，然后使用where条件查询又要转回去使用下划线命名的字段，能不能统一一下？要么全部转，要么都不转。建议增加配置让用户自己决定是否转化字段名称

```php
// where使用created_at是必须用数据库原字段名
$data = User::query()->where('created_at', '2018-09-09 11:12:34', '>')->get()->getResult()->toArray();

// 查出数据后如果要使用created_at字段，必须使用驼峰
$createdAt = $data[0]['createdAt'];
```

> 希望能改成下面这样

```php
// where使用created_at是必须用数据库原字段名
$data = User::query()->where('created_at', '2018-09-09 11:12:34', '>')->get()->getResult()->toArray();

$createdAt = $data[0]['created_at'];

// 或者
$data = User::query()->where('createdAt', '2018-09-09 11:12:34', '>')->get()->getResult()->toArray();

$createdAt = $data[0]['createdAt'];
```

**Comment by limingxinleo** [comment]
其实推荐你拿数据的时候只用entity->getCreatedAt()这种来拿。。
并且尽量避免使用entity->toArray() 

这样所有的变量就都是小写了。。

**Comment by jqhph** [comment]
> 其实推荐你拿数据的时候只用entity->getCreatedAt()这种来拿。。
> 并且尽量避免使用entity->toArray()
> 
> 这样所有的变量就都是小写了。。

能这样当然就这样操作，但是很多情况下使用数组更方便。查出的字段格式和querybuilder使用的字段格式不一致比较容易出错

**Comment by 256mywind** [comment]
我就重写了toArray方法。
在目录Models 重新写一个mode类继承基类 然后所有的实体类继承这个model类。
这样就可以保持字段在数据表和查出的数据保持一致。
```php
   /**
     * @return array
     */
    public function toArray(): array
    {
        $entities = EntityCollector::getCollector();
        $columns  = $entities[static::class]['field'];
        $data     = [];
        foreach ($columns as $propertyName => $column) {
            if (!isset($column['column'])) {
                continue;
            }
            $methodName = StringHelper::camel('get' . $propertyName);
            if (!\method_exists($this, $methodName)) {
                continue;
            }

            $value = $this->$methodName();
            if($value === null){
                continue;
            }
            $data[$column['column']] = $value;
        }

        return $data;
    }
```

**Comment by Wfuren** [comment]
+1，应该说本身的设计缺陷把，不能说通过其他方式来改变或者实现。要说实现用户有千万种方法，但是自身不应该这样，查询出来是驼峰，然后查询的时候又要用下划线

**Comment by 256mywind** [comment]
我要的是表里是什么。查出来是什么。 不能变！！。

**Comment by 256mywind** [comment]
orm 对像映射关系。你查出来的数据肯定得是和原表里的字段一样。  实体是什么，是映射使用的。你赋值取值 都可以用的方法。 是来映射的不是来改变的。像列表查出来是表里的字段 ，model查出来又是实体的字段， 你这不是让使用的人混淆嘛。。

**Comment by jqhph** [comment]
> 讲道理，既然你定义了实体那查出来的应该就是实体属性，还跟数据库字段绑定起来那这算什么ORM

实体属性没问题，但是转化为数组还是要跟数据库字段对应比较好，这样使用才是最方便的最符合大众思维的。如果orm不方便，那还要orm干嘛？

**Comment by huangzhhui** [comment]
混淆那是因为查询的实现问题，既然有实体，理应查询和输出都是实体属性

**Comment by jqhph** [comment]
其实对于用户而言，一个功能的使用是否方便和简单才是最重要的。如果一个功能设计带给大家的不是更方便更简单的使用，而是更繁琐或更复杂，那么这个设计意义在哪？大多数框架的ORM都不会这样设计吧？

**Comment by jqhph** [comment]
框架的出现难道不是为了方便开发而设计的么？Eloquent 使用实体，但是转化为数组并不会把数据库字段改成驼峰，所以并不会影响使用体验

**Comment by jqhph** [comment]
问题并不在是否orm使用实体，而在于orm转化为数组擅自帮用于改变了字段，并且在orm其他方法上字段的命名使用无法统一

**Comment by jqhph** [comment]
看了下代码确实是如此，那这个问题不是很好解决吗？在生成实体的命令加个option参数让用户自己选是否生成驼峰属性还是数据库表原属性不就完事了？

**Comment by jqhph** [comment]
那么说并不是orm设计问题，而是生成实体的命令的问题

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布

**Comment by okool** [comment]
这个问题解决了么?
我们所有跨平台交互接口,就不允许有大小写混写,只能小写或大写,
也就没有驼峰命名这种说法.
要"实体生成"工具有配置,prop保持下划线

**Comment by 233cy** [comment]
> 这个问题解决了么?
> 我们所有跨平台交互接口,就不允许有大小写混写,只能小写或大写,
> 也就没有驼峰命名这种说法.
> 要"实体生成"工具有配置,prop保持下划线

放弃吧，已经换到2.0了。2.0解决了

**Comment by okool** [comment]
> > 这个问题解决了么?
> > 我们所有跨平台交互接口,就不允许有大小写混写,只能小写或大写,
> > 也就没有驼峰命名这种说法.
> > 要"实体生成"工具有配置,prop保持下划线
> 
> 放弃吧，已经换到2.0了。2.0解决了

我现在就是2.06版,实体生成默认就是驼峰,没有配置可改.手动改不现实.
