### ISSUE TITLE
连接池报错的问题

### ISSUE THREAD

**Issue by Longjianghu** [swoft-cloud/swoft#398]
由于初学对连接池配置不正确，Swoft报了一个Service does not configure uri name=5bac86d63735b。能否把这个提示改一下，这个提示有点让人误解。

**Comment by Longjianghu** [comment]
另外文件生成工具能不能自动根据配置文件生成连接池配置文件？

**Comment by huangzhhui** [comment]
服务没有配置 URI 则返回此错误，请检查服务的相关配置
