### ISSUE TITLE
为什么使用swoft框架自身的redis，hMset写入的值时序列化后的？

### ISSUE THREAD

**Issue by qrong503** [swoft-cloud/swoft#399]
$redis = \Swoft\App::getBean('redis');
..........
..........
$redis->hMset($user_prefix_key, $cache_arr);

存储到redis值为：
![Uploading image.png…]()

这样，给hash某个key做自增时，因为值非int型会报错，怎么解决？

**Comment by huangzhhui** [comment]
@qrong503 图片无法查看，请重新上传

**Comment by qrong503** [comment]
![image](https://user-images.githubusercontent.com/23392768/46198078-28851880-c33e-11e8-940b-339d4d8e00fe.png)

**Comment by qrong503** [comment]
用原生的redis，hMset写入是正常的
代码
![image](https://user-images.githubusercontent.com/23392768/46198968-4b183100-c340-11e8-853c-9369b8d65734.png)

结果
![image](https://user-images.githubusercontent.com/23392768/46198991-5bc8a700-c340-11e8-81d3-7070c1208ce8.png)

**Comment by huangzhhui** [comment]
@qrong503 请查看 `config/cache.php` 和 `.env` 并确保 `redis` bean 的 `serialize` 参数为关闭的

**Comment by qrong503** [comment]
感谢  已解决
