### ISSUE TITLE
在TestTask.php中为何io切换成同步？

### ISSUE THREAD

**Issue by gouchaoer** [swoft-cloud/swoft#40]
可以看到redis还是协程的，为何mysql/http切换成了同步阻塞呢？

**Comment by stelin** [comment]
https://wiki.swoole.com/wiki/page/163.html
taskWorker只支持同步模式

**Comment by gouchaoer** [comment]
建议加上同步阻塞，说成同步会让人误解是协程，还有那个redis的方法有cor会误解

**Comment by stelin** [comment]
恩，好的，修正下

**Comment by stelin** [comment]
public function corTask($p1, $p2)  这个名字的函数是定义一个协程任务投递的demo，和redis协程没有关系

**Comment by whiteCcinn** [comment]
欢迎加群一起探讨
QQ：548173319
