### ISSUE TITLE
建议swoft在代码层面开放接口让用户可以直接通过代码增加bootScan目录或者是components.custom配置

### ISSUE THREAD

**Issue by jqhph** [swoft-cloud/swoft#402]
**Details**

> 建议swoft在代码层面开放接口让用户可以直接通过代码增加bootScan目录或者是components.custom配置
>这样用户在使用第三方组件的时候就不再需要手动配置bootScan或者是components.custom, 会方便非常多
>而第三方组件开发者也不用担心注解目录繁多无法被扫描的问题

```php
// 希望增加一个类似这样的接口
App::addBootScan([xxx...]);
```

**Comment by huangzhhui** [comment]
事实上一个单独的组件只需要配置一个 components.custom 配置项即可，从代码层面实现的话又会存在多一次扫描，且是全量扫描，否则如何在扫描之前检测到组件的配置项呢？

**Comment by jqhph** [comment]
> 事实上一个单独的组件只需要配置一个 components.custom 配置项即可，从代码层面实现的话又会存在多一次扫描，且是全量扫描，否则如何在扫描之前检测到组件的配置项呢？

从代码层面实现并不是需要多一层扫描，比如可以通过<code>App::addBootScan</code>接口在bean init扫描之前就把需要扫描的目录保存在App类的静态属性上，然后bean init的时候把这个静态变量的数据读出来一起扫描就行了。
有了这个功能，第三方组件开发者在composer配置一下自动加载脚本，在这个脚本里面调用<code>App::addBootScan</code>，就可以做到自己控制要扫描哪些目录，用户也不需要配置 components.custom
```php
class App 
{
    protected $customBootScan = [];

   public static function addBootScan(array $data)
   {
       static::$customBootScan = array_merge(static::$customBootScan, $data);
   }
}
``

**Comment by huangzhhui** [comment]
嗯，通过Composer的File Autoload的确可以实现

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
