### ISSUE TITLE
DB连接池的连接数在哪配置的？

### ISSUE THREAD

**Issue by minxinqing** [swoft-cloud/swoft#403]
DB_MIN_ACTIVE=5
DB_MAX_ACTIVE=10

DB_SLAVE_MIN_ACTIVE=5
DB_SLAVE_MAX_ACTIVE=10

我在env里配置了以上两项，然后跑了一次压力测试，可从"show processlist"命令来看，有40个连接在那挂着，这个最大连接数不是上面那个参数配置的吗？

**Comment by huangzhhui** [comment]
配置的Worker数量是多少？

**Comment by minxinqing** [comment]
10个worker，5个task worker

**Comment by huangzhhui** [comment]
每个Worker拥有独立的连接池，你这是并发数还不够大，只到40个连接，理应更大

**Comment by huangzhhui** [comment]
是的
