### ISSUE TITLE
如何通过连接 MySQL + SQLite

### ISSUE THREAD

**Issue by uiosun** [swoft-cloud/swoft#407]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 1.0.0 (Swoft Docker)
| Swoole version      | 4.0.3 (Swoft Docker)
| PHP version         | 7.1.22 (Swoft Docker)
| Runtime environment | Docker.

**Details**

> 1. 如何在 default 是 MySQL 的情况下，连接 SQLite，我常用的 dsn 为：`sqlite:app/data/db.sql`
> 2. .env 的 DB_NAME 与 config/properties/db.php 是否存在对应关系？后者似乎可以有两层，而 .env 只看到一层

Ps：无需很详细，请指出思路即可

**Comment by huangzhhui** [comment]
1. swoft/db 暂不支持其他协议，因为使用的是Swoole的协程客户端
2. 配置文件与 env 又两种关联关系，一种是通过使用 `env()` 函数给 config 赋值达到 config 的值的重写，另一种是通过 `@Value` 注解实现环境变量和配置文件的读取，其中 DB 的配置关联采用后者，位置于 `./vendor/swoft/db/src/Pool/Config/DbPoolConfig.php`

**Comment by huangzhhui** [comment]
@Sun-FreePort 使用 PDO 请确保使用 Swoole 4 并开启 enable_coroutine 属性

**Comment by Sun-FreePort** [comment]
已有大佬写了 SQLite 池
[Swoft-SQLite-Pool - zcmzc](https://github.com/zcmzc/swoft-sqlite-pool)
