### ISSUE TITLE
is, is not 操作符无效

### ISSUE THREAD

**Issue by AaronWB** [swoft-cloud/swoft#411]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes

**Details**
sql 或查询构造器中使用is操作符会自动省略当前条件
```php
        $condition[] = [
            'deleted_at', 'is', null
        ];
        return parent::findOne($condition, $options);
```
初步判断应该是QueryBuilder文件中addCondition方法中case中少了IS， IS_NOT。

**Comment by CodeingMonkey** [comment]
这个问题1.0版本 没修复吧 ，今天遇到了同样的需求，代码里也没找到对应的操作方法。

**Comment by AaronW-BE** [comment]
> 这个问题1.0版本 没修复吧 ，今天遇到了同样的需求，代码里也没找到对应的操作方法。

QueryBuilder.php这个文件中有代码，可以修改
