### ISSUE TITLE
使用findOne添加fields参数查询后使用rpc调用会报错

### ISSUE THREAD

**Issue by AaronWB** [swoft-cloud/swoft#412]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    |no
| Runtime environment |/Mac

**Details**
本地服务能查询到结果，调用方提示响应状态无效`Status of response is invalid`,

**Comment by huangzhhui** [comment]
@AaronWB 一个请求里，如果响应方没有正确的响应，那是毫无疑问的

**Comment by AaronWB** [comment]
如果findOne不使用fields参数，可以正常返回

**Comment by huangzhhui** [comment]
@AaronWB 请提供具体的代码示例

**Comment by yunxi177** [comment]
你这个问题是因为findOne没有查到县新返回Null了，进而rpc通信会报`Status of response is invalid,`
