### ISSUE TITLE
定时任务执行失败

### ISSUE THREAD

**Issue by cirvor** [swoft-cloud/swoft#417]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | ^1.0
| Swoole version      | 4.0.3
| PHP version         | 7.1.23
| Runtime environment | Docker

**Details**
都是基于官方Docker镜像执行，本地执行没有问题 
上传到测试环境执行报错:
> [TaskEventListener.php:45,Swoft\Task\Bootstrap\Listeners\TaskEventListener->onTask] TaskExecutor->run Call to undefined method SyncTask_5bcd41bedd35e::cronTask() file=/var/www/swoft/vendor/swoft/framework/src/Helper/PhpHelper.php line=47

**Comment by inhere** [comment]
？咋关了
