### ISSUE TITLE
swoft怎么支持laravelblade模板引擎

### ISSUE THREAD

**Issue by liuxiaojin93** [swoft-cloud/swoft#420]
在swoft里面使用blade模板引擎，需要更改其他的配置吗

**Comment by huangzhhui** [comment]
这个得了解Swoole的生命周期，结合swoft-view的做法去改动才行，不好阐述

**Comment by huangzhhui** [comment]
@daydaygo 我记得你之前是不是继承过 blade ？

**Comment by jqhph** [comment]
https://github.com/jqhph/swoft-blade
blade模板引擎swoft版本,可以直接使用

**Comment by wujunze** [comment]
很棒 可以提交到awesome swoft项目中

**Comment by jqhph** [comment]
> 很棒 可以提交到awesome swoft项目中

怎么提交？

**Comment by inhere** [comment]
这里 https://github.com/swoft-cloud/awesome-swoft

**Comment by liuxiaojin93** [comment]
收到 谢谢
