### ISSUE TITLE
上传文件

### ISSUE THREAD

**Issue by 256mywind** [swoft-cloud/swoft#422]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

你不要删我的提问撒

PACKAGE_MAX_LENGTH  这个参数 我早就看了！！ 

就是不知道什么情况！  才来提问的！

**Comment by huangzhhui** [comment]
ref: https://github.com/swoft-cloud/swoft/issues/421
@256mywind 如果原issue未解决，可直接 reopen issue 在原问题回复
