### ISSUE TITLE
如何更改session使用的redis连接池

### ISSUE THREAD

**Issue by xfni** [swoft-cloud/swoft#425]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      | 4.0.4 (by `php --ri swoole`)
| PHP version         | 7.2.11 (by `php -v`)
| Runtime environment | Docker 

**Details**

我有多个Redis连接池，如何指定session使用哪一个？

**Comment by sakuraovq** [comment]
@inject 的时候填写连接池名称即可
