### ISSUE TITLE
生成DB实体类时参数类型能支持可空类型

### ISSUE THREAD

**Issue by herojhc** [swoft-cloud/swoft#426]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 1.0.8-beta
| Swoole version      | 4.2.4 (by `php --ri swoole`)
| PHP version         | 7.2.0 (by `php -v`)
| Runtime environment | Ubuntu

**Details**

> Describe what you are trying to achieve and what goes wrong.
希望在生成DB实体类时参数类型能支持可空类型，不过得需要php7.1 版本，某些情况下，比如时间类型会赋值为空
```php
// paste output here
/**
     * @param string $value
     * @return $this
     */
    public function setBirthday(?string $value): self
    {
        $this->birthday = $value;

        return $this;
    }
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
