### ISSUE TITLE
DB类查询后返回实体类，在调用toArray建议调整

### ISSUE THREAD

**Issue by 233cy** [swoft-cloud/swoft#428]
![default](https://user-images.githubusercontent.com/29916783/47615527-e12faa80-daea-11e8-880b-de18e1408253.png)
如果没有数据返回直接调用toArray会有一个异常报错，建议调整下toArray

**Comment by geyang0101** [comment]
没有数据直接返回Swoft\Db\Collection空对象不就好了，不知为啥要返回空数组。

**Comment by huangzhhui** [comment]
FindOne返回Collection？

**Comment by nangge** [comment]
查询器`get`方法时，如果空数据时返回的是空数组，有数据返回时是`Swoft\Db\Collection`对象；
建议统一为`Swoft\Db\Collection` 对象

**Comment by inhere** [comment]
还是有大部分人直接用结果判断的，所以返回空值

**Comment by nangge** [comment]
那为什么不能返回一个`items`为空的`Collection`对象；这样的话直接用结果判断应该也没问题；
另外类似于`laravel 、TP5`这种传统MVC框架提供的分页类都会有一些渲染分页的方法和属性，如果返回数据为空时返回的不是分页对象而是一个空数组，那对于渲染时会存在较大问题

**Comment by sakuraovq** [comment]
2.0已经正式发布，建议升级到2.0  已经解决
