### ISSUE TITLE
db返回的数据是驼峰大小写，可是查询条件等要根据数据库下划线来写

### ISSUE THREAD

**Issue by 233cy** [swoft-cloud/swoft#429]
![default](https://user-images.githubusercontent.com/29916783/47615552-497e8c00-daeb-11e8-835d-8e8c63144575.png)
不知道是不是我用的不对，实体类查询完了后返回的是驼峰字段，但是查询的话又要用下划线来写

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
