### ISSUE TITLE
swoole4.2 定时任务无法正常执行

### ISSUE THREAD

**Issue by yunxi177** [swoft-cloud/swoft#432]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | 4.2
| PHP version         | 7.1
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> 在swoole4.2中定时任务无法正常执行

**Comment by huangzhhui** [comment]
请提供具体无法运行的反馈

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
