### ISSUE TITLE
当指定返回值类型时(已指定可空类型)，报错

### ISSUE THREAD

**Issue by herojhc** [swoft-cloud/swoft#435]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0.8-beta
| Swoole version      | 4.2.5 (by `php --ri swoole`)
| PHP version         | 7.2.0 (by `php -v`)
| Runtime environment | Ubuntu

**Details**

> Describe what you are trying to achieve and what goes wrong.

当指定返回值类型时(**已指定可空类型**)，报错，

Return value of XXX_5bda514a2a485::YYY must be an instance of App\Models\Entity\ZZZ, null returned /vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d

```php
// paste output here

 /**
     * @param $a
     * @param $b
     * @return ZZZ|null
     */
    public function YYY($a, $b): ?ZZZ
    {
        return ZZZ::findOne([
            ['a' => $a],
            ['b' => $b]
        ])->getResult();
    }
```
希望能尽快支持可空类型，这样在IDE中用起来比较方便，谢谢。

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by sakuraovq** [comment]
2.0已经正式发布，建议升级到2.0
