### ISSUE TITLE
Swoft-Redis 中的 Operator 目录有什么用？

### ISSUE THREAD

**Issue by Sun-FreePort** [swoft-cloud/swoft#437]
**Details**

我正在仿照 [Swoft-Redis](https://github.com/swoft-cloud/swoft-redis) 编写 Swoft-Memcached，想问一下：`src/Operator` 这个目录是干啥用的？

**Comment by huangzhhui** [comment]
定义操作命令即处理返回的结果（由于部分方法hiredis与phpredis的返回格式不一致）

**Comment by Sun-FreePort** [comment]
奶斯啊朋友，感谢。
