### ISSUE TITLE
官方CorsMiddleware中间件的DEMO是不是有问题？

### ISSUE THREAD

**Issue by 233cy** [swoft-cloud/swoft#438]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 4.0.0
| PHP version         | 7.2.6
| Runtime environment | Ubuntu

![lt f2as87h xniuqi r0 c](https://user-images.githubusercontent.com/29916783/47859509-74d5e380-de29-11e8-9318-d66bccde59ce.png)

handle后，withStatus无效是psr7的规则还是怎么回事？

**Comment by Wfuren** [comment]
> 
> 
> 并没有看到你的截图哪里有设置状态

比如这样，
`<?php

namespace App\Middlewares;

use Psr\Http\Server\RequestHandlerInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Swoft\Bean\Annotation\Bean;
use Swoft\Http\Message\Middleware\MiddlewareInterface;

/**
 * @Bean()
 */
class CorsMiddleware implements MiddlewareInterface
{
    /**
     * Process an incoming server request and return a response, optionally delegating
     * response creation to a handler.
     *
     * @param \Psr\Http\Message\ServerRequestInterface $request
     * @param \Psr\Http\Server\RequestHandlerInterface $handler
     * @return \Psr\Http\Message\ResponseInterface
     * @throws \InvalidArgumentException
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        if ('OPTIONS' === $request->getMethod()) {
            return $this->configResponse(\response());
        }

        $response = $handler->handle($request);
        $response = $response->withStatus(404);
        return $this->configResponse($response);
    }

    private function configResponse(ResponseInterface $response)
    {
        return $response
            ->withHeader('Access-Control-Allow-Origin', 'http://mysite')
            ->withHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Accept, Origin, Authorization')
            ->withHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
    }
}`

**Comment by Wfuren** [comment]
> 
> 
> 如果你没在其他middleware 覆盖这个值，或者controller 里面没有覆盖这个值，status肯定是404.你肯定是哪里把这个值给覆写了

不会的，因为我没有改任何东西，你可以下载官方SWOFT然后试验一下

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
