### ISSUE TITLE
QueryBuilder如何在get方法中使用MySQL函数？

### ISSUE THREAD

**Issue by jqhph** [swoft-cloud/swoft#440]
如下代码所示sql，用QueryBuilder如何实现？如果没有这个功能希望可以支持一下
```php
// 比如这条sql用QueryBuilder如何实现？
$sql = "SELECT `id`, sum(`id`) FROM user";

// 使用sum方法则无法查其他列内容
User::query()->sum('id')->getResult();

// 使用get方法则会报sum(id)不存在
User::query()->get(['id', 'sum(id)'])->getResult();
```

**Comment by limingxinleo** [comment]
其实可以直接使用Db:query来查

**Comment by jqhph** [comment]
> 其实可以直接使用Db:query来查

如果要写sql去查那就麻烦很多了，orm不就是为了不写原生sql吗？这种功能是很常用的，建议你们增加下这个功能

**Comment by limingxinleo** [comment]
@jqhph 嗯，你说的很有到底，但是，既然都用了sum来查了。。你也查不出orm啊，查出来的也只是array

**Comment by limingxinleo** [comment]
@jqhph 嗯，你说的很有道理，但是，既然都用了sum来查了。。你也查不出orm啊，查出来的也只是array

**Comment by jqhph** [comment]
> @jqhph 嗯，你说的很有道理，但是，既然都用了sum来查了。。你也查不出orm啊，查出来的也只是array

用不了实体没关系，但是像这种简单的sql，既然有query builder为啥还要去写sql？

**Comment by jqhph** [comment]
其实我说的不只是sum，在QueryBuilder::get方法中所有的mysql函数都用不了，这样很不方便

**Comment by Longjianghu** [comment]
我是直接用的DB::query，这个更灵活。

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
