### ISSUE TITLE
query builder查数据如果某个字段值为空，转化为array后该字段不存在

### ISSUE THREAD

**Issue by jqhph** [swoft-cloud/swoft#443]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Swoft version       | db 1.1.26

**Details**

> 如果字段值为空，则转化为数组后该字段不存在，示例如下：

```php
$list = User::query()->get(['id', 'username'])->getResult()->toArray();

// $list结果可能如下：
[
    ['id' => 1, 'username' => '张三'],
    ['id' => 2, 'username' => '李四'],
    ['id' => 3], // 如果username为空值，则数组中不存在这个字段
];
```

**Comment by jqhph** [comment]
这段时间使用swoft/db，感觉swoft/db总是会帮用户做一些不必要的操作，希望开发组有时间能好好优化一下

**Comment by alukaa** [comment]
toArray fuction. if null continue.要返回null字段目前只能不用toArray.或者你可以写一个Model  extend  Db Model.复写toArray.然后所有的entity extends你的Model.

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
