### ISSUE TITLE
实例 查询希望添加设置表别名的方法

### ISSUE THREAD

**Issue by 256mywind** [swoft-cloud/swoft#445]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
就是在query builder里面添加一个给表设置别名的方法

现在只有table()方法可以设置

```php
    public function alias(string  $alias=null)
    {
        $this->table['alias'] = $alias;
        return $this;
    }
```
因为使用实例的时候 暂时没有看到有哪里可以给表设置别名

**Comment by huangzhhui** [comment]
没能太理解你的意思，能否举个具体的例子？

**Comment by 256mywind** [comment]
我的意思是给表设置别名，添加一个方法。
现在没有地方可以给表设置别名，只有table($className, $alisas)这个方法可以设置别名
但是我如果用实例类来查询的话 ，就没有法设置别名。
希望添加一个方法
就像我上面写的那样
比如查询的时候就可以
```php
User::query()->alias('u')->where(...)->.......
```
这样的话 表的别名就设置成了u。 
我想表达的是这个意思！！

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
