### ISSUE TITLE
WebSocket的onMessage中是否有可用的路由功能？

### ISSUE THREAD

**Issue by langshen** [swoft-cloud/swoft#446]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 4.2.6 (by `php --ri swoole`)
| PHP version         | 7.2.10 (by `php -v`)
| Runtime environment | Ubuntu.

**Details**

在WebSocket的Controller中的onMessage方法中，message的交互经常需要用到路由，类于swoole-framework中的runMvc，在swoft中，是否有直接可用的功能？谢谢。

**Comment by huangzhhui** [comment]
你是指 http://doc.swoft.org/master/zh-CN/websocket-server/controller.html ？

**Comment by langshen** [comment]
> 你是指 http://doc.swoft.org/master/zh-CN/websocket-server/controller.html ？

不是呀，是里面的onMessage中，会收到不同的动作action，在swoole-framework中，是定义了一个uri的变量，然后使用runMvc重定向到不同的业务逻辑呀。比如：uri:user/login，uri:user/reg，不同的动作。

**Comment by huangzhhui** [comment]
所以你这个 URI 跟 @WebSocket("/echo") 注解上面定义的有什么不一样？

**Comment by langshen** [comment]
@WebSocket("/echo")
是握手连接URI，我说的是成功连接之后的各种不同动作的URI。

**Comment by huangzhhui** [comment]
握手连接后不就是你拿其中的一个约定的参数去对应到不同的逻辑而已吗？

**Comment by langshen** [comment]
> 握手连接后不就是你拿其中的一个约定的参数去对应到不同的逻辑而已吗？

说的就是这个意思，就是约定使用参数URI来做判断，有没有直接可用的路由方法。

没有的话我就复制那个runMVC来用了。

**Comment by huangzhhui** [comment]
这个你写个 switch 就完了，不应该由框架来做这个事情吧

**Comment by inhere** [comment]
@langshen 还没有的。原来想过，后面没做了

**Comment by langshen** [comment]
嗯嗯，谢谢，如果也能用@WebSocket来注释或是增加一个新标签绑定就太棒了，因为这几乎在所有的实例中都需要到。。

**Comment by inhere** [comment]
@langshen 可以使用2.0; 2.0 提供了消息阶段的路由功能
