### ISSUE TITLE
第一次运行时报错

### ISSUE THREAD

**Issue by hooklife** [swoft-cloud/swoft#45]
```
open(/home/vagrant/Code/swoft/runtime/logs/swoole.log) failed. Error: No such file or directory[2]
```

运行后随便访问一个url，则框架会自动生成文件，同时生成目录
runtime/logs/notice.log

退出命令行后第二次运行，由于第一次生成的文件/目录，第二次可以正常运行不报错，并可以正常写入swoole.log 文件

其实我觉得框架应该默认带runtime/logs 这个目录，方便写入日志，而不用运行时创建

**Comment by huangzhhui** [comment]
谢谢你的建议，已经默认带上相关目录了
