### ISSUE TITLE
redis 用 hMset会写入默认0 db ,怎么设置都没用

### ISSUE THREAD

**Issue by ytd7777** [swoft-cloud/swoft#450]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 这个在那看?
| Swoole version      | 4.2.3
| PHP version         |7.1
| Runtime environment | CentOS 7

**Details**

> 配置在下面，REDIS_DB 改成啥 hMset都写的是0，

```php
# Redis
REDIS_NAME=redis
REDIS_DB=1
REDIS_URI=xx:6379?auth=xxx,xx:6379?auth=xx
REDIS_MIN_ACTIVE=5
REDIS_MAX_ACTIVE=10
REDIS_MAX_WAIT=20
REDIS_MAX_WAIT_TIME=3
REDIS_MAX_IDLE_TIME=60
REDIS_TIMEOUT=3
REDIS_SERIALIZE=1
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by limingxinleo** [comment]
提供一个Demo吧，我这边是没问题的

**Comment by ytd7777** [comment]
目前最近测试开了定时任务会导致db重置为0

**Comment by ytd7777** [comment]
/**
     * redis 对象
     * @Inject()
     * @var \Swoft\Redis\Redis
     */
    private $redis; 怀疑注入导致的

**Comment by ytd7777** [comment]
$this->redis    = App::getBean(\Swoft\Redis\Redis::class); 换成这个在测试

**Comment by limingxinleo** [comment]
现在还会这样？？你代码里是否用过select

**Comment by ytd7777** [comment]
没有用过select;换成 App::getBean(\Swoft\Redis\Redis::class) 正常了

**Comment by limingxinleo** [comment]
那我关掉了 😄
