### ISSUE TITLE
官方提供Mysql Entity创建命令 Bug

### ISSUE THREAD

**Issue by studyzhanglei** [swoft-cloud/swoft#452]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 4.2.5(by `php --ri swoole`)
| PHP version         | 7.2.11 (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.
mac
**Details**
用官方提供的数据库实体创建命令，php bin/swoft entity:create -d dbname mytable,table2，
会把例如user_id 转成变量 $userId，如果我的数据表里面有个字段为userId，那么就会在entity表里面创建两个相同的变量$userId;

$array = UserStockBalance::findAll($criteria, $option)->getResult()->toArray();
里面的每个元素不是以数据库字段命名的，比如数据库为{user_d: 123}, 得到的数据为{userId: 123}

建议toArray以后，数组里面的元素下标与数据库一致。
 
> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue
DROP TABLE  IF EXISTS `user_stock_balance`;

CREATE TABLE `user_stock_balance` (
	`_id` int unsigned primary key auto_increment comment '主键',
	`user_id`	char(24) not null default '' comment '用户id',
	`product_number` int unsigned  not null default 0 comment '产品编号',
	`productNumber` int unsigned  not null default 0 comment '产品编号',
	`amount` decimal(10, 3) not null default 0.000 comment '结余数额'
)
sudo /usr/local/Cellar/php/7.2.11/bin/php bin/swoft entity:create -d nhd -i user_stock_balance --entity-file-path @app/Models/Entity/User

```php
// paste code
```
class UserStockBalance extends Model
{
    /**
     * @var int $id 主键
     * @Id()
     * @Column(name="_id", type="integer")
     */
    private $id;

    /**
     * @var string $userId 用户id
     * @Column(name="user_id", type="char", length=24, default="")
     */
    private $userId;

    /**
     * @var int $productNumber 产品编号
     * @Column(name="product_number", type="integer", default=0)
     */
    private $productNumber;

    /**
     * @var int $productNumber 产品编号
     * @Column(name="productNumber", type="integer", default=0)
     */
    private $productNumber;

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
