### ISSUE TITLE
Swoft Mysql update 能否使用 amount = amount + xxx这种形式？目前在官方文档没有看到

### ISSUE THREAD

**Issue by studyzhanglei** [swoft-cloud/swoft#453]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
关于数据库的介绍，给的文档太少了。。是否有更详细的文档！
> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by rlgy** [comment]
Query::table(User::class)->where('id',1)->counter('age',1)->getResult();
```sql
UPDATE `user`  set  `age` = `age`+1  WHERE `id` = '1'
```

**Comment by studyzhanglei** [comment]
> Query::table(User::class)->where('id',1)->counter('age',1)->getResult();
> 
> ```sql
> UPDATE `user`  set  `age` = `age`+1  WHERE `id` = '1'
> ```

thk! 文档上也看到这个了，以为是用法是计数相关的！
