### ISSUE TITLE
可否提供一个纯API 单机项目的脚手架

### ISSUE THREAD

**Issue by solarhell** [swoft-cloud/swoft#456]
你好，现在使用 ` composer create-project swoft/swoft` 创建出来的项目包含很多微服务相关的东西。 可否提供一个简易版的 JSON API 的脚手架（不需要微服务和服务发现等）？ 谢谢。

**Comment by huangzhhui** [comment]
请参考 swoft-skeleton 项目

**Comment by Wfuren** [comment]
> swoft-skeleton

swoft-skeleton项目我发现compost.json里依旧包含rpc，websocket等

**Comment by limingxinleo** [comment]
https://github.com/limingxinleo/swoft-project

@Wfuren 你可以借鉴这个，写一个适合自己的。

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
