### ISSUE TITLE
Task投递任务，执行问题

### ISSUE THREAD

**Issue by 233cy** [swoft-cloud/swoft#457]
![default](https://user-images.githubusercontent.com/29916783/48664494-29cef800-eada-11e8-9ab1-7de9344b196a.png)
如图，cronTask方法每秒执行一次，可是我在重启一下swoft后，总是要等到下分钟后才会执行为何？
没有在文档中找到对此的解释

**Comment by Wfuren** [comment]
???

**Comment by AmdRyZen** [comment]
我本地也发现 这个问题了

**Comment by Longjianghu** [comment]
貌似和环境相关，我用mac就有这个情况，但是在服务器上就没有。

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
