### ISSUE TITLE
参数验证不通过时有什么办法自定义返回格式吗？

### ISSUE THREAD

**Issue by minxinqing** [swoft-cloud/swoft#458]
现在返回的格式是：
{
    "message": "Parameter id is too big (maximum is 10)"
}

有什么办法能返回如下格式吗？
{
    "code":100001,
    "message":"Parameter id is too big (maximum is 10)",
    "data":{}
}

**Comment by Wfuren** [comment]
> 
> 
> 现在返回的格式是：
> {
> "message": "Parameter id is too big (maximum is 10)"
> }
> 
> 有什么办法能返回如下格式吗？
> {
> "code":100001,
> "message":"Parameter id is too big (maximum is 10)",
> "data":{}
> }

可以看下app目录下的Exception目录，异常处理。应该有处理这个返回结果的
