### ISSUE TITLE
可以给文档中加上目录解释吗？

### ISSUE THREAD

**Issue by Wfuren** [swoft-cloud/swoft#459]
因为是小白，略看一遍文档后，有时候看不会挨个看命名空间理解某个目录的作用，希望对开发者会用到的目录做一个粗略的解释如：
app：
  Boot进程管理
  Breaker熔断器
  Controllers控制器
  Exception异常处理
  Fallback服务降级
  Lib定义rpc接口
  Listener异步任务监听
.......（以上只是自己的理解目录，可能会不对谅解）等等之类的
有个大致的介绍，这样看到目录介绍可以根据对应的知识点搜索文档，反而比一遍遍看文档更容易上手和理解。当然只是对一些固定目录进行介绍，如一些核心目录开发者无需了解的自然不用了。希望可以尽快加上呢！

**Comment by huangzhhui** [comment]
事实上对目录没有任何要求，你可以随意写

**Comment by Wfuren** [comment]
> 
> 
> 事实上对目录没有任何要求，你可以随意写

这个知道在config配置中可以修改目录，主要是为了了解结构，便于我这种小白理解然后找对应的文档做测试和调整

**Comment by limingxinleo** [comment]
https://github.com/limingxinleo/swoft-project/wiki/Struct

目录结构真的可以自定义，没必要局限在这里的。
