### ISSUE TITLE
服务重启失败

### ISSUE THREAD

**Issue by jingpg** [swoft-cloud/swoft#461]
在生产环境运行，服务重启时偶尔不成功。经过初步排查定位为服务在停止时超时导致失败。 框架默认将超时时间设置为60秒。目前业务中有定时器任务，其执行时间超过60秒，导致停止超时。建议将服务停止时间设置为自定义，或者是将默认超时时间设定更长。

files:
vendor/swoft/framework/src/Bootstrap/Server/AbstractServer.php line 134

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
