### ISSUE TITLE
如何简便引用外部类？

### ISSUE THREAD

**Issue by tgl123** [swoft-cloud/swoft#462]
比如有个的   test.class.php   这类的一个类文件，如何简便的引用到他

**Comment by inhere** [comment]
配置 `composer.json` 能被composer加载到就行

**Comment by tgl123** [comment]
不太明白，呵呵，因为我这个不是composer下载下来的呢，是我自己写的一个类文件

**Comment by huangzhhui** [comment]
https://docs.phpcomposer.com/01-basic-usage.html#Autoloading
https://docs.phpcomposer.com/04-schema.html#autoload

**Comment by tgl123** [comment]
谢谢!
