### ISSUE TITLE
annocation 收集,Bean初始化的问题

### ISSUE THREAD

**Issue by alukaa** [swoft-cloud/swoft#464]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 4.0.3
| PHP version         | 7.2.10
| Runtime environment | Docker

**Details**

> swoft httpServer start的时候有没有办法可以加载除了/vendor/swoft和/app之外的文件的annocation,
比如说我自己写了一个包需要在初始化的时候加载一些Bean，有没有什么好的方法
![image](https://user-images.githubusercontent.com/8164389/48878524-a3e8df00-ee42-11e8-95fa-b18c4a52de10.png)

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by limingxinleo** [comment]
https://doc.swoft.org/master/zh-CN/core/component.html
