### ISSUE TITLE
Task投递异步任务，如何使用redis

### ISSUE THREAD

**Issue by PeterYangs** [swoft-cloud/swoft#466]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      |4.2.7
| PHP version         | 7.1.22
| Runtime environment | centos7

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
Task::deliver('sync', 'cache', [], Task::TYPE_ASYNC);
官方的demo跑不通，在Type为异步时
```

**Comment by huangzhhui** [comment]
请详细描述如何跑不通

**Comment by wzzq** [comment]
异步任务中，调用redis没有作用 
if ($res->Code === "OK") {
      $ret1 = $this->redis->deferCall('set', ['sms_'.$phone, $code]);
}

**Comment by Longjianghu** [comment]
我这边配置了一个Redis连接池没啥问题

**Comment by PeterYangs** [comment]
已解决，实际上是可以操作的，只是不会输出到debug控制台

**Comment by inhere** [comment]
OK @PeterYangs 😄 
使用时发现的需要注意的问题，欢迎提交到doc 
记录一下，方便后面的使用者查询
