### ISSUE TITLE
希望添加路由命名

### ISSUE THREAD

**Issue by AaronWB** [swoft-cloud/swoft#467]
| Q                   | A
| ------------------- | -----
| Bug report?         |no
| Feature request?    | yes

希望能够获取其他路由的地址

**Comment by huangzhhui** [comment]
请详细描述问题的预期及现状

**Comment by AaronWB** [comment]
> 请详细描述问题的预期及现状

不知道有没有用过laravel，路由命名的作用可以在其他地方获得命名路由的地址，而且对于param参数，query参数的传递也方便

**Comment by huangzhhui** [comment]
@AaronWB 建议贴出代码或图片详细说明问题，有助于大家理解一致

**Comment by inhere** [comment]
@AaronWB 这个功能感觉使用场景不多，有点鸡肋。估计用于重定向跳转时或者视图页面里输出路由path

**Comment by AaronWB** [comment]
> @AaronWB 这个功能感觉使用场景不多，有点鸡肋。估计用于重定向跳转时或者视图页面里输出路由path

主要用在设置回调地址，异步通知

**Comment by okool** [comment]
比如"/api/v1/user/{xxx}/topic/{xxx."这个路由命名为"user_topic".判断时不想写正则匹配Uri,不想用apigateway增加负担.
具体在哪些场景用,写控制器,中间件,还是model,这个不用操心.

我们的想法很简单,简化代码,少写点代码,少点错误而已..
```php
if($router->name==='user_topic'){
// code
}
```

而不是
```php
function searchPath($reg){
$path=$request->getUri()->getPath();
try{
 //balala
match....
}catch(){
}
}

if(searchPath('/v2/user\/[0-9]{10}\/topic/\w{4}\/?/i')){
// code
}
eleif(searchPath('/v1/user\/[0-9]{10}\/topic/\w{4}\/?/i')){
// code
}

```

**Comment by inhere** [comment]
@okool  ok，可以。
可能在后两个版本加上这个
