### ISSUE TITLE
类似symfony console confirm

### ISSUE THREAD

**Issue by alukaa** [swoft-cloud/swoft#468]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 10.0.
| Swoole version      | 4.0.1
| PHP version         | 7.2.8
| Runtime environment | Docker

**Details**

> console 支持类似symfony console confirm功能否?

https://symfony.com/doc/current/components/console/helpers/questionhelper.html
![image](https://user-images.githubusercontent.com/8164389/49137083-698daf00-f326-11e8-8728-210f1a0debe2.png)

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
有的 https://github.com/swoft-cloud/swoft-console/blob/master/src/Helper/ConsoleUtil.php#L148

if (ConsoleUtil::confirm('continue ?')) {
	// do something ...
}

**Comment by alukaa** [comment]
额，不好意思没仔细看源代码，谢谢
