### ISSUE TITLE
跨域中间件失效

### ISSUE THREAD

**Issue by cgyhbc** [swoft-cloud/swoft#469]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

路由未匹配时，请求尚未进入中间件，直接抛出异常返回，此时设置的跨域请求中间件不起作用。建议将跨域部分，直接放入请求声明周期函数中。

**Comment by huangzhhui** [comment]
请详细描述你的用法，讲道理在全局中间件写就好了

**Comment by alukaa** [comment]
#410 我是这样解决的

**Comment by alukaa** [comment]
@cgyhbc, middleware栈的方式收集mlddliwaew的结果的，当controller show exception是，前面的middleware结果都搜集不到，直接跳到了exception handler

**Comment by cgyhbc** [comment]
根据server dispatcher源码得知，请求调度时，会先执行系统定义的中间间，如路由检测等，假如执行失败的话，会直接抛出异常，到达不了全局中间件，更到达不了控制器中间间。我的解决思路是，监听请求事件，任何请求过来，会先执行这个事件，在这个事件中实现跨域




| |
ccc
邮箱：cgyhbc@126.com
|

Signature is customized by Netease Mail Master

在2018年12月08日 12:04，alukaa 写道：

@cgyhbc, middleware栈的方式收集mlddliwaew的结果的，当controller show exception是，前面的middleware结果都搜集不到，直接跳到了exception handler

**Comment by alukaa** [comment]
@cgyhbc 事件中实现不了把，即使你把reeuest 传递给了 event, listener 里面 return 起不到任何作用
![image](https://user-images.githubusercontent.com/8164389/49809968-2d813200-fd9b-11e8-88b9-c20aad6d0e6b.png)
哪里都实现不了，afterDispatch 触发事件的时候response 已经send了,

**Comment by cgyhbc** [comment]
我是这么实现的，在监听器中，直接拿到响应对象，修改完响应对象后，又将响应对象放回到请求中






在 2018-12-11 23:20:25，"alukaa" <notifications@github.com> 写道：


@cgyhbc 事件中实现不了把，即使你把reeuest 传递给了 event, listener 里面 return 起不到任何作用

哪里都实现不了，afterDispatch 触发事件的时候response 已经send了,

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
