### ISSUE TITLE
客户端ip如何取得

### ISSUE THREAD

**Issue by AaronWB** [swoft-cloud/swoft#470]
| Q                   | A
| ------------------- | -----
| Bug report?         |no
| Feature request?    | yes

HTTP服务如何获取请求方IP

**Comment by huangzhhui** [comment]
自行通过Request对象获取Swoole的Request对象获取对应的属性

**Comment by lion1120lion** [comment]
![image](https://user-images.githubusercontent.com/30719576/53705465-a2767c00-3e5f-11e9-89c1-5f9d2c027fb8.png)
这里我是使用$request->getSwooleRequest()获取的，客户端ip应该是哪个呢？
