### ISSUE TITLE
redis订阅完全无法使用

### ISSUE THREAD

**Issue by cailetech** [swoft-cloud/swoft#472]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | 最新版
| Swoole version      | 4.2.7(by `php --ri swoole`)
| PHP version         | 7.2 (by `php -v`)
| Runtime environment | CentOS 7.

**Details**
按照函数说明, 无法正确订阅
$state = $this->redis->subscribe('join_auction_dg','subscribe_test');
        echo "当前订阅: \n";
        print_r($state);

订阅结果:
Array
(
    [0] => subscribe
    [1] => subscribe_test
    [2] => 2
)

尝试
$state = $this->redis->subscribe(array('join_auction_dg'),'subscribe_test');
Array to string conversion in /www/vendor/swoft/redis/src/Operator/Processor/PrefixProcessor.php on line 252

**Comment by cailetech** [comment]
public function join_auction_dg($instance, $channelName, $message){
        echo $channelName, "==>", $message,PHP_EOL;
    }

public function subscribe_test($instance, $channelName, $message){
        echo $channelName, "==>", $message,PHP_EOL;
    }

几种都尝试过，在redis上订阅的命令可以收到返回结果，在swoft内，无法收到任何订阅信息

**Comment by 18355533677** [comment]
你后来是怎么解决得

**Comment by 18355533677** [comment]
> public function join_auction_dg($instance, $channelName, $message){
> echo $channelName, "==>", $message,PHP_EOL;
> }
> 
> public function subscribe_test($instance, $channelName, $message){
> echo $channelName, "==>", $message,PHP_EOL;
> }
> 
> 几种都尝试过，在redis上订阅的命令可以收到返回结果，在swoft内，无法收到任何订阅信息

你后来是怎么解决的
