### ISSUE TITLE
task异步任务redis问题

### ISSUE THREAD

**Issue by wzzq** [swoft-cloud/swoft#475]
异步任务中，调用有关redis的方法没有作用，官方的demo也跑不通

**Comment by Longjianghu** [comment]
你的redis环境是否正常？

**Comment by wzzq** [comment]
@Longjianghu redis环境正常，问题只出现在异步任务中，其他场景redis可以正常使用

**Comment by limingxinleo** [comment]
有什么报错的信息没

**Comment by wzzq** [comment]
没有错误信息，就是在调用redis的时候会强制进入taskfinsh监听中

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
