### ISSUE TITLE
swoft怎么引入外部文件使其生效？

### ISSUE THREAD

**Issue by 372620040** [swoft-cloud/swoft#477]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
refer https://github.com/swoft-cloud/swoft/issues/462
