### ISSUE TITLE
验证器不存在，beanName=DbJsonValidator

### ISSUE THREAD

**Issue by alukaa** [swoft-cloud/swoft#478]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      | 4.0.1
| PHP version         | 7.2.8
| Runtime environment | Docker

**Details**
数据库字段如下:
![image](https://user-images.githubusercontent.com/8164389/49577119-b5bd9c80-f981-11e8-965c-1712d4c8d9d0.png)
操作如下:
![image](https://user-images.githubusercontent.com/8164389/49577170-cd952080-f981-11e8-968d-ce980daa33bc.png)
日志如下:
![image](https://user-images.githubusercontent.com/8164389/49577189-d84fb580-f981-11e8-9cfc-1f4b3f2bdcaa.png)

不支持json类型哇
![image](https://user-images.githubusercontent.com/8164389/49577257-ff0dec00-f981-11e8-981a-2723f93323c9.png)
我只能这样额
```
 Db::query('DELETE FROM admin WHERE id=?', [$id]);
```

**Comment by limingxinleo** [comment]
Db验证器这里确实少一些，你可以自己写一个对应的bean，就可以了

**Comment by alukaa** [comment]
都有问题，我更新json字段的时候也有问题

**Comment by alukaa** [comment]
@limingxinleo 简单的加个Bean肯定是不行的，
![image](https://user-images.githubusercontent.com/8164389/49694800-b77aa080-fbcb-11e8-88be-abcd997397af.png)
这里会把entity所有的字段搞出来作为where 条件，那么问题来了，当把json 字段作为where 条件时，查询不到任何数据，删不掉的
@inhere 我有个建议，能不能再$entity->delete()的时候传递了参数，意思是哪些字段可以作为删除时的where条件，而不是把entity的全部字段取出来，或者有什么更好的方法

**Comment by alukaa** [comment]
自己写一个是可以的，写了一个json validator,更新没问题，删除的时候还是存在这个问题，所有的字段都在where 条件中，查不出数据来，只能Db::query进行删除。
问题倒是不大，只是不够完善

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
