### ISSUE TITLE
swoft不同请求存在很大的缓存

### ISSUE THREAD

**Issue by studyzhanglei** [swoft-cloud/swoft#479]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no no
| Feature request?    | yes/no yes
| Swoft version       | 1.0.0
| Swoole version      | 4.2.5
| PHP version         | 7.2.11
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
比如一个进程内，我可能要多次获取某数据，我可能会写成以下的形式，代码在下面；
但是我直接改了缓存的数据，发现获取到的数据并没有发生改变，类似的写法会存在很大的缓存吗？或者在其他用户的请求中也能使用到这类数据？
> Describe what you are trying to achieve and what goes wrong.

```php
/**
     * 获取当前活动缓存相关数据
     */
    public function getCurrentData() :?array
    {
         if (!$this->currentData) {
            $this->currentData = $this->getBasicService()->getDataFromCache($this->getActivityId());
         }
        return $this->currentData;
    }
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
一个请求里用可以放到 requestContext 里。
这个类上面有 注解的话 class只会new一次。后面一直用的同一个对象

**Comment by studyzhanglei** [comment]
因为之前都是这么写的，确实没有注意到，这个必须得全局改掉这些写法吗？

**Comment by limingxinleo** [comment]
常驻内存的情况下不能这么用。。给你一个我写的例子。

https://github.com/limingxinleo/swoft-trait-instance

**Comment by studyzhanglei** [comment]
好的  多谢两位大佬解惑，一路过来老是踩坑😭
