### ISSUE TITLE
App\Boot 下的Process里面，怎么去注册一个 Logic 啊？

### ISSUE THREAD

**Issue by jiaxinyin** [swoft-cloud/swoft#480]
/**
     * @Inject()
     *
     * @var PromotionOrderLogic
     */
    private $promotionOrderLogic;

添加了这个之后，报错：
Fatal error: Uncaught InvalidArgumentException: Bean App\Models\Logic\PromotionOrderLogic not exist in /data/web/soa-promotion/vendor/swoft/framework/src/Bean/Container.php:75
Stack trace:

我在app.php 里面
return [
    'env'          => env('APP_ENV', 'test'),
    'debug'        => env('APP_DEBUG', false),
    'version'      => '1.0',
    'autoInitBean' => true,
    'bootScan'     => [
        'App\Models',
        'App\Commands',
        'App\Boot',
    ],
bootScan 注册了models，继续报错

Fatal error: Uncaught InvalidArgumentException: Bean App_Lib_DemoInterface_25d9d808afc4a00f13c080a8e3a3ef13 not exist in /data/web/soa-promotion/vendor/swoft/framework/src/Bean/Container.php:75

**Comment by crack007** [comment]
PromotionOrderLogic类需要增加bean注解

**Comment by limingxinleo** [comment]
Boot下的类的实例化时机与其他的不同。

所以你需要在业务代码那里使用bean方法来拿对象
