### ISSUE TITLE
There is no active transaction

### ISSUE THREAD

**Issue by Longjianghu** [swoft-cloud/swoft#482]
运行环境：

swoft: 1.0.0, php: 7.2.10, swoole: 4.2.9

**Details**

> rollback报下在的错误

```php
PHP Fatal error:  Uncaught PDOException: There is no active transaction in /data/vendor/swoft/db/src/Driver/Mysql/SyncMysqlConnection.php:198
Stack trace:
#0 /data/vendor/swoft/db/src/Driver/Mysql/SyncMysqlConnection.php(198): PDO->rollBack()
#1 /data/vendor/swoft/db/src/Event/Listeners/ResourceReleaseBeforeListener.php(54): Swoft\Db\Driver\Mysql\SyncMysqlConnection->rollback()
#2 /data/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Db\Event\Listeners\ResourceReleaseBeforeListener->handle(Object(Swoft\Event\Event))
#3 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Db\Event\Listeners\ResourceReleaseBeforeListener), 'handle', Array)
#4 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(8): Swoft\Proxy\Handler\AopHandler->invoke('handle', Array)
#5 /data/vendor/swoft/framework/src/Event/EventManager.php(326): ResourceReleaseBeforeListener_5c0e0cbcd0d87->handle(Object(Swoft\Event\Event))
#6 /data/vendor/swoft/framework/src/Event/EventManager.php(260): Swo in /data/vendor/swoft/db/src/Driver/Mysql/SyncMysqlConnection.php on line 198
```

**Comment by huangzhhui** [comment]
请提供一下composer.lock下所有Swoft组件的实际安装版本

**Comment by Longjianghu** [comment]
附件是部分代码和composer.lock文件内容
[workerprocess.txt](https://github.com/swoft-cloud/swoft/files/2665649/workerprocess.txt)

**Comment by Longjianghu** [comment]
在更新的时候还报了下面的错误

`#0 /data/vendor/swoft/framework/src/Aop/Aop.php(57): App\Models\Logic\DingTalkLogic->updateDingTalkUser('{"user_id":"030...')
#1 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(App\Models\Logic\DingTalkLogic), 'updateDingTalkU...', Array)
#2 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(17): Swoft\Proxy\Handler\AopHandler->invoke('updateDingTalkU...', Array)
#3 /data/app/Tasks/DingTalkTask.php(52): DingTalkLogic_5c0f409e280d9->updateDingTalkUser('{"user_id":"030...')
#4 /data/vendor/swoft/framework/src/Aop/Aop.php(57): App\Tasks\DingTalkTask->dingTalkUser('{"user_id":"030...')
#5 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(App\Tasks\DingTalkTask), 'dingTalkUser', Array)
#6 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(11): Swoft\Proxy\Handler\AopHandler->invoke('dingTalkUser', Array)
#7 /data/vendor/swoft/framework/src/Helper/PhpHelper.php(47): DingTalkTask_5c0f409e360cb->dingTalkUser('{"user_id":"030...')
#8 /data/vendor/swoft/task/src/TaskExecutor.php(70): Swoft\Helper\PhpHelper::call(Array, Array)
#9 /data/vendor/swoft/task/src/TaskExecutor.php(50): Swoft\Task\TaskExecutor->runSyncTask(Object(DingTalkTask_5c0f409e360cb), 'dingTalkUser', Array, '', 0, 'dingTalk', 'async')
#10 /data/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Task\TaskExecutor->run(Array)
#11 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Task\TaskExecutor), 'run', Array)
#12 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(8): Swoft\Proxy\Handler\AopHandler->invoke('run', Array)
#13 /data/vendor/swoft/task/src/Bootstrap/Listeners/TaskEventListener.php(43): TaskExecutor_5c0f409e47834->run('a:6:{s:4:"name"...')
#14 /data/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Task\Bootstrap\Listeners\TaskEventListener->onTask(Object(Swoole\Http\Server), 2446, 0, 'a:6:{s:4:"name"...')
#15 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Task\Bootstrap\Listeners\TaskEventListener), 'onTask', Array)
#16 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(11): Swoft\Proxy\Handler\AopHandler->invoke('onTask', Array)
#17 [internal function]: TaskEventListener_5c0f4078a1565->onTask(Object(Swoole\Http\Server), 2446, 0, 'a:6:{s:4:"name"...')
#18 /data/vendor/swoft/http-server/src/Http/HttpServer.php(55): Swoole\Server->start()
#19 /data/vendor/swoft/http-server/src/Command/ServerCommand.php(74): Swoft\Http\Server\Http\HttpServer->start()
#20 /data/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Http\Server\Command\ServerCommand->start()
#21 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Http\Server\Command\ServerCommand), 'start', Array)
#22 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(8): Swoft\Proxy\Handler\AopHandler->invoke('start', Array)
#23 /data/vendor/swoft/framework/src/Helper/PhpHelper.php(47): ServerCommand_5c0f4078a089f->start()
#24 /data/vendor/swoft/console/src/Router/HandlerAdapter.php(112): Swoft\Helper\PhpHelper::call(Array, Array)
#25 /data/vendor/swoft/console/src/Router/HandlerAdapter.php(38): Swoft\Console\Router\HandlerAdapter->executeCommand(Object(ServerCommand_5c0f4078a089f), 'start', true, Array)
#26 /data/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Console\Router\HandlerAdapter->doHandler(Array)
#27 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Console\Router\HandlerAdapter), 'doHandler', Array)
#28 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(8): Swoft\Proxy\Handler\AopHandler->invoke('doHandler', Array)
#29 /data/vendor/swoft/console/src/Command.php(77): HandlerAdapter_5c0f4078a02a7->doHandler(Array)
#30 /data/vendor/swoft/framework/src/Aop/Aop.php(57): Swoft\Console\Command->run()
#31 /data/vendor/swoft/framework/src/Proxy/Handler/AopHandler.php(43): Swoft\Aop\Aop->execute(Object(Swoft\Console\Command), 'run', Array)
#32 /data/vendor/swoft/framework/src/Proxy/Proxy.php(44) : eval()'d code(11): Swoft\Proxy\Handler\AopHandler->invoke('run', Array)
#33 /data/vendor/swoft/console/src/Console.php(30): Command_5c0f4078a01cd->run()
#34 /data/bin/swoft(5): Swoft\Console\Console->run()
#35 {main}"
}
PHP Warning:  Swoole\Server::start(): task[0] has expired. in /data/vendor/swoft/http-server/src/Http/HttpServer.php on line 55`

**Comment by mrchenzifan** [comment]
@Longjianghu  我也是偶尔遇到
