### ISSUE TITLE
引入 TP validator

### ISSUE THREAD

**Issue by daydaygo** [swoft-cloud/swoft#485]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.0
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | docker
**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by wujunze** [comment]
建议引入 https://github.com/vlucas/valitron   0依赖 简洁 好用
