### ISSUE TITLE
consul负载均衡，永远都命中一台机器上，发现服务器列表数组获取只有一台

### ISSUE THREAD

**Issue by jxy918** [swoft-cloud/swoft#489]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 4.2.6
| Swoole version      | 4.2.6
| PHP version         | 7.1.18
| Runtime environment | CentOS 7

**Details**

> 搭建consul负载均衡，启用consul用的都是一台机器，启用两套游戏服务器，端口不一样，使用注册发现，注册发现配置方法说明：name配置一样， id和tags配置不一样， 通过name获取到连个tag的服务器ip和端口

查看php代码路径：vendor/swoft/service-governance/src/Provider/ConsulProvider.php 第255行

请求服务器列表的时候拼cunsul的url的时候key使用tag， 发现tag只能一台， 修改tags可以获取到多台列表。

```php
    /**
     * @param string $serviceName
     *
     * @return string
     */
    private function getDiscoveryUrl(string $serviceName): string
    {
        $query = [
            'passing' => $this->discoveryPassing,
            'dc'      => $this->discoveryDc,
            'near'    => $this->discoveryNear,
        ];

        if (!empty($this->discoveryTag)) {
            $query['tag'] = $this->discoveryTag;
        }

        $queryStr    = http_build_query($query);
        $path        = sprintf('%s%s', self::DISCOVERY_PATH, $serviceName);

        return sprintf('%s:%d%s?%s', $this->address, $this->port, $path, $queryStr);
    }
```

> 修改代码如下：可以实现了负载均衡了

```php
 if (!empty($this->discoveryTag)) {
            $query['tags'] = $this->discoveryTag;
        }
```

**Comment by jxy918** [comment]
http://192.168.7.197:8500/v1/health/service/notify?passing=1&dc=dc1&near=&tag=notify
consul 这样只能获取单个tag，不能实现负载均衡
http://192.168.7.197:8500/v1/health/service/notify?passing=1&dc=dc1&near=&tags=notify
consul 修改成tags 后面tag就没用了， 会找到同名的tag，这样就能拿到服务器列表

**Comment by jxy918** [comment]
我的理解问题， 配置没理解， 负载均衡不配置那个tag就可以

**Comment by inhere** [comment]
@jxy918 可以帮忙改进下文档啊 :) 😄

**Comment by jxy918** [comment]
已经提交文档pr，请审核并合并通过

**Comment by jxy918** [comment]
> @jxy918 可以帮忙改进下文档啊 :)

已经提交文档pr，请审核并合并通过

**Comment by jxy918** [comment]
> @inhere 已经提交文档pr，请审核并合并通过

**Comment by wujunze** [comment]
已经 merge  Thanks @jxy918
