### ISSUE TITLE
在homestead中同步的项目自动重载不能使用

### ISSUE THREAD

**Issue by hooklife** [swoft-cloud/swoft#49]
我把homestead 的 项目目录 和 本机的 项目目录进行同步

我在本机进行修改项目目录里的文件，自动重载不能正常进行，但是ssh到homestead中修改可以正常重载。

**Comment by inhere** [comment]
你是 Windows？

**Comment by hooklife** [comment]
@inhere 不是windows  是deepin， 不知道你了解不了解vagrant，vagrant同步的文件夹，Inotify 好像是监视不到。

**Comment by inhere** [comment]
在docker之前，使用过vagrant 在Windows下用docker挂载的也没法监控到
