### ISSUE TITLE
除了原生sql，where条件如何使用find_in_set这种函数

### ISSUE THREAD

**Issue by PeterYangs** [swoft-cloud/swoft#490]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
如题
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by PeterYangs** [comment]
各位大佬，有没有知道的啊

**Comment by minxinqing** [comment]
找了一圈，没发现findAll方法的$condition参数怎么支持 find_in_set

**Comment by PeterYangs** [comment]
> 找了一圈，没发现findAll方法的$condition参数怎么支持 find_in_set

我用 Db::query();简单封装了一个模型类

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布

**Comment by hpc-code** [comment]
$model = $model->whereRaw("FIND_IN_SET('{$platform,`platform`)");
