### ISSUE TITLE
Task长时间运行内存回收问题

### ISSUE THREAD

**Issue by AaronWB** [swoft-cloud/swoft#491]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    |no
| Runtime environment |Mac

**Details**
报错
···
PHP Warning:  Swoole\Table::set(): unable to allocate memory.in /vendor/swoft/task/src/Crontab/Crontab.php on line 245
···

**Comment by Longjianghu** [comment]
这个问题我也遇到了

**Comment by zhana0** [comment]
我也遇到这个问题了，有解决办吧了吗？

**Comment by AaronWB** [comment]
> 我也遇到这个问题了，有解决办吧了吗？

已放弃
