### ISSUE TITLE
怎么一对多查询或者多对一查询？

### ISSUE THREAD

**Issue by 191834552** [swoft-cloud/swoft#493]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      |2.2.0
| PHP version         |7.1.2
| Runtime environment | Ubuntu

**Details**

> 怎么进行一对多或者多对一查询啊，能否像laravel那样使用with进行查询啊？

**Comment by AaronWB** [comment]
连接

**Comment by Longjianghu** [comment]
我这边全部用的原生sql，这个更灵活。

**Comment by sakuraovq** [comment]
2.0 后续会支持模型关联
