### ISSUE TITLE
跨机器服务调用，返回数据问题

### ISSUE THREAD

**Issue by AaronWB** [swoft-cloud/swoft#494]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no

| Runtime environment | MAC OS, UBUNTU 17
**Details**
服务返回长数据无法接收，报错如下
```
InvalidArgumentException 
json_decode error: Control character error, possibly incorrectly encoded
```
，并且返回的数据被截断。

**Comment by inhere** [comment]
你配置下 length 啊

**Comment by AaronWB** [comment]
> 你配置下 length 啊

配置了，已经配置到很大了
