### ISSUE TITLE
swoft 2.0 开发意见收集

### ISSUE THREAD

**Issue by inhere** [swoft-cloud/swoft#498]
# swoft 2.0 开发意见收集

鉴于1.0的规划过于庞大，一些组件其实很少人使用，开发团队感觉维护困难。

决定开发2.0:

- 全协程化: swoole 4.3+, php 7.1+
- 重心调整：核心团队首先专注基础框架和核心组件的开发维护
- 其他组件的重心放低，鼓励社区和感兴趣的人开发维护
- 有更充足的时间编写单元测试和相关文档

## 这里做一些意见收集

- 那些是你认为的核心组件？
- 在使用中有哪些不足或者没有你希望的效果？
- 对一些核心功能，希望怎么改进？或有什么建议？

**去除的功能：**

- `auto reload` 极大的增加了框架启动逻辑复杂度
- `defer`(getResult) 很少人使用
- 框架核心，不再提供服务注册和发现这一套（**待定**）。
- 不再提供redis 前缀支持
- 不再提供定时任务(分布式任务系统扩展)
- 不再提供session支持

**需改进的功能：**

- 注解扫描将会重构
- 改进和简化组件的注册
- 验证将会重构，简化使用 (@jqcool )
- 路由将会改进: 支持命名路由
- 关于开发时自动重启：提供一个 `swoft-cli` 它来监控项目变动，发送重启信号
- 数据库ORM大体会和laravel使用一样
- rpc 协议支持适配器，默认提供 jsonrpc 适配器,用户可以根据接口实现自己需要的协议 (@herojhc )
- config 支持常用的配置格式(yaml json)
- bean的注册和收集将会做一些调整
  - 增加支持别名
  - 数组方式配置支持添加bean选项（支持别名，作用域设置）
- 提供测试辅助工具库 更方便编写单元测试
- 异常处理优化

**新增的功能：**

- 进程池的封装
- 迁移脚本

**Comment by inhere** [comment]
## 2.0 目标

- 全协程，核心化，易扩展，简洁易用。
- 支持swoole 4+, php 7.1+
- **> 90%** 的单元覆盖率

## 核心组件

- 注解
- AOP
- 事件
- HTTP server(路由，中间件)
- WebSocket server
- RPC server

**Comment by dusong0717** [comment]
mongodb 驱动支持，消息队列支持：kafka、rabbitmq、beanstalk等
另外demo希望更加完善一些，便于上手开发降低学习成本。

**Comment by inhere** [comment]
> mongodb 驱动支持，消息队列支持：kafka、rabbitmq、beanstalk等
> 另外demo希望更加完善一些，便于上手开发降低学习成本。

- mongodb 要看swoole的支持
- 消息队列 这些将不在核心组件中，有需要的可以自己扩展。

**Comment by jqcool** [comment]
建议完善中间件，可参考下laravel的，路由可设定参数，中间件可获取
优化验证机制，现有的验证感觉好鸡肋，开发效率相当的低

**Comment by deepziyu** [comment]
土壤原因，我觉得成为 spring-cloud 那样的生态是不现实的，

**Comment by 191834552** [comment]
希望整合laravel的orm系统

**Comment by stelin** [comment]
@deepziyu 是的，我们也意思到这个问题，所有重构2.0

**Comment by jqcool** [comment]
> 土壤原因，我觉得成为 spring-cloud 那样的生态是不现实的，

这个很有道理，php的特性就是方便快捷，spring-cloud的生态不适phper，适合java转型的

**Comment by inhere** [comment]
> 建议完善中间件，可参考下laravel的，路由可设定参数，中间件可获取
> 优化验证机制，现有的验证感觉好鸡肋，开发效率相当的低

- 这个是支持的 `路由可设定参数，中间件可获取`
- 验证之前做的很匆忙，这次会重新调整

**Comment by herojhc** [comment]
希望把RPC server 完善下，尤其是 错误处理。

**Comment by yemaozi999** [comment]
demo希望更加完善一些，便于上手开发降低学习成本。

**Comment by manaphp** [comment]
manaphp的ORM更强大，使用Query与Model兼容mongodb与sql

**Comment by chenjing0521** [comment]
希望文档能完善一些 最好把你们自己写的测试demo发一套代码出来

**Comment by inhere** [comment]
> 希望文档能完善一些 最好把你们自己写的测试demo发一套代码出来

现在 swoft 项目就是一个完整的demo 我们的测试也是用的它，还有些功能测试代码 就在各个组件的 test 目录下

**Comment by jqhph** [comment]
服务注册和发现希望能继续支持并完善。php微服务化还不成熟，大多数phper对rpc也不熟悉，如果仅仅只提供rpc的server和client的通讯功能，那想使用rpc就会困难很多了。rpc通讯很多框架早就提供了，这一块并不是难点，如果swoft能提供一套稳定完善的rpc微服务解决方案，那才是优势所在。

另外希望增加以下rpc service的exception handler支持。

**Comment by jqhph** [comment]
易扩展和简洁易用在1.0就做得不是很好，我觉得最主要是体现在bean容器，orm和扩展swoft组件上，希望2.0能着重优化下。
swoft bean容器是在服务启动之时就注入好的，但是这么做就有个坑爹的地方了：如果我是需要在服务启动之时做一些操作，就会发现有些bean容器里面的对象（包括官方的和自定义的）用不了！！而且通过数组方式注册服务到bean容器的时候是强制使用单例的！而且注册服务到bean容器不能像laravel那样在注册之时带一些逻辑。
还有就是custom.component这个功能有问题，配置了注解文件的命名空间也不一定能扫描到

**Comment by yangguangwuwu** [comment]
希望模仿laravel的orm系统 方法 用法一样也行

**Comment by solarhell** [comment]
创建项目可以选择自己希望的特性，比如不需要微服务？ 配置文件希望也能明确一点，现在不看源码基本不知道哪些最后的配置文件是什么样子。（可以在应用运行后生成最终的配置文件？）

**Comment by inhere** [comment]
> 创建项目可以选择自己希望的特性，比如不需要微服务？ 配置文件希望也能明确一点，现在不看源码基本不知道哪些最后的配置文件是什么样子。（可以在应用运行后生成最终的配置文件？）

- 后面会简化配置。
- 创建项目后面会调整，提供几个通用的服务模板项目
- 另外最后的配置可以通过 devtools 看到的

**Comment by herojhc** [comment]
环境变量配置现在已经很方便了，尤其是像docker、k8s 这样的容器部署，有一点就是希望配置文件能分环境（不改变config文件），类似laravel的 .env 和 .env.production  这样一些非敏感信息 可以通过git 提交到代码库，部署的时候不用再配置环境变量。

**Comment by adotpeng** [comment]
### 建议的核心组件

- 常见协议的 server，接口留出，允许自定义其他应用协议
- db，AR 参考 Yii2，AR 中常用的操作要丰富
- cache，接口要给出，常见的，例如 redis 实现一个，其他的依据接口自行扩展
- devtool，脚手架更丰富些，涉及常见操作
- jwt，既然不要 session
- view，模板引擎适配器留出，自行接入常见模板引擎
- http-message
- i18n
- memory
- task
- swagger
- router，除了注解路由也支持自定义路由和路由

### 建议改进的

1. 及时更新文档
2. 丰富的 demo，能用 demo 说明白的，不写字
3. 提高 pr 进入新版本的速度
4. 真正可以一键打包 phar

**Comment by inhere** [comment]
@adotpeng 

- 这次去除一些非核心的组件，更有精力专注核心文档。非核心的组件文档靠维护者和社区贡献
- PR 合并速度受这个PR的代码影响。代码牵扯到较多的逻辑就会慢一些
- demo 会尽量提供。也需要用户贡献才能丰富，有些我们不一定能想到
- phar 打包一直都提供了的，只是有些兼容问题。这个看情况，因为并未听到有多少人用。

**Comment by jqhph** [comment]
> @jqhph bean对象用不了 指的是？

比如beforeStart事件中有些注册bean容器的对象就用不了，

**Comment by jlzan1314** [comment]
重启加载的时候,能不能变快点,有的东西compose 目录不需要多次扫描的,开发的时候有时候调试,修修改改很正常..每次等10s以上,好麻烦,尽量扫描的快些,,5秒内最好

**Comment by yaowenqiang** [comment]
参考laravel,yii,symfony做一个debug bar,可以极大的方便开发和调试

**Comment by 191834552** [comment]
> 参考laravel,yii,symfony做一个debug bar,可以极大的方便开发和调试

对，SQL报错，也不提示。找个错误好难

**Comment by jxy918** [comment]
希望tcp协议支持多种数据格式传输， 支持msgpack，protobuf，这两种格式对游戏开发生态比较好

**Comment by simapple** [comment]
不提供session 支持？是否提供其他类型的会话权限认证？

**Comment by hidahua** [comment]
建议：
1，期望有zf2框架相似的模块化部署结构；
2，mongodb连接池，如同mysql连接池实现；

**Comment by 13193310336** [comment]
路由。路由。路由呀。要支持自定义呀

**Comment by tw2066** [comment]
希望2.0的组件能解构;能做到其他框架composer引入可以直接使用

**Comment by cgyhbc** [comment]
能支持http的chunk吗，不分片的吗，大文件无法下载。

**Comment by 13193310336** [comment]
> > 路由。路由。路由呀。要支持自定义呀
> 
> 怎么自定义？详细说明下

文件自定义路由，类似laravel那样，可以考虑分路由模式或者做下兼容

**Comment by xiangjihan** [comment]
我觉得 应该把swoft完全做成一个php的应用容器，然后就是加载各种组件的事了。哪怕组价有问题，也不要把应用容器搞挂了。

**Comment by tanpeng** [comment]
常用的Tcp、Upd server更好的支持~
服务启动速度能进一步优化就更好了
其他上述其他道友也基本都提到了

**Comment by xiaotianhu** [comment]
还是希望核心组件能包含队列
这个太常用了.第三方实现不是很靠谱 与框架集成配合不完美很容易不好用

**Comment by DavidYanXW** [comment]
建议：
抽取出基础的依赖库，可供swoft本身、其它流行框架共用
目前，对于rpc的需求还是很强烈的。

**Comment by amuluowin** [comment]
1.建议依赖注入支持注解，配置，autowire多种方式，方便引入其他包和组件，也方便swoft的包和组件能简单注入其他框架。
2.抽象qb和ar的接口，方便后续对接各种db的时候有统一的调用方式，可以参考yii2。

**Comment by tw2066** [comment]
注解:希望多给一点例子和**原理讲解** , 降低入门门槛 ; 基本没有php框架用注解功能

**Comment by cheerego** [comment]
什么时候开始，代码在哪里？

**Comment by inhere** [comment]
先收集意见，下周估计开始规划

**Comment by yanwuguangjun** [comment]
有这么几个想法：

1. 希望能从现今的版本比较平滑的迁移到2.0版本；

2.数据库ORM方面希望能够增加对json 类型的支持；

3.能够更好的处理生命周期逻辑（其实现在也已经很好了，可能是文档没吃透）

4.注解的类提示上可以再友好点（原谅技术太渣很多东西只能靠提示来弥补）

**Comment by inhere** [comment]
@yanwuguangjun 我在这再回复下 :)

1. 平滑迁移的可能性不大，2.0 出来后，看情况
2. 这到得看时间了... 有兴趣的话，可以贡献
3. 有啥发现的问题，可以向我们提
4. 类提示靠的是IDE插件 😄

**Comment by xnnyeYp** [comment]
希望能够支持mongodb协程客户端，类似mysql

**Comment by wslinging** [comment]
希望重点优化mysql数据库还有redis在协程下的使用体验。这是我最希望有的改进

**Comment by inhere** [comment]
> 希望能够支持mongodb协程客户端，类似mysql。还有就是我们公司在使用过程中发现，水平较为初级的开发者认为文档较为难懂，不是很详细，个人认为文档如果能更易懂详细的话，更利于框架的推广吧

有些文档使用，我们没发站到使用者的角度或者没想到。需要使用者帮忙贡献下，使用中的注意 文档补充

**Comment by AoeSyL** [comment]
希望增加对log的优化
mongo的支持
还有队列呀 队列
注解的文档 如果可以的话 能完善下 就更好啦~~~

**Comment by mlsjla** [comment]
swoft-cli生成项目，建议可以替换swoft关键词，可以由开发者自定义关键词。并非不尊重版权云云，是希望swoft更加开放。

如我们开发商业产品，如产品源码大量出现swoft关键词对商业产品有不好影响。
这点beego之类框架做得很好都做得不错

**Comment by inhere** [comment]
> swoft-cli生成项目，建议可以替换swoft关键词，可以由开发者自定义关键词。并非不尊重版权云云，是希望swoft更加开放。
> 
> 如我们开发商业产品，如产品源码大量出现swoft关键词对商业产品有不好影响。
> 这点beego之类框架做得很好都做得不错

没明白，你是说 `swoft-cli` 这个名字吗？ 还是说框架的代码里有Swoft关键字？

- `swoft-cli` 只是个包名，工具名。就像 `vue-cli` 一样
- 至于用Swoft开发的项目，里面的代码 Swoft并没有任何限制

**Comment by mlsjla** [comment]
@inhere 

实际上依赖文件内swoft关键词没啥。

如下启动脚本关键词对于开发商业软件还是介意的。
当然也可以自己麻烦下去改， 不过还是希望swoft-cli创建项目的时候本身就集成了修改的功能

// Start HTTP Server
php bin/swoft start

// Start Daemonize HTTP Server
php bin/swoft start -d

// Restart HTTP server
php bin/swoft restart

// Reload HTTP server
php bin/swoft reload

// Stop HTTP server
php bin/swoft stop

**Comment by inhere** [comment]
`bin/swoft` 这个吗？ 只是个入口文件 你可以随便命名的

**Comment by tw2066** [comment]
> > 最近使用swoft1.0 , ab压力测试了一下,性能和其他swoole框架比较起来, 相差较大; 希望在2.0 能对性能方面有提高
> 
> 能具体说明下对比的框架是哪个么?

使用vm虚拟机测试:配置1核1G swoole=4.2.10  worker_num=1
测试命令:ab -n 10000 -c 1000  url
**easyswoole 3.0.9**:
Benchmarking 192.168.22.134 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        EasySwoole
Server Hostname:        192.168.22.134
Server Port:            9501

Document Path:          /test
Document Length:        21 bytes

Concurrency Level:      1000
Time taken for tests:   4.516 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      1690000 bytes
HTML transferred:       210000 bytes
Requests per second:    2214.50 [#/sec] (mean)
Time per request:       451.570 [ms] (mean)
Time per request:       0.452 [ms] (mean, across all concurrent requests)
Transfer rate:          365.48 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.8      0       8
Processing:   241  426  55.8    439     513
Waiting:      156  415  64.0    431     510
Total:        241  426  55.9    440     513
**swoft1.0.8**:(关闭日志,命令行输出)
Benchmarking 192.168.22.134 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        swoole-http-server
Server Hostname:        192.168.22.134
Server Port:            9988

Document Path:          /hi/index
Document Length:        5 bytes

Concurrency Level:      1000
Time taken for tests:   6.734 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      2240000 bytes
HTML transferred:       50000 bytes
Requests per second:    1484.95 [#/sec] (mean)
Time per request:       673.426 [ms] (mean)
Time per request:       0.673 [ms] (mean, across all concurrent requests)
Transfer rate:          324.83 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   1.0      0       8
Processing:    51  657 152.3    680     850
Waiting:       51  518 137.8    530     831
Total:         52  658 152.4    681     851
WARNING: The median and mean for the initial connection time are not within a normal deviation
        These results are probably not that reliable.

Percentage of the requests served within a certain time (ms)
  50%    681
  66%    733
  75%    750
  80%    761
  90%    792
  95%    835
  98%    846
  99%    847
 100%    851 (longest request)

**mixphp**:
Benchmarking 192.168.22.134 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        swoole-http-server
Server Hostname:        192.168.22.134
Server Port:            9966

Document Path:          /
Document Length:        29 bytes

Concurrency Level:      1000
Time taken for tests:   3.355 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      1990000 bytes
HTML transferred:       290000 bytes
Requests per second:    2980.58 [#/sec] (mean)
Time per request:       335.505 [ms] (mean)
Time per request:       0.336 [ms] (mean, across all concurrent requests)
Transfer rate:          579.23 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.6      0       6
Processing:    89  317  55.7    319     421
Waiting:       89  275  55.0    278     416
Total:         89  317  55.8    319     421

Percentage of the requests served within a certain time (ms)
  50%    319
  66%    337
  75%    351
  80%    357
  90%    368
  95%    394
  98%    406
  99%    412
 100%    421 (longest request)

**Comment by mlsjla** [comment]
我本机测试了下， mac15款 I5+8G内存， 开了一堆程序。

swoole原生测试8000Requests per secon

easyswoole 测试大概是5000
swoft  测试4000多

以上测试都是hello测试  AB测试

**Comment by tanpeng** [comment]
也简单ab压测了下easyswoole，swoft。关闭日志，debug，开启1个worker，仅输出hello world。
easyswoole：swoft 大概 1650：1200，有些差距。
但是喜欢swoft。所以，还是非常期待swoft 2.0的。 加油！！！

**Comment by studyzhanglei** [comment]
MongoDB连接池支持，github上开源的基本上很少～

**Comment by AmdRyZen** [comment]
> @tw2066 @mlsjla 2.0 会优化的，流程会理清晰后再做开发

其实应该是  简介化    性能优先   对比mixPHP 性能差的更多    使用swoole的 一般都是对新技术比较喜欢 切数据安全要求不高的项目   性能更有说服力。。。学swoft和学spring一样就没必要    有哪样的项目 也不会选择PHP   和 swoft框架   ，大部分公司负责人 都不敢把核心项目方在swoole上跑

**Comment by inhere** [comment]
@AmdRyZen  所以我们朝着这个方向努力啊，出一个能支撑大项目的框架

**Comment by tw2066** [comment]
@inhere 支持支持,期待2.0发布

**Comment by to2false** [comment]
配置部分：
- 一些组件默认env覆盖config配置项，不是很直观，可以将这个操作改成只从config文件里读取，config里通过env获取覆盖？

**Comment by jqhph** [comment]
> 对新技术比较喜欢 切数据安全要求不高的项目 性能更有说服力。。。学swoft和学spring一样就没必要 有哪样的项目 也不会选择PHP 和 swoft框架 ，大部分公司负责人 都不敢把核心项目方在swoole上跑

既然基于swoole性能方面就不需要太担心。框架稳定和易用这个是最最重要的，swoft应该着重在这方面下功夫。

**Comment by ixingjue** [comment]
希望swoft 2.0提供类似于php artisan vendor:publish 这种命令，便于发布vendor扩展包下的配置文件，比如我要使用devtool这个包时，可以通过发布配置文件到config目录，然后可以自定义配置文件，生成符合项目需求的配置文件。比如
![image](https://user-images.githubusercontent.com/25813184/50622086-ab250180-0f45-11e9-9f37-a4b9f55c9417.png)这种头文件信息，可以通过自定义配置文件配置。

**Comment by tanpeng** [comment]
希望swoft2.0连接池，能够支持多个负载服务地址，指定获取某个地址的连接功能。
需求其实主要是针对rpc这块，目前有些应用场景，对应多个rpc-server，希望能够定向分配一个server（比如用户登录成功后固定分配某一个server）。
目前1.0是按照连接池配置、服务写死的，有了这个功能，我想可以做到rpc-server动态上下线。

**Comment by sunnyos** [comment]
> 希望swoft 2.0提供类似于php artisan vendor:publish 这种命令，便于发布vendor扩展包下的配置文件，比如我要使用devtool这个包时，可以通过发布配置文件到config目录，然后可以自定义配置文件，生成符合项目需求的配置文件。比如
> ![image](https://user-images.githubusercontent.com/25813184/50622086-ab250180-0f45-11e9-9f37-a4b9f55c9417.png)这种头文件信息，可以通过自定义配置文件配置。

目前这部分可以通过修改头配置文件实现，可以看一下：https://doc.swoft.org/master/zh-CN/devtool/gen-commands.html

**Comment by Super-Boom** [comment]
用ci用久了，发现这个有点难学，希望文档再详细一点，加油😊

**Comment by minbaby** [comment]
比较关心 `2.0` 是否是一个不兼容更新，如果是，那么会提供详细的升级说明

**Comment by alukaa** [comment]
我觉得http server 部分舍弃view部分，只提供api接口功能就够了

**Comment by inhere** [comment]
> 我觉得http server 部分舍弃view部分，只提供api接口功能就够了

嗯 view 一直是可选的

**Comment by inhere** [comment]
> 比较关心 `2.0` 是否是一个不兼容更新，如果是，那么是否会提供详细的升级说明

这个到时要考虑下

**Comment by abnereel** [comment]
希望文档能丰富一些

**Comment by Lxido** [comment]
希望能更加安全和注意细节 97404667 邮箱97404667@qq.com 签名由 网易邮箱大师 定制 在2019年01月23日 17:21，拾年磨一剑 写道： 希望文档能丰富一些 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by shulinqian** [comment]
我能提个过分的需求么
强烈建议支持
https://github.com/alibaba/fescar
解决数据一致性一直很头痛。。。要撸巨多修复代码，能支持fescar或者GTS这种分布式事务框架就好了。微服务话才能轻松进行

**Comment by Yuebanfuxiao** [comment]
swoft中间件希望能够像laravel的中间件一样可以实现传参，现在的中间件实用性不高

**Comment by inhere** [comment]
> swoft中间件希望能够像laravel的中间件一样可以实现传参，现在的中间件实用性不高

传参 指的是提前new出中间件对象，设置一些东西吗？

**Comment by php-lsys** [comment]
为什么微核心,把所有的功能都组件化.

**Comment by php-lsys** [comment]
线程池管理跟线程池基类为什么要混在一块.

**Comment by php-lsys** [comment]
对于event log pipe pool proxy Validator 甚至APP都可以组件化.

**Comment by php-lsys** [comment]
极其讨厌 注解 方式写代码.
为什么不能像 symfony提供两种方式?

**Comment by inhere** [comment]
> 极其讨厌 注解 方式写代码.
> 为什么不能像 symfony提供两种方式?

工作量太大 😄 不喜欢注解可以用 easyswoole imi mixphp 等基于swoole的框架

**Comment by shanliu** [comment]
连接池可以抽离出来
连接池包
数据库连接池包
redis连接池包
....
按需在composer中引入 
默认框架可以引入部分
然后其他人有需要在不用这框架也可以引入使用

**Comment by to2false** [comment]
关于项目初始化提供的大量例子，我觉得全部移至文档或一个demo repo，保持初始化最简单

**Comment by inhere** [comment]
> 关于项目初始化提供的大量例子，我觉得全部移至文档或一个demo repo，保持初始化最简单

2.0 的初始化项目结构会保持最精简的 同时会提供一些含有其他demo的初始化repo

**Comment by leiyu1994** [comment]
![image](https://user-images.githubusercontent.com/25173933/54473737-d4e88780-4816-11e9-97a8-75dce6b66692.png)
是否考虑socket增加心跳机制和分组

**Comment by inhere** [comment]
这个配置是 swoole 就提供了的啊

**Comment by xxy123456** [comment]
swoole的timer中的一次和多次定时器需要支持下

**Comment by 995933447** [comment]
服务注册和发现那是必须得有啊 哈哈哈

**Comment by inhere** [comment]
> 服务注册和发现那是必须得有啊 哈哈哈

这个不再是必须的了 😄  现在 service mesh 这么火，他可以把这些都做了
后面可能会提供一些辅助类，帮助快速注册到 consul 之类的

**Comment by yelstr** [comment]
希望能增加依赖注入，配合注解使用还是很不错的。

**Comment by lackoxygen** [comment]
轻一点 然后需要即加载

**Comment by sowork** [comment]
有没有考虑过添加Requsts和Resources两层
Requests 专门做入参校验、比如类里面有属性，对应入参的值，在属性上可以添加注解进行校验，通过在controller具体的操作方法中用注解引入Requst 校验类 ，目前所有的字段添加到controller还是臃肿了

Resources 专门做出参格式化，从Logic获取数据后，通过Resource格式化为对应的格式输出

后期可以针对request和resource做一个api导出工具，既有入参又有出参

**Comment by inhere** [comment]
@sowork 是有想支持将验证的独立到一个类来做，这样对于一些字段较多的提交比较清晰

**Comment by sowork** [comment]
@inhere 是的，这是一个需求

如果能在其基础上扩充功能，比如根据入参属性生成文档，响应的时候，根据出参属性，自动返回给定的格式

**Comment by tanpeng** [comment]
> 希望swoft2.0连接池，配置中的多个负载地址，能够支持获取其中某个地址连接的功能。
> 需求其实主要是针对rpc这块，目前有些应用场景，对应多个rpc-server，希望能够定向分配一个server（比如用户登录成功后固定分配某一个server）。有些场景下的根据hash分库存储也可以用上。
> 目前1.0是按照连接池配置、服务写死的，有了这个功能，我想可以做到rpc-server动态上下线。

再确认下，这个2.0会支持么。

**Comment by stelin** [comment]
@tanpeng 你的原生需求是什么

**Comment by tanpeng** [comment]
> @tanpeng 你的原始需求是什么
@stelin 
![image](https://user-images.githubusercontent.com/2149695/55460170-d7731b80-5623-11e9-8005-907add54637d.png)

上图是1.0 连接池DB配置以及支持的形式（rpc也是一样的），支持配置多个地址进行负载。
主要需求是，希望能明确获取多个地址中指定的某一个；进一步的需求是，配置地址队列能动态增加或者摘除，这点不知道是否过份 (^.^)(^.^)。
因为现在多个地址，最大连接数等配置参数是共用的，某个地址最终建立多少连接是完全随机的，地址是否有效，也是不能动态去处理的。

**Comment by stelin** [comment]
@tanpeng 这个需求暂时不实现。

**Comment by hihozhou** [comment]
@stelin @inhere 大佬们，请问swoft2.0有预计发布日期吗

**Comment by to2false** [comment]
新版是否有改进env里关于开发环境又不同的处理策略
比如异常处理，env是prod和dev应该有不同的错误输出（prod隐藏错误细节，dev输出详情），或者设置APP_DEBUG开控制

**Comment by inhere** [comment]
> 新版是否有改进env里关于开发环境又不同的处理策略
> 比如异常处理，env是prod和dev应该有不同的错误输出（prod隐藏错误细节，dev输出详情），或者设置APP_DEBUG开控制

异常处理都在 app/exception 里, 你可以自己根据 APP_DEUBG 之类的来调整输出

**Comment by to2false** [comment]
@inhere 我现在是这么处理的，感觉这些细节框架初始化直接附带上是不是更好点

**Comment by inhere** [comment]
也是可以的，不过现在这样自定义性更高

直接附带 - 就是在我们发的demo里加上这个判断就行了 😄

**Comment by to2false** [comment]
db这边的语法错误提示
比如
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'xxx' in 'where clause' file=/vendor/swoft/db/src/Driver/Mysql/SyncMysqlConnection.php line=85
```
这样的提示如果能补全到发生在哪个dao的具体位置会不会更好

**Comment by scguang301** [comment]
希望orm部分考虑分库分表，可以有一些比较简单的使用

**Comment by inhere** [comment]
快速切换DB会提供。分表就不会实现了。。。

**Comment by huxiaoguang** [comment]
定时任务用的相当多，去掉是为什么呀

**Comment by hihozhou** [comment]
@scguang301 分表分库这种应该考虑使用一些中间件，如Mycat

**Comment by inhere** [comment]
是想后面重写定时任务这块，但是暂时没时间

**Comment by scguang301** [comment]
> 快速切换DB会提供。分表就不会实现了。。。

快速切换表是否可以提供

**Comment by phper666** [comment]
现在用1.0做开发框架了，1.0能完美升级到2.0吗？

**Comment by inhere** [comment]
> > 快速切换DB会提供。分表就不会实现了。。。
> 
> 快速切换表是否可以提供

哈哈 这样 `DB::table('table name')` 就可以了

**Comment by inhere** [comment]
> 现在用1.0做开发框架了，1.0能完美升级到2.0吗？

**完美** 应该是不行的。
不过表面上的使用大体都是没有变动的，变动最明显的是db吧。

**Comment by phper666** [comment]
> > 现在用1.0做开发框架了，1.0能完美升级到2.0吗？
> 
> **完美** 应该是不行的。
> 不过表面上的使用大体都是没有变动的，变动最明显的是db吧。

是打算用laravel的orm吗？个人觉得Yii2的AR 操作也很丰富，如果可以兼容yii2的AR就更好了

**Comment by stelin** [comment]
@phper666 现在数据库已经高度兼容 laravel，至于 Yii 不会考虑兼容。

**Comment by scguang301** [comment]
> > > 快速切换DB会提供。分表就不会实现了。。。
> > 
> > 
> > 快速切换表是否可以提供
> 
> 哈哈 这样 `DB::table('table name')` 就可以了

根据表生成的Model，可以快速表table吗，分表后表比较多，只想保留一个

**Comment by stelin** [comment]
快速表table，什么意思？

**Comment by scguang301** [comment]
> 快速表table，什么意思？

快速切换表

**Comment by hihozhou** [comment]
@inhere @stelin 昨天试了一下master的代码，发现会报错
```bash
Call to undefined method Swoole\Coroutine::getCid()
```
看了一下swoole源码发现4.3才提供`getCid`方法，所以这里要改一下
![image](https://user-images.githubusercontent.com/12164486/56413273-84eb5d80-62b9-11e9-8f53-b6701b8f03b7.png)

**Comment by inhere** [comment]
@hihozhou  好吧 改成 4.3+ 了

**Comment by geXingW** [comment]
亟需一款强力 Debugger

**Comment by strivefatup** [comment]
希望orm是组件化的,可以替换成其它orm,比如Doctrine

**Comment by f39516046** [comment]
日志如果选用本地File的话，是否可以做 文件大小 的配置，日志写入的时候 如果当前文件达到size就进行切割， 同时日志这块是否可以本地以年月为目录，日志名以当天day，切割后的文件名以 day_时间戳  这样类似的格式进行保存。

本地存储日志文件这块是个问题，因为一旦单个文件size变大的时候很麻烦。 希望新版本可以进行变动一下

**Comment by to2false** [comment]
@f39516046 老的可以自定义log handler

**Comment by f39516046** [comment]
> @f39516046 老的可以自定义log handler

这块如果内置的话，应该会更好吧， 一旦服务启动后，日志文件大小完全像滚雪球一样快速增大。
个人建议

**Comment by f39516046** [comment]
这块如果内置的话，应该会更好吧， 一旦服务启动后，日志文件大小完全像滚雪球一样快速增大。
个人建议

**Comment by akrick** [comment]
希望加入一个企业级的RPC服务组件

**Comment by stelin** [comment]
@geXingW  debugger 应该很后面才考虑，暂时应该是基础组件

**Comment by stelin** [comment]
@strivefatup 直接替换其它 ORM 有点难，2.0 ORM高度兼容laravel，熟悉laravel的用户，可以快速上手。

**Comment by stelin** [comment]
@f39516046 内置不太好，因为每个人拆分日志业务不一样，可以做好预留，根据用户需求自己按业务拆分。

**Comment by strivefatup** [comment]
> @strivefatup直接替换其它ORM有点难，2.0 ORM高度兼容laravel，熟悉laravel的用户，可以快速上手。
在开发大型和复杂的应用时,[Doctrine](https://www.doctrine-project.org/projects/orm.html)更具有优势,社区也比较完善

**Comment by oyxp** [comment]
希望redis组件支持redis cluster

**Comment by 601157475** [comment]
2.0基础文档,能不能赶紧上一版

**Comment by geXingW** [comment]
@inhere 
> @geXingW debugger 应该很后面才考虑，暂时应该是基础组件

debugger 方便开发者追踪、调试、学习，直接降低门槛、提高了开发效率

**Comment by scguang301** [comment]
orm， model层联合主键会支持吗

**Comment by ywqyuan** [comment]
自动扫描文件需要考虑 `vim` 生成的交换文件 `*.php.swap` 扫描问题，虽然可以通过设置不生成交换文件，但是不是最好的选择。

**Comment by BardoQi** [comment]
建议增加SOCKET通讯支持。最好集成编解码组件。参见：
https://github.com/byteferry/sdds_php
