### ISSUE TITLE
entity生成命令报错

### ISSUE THREAD

**Issue by yelstr** [swoft-cloud/swoft#499]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0
| Swoole version      | 4.2.8-alpha
| PHP version         | 7.2.11 
| Runtime environment |Mac

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// 执行 php72 bin/swoft gen:entity -d datement 打印获取的如下sql：SELECT `TABLE_NAME` AS `name`, `TABLE_COMMENT` AS `comment` FROM `information_schema.`tables`` WHERE `TABLE_SCHEMA` = :5c1600062519a AND  `TABLE_TYPE` = :5c160006251a0 Params: :5c1600062519a=test :5c160006251a0=BASE TABLE 
问题是  `information_schema.`tables`` 格式有问题，另外指定的数据库没有赋值上去，取了固定test值
```

**Comment by sakuraovq** [comment]
2.0已经正式发布，建议升级到2.0 @yelstr  entity 生成简单好用
