### ISSUE TITLE
文件下载怎么实现

### ISSUE THREAD

**Issue by cgyhbc** [swoft-cloud/swoft#500]
我们有个导出数据的功能，我想直接导出cvs格式的文件,swoft应该如何实现。

**Comment by cgyhbc** [comment]
小文件下载，只需要设置Response头就可以了，然后return 数据，代码如下：
`
$response = $response->withHeader('Content-Type', 'application/vnd.ms-excel');
$response = $response->withHeader('Content-Disposition', 'attachment;filename='.time().'.xls');
$response = $response->withHeader('Cache-Control', 'max-age=0');
RequestContext::setResponse($response);
return 'hello world';
`
但是如何实现大文件下载呢，swoole有一个 $server->write()方法，是通过chunk的方式实现大文件的下载功能，swoft的话，该如何实现？

**Comment by alukaa** [comment]
@cgyhbc 兄得，上传的图片显示怎么玩

**Comment by wp-breeder** [comment]
`swoft` 文档中有关于[获取 `swoole` 的 `http response` 对象的文档](https://doc.swoft.org/master/zh-CN/http-server/request-response.html#%E9%A2%9D%E5%A4%96%E7%9A%84%E6%96%B9%E6%B3%95)的说明，在 [`swoft-http-message 1.0.5`](https://github.com/swoft-cloud/swoft-http-message/releases/tag/v1.0.5) 中已经可以使用，其他版本需要手动修改参考 ([`swoft-cloud / swoft-component#265`](https://github.com/swoft-cloud/swoft-component/pull/265))
- 下载文件，使用 `write` 方式：
```php
//设置header头
$response->getSwooleResponse()->header('Content-Type', 'application/octet-stream');
$response->getSwooleResponse()->header('Content-Disposition', 
'attachment;filename=test_' . time());
$response->getSwooleResponse()->header('Cache-Control', 'max-age=0');
//使用write 通过chunk方式
 return $response->getSwooleResponse()->write($data);
```
- 下载文件，使用 `sendfile` 方式：
```php
//设置header头
$response->getSwooleResponse()->header('Content-Type', 'application/octet-stream');
$response->getSwooleResponse()->header('Content-Disposition',
 'attachment;filename=test_' . time());
$response->getSwooleResponse()->header('Cache-Control', 'max-age=0');
// 通过sendfile api 实现下载文件
return $response->getSwooleResponse()->sendfile($filePath);
```
- 下载文件，直接放在 `public` 下,也可以实现文件下载，文档详见 [`document_root` 配置 ](https://wiki.swoole.com/wiki/page/783.html)

更多介绍详见 [`swoole http-server` 文档](https://toxmc.github.io/swoole-cs.github.io/#HttpServer)

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
