### ISSUE TITLE
httpClient 302 

### ISSUE THREAD

**Issue by AoeSyL** [swoft-cloud/swoft#505]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | x.y.z
| Swoole version      | 4.1.2
| PHP version         |  7.1.21 
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
$client = new Client();
        $result = $client->get($domain,[
             "headers" =>[
                'user-agent' => 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36',
                'referer' => $domain
             ],
            'followlocation' => true,
        ])->getResult();
请求返回302重定向，如何能在 Client开启 curl中CURLOPT_FOLLOWLOCATION 属性来进行自动重定向

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by huangzhhui** [comment]
暂不支持重定向，CURL可以支持Swoole驱动也无法支持
