### ISSUE TITLE
Response to send file

### ISSUE THREAD

**Issue by alukaa** [swoft-cloud/swoft#512]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 1.0.2
| Swoole version      | 4.0.1
| PHP version         | 7.2.8
| Runtime environment | Docker

**Details**

貌似swoft 没有实现swoole, response->sendFile,这时我上传了图片需要显示，怎么搞呢

**Comment by alukaa** [comment]
感觉实现得好生硬
![image](https://user-images.githubusercontent.com/8164389/50356599-96339000-058d-11e9-9a76-fe0a426e9473.png)
![image](https://user-images.githubusercontent.com/8164389/50356617-ac415080-058d-11e9-9049-885bb7d26d96.png)

**Comment by inhere** [comment]
更新下 swoft/http-message 到 1.0.5 加了 `getSwooleResponse`

**Comment by alukaa** [comment]
ok
