### ISSUE TITLE
关于『认证管理』有一些疑问

### ISSUE THREAD

**Issue by Wiidz** [swoft-cloud/swoft#520]
| Q                   | A
| ------------------- | -----
| Bug report?         |no
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      | 4.0.3
| PHP version         | 7.1.24
| Runtime environment | CentOS 7

**Details**

首先非常感谢swoft开发组的努力，让我用上了这么好的框架，我是从phalcon转过来的，发现还是有不少地方不好理解，关于『认证管理』有一些疑问，希望能得到答案

仔细阅读了很久的文档，这部分的解释个人还是无法理解，有以下几个点：

# 配置验证管理 AuthManagerInterface

```PHP
class AdminNormalAccount implements AccountTypeInterface{
}

```

### Q2. 由于需要使用了@Bean()、@Inject()，建议在文档代码中也写上相应的use

----

```PHP
class AuthManagerService extends AuthManager implements AuthManagerInterface{
}
```

### Q3. 上述AuthManagerService子类又应该放在什么目录中？
----
```PHP
\Swoft\Auth\Mapping\AuthManagerInterface::class => [
    'class'=>App\Domain\User\Service\AuthManagerService::class
],
```
文档中如下写道：
> 然后在 config/beans/base.php 中把系统默认的 AuthManager Bean 替换为我们自己的 AuthManagerService，添加如下代码进行替换

**Comment by AoeSyL** [comment]
A1: 
AdminNormalAccount可以随意放置 在通过AuthManagerService中实现时实例化进来
A2:
AuthManagerService
```
 use Swoft\Auth\AuthManager;
 use Swoft\Auth\Mapping\AuthManagerInterface;
 use Swoft\Auth\Bean\AuthSession;
 use Swoft\Bean\Annotation\Bean;
 use Swoft\Redis\Redis;
```


AuthService
```
use Psr\Http\Message\ServerRequestInterface;
use Swoft\Auth\AuthUserService;
use Swoft\Auth\Mapping\AuthServiceInterface;
use Swoft\Bean\Annotation\Bean;
```

UserNormalAccount


```
use App\Models\Dao\AdminDao;
use Swoft\Auth\Mapping\AccountTypeInterface;
use Swoft\Auth\Bean\AuthResult;
use Swoft\Bean\Annotation\Bean;
use Swoft\Bean\Annotation\Inject;
```


AuthManagerService  extends AuthManager
所以在AuthManagerService设置一些属性
 /**
     * @var string
     */
    protected $cacheClass = Redis::class;

    /**
     * @var bool 开启缓存
     */
    protected $cacheEnable = true;

具体可以进入AuthManager中查看

A3:
AuthManagerService放置目录应根据
    'class'=>App\Domain\User\Service\AuthManagerService::class
决定
@Wiidz

**Comment by Wiidz** [comment]
感谢指点，请问Q4如何修改base.php
@AoeSyL

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
