### ISSUE TITLE
Rpc 的控制器无法属性注入问题

### ISSUE THREAD

**Issue by brewlin** [swoft-cloud/swoft#521]
swoft1.0 
Http控制器的属性注入在 框架初始化的时候是能够注入成功的，能够拿到连接的
Rpc控制器的属性注入@ Reference  注入连接池，在框架初始化后拿到的代理 通过打印发现没有注入成功，依然是null ，但是Http控制器是注入成功的，
例子：
官网的 demoservice2（Rpc 客户端连接池） 在Http 下的RpcController 下是可以注入成功的，但是 在Rpc的DemoSservice 里是拿到不到user的连接的，底层打印也是null
是不是在依赖注入那里判断有问题？

**Comment by Lxido** [comment]
可是测了 Rpc Service确实不能注入Rpc Client呀，而且在框架属性注入源码哪里打印发现也没有注入成功呀，Http控制器是可以注入RpcClient的

**Comment by Lxido** [comment]
相当于 我在Rpc服务里 调用其他的Rpc服务，结果在注入Rpc Client的时候 是null，

**Comment by inhere** [comment]
能贴一下你的demo代码吗？语言描述有些不能表述出来

**Comment by Lxido** [comment]
这是Http控制器， 然后user服务的RpcClient 拿到了，也可以正常调用user服务
```
/**
 * rpc controller test
 *
 * @Controller(prefix="rpc")
 */
class RpcController extends BaseController
{

    /**
     * @Reference(name="user", fallback="demoFallback")
     *
     * @var DemoInterface
     */
    private $demoService;
    /**
     * @Reference(name="user")
     * @var OrderInterface
     */
    private $order;

    /**
     * @RequestMapping(route="order")
     */
    public function makeOrder()
    {
        return [$this->test(),$this->order->makeOrder(1)];

    }
```

2.这是Rpc 控制器，user服务的Rpc client的没有拿到，属性是order属性是null，源码那里注入完成后打印也是空，就无法调用user服务
```
/**
 * Demo service
 *
 * @method ResultInterface deferGetUsers(array $ids)
 * @method ResultInterface deferGetUser(string $id)
 * @method ResultInterface deferGetUserByCond(int $type, int $uid, string $name, float $price, string $desc = "desc")
 * @Service(version="1.0.1")
 */
class DemoServiceV2 implements DemoInterface
{

    /**
     * @Reference(name="user")
     *
     * @var OrderInterface
     */
    private $order;

    public function getUsers(array $ids)
    {
        return $this->order->makeOrder(3);
    }
```
：疑问：框架初始化的时候，基本上所有属性有注解的类都会通过动态代理实现属性注入，可是只有Rpc服务也就是Services下的控制器无法属性注入成功，也就是通过Reference注解拿不到连接。

**Comment by inhere** [comment]
```php
public function getUsers(array $ids)
{
	$order = \bean('user'); // 这样的方式能获取到不
	// ...
}
```

**Comment by Lxido** [comment]
：user是另外一个服务的Rpc连接池。
            我通过其他方式是注入bean是可以拿到的，就是在Rpc控制器里属性注入不了，
：$order = \bean('user') 打印了下 获取不到

**Comment by Lxido** [comment]
当前服务（195）
都是同样的通过Reference注解 注入user（调用服务140）Rpc Client 
HttpController 框架初始化（动态代理->属性注入）后 通过打印是注入成功的，而且可以调用 user服务
Service 模块下Rpc控制器 经过框架初始化（动态代理->属性注入）后通过打印都是null，而且调用失败(call to a member function getUser() on null)

**Comment by Lxido** [comment]
Services Reference 注入Rpc Client 可以么嘿嘿

**Comment by Lxido** [comment]
这个问题现在在改么^_^

**Comment by Lxido** [comment]
大佬们  这个算是个bug么，人捏

**Comment by Lxido** [comment]
等的我好焦躁

**Comment by inhere** [comment]
问了 strlin 现在好像不支持，rpc服务里直接注入另一个rpc服务

**Comment by inhere** [comment]
你可以变通下，demo2 里注入一个 userLogic, userLogic 里注入 user service.

**Comment by Lxido** [comment]
我知道 那样我试过 就是感觉有点变扭 哈哈，
我源码打印了 ，就Rpc的控制器没有拿到属性。应该是bug吧 哈哈

**Comment by inhere** [comment]
1.0 里面没有实现这个 😄 
2.0 里面会加上这个

**Comment by Lxido** [comment]
哈哈，我1.0的项目还没有做完，2.0就出来了，变动很大么，不兼容 得改很多，难受 哈哈

**Comment by inhere** [comment]
底层全部重写了，变动挺大 
但是在使用上，变动到不是很多

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
