### ISSUE TITLE
I18n配置有点乱

### ISSUE THREAD

**Issue by Wfuren** [swoft-cloud/swoft#522]
首先.env中没有I18n的默认配置，虽然手写可以
![default](https://user-images.githubusercontent.com/29916783/50494483-810fa300-0a5e-11e9-8144-043e43fe2018.png)
在一个最新下载的代码配置是这样的
![default](https://user-images.githubusercontent.com/29916783/50494501-9a185400-0a5e-11e9-8b16-97a3c56b6fa5.png)
然而文档中却又是这样
![default](https://user-images.githubusercontent.com/29916783/50494513-aa303380-0a5e-11e9-9e26-1e110805139b.png)

**Comment by inhere** [comment]
...后面改过一次，没同步 :( 😄
