### ISSUE TITLE
在task中无法使用redis解决办法

### ISSUE THREAD

**Issue by PeterYangs** [swoft-cloud/swoft#524]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
 发现在task中无法使用redis,查看代码发现task调用redis是使用$redis  = new \Redis();，需要安装phpredis拓展，希望官方在文档中提醒
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
