### ISSUE TITLE
rpc-client 连接池归还异常

### ISSUE THREAD

**Issue by tanpeng** [swoft-cloud/swoft#526]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by tanpeng** [comment]
rpc-client异常状态下，连接池归还异常。 （不小心误回车了，接上述问题描述）
目前只读了下代码，还未做代码验证：
1、Swoft\Rpc\Client\Service  101行，提前直接return，是否会存在连接不归还情况。下列为相关代码段。
`$client = $connectPool->getConnection();

$packer   = service_packer();
$type     = $this->getPackerName();
$data     = $packer->formatData($this->interface, $this->version, $func, $params);
$packData = $packer->pack($data, $type);

$result = $circuitBreaker->call([$client, 'send'], [$packData], $fallback);
if ($result === null || $result === false) {
    return null;
}`

2、Swoft\Rpc\Client\Service  139行，client close仅做了连接关闭，是否会存在连接不归还情况。下列为相关代码段。
`if ($closeStatus && isset($client) && $client instanceof AbstractServiceConnection) {
$client->close();
App::error(sprintf('%s call %s failed, data=%s, message=%s, code=%s',
    $this->interface,
    $func,
    json_encode($data, JSON_UNESCAPED_UNICODE),
    $throwable->getMessage(),
    $throwable->getCode()
));
}
if (empty($fallback)) {
throw $throwable;
}
$data = PhpHelper::call($fallback, $params);`

**Comment by stelin** [comment]
建议升级到2.0， 2.0 已经正式发布
