### ISSUE TITLE
使用gen:controller命令时，如何自定义文件头部注释？

### ISSUE THREAD

**Issue by ixingjue** [swoft-cloud/swoft#527]
![image](https://user-images.githubusercontent.com/25813184/50591696-d9fe9180-0ecb-11e9-80a0-9e61f09825d0.png)
比如我要将这些swoft相关的信息改成自己项目信息

**Comment by inhere** [comment]
简单直接的可以到 `vendor/swoft/devtool/res/templates` 里，改下 `file-header.stub` 这个模板文件

**Comment by inhere** [comment]
也可以参考现有模板，自定义模板文件。

运行: `php bin/swoft gen:controller -h` 可以看到可用选项，
是允许自定义模板目录和指定的模板文件名的

**Comment by sunnyos** [comment]
> ![image](https://user-images.githubusercontent.com/25813184/50591696-d9fe9180-0ecb-11e9-80a0-9e61f09825d0.png)
> 比如我要将这些swoft相关的信息改成自己项目信息

https://doc.swoft.org/master/zh-CN/devtool/gen-commands.html 参考这个
