### ISSUE TITLE
压测结果有超时的现象

### ISSUE THREAD

**Issue by lizhanfei** [swoft-cloud/swoft#528]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0
| Swoole version      | 4.2.7  (by `php --ri swoole`)
| PHP version         | 7.2.13 (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> 我们开发了一个简单的接口。
传入参数member_id，可以是一个或者多个
根据传入的member_id去查询member数据表里的member数据。
member表16W的数据。
压测的结果，大部分请求都能正常响应，但是会有0.015%的概率出现响应超时。
请问是什么原因呢？

```php
超时没有返回
```

> Provide minimal script to reproduce the issue

```php
        $timeStart = microtime(true);
        $member_id = $request->json('member_id');
        if (empty($member_id)) {
            $code = 400;
            $message = "参数错误";
            return compact('code', 'message');
        }
        $member_id = explode(',', $member_id);
        $result = ***Member::findAll(['member_id', 'in', $member_id])->getResult();
        $data = $result;
        $code = 200;
        $message = "获取数据成功";
        $timeEnd = microtime(true);
//这里测试的时候做了个判断，如果$timeEnd - $timeStart >3 会记录日志
//但是压测中出现超时的时候，这里并没有记录到日志信息
//@file_put_contents('/data/swoft/runtime/runtime.log', 'time_cost:'. ($timeEnd - $timeStart). PHP_EOL, FILE_APPEND);
        return compact('code', 'message', 'data');
```

**Comment by inhere** [comment]
请求日志里没有错误信息吗

**Comment by lizhanfei** [comment]
swoole.log里没有错误信息。还有别的日志吗？

**Comment by inhere** [comment]
`@runtime/logs/notice.log`  `@runtime/logs/error.log`

**Comment by lizhanfei** [comment]
日志里没有找到有效信息，notice.log都是notice、info、debug信息，
error.log里只有一些错误的route信息记录。
如果php本身开启了log，是否也应该有日志记录？？

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
