### ISSUE TITLE
关于...可变参数不知道和框架预期的是否一致

### ISSUE THREAD

**Issue by 233cy** [swoft-cloud/swoft#529]
![default](https://user-images.githubusercontent.com/29916783/50708501-71680e00-109f-11e9-9902-6e0aa24e153c.png)
![default](https://user-images.githubusercontent.com/29916783/50708506-775def00-109f-11e9-8c29-411944e1fd32.png)
如图，我在service中使用了可变参数$_opt，但是在Interface中没有定义$_opt可变参数。
这样的情况下我可以通过传入可变参数直接在service中取得，不知道这里和框架设计的与预期中的结果一样吗

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
