### ISSUE TITLE
启动后出现，the pool of default.master is not exist

### ISSUE THREAD

**Issue by PeterYangs** [swoft-cloud/swoft#530]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
