### ISSUE TITLE
rpc-client的应该开放client的tcp_type指定

### ISSUE THREAD

**Issue by pkdog** [swoft-cloud/swoft#531]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 1.0.8
| Swoole version      | 4.2.11 (by `php --ri swoole`)
| PHP version         | 7.1.7
| Runtime environment | Mac

**Details**

我所在的团队在使用swoft有加密的需求，现在已经实现了在不改动swoft核心代码的情况下server端的ssl加密。可是rpc-client下的client对象的type是写死为SWOOLE_SOCK_TCP | SWOOLE_KEEP 。这样会导致没法实现rpc-client的ssl加密通信。

修改建议是ServiceConnection.php 下的第24句修改为允许利用在配置文件指定client的tcp type.

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
