### ISSUE TITLE
中间件中取不到 response 内容

### ISSUE THREAD

**Issue by 1024i** [swoft-cloud/swoft#532]
在中间件中
直接 print_r($response) 看结构体里是有输出内容的
但时通过 $response->getBody()->getContents() 获取不到内容，同时 response 的内容被清除

`<?php

namespace App\Middlewares;

use Psr\Http\Server\RequestHandlerInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Swoft\Bean\Annotation\Bean;
use Swoft\Exception\Exception;
use Swoft\Http\Message\Middleware\MiddlewareInterface;
use Swoft\Db\Db;

/**
 * @Bean()
 * @uses QiMenMiddleware
 */
class LogMiddleware implements MiddlewareInterface
{

    /**
     * 记录访问日志
     *
     * @param \Psr\Http\Message\ServerRequestInterface $request
     * @param \Psr\Http\Server\RequestHandlerInterface $handler
     * @return \Psr\Http\Message\ResponseInterface
     * @throws \InvalidArgumentException | Exception
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $response = $handler->handle($request);

        try {
            Db::query('INSERT INTO qimen_log(request_url, request_body, response_body, create_time) VALUES(?, ?, ?, ?)', [
                $request->url(),
                json_encode($request->input()),
                $response->getBody()->getContents(),
                date('Y-m-d H:i:s')
            ])->getResult();
        } catch (\Exception $e) {

        }

        return $response;
    }

}

`

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
