### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by QiiSyhx** [swoft-cloud/swoft#536]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | master
| Swoole version      | 4.2.12
| PHP version         | PHP 7.1.25 (cli) (built: Dec  7 2018 01:04:25) ( NTS )
| Runtime environment | CentOS release 6.7 (Final)

**Details**
php bin/swoft start -d
```php
// paste output here
Call to undefined function Swoft\Bootstrap\Server\posix_kill()
```

**Comment by huangzhhui** [comment]
请安装posix扩展
