### ISSUE TITLE
全新的项目 使用__devtool 工具无法生成 websocket 控制器

### ISSUE THREAD

**Issue by yanwuguangjun** [swoft-cloud/swoft#537]
全新的项目  使用__devtool 工具无法生成 websocket 控制器 其他尝试了下controller的也不行 
环境  bash on  windows
![image](https://user-images.githubusercontent.com/17357142/51333760-66f33e80-1ab9-11e9-856c-70e4470f3df6.png)

全新的项目  __devtool工具无法连接webosket  几个月前不是还可以用的嘛
![image](https://user-images.githubusercontent.com/17357142/51333976-d1a47a00-1ab9-11e9-99d6-6aa3b4ef49ec.png)

**Comment by inhere** [comment]
ip 后面咋还有 `/` ?
你到路由面板里看下 注册的 WS路由

**Comment by yanwuguangjun** [comment]
![image](https://user-images.githubusercontent.com/17357142/51335537-4a590580-1abd-11e9-916d-2fa32033c1cc.png)
这样也是秒断的

**Comment by inhere** [comment]
是不是启动的不是 ws server啊

**Comment by yanwuguangjun** [comment]
server  是真的websocket server

**Comment by inhere** [comment]
你通过左侧 路由 菜单，进去看下 websocket 路由有哪些

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
