### ISSUE TITLE
如果我myql使用了其他连接池，开启事务的时候， Db::beginTransaction();，里面的参数是否也要写改

### ISSUE THREAD

**Issue by PeterYangs** [swoft-cloud/swoft#540]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php

   try {

            Db::beginTransaction('other');


            Db::query('select * from test',[],'other');



            Db::commit('other');
        }catch (\Exception $exception){

            Db::rollback('other');


        }

```

> Provide minimal script to reproduce the issue

```php
是否需要这样呢
```

**Comment by PeterYangs** [comment]
还有一个事情，事务开启后抛出异常后，下一个sql语句会出现mysql client is waiting for calling recv, cannot send new sql query，官方最新的swoft/db包修复了这个bug，但是版本是dev-mater，希望官方给最新版本打一个版本号，不然只能用dev-mater更新了

**Comment by PeterYangs** [comment]
刚刚测试后，如果用了其他实例，事务里面的连接池参数也要更改成相应的连接池名称

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
