### ISSUE TITLE
多重事务嵌套支持

### ISSUE THREAD

**Issue by Hiber0385** [swoft-cloud/swoft#544]
倘若需要类似laravel 那种多重事务嵌套 自动处理.因协程这块不太了解,这个数比较合适在哪里计比较合适.能否给点建议呢.
Laravel主要实现原理是  本连接实例中 事务进行计数,每次进入事务,计数加1,  只在计数为1时,  开启事务

并且只在计数1时,才做commit 动作. 每做一次commit 计数减1

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
