### ISSUE TITLE
可不可以在RPC加上自定义

### ISSUE THREAD

**Issue by 233cy** [swoft-cloud/swoft#546]
可以不可以在RPC微服务中加上附带参数？
类似讲request转发过去或者可以自定义要转发的参数内容

**Comment by inhere** [comment]
1.0 的暂时不准备改进了。

**Comment by cjieyan** [comment]
重写了一个基于tars协议的rpc
https://github.com/cjieyan/swoft-tars-rpc
想要自定义只能自己想办法重写了

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
