### ISSUE TITLE
devltool空白不显示

### ISSUE THREAD

**Issue by guchangsheng** [swoft-cloud/swoft#547]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | v1.0.8-beta
| Swoole version      | 4.0.2
| PHP version         | php7.0.2
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
按照文档配置完成devltool，访问页面空白，控制台js报错，显示调用js路径路由找不到
![image](https://user-images.githubusercontent.com/28506312/51520075-bd67d080-1e5d-11e9-9ff4-07d3da932c99.png)

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

![image](https://user-images.githubusercontent.com/28506312/51519660-92c94800-1e5c-11e9-8c5d-0491818da019.png)

**Comment by inhere** [comment]
你看下static 目录下有没有devtool的静态资源

**Comment by guchangsheng** [comment]
![image](https://user-images.githubusercontent.com/28506312/51580318-058aff80-1eff-11e9-991a-4064e4a127da.png)
![image](https://user-images.githubusercontent.com/28506312/51580332-0c197700-1eff-11e9-90f6-af1429932c5c.png)
目录下有静态资源

**Comment by nemoxiaolan** [comment]
原因是没有开启静态文件处理，.env 增加配置 `ENABLE_STATIC_HANDLER=true`，花了我一个小时功夫好歹找到了。参考： https://wiki.swoole.com/wiki/page/327.html

**Comment by im55cc** [comment]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      |4.3.1
| PHP version         | 7.1.8
| Runtime environment | Win10/vagrant 2.2.3/centos 7.0|
--

**Details**
enable_static_handler 这参数也设置为 ture了，就是显示不出来，不知道为什么呢。
```
{
  "msg": "Route not found for /devtool/static/js/manifest.dffd4c171722145f4ae3.js",
  "file": "/www_project/php-msf/03_swoft/vendor/swoft/http-server/src/Router/HandlerAdapter.php",
  "line": 49,
  "code": 404
}
```

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by ywqyuan** [comment]
设置了 enable_static_handler=true 同样无效
