### ISSUE TITLE
在websocket中没办法调用RPC服务端信息

### ISSUE THREAD

**Issue by linuxlan** [swoft-cloud/swoft#549]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0
| Swoole version      | 4.2.10-alpha
| PHP version         | PHP 7.2.10
| Runtime environment | Mac/CentOS 7

在WebScoket中调用RPC服务返回NULL

> Provide minimal script to reproduce the issue

```php'
 use App\Lib\UserInterface;
use Swoft\Rpc\Client\Bean\Annotation\Reference;
以上是引用

下方是class中的声明：
    /**
     * @Reference("user",breaker="user", version="1.0")
     * @var UserInterface
     */
    private $user_service;

   public function onMessage(Server $server, Frame $frame){
   var_dump($this->user_service); //返回的是NULL
}
```

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
