### ISSUE TITLE
PHP Warning:  Swoole\Server::sendMessage(): can't send messages to self. in /var/www/swoft/vendor/swoft/task/src/Task.php on line 100

### ISSUE THREAD

**Issue by longjianghu** [swoft-cloud/swoft#551]
Swoole:
swoole support => enabled
Version => 4.2.9
Author => Swoole Group[email: team@swoole.com]
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
openssl => LibreSSL 2.7.4
http2 => 1.32.0
pcre => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.aio_thread_num => 2 => 2
swoole.display_errors => On => On
swoole.use_namespace => On => On
swoole.use_shortname => On => On
swoole.fast_serialize => Off => Off
swoole.unixsock_buffer_size => 8388608 => 8388608

PHP版本：
PHP 7.2.10 (cli) (built: Sep 17 2018 09:23:43) ( NTS )

Task在执行任务的时候报以下错误（我在task里定义了一个任务名称也叫sendMessage，不知道是不是重名的原因）：
PHP Warning:  Swoole\Server::sendMessage(): can't send messages to self. in /var/www/swoft/vendor/swoft/task/src/Task.php on line 100

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
