### ISSUE TITLE
\swoft::$server->getClientInfo() 返回array 的问题

### ISSUE THREAD

**Issue by Lxido** [swoft-cloud/swoft#555]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | 1
| Swoole version      | 2.1.3
| PHP version         |7.1
| Runtime environment | ubuntu 14

**Details**

> websocket 中获取fd的链接信息 ，swoft封装后实际上当fd不存在会返回boolean，而swoft封装后必须返回array，这样我的程序就中断了

```php

    /**
     * @param int $fd
     * @return array
     */
    public function getClientInfo(int $fd): array
    {
        return $this->server->getClientInfo($fd);
    }

    /**
     * @return array
     */
    public function getWsSettings(): array
    {
        return $this->wsSettings;
    }
}

```
php 7 严格控制返回值

**Comment by inhere** [comment]
可以帮忙提PR改下 强制转换为 array
