### ISSUE TITLE
mysql事务问题

### ISSUE THREAD

**Issue by yangjieqq** [swoft-cloud/swoft#556]
mysql连接池一段时间不使用  再次使用的时候 不用事务没问题  用事务的commit  rollback会出现问题 
line=>206  There is no active transaction  file/home/swoftendor/swoftc/Driver/Mysql/SyncMysqlConnection.phpArray0

**Comment by yangjieqq** [comment]
@stelin @
![zprpe0w27a325jzb7y ijnp](https://user-images.githubusercontent.com/44186134/52693958-3234b300-2fa3-11e9-96e3-250392715066.png)

**Comment by yangjieqq** [comment]
![image](https://user-images.githubusercontent.com/44186134/52694015-60b28e00-2fa3-11e9-9749-88fb98fce376.png)

**Comment by stelin** [comment]
你这个问题要怎么复现

**Comment by yangjieqq** [comment]
隔10分钟去调用task  可以定时器 或者api去调下   task里面事务操作 涉及curd  提交事务和回滚的时候就会有连接问题

**Comment by 372620040** [comment]
在一个事务下操作多张表，然后最后一起提交，中间在操作了第一张表后就return掉，然后发现事务也自动提交了，都会自动提交的吗

**Comment by huangzhhui** [comment]
每个事务必须得提交或回滚，每个请求结束时框架会自动处理没处理的连接然后返还给连接池，否则你的连接池里面的连接你马上就能耗完

**Comment by yangjieqq** [comment]
就是做提交或者回滚操作都会有问题，报这个连接没有活跃事务

**Comment by to2false** [comment]
@huangzhhui 同这个问题，我是这样操作的
```
try {
    Db::beginTransaction();
    // 这里进行更新操作
    Db::commit();
} catch (\Exception $e) {
    Db::rollback();
}
```

**Comment by JoeXiong** [comment]
同样遇到这个问题：
2019-04-26 07:05:57 [error] [swoft-data-processing-center-ecs] [logid:5cc1d7afd5412] [spanid:0] trace[RuleCenter.php:126,App\M
essageResponse\Production\Rules\RuleCenter->process] RuleCenter process Throwable : There is no active transaction /data/relea
se/swoft/data_processing_center/ecs/base/vendor/swoft/db/src/Driver/Mysql/SyncMysqlConnection.php 206
2019-04-26 07:11:17 [error] [swoft-data-processing-center-ecs] [logid:5cc1d7afd5412] [spanid:0] trace[RuleCenter.php:126,App\M
essageResponse\Production\Rules\RuleCenter->process] RuleCenter process Throwable : There is no active transaction /data/relea
se/swoft/data_processing_center/ecs/base/vendor/swoft/db/src/Driver/Mysql/SyncMysqlConnection.php 198
检查了代码开启事务的，都进行了提交或回滚

**Comment by to2false** [comment]
自己调用的代码里已经commit/rollback了，然后释放资源那里还调用了一次rollback导致的错误

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。

**Comment by yudingbin** [comment]
@yangjieqq 这个问题解决了吗 ？ 我也遇到了
@stelin 2.0和1.0版本很多不兼容，故一直在使用1.0版本

**Comment by yangjieqq** [comment]
解决了  task的连接池重连的地方记得把smtm重置了  sync连接数据库的文件

**Comment by yudingbin** [comment]
@yangjieqq 
smtm 啥东西，方便贴代码具体说明下么 ？
我现在测试发现只要每次 beginTransaction 前都执行以下无影响结果的update操作，后面的事务都能正常工作。

**Comment by yangjieqq** [comment]
<img width="727" alt="QQ20190905-172530@2x" src="https://user-images.githubusercontent.com/44186134/64329879-89af7480-d002-11e9-9101-5cfa633708d7.png">

**Comment by yudingbin** [comment]
@yangjieqq 感谢，确实解决了问题。
@stelin 方便更新到1.x的代码仓库吗 ？

**Comment by yangjieqq** [comment]
这个问题我跟inhere说过 上次我没弄进去。。。

**Comment by inhere** [comment]
@yangjieqq 😊 ...忘了，之前发过pr吗？

**Comment by yangjieqq** [comment]
就是哇、上次qq给你说了 但是我发pr弄错了 让你加一下 哈哈
