### ISSUE TITLE
Query::table实例化，第一次查询一条记录，不重新实例化，更新操作不正确

### ISSUE THREAD

**Issue by CodeingMonkey** [swoft-cloud/swoft#557]
![image](https://user-images.githubusercontent.com/20737017/52698308-387c5c80-2fae-11e9-9743-961c7b3931e8.png)
打印更新的SQL语句为
SELECT `status` FROM `profit_device_config` WHERE `id` = '6' AND  `id` = '6' LIMIT

**Comment by inhere** [comment]
你该在未使用之前 clone 一个后面用 或者 从新用 query::table 创建一个

**Comment by CodeingMonkey** [comment]
感谢 问题已经解决 使用了clone方式
