### ISSUE TITLE
写日志时内存超出PHP限制

### ISSUE THREAD

**Issue by xnnyeYp** [swoft-cloud/swoft#561]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      | 4.2.9 (by `php --ri swoole`)
| PHP version         | 7.1.3 (by `php -v`)
| Runtime environment | CentOS 6.5.

**Details**

> 错误日志内容： PHP Fatal error:  Allowed memory size of 402653184 bytes exhausted (tried to allocate 262144 bytes) in /data/www/project-wechat-message/vendor/swoft/framework/src/Log/FileHandler.php on line 83

>报错部分代码
```php
private function coWrite(string $logFile, string $messageText)
    {
        go(function () use ($logFile, $messageText) {
            $res = Coroutine::writeFile($logFile, $messageText, FILE_APPEND);
            if ($res === false) {
                throw new \InvalidArgumentException("Unable to append to log file: {$this->logFile}");
            }
        });
    }
```

**Comment by inhere** [comment]
你检查下是不是哪里业务出问题了，一下写了非常多的日志进来

开启了 `flushInterval` 到达一定记录就自动写文件吗

**Comment by xnnyeYp** [comment]
flushInterval 现在是100，我改成1试试

**Comment by xnnyeYp** [comment]
flushRequest 我设置为 true 的，应该是每有一条日志就会写入吧

**Comment by inhere** [comment]
100 不算大
flushRequest 设置为 true - 是每次请求完成，就写一次

**Comment by xnnyeYp** [comment]
对啊，100 并不大，请问这个有什么方法可以排查吗

**Comment by inhere** [comment]
在这出错了，这个时间点之前日志有写入成功吗？能观察到这个请求写入了多少日志吗？哪个API调用写入的这次日志

**Comment by xnnyeYp** [comment]
好的，谢谢，我自己先排查下

**Comment by jianwubayiba** [comment]
我是docker就出错，日志报错的机率很小，小于5%

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
