### ISSUE TITLE
file日志内存泄漏

### ISSUE THREAD

**Issue by jianwubayiba** [swoft-cloud/swoft#562]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      | 4.2.7
| PHP version         | 7.2.12
| Runtime environment | Docker

**Details**

> Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /var/www/swoft/vendor/swoft/framework/src/Log/FileHandler.php on line 83
Warning: Swoole\Process::close(): no pipe, can not close the pipe. in /var/www/swoft/vendor/swoft/process/src/Process.php on line 160
Warning: Swoole\Process::exit(): not current process. in /var/www/swoft/vendor/swoft/process/src/Process.php on line 172

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
refer #561

**Comment by jianwubayiba** [comment]
docker启动就报错。
```php
in boot\myProcess

$process = ProcessBuilder::create($name);
...
```

**Comment by jianwubayiba** [comment]
发现里面的while(true){}循环一直占用内存。

**Comment by wujunze** [comment]
> 发现里面的while(true){}循环一直占用内存。

哪一行代码

**Comment by jianwubayiba** [comment]
我想说的是，相比http或ws这种request->response响应式回答，请求->返回结果->释放流程的操作。对于create process后一直占用的任务，内存占用一直飙升。
`
public function run(SwoftProcess $process)
{
	$process->name("some");

	$amqp = new Amqp();
    $amqp->listen($exchange, $queue, function (array $data) {
		call_user_func(function(array $data){}, $data);
	}, 'fanout');
}
`
而$amqp->listen方法实际是一个一直while阻塞的函数：
`
// do something ...
while (count($channel->callbacks)) {
	$channel->wait(null, true);
}
`
这个就是对消息队列的监听与处理。
按我的理解，内存一直上升的原因，是因为函数创建后，无法释放里面的变量引用，gc无机会回收内存。
对于这种任务是否有办法进行处理？

**Comment by jianwubayiba** [comment]
> > 发现里面的while(true){}循环一直占用内存。
> 
> 哪一行代码

我想说的是，相比http或ws这种request->response响应式回答，请求->返回结果->释放流程的操作。对于create process后一直占用的任务，内存占用不断飙升。
`
public function run(SwoftProcess $process)
{
$process->name("some");

$amqp = new Amqp();
    $amqp->listen($exchange, $queue, function (array $data) {
	call_user_func(function(array $data){}, $data);
}, 'fanout');
}
而$amqp->listen方法实际是一个一直while阻塞的函数：
// do something ...
while (count($channel->callbacks)) {
$channel->wait(null, true);
}
`
这个就是对消息队列的监听与处理。
按我的理解，内存一直上升的原因，是因为函数创建后，无法释放里面的变量引用，gc无机会回收内存。
对于这种任务是否有办法进行处理？

**Comment by wujunze** [comment]
> > > 发现里面的while(true){}循环一直占用内存。
> > 
> > 
> > 哪一行代码
> 
> 我想说的是，相比http或ws这种request->response响应式回答，请求->返回结果->释放流程的操作。对于create process后一直占用的任务，内存占用不断飙升。
> 
> > public function run(SwoftProcess $process)
> > {
> > $process->name("some");
> > $amqp = new Amqp();
> > $amqp->listen($exchange, $queue, function (array $data) {
> > call_user_func(function(array $data){}, $data);
> > }, 'fanout');
> > }
> 
> 而$amqp->listen方法实际是一个一直while阻塞的函数：
> 
> > // do something ...
> > while (count($channel->callbacks)) {
> > $channel->wait(null, true);
> > }
> 
> 这个就是对消息队列的监听与处理。
> 按我的理解，内存一直上升的原因，是因为函数创建后，无法释放里面的变量引用，gc无机会回收内存。
> 对于这种任务是否有办法进行处理？

有一种比较笨 但是很有效的方案     定时重启

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
