### ISSUE TITLE
swoft  webscoket 下使用zookeeper 连接会断开

### ISSUE THREAD

**Issue by YeDongaidiiqu** [swoft-cloud/swoft#564]
![image](https://user-images.githubusercontent.com/25131877/53229213-9ef42f80-36be-11e9-9951-928da61d55a8.png)

创建websocket连接时 实例化了zookeeper的连接

![image](https://user-images.githubusercontent.com/25131877/53229285-cb0fb080-36be-11e9-9ee5-b7f2667c4e5b.png)

这时会报错
![image](https://user-images.githubusercontent.com/25131877/53229315-db279000-36be-11e9-8f76-9853171281ce.png)

同时客户端连接会断开,这是什么原因造成的 @DanielRuf @kcloze

**Comment by YeDongaidiiqu** [comment]
换了一种写法好像就可以了，是因为open 的时候再建立一个连接，这时候本来的websocket 连接就会断掉么，没看源码，机制还不了解，
附上新写法:
![image](https://user-images.githubusercontent.com/25131877/53229962-8a189b80-36c0-11e9-8a70-678fd545c700.png)

**Comment by DanielRuf** [comment]
Not sure why I was linked here. I guess this was by accident.
