### ISSUE TITLE
win10 下通过docker-compose up运行错误！！！

### ISSUE THREAD

**Issue by akrick** [swoft-cloud/swoft#565]
通过win10命令行在clone的swoft目录下执行docker-compose up
得到如下结果提示：

Creating swoft_swoft_1 ... done
Attaching to swoft_swoft_1
swoft_1  | Could not open input file: /var/www/swoft/bin/swoft
swoft_swoft_1 exited with code 1

**Comment by inhere** [comment]
要自己配置下 docker-compose.yml 挂载当前目录进去

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
