### ISSUE TITLE
地址传参出现无法通过修改形参的方式改变实参

### ISSUE THREAD

**Issue by FFAIY** [swoft-cloud/swoft#567]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> 在方法中以地址传参的方式向其他类传参发现修改了形参后实参并没有改变。

```php
// paste output here

//这里是控制器里面的方法
/**
     * @Inject()
     * @var DemoLogic
     */
    private $demoLogic;

    /**
     * @RequestMapping(route="test_param")
     */
    public function testParam(){
        $a = 'a';
        $b = 'b';
        echo "before:{$a}\n";
        echo "before:{$b}\n";
        $this->demoLogic->testParam($a, $b);
        echo "after:{$a}\n";
        echo "after:{$b}\n";
    }


//这里是DemoLogic.php
public function testParam(&$a, &$b){
        $a = 'c';
        $b = 'd';
    }
```

> Provide minimal script to reproduce the issue

```php
// paste code
before:a
before:b
after:a
after:b

这是最后的结果
```

**Comment by inhere** [comment]
建议使用 2.0
