### ISSUE TITLE
协程不会自动关闭么？

### ISSUE THREAD

**Issue by YeDongaidiiqu** [swoft-cloud/swoft#569]
![image](https://user-images.githubusercontent.com/25131877/53385728-6607d380-39ba-11e9-95c0-eef6df28a70f.png)

![image](https://user-images.githubusercontent.com/25131877/53385735-6d2ee180-39ba-11e9-8caa-a1d598bca805.png)

zhedua这段代码报错，应该是这个循环，在循环里面主要是用到了协程，感觉每个循环的协程不会自动释放，
![image](https://user-images.githubusercontent.com/25131877/53385776-96e80880-39ba-11e9-9e25-33240bfddd8f.png)

是这样的么

**Comment by huangzhhui** [comment]
你对协程的理解有误，协程不是这么用的
