### ISSUE TITLE
RequestHandler可以用协程解耦吗？

### ISSUE THREAD

**Issue by akrick** [swoft-cloud/swoft#570]
Http-Server的Router，RequestHandler可以用协程解耦吗？就是支持高并发路由请求，然后由协程处理controller响应。目前http-server看上去和Symfony的方式好像差别不大，没有感觉到能支持协程级别的高并发。

**Comment by inhere** [comment]
在swoole里 每个请求 request 周期都是在一个协程里面的执行的

**Comment by akrick** [comment]
看到了 谢谢  非常感谢你的回复。 支持Swoft，一个全新的高并发PHP框架，一定可以成为行业的标杆。
