### ISSUE TITLE
频繁操作 srem 和 hdel 有可能删除不掉某些key

### ISSUE THREAD

**Issue by ytd7777** [swoft-cloud/swoft#573]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | x.y.z
| Swoole version      | 4.2.7
| PHP version         | 7
| Runtime environment | CentOS 7

**Details**

> srem 和 hdel  执行后 key或对象还是存在，后来加了deferCall 依然还有残留

```php
$res2 = $this->redis->hDel(REDIS_VIDE, $roomId);
if ($res2 == 0){
            $res2 = $this->redis->deferCall('hdel', [REDIS_VIDE, $roomId])->getResult();
}
```

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
