### ISSUE TITLE
mysql主从有时候回失效

### ISSUE THREAD

**Issue by kenny1002** [swoft-cloud/swoft#579]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      | 4.2.13 
| PHP version         | 7.3.1
| Runtime environment | CentOS 7

**Details**

> 用mysql连接池,select语句有时候会请求到主库去

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
@kenny1002 2.0已发布，建议升级到2.0
