### ISSUE TITLE
redis 连接池默认运行一段时间后，连接的是1库，最后操作变成了0库

### ISSUE THREAD

**Issue by YeDongaidiiqu** [swoft-cloud/swoft#580]
php版本  7.2.0
swoole    4.3
swoft      1.0.3

配置文件连接的是11库
使用swoft 的ws服务器，在应用初始化保存redis 连接池句柄，在ws onopen 的时候，操作的是11库。而是在onmessage  操作的时候redis操作到了0库。这个很诡异

![image](https://user-images.githubusercontent.com/25131877/54248028-20c8d180-4576-11e9-8b28-75e2bad369a5.png)
操作在11库
![image](https://user-images.githubusercontent.com/25131877/54248037-2a523980-4576-11e9-9bc1-01fc44bcb002.png)

![image](https://user-images.githubusercontent.com/25131877/54248047-30e0b100-4576-11e9-842f-e6becbbdb20f.png)
操作变成了0库

**Comment by php-lsys** [comment]
这框架连接池设计本身就存在问题.
检查下你代码 是不是有请求后没getResult 不管你要不要结果 都必须调用.不然连接取出后就不会交还给连接池

**Comment by YeDongaidiiqu** [comment]
能否详细说明下或者贴上代码，怎样getResult @php-lsys

**Comment by YeDongaidiiqu** [comment]
意思就是真能延迟收包的方式去操作redis

![image](https://user-images.githubusercontent.com/25131877/54259479-ce50da80-45a0-11e9-8713-0333301f7ea6.png)

@php-lsys

**Comment by shanliu** [comment]
延迟收包是swoole为了并发请求设计的 本身跟连接池没什么关系 没搞明白作者为什么要在connectioninterface上加上那两个方法 连接池那些接口还是抽离出来一个composer包好 目前所有框架都在组件化 核心越小越好 symfony跟zf这方面就做的很好 很多组件都是可以在任何框架中使用 不会绑死在框架中  而框架本身只是融合各个组件的一个桥梁 larval 新版本都开始组件化 orm已经基本脱离出来了 我也曾经用 唯一认同的就是contracts 思想 什么狗屁优雅都是自我感觉良好 内部组件严重相互依赖这点真把我恶心到了 个人感觉symfony4比larval很多方面都好很多 人家也没在页面上扯什么优雅

**Comment by kenny1002** [comment]
开多个连接池,一个连接池默认连接0库,一个连接池默认连接1库.
用0库连接池读取数据的时候有几率请求到1库去

**Comment by kenny1002** [comment]
跟mysql连接池的问题相似

**Comment by YeDongaidiiqu** [comment]
是的，框架的连接池还是有很多bug的，准备自己实现连接复用，不用框架的了

**Comment by php-lsys** [comment]
> 是的，框架的连接池还是有很多bug的，准备自己实现连接复用，不用框架的了

我也在自己实现一套 .实现后在分享出来.

**Comment by php-lsys** [comment]
> 是的，框架的连接池还是有很多bug的，准备自己实现连接复用，不用框架的了

准备把断链 主从加权重等一块封装了.

**Comment by YeDongaidiiqu** [comment]
> > 是的，框架的连接池还是有很多bug的，准备自己实现连接复用，不用框架的了
> 
> 准备把断链 主从加权重等一块封装了.
连接池链接的自动重连与恢复，连接池连接的消耗和补全，其实连接池本身就是一个队列，可以先考虑实现这个基础功能，不需要太复杂

**Comment by php-lsys** [comment]
已邮件给你 看有什么改进意见.

**Comment by stelin** [comment]
@YeDongaidiiqu 2.0已发布，建议升级到2.0
