### ISSUE TITLE
在定时任务中使用redis scan 命令，只能获取指定数据集前面10条

### ISSUE THREAD

**Issue by wp-breeder** [swoft-cloud/swoft#581]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      |  4.2.9 (by `php --ri swoole`)
| PHP version         | PHP 7.2.13 (cli) (by `php -v`)
| Runtime environment | Docker 

**Details**
在redis中模拟100条数据，使用scan迭代,。task中注入redis，设置setOption，使用scan迭代所有key,直接使用注入的redis对象，scan始终只能返回前10条数据，而使用 phpredis connection(修改源代码),则可正常迭代。是否因为使用闭包调用，未正常接收游标位置？

**使用phpredis connection**
```php
//模拟100条数据
for ($i = 0; $i <= 100; $i++) {
      $this->redis->set('test_'. $i, $i);
 }

// 在task中建立一个定时任务
   /**
     * redis pool
     * @var Redis
     */
    private $redis;

    /**
     * test redis
     * @Scheduled(cron="* * * * * *")
     */
    public function test()
    {
        if (!$this->redis) {
            /* @var PoolInterface $connectPool */
            $connectPool = App::getPool(RedisPool::class);
            /* @var SyncRedisConnection $client */
            $client = $connectPool->getConnection();
            $this->redis = $client->getConnection();
        }
        //设置迭代模式
        $this->redis->setOption(\Redis::OPT_SCAN, \Redis::SCAN_RETRY);
        $it = NULL;
        do {
            $keys = $this->redis->scan($it, 'redis_*');
            if ($keys !== FALSE) {
                foreach ($keys as $key) {
                    echo $key . PHP_EOL;
                }
            }

        } while ($it > 0);
    }
```
**swoft redis**
```php
//在task中建立一个定时任务
   /**
     * redis pool
     * @Inject()
     * @var Redis
     */
    private $redis;

    /**
     * test redis
     * @Scheduled(cron="* * * * * *")
     */
    public function test()
    {
        //设置迭代模式
        $this->redis->setOption(\Redis::OPT_SCAN, \Redis::SCAN_RETRY);
        $it = NULL;
        do {
            $keys = $this->redis->scan($it, 'redis_*');
            if ($keys !== FALSE) {
                foreach ($keys as $key) {
                    echo $key . PHP_EOL;
                }
            }

        } while ($it > 0);
    }
```

**Comment by lovephalcon1990** [comment]
你好 请问下 这个问题怎么解决的 我也遇到iterator 取不到的问题了

**Comment by wp-breeder** [comment]
我使用的是swoft 1.0, 如果是的话，修改源码，把  phpredis connection属性设置为public,然后直接使用$connection即可；
![image](https://user-images.githubusercontent.com/18710927/59412060-38228f80-8def-11e9-876a-bb2471b6f5a3.png)
> ps. 文件路径为 `/path/to/project/vendor/swoft/redis/src/AbstractRedisConnection`

**Comment by lovephalcon1990** [comment]
> 我使用的是swoft 1.0, 如果是的话，修改源码，把 phpredis connection属性设置为public,然后直接使用$connection即可；
> ![image](https://user-images.githubusercontent.com/18710927/59412060-38228f80-8def-11e9-876a-bb2471b6f5a3.png)
> 
> > ps. 文件路径为 `/path/to/project/vendor/swoft/redis/src/AbstractRedisConnection`

按照你说的方法试了下  结果：
![image](https://user-images.githubusercontent.com/7123896/59433027-379fee00-8e1b-11e9-8209-adb7c5fccf6f.png)
看了下源代码  应该是__call 魔术方法导致    call_user_func_array 正常。
` /** redis scan */
    public function scan(){
        /* @var PoolInterface $connectPool */
        $connectPool = App::getPool("gamestats");
        /* @var SyncRedisConnection $client */
        $client = $connectPool->getConnection();
        $it = null;
        $keys = call_user_func_array([$client, 'scan'],[&$it, "GSE:*"]);
//        $keys = $client->scan($it, "GSE:*");
        p([$it, $keys]);
    }`
