### ISSUE TITLE
注入配置值到属性时，数据错误

### ISSUE THREAD

**Issue by 1291061979** [swoft-cloud/swoft#582]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.0,
| Swoole version      | 4.3.0
| PHP version         |  7.3.2
| Runtime environment | Win10 wsl

**Details**

> 通过php数组配置文件，注入属性值时，数据丢失

```php
// 以下为会导致错误的配置内容
[
    "testgame" => [
        // 所用模板
        "template" => "gsk",
        // 服务端配置
        "server"   => [],
        // 客户端配置
        "client"   => [
            "logo" => "test",
        ],
    ],
];
// 以下为注入值的代码
/**
 * @Value("${config.game}")
 * @var array
 */
public $game;
// 以下为打印出来的内容，可以看到丢了字符串的配置
array(
    'testgame' => array(
        'server' => array(),
        'client' => array(
            'logo' => 'test',
        ),
    ),
);
```

> 我发现只要某一级里同时存在字符串和数组，注入后就容易把字符串给丢了

**Comment by huangzhhui** [comment]
已修复，请更新 swoft/framework 到 1.0.29 以上的版本
