### ISSUE TITLE
前置进程会一直重启

### ISSUE THREAD

**Issue by jury09** [swoft-cloud/swoft#583]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      | 4.0.4 (by `php --ri swoole`)
| PHP version         | 7.2.12 (by `php -v`)
| Runtime environment | Mac

**Details**

> Server 前置进程会一直重启

```php
namespace App\Boot;

use Swoft\App;
use Swoft\Process\Bean\Annotation\Process;
use Swoft\Process\Process as SwoftProcess;
use Swoft\Process\ProcessBuilder;
use Swoft\Process\ProcessInterface;

/**
 * Custom process
 * @Process(boot=true)
 */
class ServiceProcess implements ProcessInterface
{
    public function run(SwoftProcess $process)
    {
        $pname = App::$server->getPname();
        App::debug($pname."：服务启动成功");
        //ProcessBuilder::create('getGoodProcess')->start();
    }

    public function check(): bool
    {
        return true;
    }
}
```
![image](https://user-images.githubusercontent.com/2839476/54525171-8f5ec280-49ae-11e9-8ba7-00a3b61dd49b.png)

**Comment by hidahua** [comment]
这个自定义进程结束master进程自动启动一个新的;
需要挂起;
while (1)  ...

**Comment by jury09** [comment]
@hidahua 这个是框架自己启动的进程，要在哪里挂起？

**Comment by hidahua** [comment]
你的应用场景是啥样的呢?
我理解的:
这里的自定义进程,适合的场景应当是:
 需要长时间运行的程序,比如 使用while(true) 从消息队列中获取消息,然后处理的;

这个进程结束了,master进程则又会重新启动一个,所以你看到无限启动(进程结束=>启动新进程)

假设你的场景是运行一次执行某个事情,那不如就用定时任务呗;

**Comment by cirvor** [comment]
[Swoole Process->name](https://wiki.swoole.com/wiki/page/364.html)
这是因为swoft在实现自定义进程时使用到了swoole的`name`来命名进程名，从而进行自定义进程的检测
一旦发现这个名字的进程不存在 则再次启动
然而mac的环境 `name`是不支持的

可以的话 尽量使用定时任务去执行操作
如果实在需要使用自定义进程的话  mac可以安装docker用来跑swoft
[ Run Swoft with Docker](https://www.swoft.org/docs/v1/zh-CN/quickstart/docker-installation.html)

swoft源码：
```php
/**
     * Set the name of process
     *
     * @param string $name
     */
    public function name(string $name)
    {
        if (!PhpHelper::isMac()) {
            $this->process->name($name);
        }
    }
```

swoole_set_process_name is not supported on MacOS with swoft use it to realize custom process
you can use Docker to run swoft

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
