### ISSUE TITLE
Task投递的任务，部分报json_decode Syntax error

### ISSUE THREAD

**Issue by Abnerwei** [swoft-cloud/swoft#584]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 1.0.28
| Swoole version      | 4.3.1/4.0.3 (by `php --ri swoole`)
| PHP version         | 7.1.23 (by `php -v`)
| Runtime environment | Mac/CentOS 7

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
//vendor/swoft/rpc-client/src/Service.php#104
App::profileStart($profileKey);
            try {
                $result = $client->receive();
            } catch (\Throwable $ex) {
```
例如通过RPC调用服务50次，有10%几率失败，其中通过Task投递任务，到这一步`$client->receive()`获取的$result部分情况下为空，导致`json_decode`直接报错退出，业务失败。
> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by 601157475** [comment]
不是合法的json数据吧

**Comment by Abnerwei** [comment]
> 不是合法的json数据吧

业务json是合法的，这里我打过断点调试，`$result = $client->receive();`这里接收到的是空字符串

**Comment by stelin** [comment]
@Abnerwei 建议升级到2.0，2.0已经发布

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
