### ISSUE TITLE
不能向页面返回数据0 然后不能给数组下标为0的赋值

### ISSUE THREAD

**Issue by gaobinzhan** [swoft-cloud/swoft#585]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
提供一点示例代码呢

**Comment by stelin** [comment]
@gaobinzhan 建议升级到2.0
