### ISSUE TITLE
修改server.php中的配置加入参数：'task_enable_coroutine' => true报错

### ISSUE THREAD

**Issue by glenshappy** [swoft-cloud/swoft#588]
![QQ截图20190402171429](https://user-images.githubusercontent.com/17639873/55391177-65d79680-556b-11e9-8868-9f43ce2c77b7.png)
![QQ截图20190402171356](https://user-images.githubusercontent.com/17639873/55391180-67a15a00-556b-11e9-94b2-0c78dacd90f1.png)
![QQ图片20190402171732](https://user-images.githubusercontent.com/17639873/55391197-738d1c00-556b-11e9-884c-666dd48d063d.png)

**Comment by daydaygo** [comment]
@glenshappy swoft 那个版本

**Comment by stelin** [comment]
@glenshappy 建议升级到2.0
