### ISSUE TITLE
建议：请正确写单词

### ISSUE THREAD

**Issue by fsrm365** [swoft-cloud/swoft#59]
首先，对这个框架，我是非常肯定和认可的。确实也是很NB的一个框架。
当我去翻框架的时候发现，好多单词写错了，phpstorm有N多错单词的提示。举例：
current写成了currrent,switch写成了swith.

**Comment by stelin** [comment]
感谢对 Swoft 的支持，我们会努力做的更好！我们也就有修正的计划，现在正在继续中，包括所有代码注释英文化.

**Comment by huangzhhui** [comment]
有发现也请直接提pr帮助我们改善哦
