### ISSUE TITLE
css 样式加载无效。

### ISSUE THREAD

**Issue by ywqyuan** [swoft-cloud/swoft#590]
`Swoft 可以提供静态资源访问的支持，将静态文件放置于根目录下的 public 目录内即可，下面是一个引用的示例，注意引用时无需包含 public`
 
按照文档的这句话css 无法加载

**Comment by inhere** [comment]
注意要开启静态资源处理才行，默认是关闭的

**Comment by ywqyuan** [comment]
enable_static_handler=true 同样无效
![image](https://user-images.githubusercontent.com/17509915/55886490-6eb90f80-5bde-11e9-8e85-49b9f4336350.png)
框架全局就这两个地方配置了，都不知道哪里引用了？确定这个有生效嘛？

**Comment by ywqyuan** [comment]
![image](https://user-images.githubusercontent.com/17509915/55886568-960fdc80-5bde-11e9-873c-0f5da423a576.png)

**Comment by inhere** [comment]
只是 css 文件无法加载？ 其他静态资源呢？

**Comment by ywqyuan** [comment]
js 也是不行

**Comment by ywqyuan** [comment]
看了源码，没有看到对这块做处理的代码。

**Comment by inhere** [comment]
这个不是 swoft 处理的，直接是 swoole 处理的。

 `enable_static_handler` 也是swoole server的配置。参考：

https://wiki.swoole.com/wiki/page/783.html

**Comment by ywqyuan** [comment]
![J}Z7)V%BF$K(MX7I3Z$Z2~A](https://user-images.githubusercontent.com/17509915/55938882-fb131300-5c6e-11e9-9fba-e0adb286f2a1.png)
看到这个配置了
输出的是以下
![32HU$28Z`${DIU4_$H6B L5](https://user-images.githubusercontent.com/17509915/55938935-17af4b00-5c6f-11e9-9c13-fe1aa3811bd8.png)

**Comment by ywqyuan** [comment]
按照这种方式无效的

**Comment by inhere** [comment]
为啥无效，大家都是这么用的呀 ？？

**Comment by ywqyuan** [comment]
![LXOB}$1TBUE3LUNZY{40B_1](https://user-images.githubusercontent.com/17509915/55939127-90160c00-5c6f-11e9-8517-5e45402498d6.png)

**Comment by ywqyuan** [comment]
如果不行的话我只能用nginx 去做一个代理了。

**Comment by inhere** [comment]
好吧 用ng也可以，如果要使用静态资源，上线还是要配合ng的
