### ISSUE TITLE
本地无法访问

### ISSUE THREAD

**Issue by joyqhs** [swoft-cloud/swoft#593]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

使用docker
docker run -d -p 80:80 --name swoft  swoft/swoft
宿主IP可以正常访问，本地却无法访问
docker run -d -p 80:80 -v /e/www/swoft:/var/www/swoft  --name swoft  swoft/swoft、
将本地项目和宿主关联上之后，宿主机无法访问，本地也无法访问了

**Comment by sunnyos** [comment]
> Q	A
> Bug report?	yes/no
> Feature request?	yes/no
> Swoft version	x.y.z
> Swoole version	x.y.z (by `php --ri swoole`)
> PHP version	x.y.z (by `php -v`)
> Runtime environment	Win10/Mac/CentOS 7/Ubuntu/Docker etc.
> **Details**
> 
> > Describe what you are trying to achieve and what goes wrong.
> 
> ```
> // paste output here
> ```
> 
> > Provide minimal script to reproduce the issue
> 
> ```
> // paste code
> ```
> 
> 使用docker
> docker run -d -p 80:80 --name swoft swoft/swoft
> 宿主IP可以正常访问，本地却无法访问
> docker run -d -p 80:80 -v /e/www/swoft:/var/www/swoft --name swoft swoft/swoft、
> 将本地项目和宿主关联上之后，宿主机无法访问，本地也无法访问了

看一下swoft启动的http端口是多少，默认端口是 18306，为看到docker映射的端口是80，确认一下配置的端口
