### ISSUE TITLE
websocket的onOpen的$request参数为空！不知道是故意的不？

### ISSUE THREAD

**Issue by qidong364482611** [swoft-cloud/swoft#599]
`    public function onOpen(Server $server, Request $request, int $fd)
    {
        $server->push($fd,json_encode($server));
        $server->push($fd,json_encode($request));
    }`

环境swoole4.3.2 框架swoft-1.0.9 不知道是不是故意为空值？还是bug？
前端代码
`        var socket=new WebSocket("ws://swoft.swoole.com:9501/ws");
        socket.onopen=function(o){
            console.log(o);
        };
        socket.onmessage=function(data){
            console.log(JSON.parse(data.data));
        };
        socket.onclose=function(){

        };`

![屏幕快照 2019-04-18 下午4 34 31](https://user-images.githubusercontent.com/19990583/56348025-29a56680-61f8-11e9-8a93-638c4838955a.png)

**Comment by inhere** [comment]
没有啊 `$request` 肯定是存在的

**Comment by inhere** [comment]
没有啊 `$request` 肯定是存在的

**Comment by qidong364482611** [comment]
> 没有啊 `$request` 肯定是存在的

  我这真没有  是空值  。 $server 没问题。  $request 真是空值

**Comment by qidong364482611** [comment]
明白了  全私有的方法
