### ISSUE TITLE
感觉性能上还需要优化啊

### ISSUE THREAD

**Issue by CoolDUp** [swoft-cloud/swoft#601]
在一台机器上对比hello页面的压测数据
php fpm 3200qps,
swoft 2.0 4800qps,
easyswoole 8400qps

swoft 1.0 就不测了，我印象中比fpm还慢了。。

**Comment by huangzhhui** [comment]
你应该提供一下你设置的Worker数量

**Comment by CoolDUp** [comment]
这有详细的，debug和日志都是关闭的
https://github.com/CoolDUp/tmp/blob/master/easy.log
https://github.com/CoolDUp/tmp/blob/master/swoft2.log

**Comment by stelin** [comment]
底层需要开启AOP过滤，不是底层所有对象都会走代理，大大降低了性能。

**Comment by stelin** [comment]
由于开发，测试方便，快速暴露问题，底层没有过滤。
