### ISSUE TITLE
数据库实体多次fill会出现上一次fill的数据，先update再add

### ISSUE THREAD

**Issue by songmingming121** [swoft-cloud/swoft#605]
/**
	 * Notes:更新数据
	 * Date: 2019/3/27
	 * @param array $where
	 * @param array $updateDate
	 * @return mixed
	 */
	public function updateData(array $updateDate){
		return $this->xnIgetui->fill($updateDate)->update()->getResult();
	}

	/**
	 * Notes:插入数据
	 * Date: 2019/3/27
	 * @param array $addData
	 * @return mixed
	 */
	public function addGetui(array $addData){
		return $this->xnIgetui->fill($addData)->save()->getResult();
	}

**Comment by stelin** [comment]
@songmingming121 建议升级到2.0
