### ISSUE TITLE
初次学习swoft，咨询个问题，每次文件变更，会自动reload，但是貌似这个等待时间有点长啊，日常开发，频繁改动，这个等待时间不能忍啊？

### ISSUE THREAD

**Issue by hiicup** [swoft-cloud/swoft#606]
初次学习swoft，咨询个问题，每次文件变更，会自动reload，但是貌似这个等待时间有点长啊，日常开发，频繁改动，这个等待时间不能忍啊？

**Comment by hiicup** [comment]
感觉主要耗时在重新分析文件注解的操作上

**Comment by stelin** [comment]
你是用了文件映射吧，这个是文件射的问题，你可以实时在本地环境开发。

**Comment by hiicup** [comment]
> 你是用了文件映射吧，这个是文件射的问题，你可以实时在本地环境开发。

我是用docker来作为开发环境，代码是挂载到容器中运行

**Comment by stelin** [comment]
就是挂载的问题，你在本地开发就好了
