### ISSUE TITLE
我想要websocket服务是动态的uri我在websocket控制器应该怎么做

### ISSUE THREAD

**Issue by qidong364482611** [swoft-cloud/swoft#607]
![屏幕快照 2019-04-25 上午10 19 07](https://user-images.githubusercontent.com/19990583/56705472-957d5700-6743-11e9-8d37-9c049bb7ee1d.png)
如何能让  @WebSocket("/ws")  支持动态的uri。 
用 ws://swoft.swoole.com/ws/$userid  这种形式。

**Comment by inhere** [comment]
😄 没有支持 可以吧uid放在query里嘛

**Comment by inhere** [comment]
2.0 支持这样定义path了
