### ISSUE TITLE
webscoket onOpen中建立redis链接都是同步的

### ISSUE THREAD

**Issue by qwe840207103** [swoft-cloud/swoft#608]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    |no
| Swoft version       | 1.0.29
| Swoole version      | 4.2.13
| PHP version         | 7.2.17
| Runtime environment | Docker

**Details**
 server->defer函数导致执行onWsOpen时已退出协程 

<img width="1550" alt="WeChat8bc120cdc5557e7022899a2c8cd9faa3" src="https://user-images.githubusercontent.com/13118623/56718162-d5a6fe80-6770-11e9-8b3a-a38b6cf9ec46.png">

**Comment by inhere** [comment]
建议使用 2.0，全协程环境里了
