### ISSUE TITLE
这v2.0怎么没有vendor目录啊

### ISSUE THREAD

**Issue by xiaoxiczx** [swoft-cloud/swoft#609]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by huangzhhui** [comment]
1.0 就有了吗？ `composer install` 自己安装啊兄弟
