### ISSUE TITLE
2.0连接mysql，中文出现乱码

### ISSUE THREAD

**Issue by webphplove** [swoft-cloud/swoft#622]
使用swoft默认的mysql的charset，抑或是修改 charset=‘utf8'， 都会出现乱码

**Comment by stelin** [comment]
嗯，我们修复下这个bug, 有具体复现步骤么

**Comment by sakuraovq** [comment]
'db'       => [
        'class'    => Database::class,
        'dsn'      => 'mysql:dbname=swoft;host=127.0.0.1',
        'charset'  => 'utf8mb4',
    ],
在 app\bean.php  db 里面加上 charset 再试试
我这边测试 插入和 查询都是没有问题的

**Comment by sakuraovq** [comment]
@webphplove

**Comment by webphplove** [comment]
我已经试过了，还是出现乱码 @sakuraovq

**Comment by sakuraovq** [comment]
@webphplove 你确认下你的数据表真实的 charset呢

**Comment by sakuraovq** [comment]
发下你的配置呢 我看看 @webphplove

**Comment by webphplove** [comment]
表是这样设置的 CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci @sakuraovq

**Comment by sakuraovq** [comment]
@webphplove bean的db配置一起发我看看呀

**Comment by webphplove** [comment]
还有个问题，如果我将数据序列化存redis，如果重启，然后再向redis拿数据， 会报错
php代码：
```
    public function remember($key, \Closure $entity)
    {
        $value = Redis::get($key);
        if ($value == null) {
            $value = $entity();
            Redis::set($key, serialize($value), $this->cacheTime());
        }
        if (is_string($value))
            return unserialize($value);
        return $value;
    }
```
报错：
```
The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "App\Model\Entity\*" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition  in "/path/swoft/project/**"
```
过了缓存时间，可以正常获取，如果又重启， 还是报同样的错
2.0不支持序列化吗？
 @stelin

**Comment by webphplove** [comment]
@sakuraovq 
```
    'db'         => [
        'class'    => Database::class,
        'dsn'      => 'mysql:dbname=test;host=127.0.0.1',
        'charset' => 'utf8mb4',
        'username' => 'test',
        'password' => 'test',
    ],
```

**Comment by sakuraovq** [comment]
@webphplove 我这边和你配置一样的我写了一个单测都是没有问题都 

我数据表和你的配置一样的没有复现出问题

**Comment by sakuraovq** [comment]
@webphplove  Redis缓存对象可能有点问题吧 反序列化的时候不是报错了 是缺少对象依赖

**Comment by sakuraovq** [comment]
@webphplove 不要把实体丢进 redis 啊

**Comment by sakuraovq** [comment]
@webphplove  你缓存的 `$value` 是一个什么东西

**Comment by webphplove** [comment]
@sakuraovq  entity() 是实体，  存已serialize的实体, 从redis拿`$value`是字符串，然后反序列化成对象。
如果不重启服务器，存拿数据是正常的，就是重启后不行了

**Comment by sakuraovq** [comment]
@webphplove 重启redis 还是服务

**Comment by webphplove** [comment]
@sakuraovq 服务器...

**Comment by sakuraovq** [comment]
@webphplove 这个方法不用连续调用**两次**就要报错 不用重启 `http server`

**Comment by webphplove** [comment]
@stelin @sakuraovq  我刚刚发现了好像是实体的问题， 总服务器打印是正确的数据，但是response返回的时候就乱码了

**Comment by sakuraovq** [comment]
@webphplove  redis 这个写法有点错误的 如果你**反序列化**没有执行`闭包`就会报错

**Comment by sakuraovq** [comment]
@webphplove 嗯确实是 `response`  我们改下

**Comment by sakuraovq** [comment]
@webphplove  是json_encode的问题

**Comment by webphplove** [comment]
@sakuraovq  闭包没有问题，我发现 重启之后， 从redis拿数据，然后反序列化得到的对象名称是不一样
异常：
```
object(__PHP_Incomplete_Class)#13470 (20) {
  ["__PHP_Incomplete_Class_Name"]=>
  string(36) "App\Model\Entity\*"
  ["id":"App\Model\Entity\*":private]=>
````
正常：
```
object(App\Model\Entity\*_5ccc2b2ae2e59)#10619 (19) {
  ["id":"App\Model\Entity\*":private]=>
```
这个改如何解决？？

**Comment by sakuraovq** [comment]
@webphplove 闭包 重启了之后执行下在反序列化试试

**Comment by sakuraovq** [comment]
@webphplove 每个对象有一个 对象hash值 对象发送了改变 对象名称也不一样了哈
不要把对象存到redis 很不可靠 

response 中文乱码的事情要确认下 是因为json_encode 没有编码中文 然后和 content-type 又是text/html

**Comment by webphplove** [comment]
@sakuraovq  我倒是想存数组啊，但是没有fil填充成实体。所以只存这个对象了

**Comment by sakuraovq** [comment]
@webphplove toArray() 啊

**Comment by webphplove** [comment]
@sakuraovq  我觉得应该是重启之后， redis反序列化的实体对象，这个对象没有服务器annotation中注册， 所以报错。
我是说从数组变成实体对象。。

**Comment by sakuraovq** [comment]
嗯 这个暂时就不管了
中文乱码要确认下

**Comment by sakuraovq** [comment]
最好不要用这种方式 数组变成实体方式很多

**Comment by webphplove** [comment]
@sakuraovq  试了几个方法，syncOriginalAttributes方法可以让toArray()的数据填充进去了。
谢谢！

**Comment by stelin** [comment]
@webphplove reponse 中文乱码，是bug么

**Comment by stelin** [comment]
实体可以直接toArray

**Comment by webphplove** [comment]
@stelin  开始的时候，我以为是charset问题，结果是reponse问题
