### ISSUE TITLE
redis lpush key

### ISSUE THREAD

**Issue by CodeingMonkey** [swoft-cloud/swoft#624]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> redis写入string格式正常，key为appointment_follow_sms_count，后续redis使用lpush key为appointment_follow_sms的list失败，key改为appointment_follow_sms_list就正常

```php
            $this->redis->set('appointment_follow_sms_count', 1);

            $this->redis->lPush('appointment_follow_sms_list', json_encode($smsData));

```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by sakuraovq** [comment]
。。。 key 已经是string 类型存在了 ，当然不能作为 list存在

**Comment by CodeingMonkey** [comment]
> 。。。 key 已经是string 类型存在了 ，当然不能作为 list存在

审题不清晰啊  我两个key用的是不一样的 在redis客户端试了是可以的

**Comment by sakuraovq** [comment]
@CodeingMonkey 你估计是用的 1.0 把 。你可以使用 2.0 没有问题的
