### ISSUE TITLE
ab测试数据查询，使用连接池，会报SQLSTATE[08004] [1040] Too many connections错误

### ISSUE THREAD

**Issue by hihozhou** [swoft-cloud/swoft#625]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes/no
| Swoft version       | master（2.x）
| Swoole version      | 4.3.3
| PHP version         | 7.2.17
| Runtime environment | Ubuntu 18.04.

**Details**

> 使用ab测试数据查询，会报SQLSTATE[08004] [1040] Too many connections错误

php代码：

```php
/**
  * @RequestMapping(route="ts")
  *
  * @return false|string
  */
 public function ts()
 {
     DB::beginTransaction();
     $user = User::find(1);

     \sgo(function () {
         DB::beginTransaction();
         User::find(1);
     });

     return json_encode($user->toArray());
 }
```

`app\bean.php`链接池配置：
```php
'db' => [
    'class' => Database::class,
    'dsn' => 'mysql:dbname=test;host=127.0.0.1',
    'username' => 'root',
    'password' => 'root',
],

'db.pool' => [
    'class' => \Swoft\Db\Pool::class,
    'database' => \bean('db'),
    'minActive' => 50,
    'maxActive' => 100,
    'maxWait' => 0,
    'maxWaitTime' => 0,
    'maxIdleTime' => 60,
],
```

mysql 最大链接数为`151`，但`maxActive`只设置`100`

```bash
show variables like '%max_connections%'
```

ab测试后发现连接数达`152`

```bash
show full processlist;
```
![image](https://user-images.githubusercontent.com/12164486/57346709-29a6df80-7182-11e9-9aa3-deaaa89971bd.png)

> ab测试脚本

```bash
ab -n 10000 -c 2000  http://127.0.0.1:18306/dbTransaction/ts
```

另外，配置没有添加`db.pool`时候没有发生这个错误

**Comment by hihozhou** [comment]
这里找到原因了，是我配置问题，我配置了worker_num为4，没有仔细看文档
`每一个 worker 都会创建一个同样的连接池。`

**Comment by inhere** [comment]
连接池是每个worker进程一个。 你这里的最大连接数的乘以worker数，就超过了mysql的配置了
