### ISSUE TITLE
自动扫描文件需要考虑 `vim` 生成的交换文件 `*.php.swap` 扫描问题

### ISSUE THREAD

**Issue by inhere** [swoft-cloud/swoft#626]
自动扫描文件需要考虑 `vim` 生成的交换文件 `*.php.swap` 扫描问题，虽然可以通过设置不生成交换文件，但是不是最好的选择。

_Originally posted by @ywqyuan in https://github.com/swoft-cloud/swoft/issues/498#issuecomment-490356670_

**Comment by stelin** [comment]
已复查，目前已经兼容这种方式，只会扫描`.php`结尾文件。如果你还有问题，提出复现具体步骤。
