### ISSUE TITLE
swoft 2.0RPC服务端项目重启后，客户端项目不重启调用错误

### ISSUE THREAD

**Issue by hihozhou** [swoft-cloud/swoft#627]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Swoft version       | master（2.x）
| Swoole version      | 4.3.3
| PHP version         | 7.2.17
| Runtime environment | Ubuntu 18.04.

**Details**

> 我使用在是用RPC服务功能时，一个项目作为`RPC服务端`，一个项目作为`RPC客户端`，发现如果在`客户端项目`调用`服务端项目`后，`RPC服务端`的项目重启后，如果RPC客户端项目不重启会报`(InvalidArgumentException) json_decode error: Syntax error","file"`错误

RPC客户端项目控制台显示错误信息为：
```bash
[2019-05-09 11:17:10 *14954.3]  WARNING swSignalfd_onSignal (ERRNO 707): Unable to find callback function for signal Broken pipe: 13
```

**Comment by stelin** [comment]
我查下什么问题

**Comment by stelin** [comment]
@hihozhou 更新最新代码，已经修复bug, 新增断线重连

**Comment by hihozhou** [comment]
是否还没提交到仓库？
![image](https://user-images.githubusercontent.com/12164486/57500118-ae296780-7314-11e9-95ab-bc3bddc325d3.png)

**Comment by stelin** [comment]
swoft-component 组件更新就好了

**Comment by hihozhou** [comment]
ok
