### ISSUE TITLE
Run the server, extension 'swoole 2.x' is required!

### ISSUE THREAD

**Issue by coltguo** [swoft-cloud/swoft#629]
PHP Notice:  Use of undefined constant SWOOLE_PROCESS - assumed 'SWOOLE_PROCESS' in /var/www/swoft-ucoin/config/server.php on line 21
PHP Notice:  Use of undefined constant SWOOLE_SOCK_TCP - assumed 'SWOOLE_SOCK_TCP' in /var/www/swoft-ucoin/config/server.php on line 22
PHP Notice:  Use of undefined constant SWOOLE_PROCESS - assumed 'SWOOLE_PROCESS' in /var/www/swoft-ucoin/config/server.php on line 37
PHP Notice:  Use of undefined constant SWOOLE_SOCK_TCP - assumed 'SWOOLE_SOCK_TCP' in /var/www/swoft-ucoin/config/server.php on line 38
Run the server, extension 'swoole 2.x' is required!
Trace:
#0 /var/www/swoft-ucoin/vendor/swoft/http-server/src/Command/ServerCommand.php(174): Swoft\Helper\EnvHelper::check()
#1 /var/www/swoft-ucoin/vendor/swoft/http-server/src/Command/ServerCommand.php(31): Swoft\Http\Server\Command\ServerCommand->getHttpServer()
#2 /var/www/swoft-ucoin/vendor/swoft/framework/src/Helper/PhpHelper.php(47): Swoft\Http\Server\Command\ServerCommand->start()
#3 /var/www/swoft-ucoin/vendor/swoft/console/src/Router/HandlerAdapter.php(112): Swoft\Helper\PhpHelper::call(Array, Array)
#4 /var/www/swoft-ucoin/vendor/swoft/console/src/Router/HandlerAdapter.php(38): Swoft\Console\Router\HandlerAdapter->executeCommand(Object(Swoft\Http\Server\Command\ServerCommand), 'start', true, Array)
#5 /var/www/swoft-ucoin/vendor/swoft/console/src/Command.php(77): Swoft\Console\Router\HandlerAdapter->doHandler(Array)
#6 /var/www/swoft-ucoin/vendor/swoft/console/src/Console.php(30): Swoft\Console\Command->run()
#7 /var/www/swoft-ucoin/bin/swoft(5): Swoft\Console\Console->run()

是什么原因导致出现这个的啊？

**Comment by stelin** [comment]
你安装扩展 swoole 没

**Comment by coltguo** [comment]
> 你安装扩展 swoole 没

安装了大哥
