### ISSUE TITLE
2.0 快速生成实体类 如何操作

### ISSUE THREAD

**Issue by sevend93** [swoft-cloud/swoft#631]
2.0 快速生成实体类 如何操作？
没找到这个东西，手写好痛苦

**Comment by jlzan1314** [comment]
https://github.com/jlzan1314/swoft-entity

**Comment by sevend93** [comment]
> https://github.com/jlzan1314/swoft-entity

Tx.

**Comment by stelin** [comment]
@sevend93 官方马上回实现实体生成、迁移脚本

**Comment by sevend93** [comment]
@stelin  么么哒😘
