### ISSUE TITLE
Please consider making the accessibility of Swoft\Bean\Container::set as public.

### ISSUE THREAD

**Issue by clarifysky** [swoft-cloud/swoft#634]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 1.0.0
| Swoole version      | 4.0.3 (by `php --ri swoole`)
| PHP version         | 7.1.26 (by `php -v`)
| Runtime environment | Docker (Win10/Mac/CentOS 7/Ubuntu/Docker etc. )

**Details**

> Describe what you are trying to achieve and what goes wrong.

Please consider making the accessibility of `Swoft\Bean\Container::set` as `public`. In some scenarios, developers may instantiated an object manually, after current work finished, they may also use that object in other places, store this manually created object into container may reduce resources waste, and improve the performance.

In once you made the accessiblity of `Swoft\Bean\Container::set` as `public`, you may also need to provide a way to remove the manually stored object in `Swoft\Bean\Container`, e.g. via `unset`, which also should be `public`。

```php
   /**
     * 创建bean
     *
     * @param string           $name             名称
     * @param ObjectDefinition $objectDefinition bean定义
     *
     * @return object
     * @throws \ReflectionException
     * @throws \InvalidArgumentException
     */
    private function set(string $name, ObjectDefinition $objectDefinition)
    {
        // bean创建信息
        $scope             = $objectDefinition->getScope();
        $className         = $objectDefinition->getClassName();
        $propertyInjects   = $objectDefinition->getPropertyInjections();
        $constructorInject = $objectDefinition->getConstructorInjection();

        //......

        // 单例处理
        if ($scope === Scope::SINGLETON) {
            $this->singletonEntries[$name] = $object;
        }

        return $object;
    }
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
@clarifysky 1.x is not supported yet!
