### ISSUE TITLE
2.0 模型 toArray 不能全部导出属性的问题

### ISSUE THREAD

**Issue by jlzan1314** [swoft-cloud/swoft#642]
$admin=Admin::new();
		$data['admId']=null;
		$admin->fill($data);
		if ($admin->save()) {
			return $admin->toArray();
		}
toArray 这样才能导出admId,,这个和预期不符.toArray 应该到出全部的属性除了标记为hidden的属性
fill 会修改attriable,但是未修改的导出不了,

**Comment by sakuraovq** [comment]
@jlzan1314 fill 方法填充只能是数据库字段哈

**Comment by jlzan1314** [comment]
> 
> 
> @jlzan1314 fill 方法填充只能是数据库字段哈
admId 就是字段,数据库里面有的,,这里的是toArray问题,返回不了,如果fill 数组里有adm_id 那么就可以被toArray(),不然不能toArray()

**Comment by sunnyos** [comment]
> > @jlzan1314 fill 方法填充只能是数据库字段哈
> > admId 就是字段,数据库里面有的,,这里的是toArray问题,返回不了,如果fill 数组里有adm_id 那么就可以被toArray(),不然不能toArray()

如果你的Entity里面写的是成员属性是 adm_id 则只能在数组使用 adm_id，想要admId可以，需要Entity的成员属性为 admId

**Comment by sakuraovq** [comment]
```php
   /**
     * @Column(name="adminId")
     *
     * @var int
     */
    private $adminId;

    /**
     * @return mixed
     */
    public function getAdminId()
    {
        return $this->adminId;
    }

    /**
     * @param mixed $adminId
     */
    public function setAdminId($adminId): void
    {
        $this->adminId = $adminId;
    }
 //. ......

   /**
     * @RequestMapping(route="pick")
     *
     * @return false|string
     */
    public function pick()
    {
        User::firstOrCreate(['id' => 2], ['adminId' => 2]);
        User::new()->fill(['adminId'=>2])->toArray();
    }
```

亲测没有问题 数据库字段 是 `adminId`
