### ISSUE TITLE
公共函数加任何一个函数报错，程序启动不了

### ISSUE THREAD

**Issue by caige-phper** [swoft-cloud/swoft#643]
在app\Helper\Functions.php中加入任何一个函数，程序启动报错

PHP Fatal error:  Cannot redeclare test() (previously declared in /home/wwwroot/swoft2/app/Helper/Functions.php:7)

**Comment by sunnyos** [comment]
> 在app\Helper\Functions.php中加入任何一个函数，程序启动报错
> 
> PHP Fatal error: Cannot redeclare test() (previously declared in /home/wwwroot/swoft2/app/Helper/Functions.php:7)

使用function_exists判断函数是否已经存在，不存在才定义就好了
