### ISSUE TITLE
2.0的文件上传有问题， 文件已经上传成功了，但是不能moveTo到指定的位置

### ISSUE THREAD

**Issue by webphplove** [swoft-cloud/swoft#644]
2.0的文件上传有问题， 文件已经上传成功了，可以正常打印上传文件的信息，但是不能moveTo到指定的位置。

**Comment by stelin** [comment]
@webphplove 你看下是不是你权限问题，因为你已经都可以看到文件信息。

**Comment by webphplove** [comment]
@stelin 不是权限问题，已经给了777权限了

**Comment by sunnyos** [comment]
> @stelin 不是权限问题，已经给了777权限了

上传一下实例代码

**Comment by webphplove** [comment]
@sunnyos 
```

/**
 * @Controller()
 */
class UploadController
{
    /**
     *
     * @RequestMapping(route="/upload_file")
     * @param Request $request
     * @return array
     */
    public function uploadFile(Request $request){
        $file = $request->file('image');
        if ($file instanceof  UploadedFileInterface){
            $file->moveTo(\alias('@base/public').'/'.$file->getClientFilename());
            var_dump(\alias('@base/public').'/'.$file->getClientFilename());
        }

        return [];
    }
}
```

**Comment by sunnyos** [comment]
> @webphplove 你看下是不是你权限问题，因为你已经都可以看到文件信息。

moveTo方法为空，已经提交pr

**Comment by sunnyos** [comment]
> @sunnyos
> 
> ```
> 
> /**
>  * @Controller()
>  */
> class UploadController
> {
>     /**
>      *
>      * @RequestMapping(route="/upload_file")
>      * @param Request $request
>      * @return array
>      */
>     public function uploadFile(Request $request){
>         $file = $request->file('image');
>         if ($file instanceof  UploadedFileInterface){
>             $file->moveTo(\alias('@base/public').'/'.$file->getClientFilename());
>             var_dump(\alias('@base/public').'/'.$file->getClientFilename());
>         }
> 
>         return [];
>     }
> }
> ```
> 
> 很简单的代码，就是不能moveTo

如果着急使用请先按照这个链接的文件修改 [UploadedFile.php](https://github.com/sunnyos/swoft-component/blob/master/src/http-message/src/Upload/UploadedFile.php)
