### ISSUE TITLE
rpc解析问题

### ISSUE THREAD

**Issue by Xs2296** [swoft-cloud/swoft#645]
http://127.0.0.1:18306/rpc/getList

Rpc访问报错 
 Array to string conversion At /mnt/c/Apps/Web/swoft/vendor/swoft/rpc-client/src/Concern/ServiceTrait.php line 66

追踪结果如下：
{"jsonrpc":"2.0","error":{"code":-32600,"message":"Route(1.0-App\\Rpc\\Lib\\UserInterface) is not founded!","data":{"jsonrpc":"2.0"}}}

Swoft\Rpc\Response_5ce3d6f397e95 Object
(
    [result:Swoft\Rpc\Response:private] =>
    [error:Swoft\Rpc\Response:private] => Swoft\Rpc\Error_5ce3d6f392aa3 Object
        (
            [code:Swoft\Rpc\Error:private] => -32600
            [message:Swoft\Rpc\Error:private] => Route(1.0-App\Rpc\Lib\UserInterface) is not founded!
            [data:Swoft\Rpc\Error:private] => Array
                (
                    [jsonrpc] => 2.0
                )
        )
)

**Comment by inhere** [comment]
是否同时启动了 RPC server

**Comment by Xs2296** [comment]
是的，不能同时使用？

**Comment by daydaygo** [comment]
> 是的，不能同时使用？

@Xs2296 看到了 2 个报错, 先检查这2个地方:
- Array to string conversion
- App\Rpc\Lib\UserInterface

关于 rpc 的使用, 建议再看一遍文档:
- 使用 rpc client , 当然需要对应的 rpc server 响应的. swoft 是组件式的, 可以同时加载很多组件, 包括 rpc client 和 rpc server

**Comment by Xs2296** [comment]
> > 是的，不能同时使用？
> 
> @Xs2296 看到了 2 个报错, 先检查这2个地方:
> 
> * Array to string conversion
> * App\Rpc\Lib\UserInterface
> 
> 关于 rpc 的使用, 建议再看一遍文档:
> 
> * 使用 rpc client , 当然需要对应的 rpc server 响应的. swoft 是组件式的, 可以同时加载很多组件, 包括 rpc client 和 rpc server

重新测试了下官方的代码也是跑不起

**Comment by stelin** [comment]
@Xs2296 Array to string conversion 你怎么使用的，这里错误意思是，你传递参数类型不对

**Comment by Xs2296** [comment]
1.0-2.0 composer缓存问题

**Comment by MengYongKange** [comment]
我也遇到同样的问题，返回内容：{"jsonrpc":"2.0","error":{"code":-32600,"message":"Route(1.0-\\App\\Rpc\\Lib\\UserInterface) is not founded!","data":{"jsonrpc":"2.0"}}}
rpc确认已经开启了，我是通过官方给的request方法去请求官方给出的UserInterface接口
