### ISSUE TITLE
2.0 进程异常后，无法使用php bin/swoft http:start启动

### ISSUE THREAD

**Issue by f39516046** [swoft-cloud/swoft#646]
使用的是自建docker 环境， composer create-project安装的2.0版本
docker cmd 是  php bin/swoft http:start
平时应用是  docker restart对应用进行重启

但是在2.0版本上 由于docker restart 没有正常退出swoft进程，导致 第二次 后续所有的docker启动都是无法正常重启的， 也尝试过  php bin/swoft http:restart ，但是提示无法拉起进程，超时退出

这块在之前1.x版本上是可以 docker restart 随时都能正常重启运行的， 这块中间有什么差别吗？

**Comment by inhere** [comment]
应该有bug，我们追查下

**Comment by f39516046** [comment]
vendor/swoft/server/src/Server.php
isRunning()方法中的 return 改成 跟1.X版本的一样就正常启动了
return $masterPID > 0 && Process::kill($managerPID, 0);  //Process::kill($masterPID , 0) -> Process::kill($managerPID, 0)

**Comment by Ckeungkin** [comment]
删除runtime目录下单swoft,pid 再 php bin/swoft http:start
