### ISSUE TITLE
php bin/swoft  'Swoole\Runtime' not found 报错是什么情况

### ISSUE THREAD

**Issue by lzmshow** [swoft-cloud/swoft#647]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | 2.X
| Swoole version      | 4.0.3 (by `php --ri swoole`)
| PHP version         | 7.2.11 (by `php -v`)
| Runtime environment | Ubuntu/

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
PHP Fatal error:  Uncaught Error: Class 'Swoole\Runtime' not found in /home/vagrant/code/swoft1/bin/swoft:7
Stack trace:
#0 {main}
  thrown in /home/vagrant/code/swoft1/bin/swoft on line 7

Fatal error: Uncaught Error: Class 'Swoole\Runtime' not found in /home/vagrant/code/swoft1/bin/swoft:7
Stack trace:
#0 {main}
  thrown in /home/vagrant/code/swoft1/bin/swoft on line 7

**Comment by sunnyos** [comment]
> Q	A
> Bug report?	yes/no
> Feature request?	yes/no
> Swoft version	2.X
> Swoole version	4.0.3 (by `php --ri swoole`)
> PHP version	7.2.11 (by `php -v`)
> Runtime environment	Ubuntu/
> **Details**
> 
> > Describe what you are trying to achieve and what goes wrong.
> 
> ```
> PHP Fatal error:  Uncaught Error: Class 'Swoole\Runtime' not found in /home/vagrant/code/swoft1/bin/swoft:7
> Stack trace:
> #0 {main}
>   thrown in /home/vagrant/code/swoft1/bin/swoft on line 7
> 
> Fatal error: Uncaught Error: Class 'Swoole\Runtime' not found in /home/vagrant/code/swoft1/bin/swoft:7
> Stack trace:
> #0 {main}
>   thrown in /home/vagrant/code/swoft1/bin/swoft on line 7
> ```

报告你的swoole版本，swoole最好是4.2以上

**Comment by sunnyos** [comment]
> Q	A
> Bug report?	yes/no
> Feature request?	yes/no
> Swoft version	2.X
> Swoole version	4.0.3 (by `php --ri swoole`)
> PHP version	7.2.11 (by `php -v`)
> Runtime environment	Ubuntu/
> **Details**
> 
> > Describe what you are trying to achieve and what goes wrong.
> 
> ```
> PHP Fatal error:  Uncaught Error: Class 'Swoole\Runtime' not found in /home/vagrant/code/swoft1/bin/swoft:7
> Stack trace:
> #0 {main}
>   thrown in /home/vagrant/code/swoft1/bin/swoft on line 7
> 
> Fatal error: Uncaught Error: Class 'Swoole\Runtime' not found in /home/vagrant/code/swoft1/bin/swoft:7
> Stack trace:
> #0 {main}
>   thrown in /home/vagrant/code/swoft1/bin/swoft on line 7
> ```

升级swoole版本，升级到最新的

**Comment by lzmshow** [comment]
我用官方的Dockerfile也是这个版本，好像可以运行，有点奇怪

**Comment by mfkickdx78** [comment]
> 我用官方的Dockerfile也是这个版本，好像可以运行，有点奇怪

版本的问题，swoft 2.0 得用 swoole 4.3.3 的版本

docker pull下来的 默认 swoole 版本是 4.0.0
