### ISSUE TITLE
NOTICE  swFactoryProcess_finish (ERRNO 1005): connection[fd=27] does not exists

### ISSUE THREAD

**Issue by hihozhou** [swoft-cloud/swoft#648]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes/no
| Swoft version       | master（2.x）
| Swoole version      | 4.3.3
| PHP version         | 7.2.17
| Runtime environment | Ubuntu 18.04.
**Details**

> 使用连接池连接远程数据库时，过一段时间会提示`NOTICE  swFactoryProcess_finish (ERRNO 1005): connection[fd=15] does not exists`错误，然后如果查询数据会一直loading

![image](https://user-images.githubusercontent.com/12164486/58165613-b2f9fe00-7cba-11e9-9fc9-f24dfd56aa86.png)

但是数据库的连接还是保持链接，即使关闭项目服务也还是保持链接状态（正常测试，关闭服务的时候mysql连接池的连接是会自动断开的）

![image](https://user-images.githubusercontent.com/12164486/58165802-13893b00-7cbb-11e9-86bb-12f0a25e47a4.png)

**Comment by stelin** [comment]
@hihozhou 请问下怎么复现

**Comment by hihozhou** [comment]
1.`php bin/swoft http:start` 启动http服务
2.然后就是正常访问接口（接口中有查询数据库，使用数据库连接池）
3.等待一段时间后（大概20分钟左右），发现连接池的连接都在sleep中，并且再次调用不会使用原有连接池中的连接，并且如果有查询数据库的请求会一直pending，swoft控制台循环出现notice `swFactoryProcess_finish (ERRNO 1005): connection[fd=xx] does not exists`
4.然后我尝试关闭swoft服务，发现数据库中还是有大量sleep连接（确认是使用swoft连接池产生的，因为只有我开启swoft服务链接这个数据库）
5.这个是重点，这个数据库是`远程阿里云服务器上搭建数据库`，`本地局域网的数据库`没有发现该问题
6.数据库超时连接均是一样配置

![image](https://user-images.githubusercontent.com/12164486/58220172-6953f680-7d40-11e9-905d-8691b6bae8ed.png)

**Comment by hihozhou** [comment]
swFactoryProcess_finish (ERRNO 1005): connection[fd=xx] does not exists 是http客户端主动关闭，服务端控制台输出的提示

**Comment by hihozhou** [comment]
重新整理数据库连接问题 https://github.com/swoft-cloud/swoft/issues/653
