### ISSUE TITLE
例子:HomeController里面的hello方法,传参中文,返回乱码

### ISSUE THREAD

**Issue by Ckeungkin** [swoft-cloud/swoft#650]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0
| Swoole version      | 4.3.3 (by `php --ri swoole`)
| PHP version         | 7.2 (by `php -v`)
| Runtime environment | Docker etc.

![image](https://user-images.githubusercontent.com/16289487/58177163-6c1a0180-7cd6-11e9-820f-2f2e1fa9ce49.png)

**Comment by sunnyos** [comment]
已经修改完成，等待合并
