### ISSUE TITLE
数据库连接池连接等待一段时间后，关闭服务，连接未自动关闭

### ISSUE THREAD

**Issue by hihozhou** [swoft-cloud/swoft#653]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes/no
| Swoft version       | master（2.x）
| Swoole version      | 4.3.3
| PHP version         | 7.2.17
| Runtime environment | Ubuntu 18.04.

**Details**

> 开启数据库连接池后，在等待一段时间未使用时，关闭swoft服务，数据库连接池连接未关闭，一直处于sleep中

![image](https://user-images.githubusercontent.com/12164486/58225223-9fe73c80-7d53-11e9-9223-c10084e3453c.png)

**Comment by stelin** [comment]
@hihozhou 2.0.1 已修复
