### ISSUE TITLE
如何修改缓冲区大小

### ISSUE THREAD

**Issue by RogerDzhang** [swoft-cloud/swoft#654]
| Q                   | A
| ------------------- | -----
| Bug report?         |no
| Feature request?    |no
| Swoft version       | 1.0
| Swoole version      | 4.2.13
| PHP version         | 7.2.18
| Runtime environment | Mac

**Details**

> 需要插入数据库的字段中有一个longtext，字符串长度1913420，插入失败.
在swoole.log日志
`WARNING swReactor_write (ERROR 1201): data is too large, cannot exceed buffer size `
`WARNING swManager_check_exit_status: worker#18 abnormal exit, status=255, signal=0`
应该是，数据超过缓冲区大小了。

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
@RogerDzhang https://wiki.swoole.com/wiki/page/612.html

**Comment by stelin** [comment]
框架配置参数，配置整个项

**Comment by stelin** [comment]
建议升级到2.0, 2.0 已经正式发布，更稳定简单。
