### ISSUE TITLE
vue axios post 请求自动进行校验的问题

### ISSUE THREAD

**Issue by sevend93** [swoft-cloud/swoft#659]
使用vue axios 做post请求返回错误

 Argument 1 passed to Swoft\Validator\Validator_5ce94ba121f56::validate() must be of the type array, string given, called in /www/wwwroot/flower-system-api/vendor/swoft/http-server/src/Middleware/ValidatorMiddleware.php on line 58 At /tmp/Validator_5ce94ba121f56.php line 35

已经重新下载一个干净的swoft，把demo HomeController 的路由改成  /api/auth，
然后POST数据，就返回以上错误，而通过postman又没有该问题，看了请求的头部也没异样，非常的无解

**Comment by sevend93** [comment]
2.0版本

**Comment by sevend93** [comment]
找到问题了  当请求头的 Content-Type 为  application/json;charset=UTF-8  就会报以上错误

**Comment by sevend93** [comment]
请求头  'Content-Type': 'application/json' 改成这个就像没问题，按道理 application/json;charset=UTF-8 这个也是没错的吧

**Comment by stelin** [comment]
这个问题已经修复了，最近一两天会发一个版本

**Comment by stelin** [comment]
@sevend93 2.0.1 已修复
