### ISSUE TITLE
rpc-client Connection $port 类型错误

### ISSUE THREAD

**Issue by penghaicheng** [swoft-cloud/swoft#663]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | 2.0
| Swoole version      | 4.3.3
| PHP version         | 7.2
| Runtime environment | CentOS 7

**Details**
Connection.php
!$connection->connect($host,$port)
$port 类型错误，string要转为int型

**Comment by wujunze** [comment]
got it

**Comment by stelin** [comment]
2.0.1 已优化
