### ISSUE TITLE
2.0 redis使用env配置，redis配置项port和database提示RedisDb::getPort() must be of the type integer, string returned

### ISSUE THREAD

**Issue by donglf681** [swoft-cloud/swoft#664]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | 2.0 beta
| Swoole version      | 4.3.3
| PHP version         | PHP 7.2.15
| Runtime environment | linux

**Details**
app/bean.php
`'redis'      => [
        'class'    => RedisDb::class,
        'host'     => env('REDIS_HOST'),
        'port'     => env('REDIS_PORT'),
        'database' => env('REDIS_DB'),
        'options' => [
            'prefix' => env('REDIS_PREFIX')
        ],
    ],`
提示“ Pool error is Create connection error(Return value of Swoft\Redis\RedisDb::getPort() must be of the type integer, string returned) file(/var/www/vendor/swoft/redis/src/RedisDb.php) line (212) file=/var/www/vendor/swoft/connection-pool/src/AbstractPool.php line=184 At /var/www/vendor/swoft/redis/src/Redis.php line 157”
只有将env强制转int之后才能正常连接，改之后代码
`'redis'      => [
        'class'    => RedisDb::class,
        'host'     => env('REDIS_HOST'),
        'port'     => (int)env('REDIS_PORT'),
        'database' => (int)env('REDIS_DB'),
        'options' => [
            'prefix' => env('REDIS_PREFIX')
        ],
    ],`
建议底层直接强制转int而不是在bean.php上强制转换

**Comment by sakuraovq** [comment]
@donglf681  已经发布了哈

**Comment by donglf681** [comment]
端口解决了，但database未解决， Pool error is Create connection error(Return value of Swoft\Redis\RedisDb::getDatabase() must be of the type integer, string returned) file(/var/www/vendor/swoft/redis/src/RedisDb.php) line (220) file=/var/www/vendor/swoft/connection-pool/src/AbstractPool.php line=223 At /var/www/vendor/swoft/redis/src/Redis.php line 157

**Comment by sakuraovq** [comment]
😄 这个在 2.0.2 发布哈

**Comment by sakuraovq** [comment]
@donglf681 在主干上已经有了哈 感谢反馈
