### ISSUE TITLE
分页查询paginate方法指定多列返回结果集为空

### ISSUE THREAD

**Issue by abdons** [swoft-cloud/swoft#666]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.1
| Swoole version      |  4.3.4
| PHP version         | 7.2.18 
| Runtime environment | Mac

**Details**
> Describe what you are trying to achieve and what goes wrong

vendor/swoft/db/src/Query/Builder.php
分页查询指定多列没有任何响应，Builder.php文件中paginate方法下 $count = $this->getCountForPagination($columns)，得不到返回结果，没有任何报错信息，查询不指定指定单列没有影响能正确返回

> Provide minimal script to reproduce the issue

```php
$list = DB::table('ymt_project')->paginate($currentPage, $pageSize,['id','status']);
```

**Comment by sakuraovq** [comment]
@abdons  下午就可以了哈

**Comment by sakuraovq** [comment]
@abdons  解决了哈，在主干上  感谢反馈🙏
