### ISSUE TITLE
PHP引用传递修改失败

### ISSUE THREAD

**Issue by CodeingMonkey** [swoft-cloud/swoft#667]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    |no
| Swoft version       | 1.0
| Swoole version      | 4.3.0
| PHP version         | 7.2.14
| Runtime environment | CentOS 7

**Details**

> PHP引用传递修改失败

> Provide minimal script to reproduce the issue

```php
private function replaceOrderInfo(&$msgTemplate, $order)
    {
        foreach ($msgTemplate as &$item) {
            $item['content'] = preg_replace('#{orderNumber}#', $order['number'], $item['content']);
        }

    }
```
相同的代码，当方法调用放到同一文件下时，引用传递修改成功，使用bean方式传递数据到另一个文件中，引用传递修改失败，没有报错，不过结果不正确。
![image](https://user-images.githubusercontent.com/20737017/58525500-871cd200-81fe-11e9-80a6-76dec0bddd2a.png)
![image](https://user-images.githubusercontent.com/20737017/58525515-93a12a80-81fe-11e9-97d3-24ae7df64e03.png)
![image](https://user-images.githubusercontent.com/20737017/58525526-9b60cf00-81fe-11e9-921c-854f5ec65d3c.png)

**Comment by stelin** [comment]
@CodeingMonkey 这个bug 无解，因为 PHP 可变参数问题，你可以使用传递对象，解决这个问题
