### ISSUE TITLE
实体类join表，获取不到表的字段

### ISSUE THREAD

**Issue by abdons** [swoft-cloud/swoft#669]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 2.0.1
| Swoole version      | 4.3.4
| PHP version         | 7.2.18
| Runtime environment | Mac

**Details**

> Describe what you are trying to achieve and what goes wrong.

实体类join表，获取不到表的字段

> Provide minimal script to reproduce the issue

```php
Student::join("score","student.id","=","score.student_id")–>get();
```
获取不到score表的字段

**Comment by sakuraovq** [comment]
来咧 ～

**Comment by sakuraovq** [comment]
已修复
