### ISSUE TITLE
ValidatorMiddleware 没有对raw方式提交的数据做兼容

### ISSUE THREAD

**Issue by yangjianfeng9527** [swoft-cloud/swoft#670]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | 2.0.1
| Swoole version      | 4.2
| PHP version         | 7.2
| Runtime environment | Mac

**Details**

Swoft\Http\Server\Middleware\ValidatorMiddleware 中间件没有处理raw方式提交json字符串的情况做处理

$request->getParsedBody();获取到的可能是个字符串

Swoft\Validator\Validator中的validate方法第一个参数是数组，所以会报错。

```php
$data = $request->getParsedBody();
        $query = $request->getQueryParams();

        // Fix body is empty string
        $data = empty($data) ? [] : $data;

        /* @var Validator $validator*/
        $validator = BeanFactory::getBean('validator');

        /* @var Request $request*/
        [$data, $query] = $validator->validate($data, $className, $method, $query);
        $request = $request->withParsedBody($data)->withParsedQuery($query);
```

我把它改成了

```php
 if ($request->getMethod() == 'POST') {
            $data = $request->getParsedBody();
            if (is_string($data)) {
                $data = json_decode($data, true);
            }
        }
        $query = $request->getQueryParams();

        // Fix body is empty string
        $data = empty($data) ? [] : $data;

        /* @var Validator $validator */
        $validator = BeanFactory::getBean('validator');

        /* @var Request $request */
        [$data, $query] = $validator->validate($data, $className, $method, $query);
        $request = $request->withParsedBody($data)->withParsedQuery($query);
```
暂时没问题

**Comment by stelin** [comment]
@yangjianfeng9527 你使用方式不对，你请求conten-type 为application/json 会自动解析成数组的

**Comment by stelin** [comment]
默认支持两种，用户可以扩展

```
'httpRequest'     => [
                'parsers' => [
                    ContentType::XML  => bean(XmlRequestParser::class),
                    ContentType::JSON => bean(JsonRequestParser::class),
                ]
            ],
```

**Comment by SuKerd** [comment]
> 
> 
> 默认支持两种，用户可以扩展
> 
> ```
>            'httpRequest'     => [
>                 'parsers' => [
>                     ContentType::XML  => bean(XmlRequestParser::class),
>                     ContentType::JSON => bean(JsonRequestParser::class),
>                 ]
>             ],
> ```

没用

**Comment by SuKerd** [comment]
> 
> 
> @yangjianfeng9527 你使用方式不对，你请求conten-type 为application/json 会自动解析成数组的

application/json 会自动解析成数组，但 application/json;charset=utf-8 不会，去掉charset=utf-8 就解决问题，如果去不掉还是用楼主的方法吧

**Comment by yangjianfeng9527** [comment]
好的，试试


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: SuKerd <notifications@github.com>
发送时间: 2019年5月30日 16:54
收件人: swoft-cloud/swoft <swoft@noreply.github.com>
抄送: yangjianfeng9527 <403565474@qq.com>, Mention <mention@noreply.github.com>
主题: 回复：[swoft-cloud/swoft] ValidatorMiddleware 没有对raw方式提交的数据做兼容 (#670)



 
@yangjianfeng9527 你使用方式不对，你请求conten-type 为application/json 会自动解析成数组的
  
application/json 会自动解析成数组，但 application/json;charset=utf-8 不会，去掉charset=utf-8 就解决问题，如果去不掉还是用楼主的方法吧
