### ISSUE TITLE
自定义配置文件该如何加载?

### ISSUE THREAD

**Issue by Ckeungkin** [swoft-cloud/swoft#671]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | 2.0.1-beta
| Swoole version      | 4.3.4
| PHP version         | 7.2
| Runtime environment | Docker etc.

**Details**
1.bean.php文件里配置config不起效
![image](https://user-images.githubusercontent.com/16289487/58625055-35f70600-8304-11e9-986c-a23850dde20f.png)
![image](https://user-images.githubusercontent.com/16289487/58624747-8ae64c80-8303-11e9-8892-0c8bede00770.png)
2.那么在config目录下的user目录下的配置文件怎么读取?
![image](https://user-images.githubusercontent.com/16289487/58625108-52933e00-8304-11e9-9922-e1c9f3d35a72.png)
看文档,通过配置env参数也并没有像文档描述的一样,会合并user目录下的配置文件
![image](https://user-images.githubusercontent.com/16289487/58625282-b61d6b80-8304-11e9-8e40-6beebcd650fa.png)
![image](https://user-images.githubusercontent.com/16289487/58625268-af8ef400-8304-11e9-8b3b-d91b2f6ffbcc.png)

**Comment by stelin** [comment]
@Ckeungkin  具体描述下你的问题， https://www.swoft.org/docs/2.x/zh-CN/config/config.html 可以看下使用文档

**Comment by Ckeungkin** [comment]
@stelin 谢谢回复,我想表达的意思是,按照文档描述,只要在bean.php的config选项配置env=>'user',那么是可以读取到config/user目录下的配置文件的,但是实际是并不行.我尝试查看swoft/config组件查找答案,但是能力有限,所以麻烦您们看看这个问题是bug?还是功能未开发?还是文档描述有误?谢谢
