### ISSUE TITLE
2.0.0-beta 如何监听CONNECT以及RECEIVE

### ISSUE THREAD

**Issue by 6xiaowu9** [swoft-cloud/swoft#672]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 2.0.0-beta
| Swoole version      | 4.3.1
| PHP version         | 7.2.15
| Runtime environment | CentOS 7

引用实例开发`START`可以监听到 但是`CONNECT` 和 `RECEIVE`不知到为什么监听不到 
以下是我的代码。
然后可否分隔开http和rpc的监听事件 我分别单独启动服务的时候有这个需求

```php

<?php declare(strict_types=1);

namespace App\Listener;

use ReflectionException;
use Swoft\Bean\Exception\ContainerException;
use Swoft\Event\Annotation\Mapping\Listener;
use Swoft\Event\EventHandlerInterface;
use Swoft\Event\EventInterface;
use Swoft\Log\Helper\CLog;
use Swoft\Server\Swoole\SwooleEvent;

/**
 * Class ConnectListener
 *
 * @Listener(SwooleEvent::CONNECT)
 */
class ConnectListener implements EventHandlerInterface
{
    /**
     * @param EventInterface $event
     *
     * @throws ReflectionException
     * @throws ContainerException
     */
    public function handle(EventInterface $event): void
    {
        var_dump('-----------------[CONNECT]');
    }
}
```

**Comment by 6xiaowu9** [comment]
翻了半天源码通过 
```php
/*
 * @Listener(ServiceServerEvent::CONNECT)
*/
```
解决了CONNECT的监听但是Receive 如何监听 源码里好像没有做hook？

**Comment by 6xiaowu9** [comment]
还有就是我这样做是否正确呢？

**Comment by 6xiaowu9** [comment]
我从bean 给rpcServer配置了on 
```php
'on'       => [
    SwooleEvent::RECEIVE   => bean(ReceiveListener::class),
],
```
将RECEIVE 指向我自己的ReceiveListener 做到了RECEIVE监听 
但是这样做是不是不再是从框架内部暴露出来的HOOK 会不会有影响？ 是否正确？

**Comment by stelin** [comment]
@6xiaowu9 可以分开启动，首先是你要监听 RPC 的CONNECT以及RECEIVE么

**Comment by 6xiaowu9** [comment]
查看了源码，现在已经实现了监听，向上面说的实现了。我现在想了解下如何配置redis 因为我是一个redis服务 但是我需要使用不同的库 我应该怎么去配置 这应该不属于集群配置，看到文档上的配置只有单个库的配置？另外用了文档的配置，当我配置redis的时候有一个报错 readTimeout 预期是string但传入int的错误。我看了源码 源码没有强转 但是传进去的参数确实是int并且超时时间应该预期应该是int才对吧。

**Comment by stelin** [comment]
你的需求是根据什么来切换数据库，

**Comment by stelin** [comment]
readTimeout 预期是string但传入int 这个已经底层解决了，后续版本更新，注入属性值的时候检查了类型，自动转换

**Comment by 6xiaowu9** [comment]
我是根据不请求源区分不同的客户端 然后分别使用不同的库隔离开缓存数据库，这个需求1.0版本的配置是可以满足我的需求的。但是2.0不知道该如何去配置了

**Comment by stelin** [comment]
@6xiaowu9 1.0 你们怎么使用的，2.0 我可以提供一个接口，selectDb 使用的自动切换，还没做，只是有个想法。

**Comment by 6xiaowu9** [comment]
1.0我配置的多个连接池来解决这个问题。我希望是从配置文件和注解来解决这个问题😀 直接可以@Inject不同库的连接池
