### ISSUE TITLE
建议：希望swoft2.0能提供rpc客户端自定义处理结果的功能

### ISSUE THREAD

**Issue by hihozhou** [swoft-cloud/swoft#673]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes/no
| Swoft version       | master（2.x）
| Swoole version      | 4.3.3
| PHP version         | 7.2.17
| Runtime environment | Ubuntu 18.04.

**Details**

> 由于系统拆分成3个RPC服务系统，有时候一个接口内部可能需要调用3到4次不同RPC服务，现在没有自定义处理结构，只抛出简单的错误，开发时候难以快速排查到底是哪个RPC服务出问题

**Comment by stelin** [comment]
@hihozhou 这个需要仔细想下，用那种方式提供
