### ISSUE TITLE
swoft2.0 restful路由中文字符问题

### ISSUE THREAD

**Issue by chenzx023** [swoft-cloud/swoft#678]
中文字符通过restful get方法，框架接收到的字符确实框架自动转换成某个字母，或者出现报错路由未定义

**Comment by xiaoxiczx** [comment]
PHP版本7.3 ,swoole版本 4.3.3,OS: macOS

**Comment by inhere** [comment]
提供一个可复现的demo代码

**Comment by xiaoxiczx** [comment]
> 提供一个可复现的演示代码

/**
     * 搜索某个资源
     * @RequestMapping(route="search/{name}", method={RequestMethod::GET})
     * @param Request $request
     * @param string $name
     * @return array
     */
    public function search(Request $request, string $name)
    {
        try {
            $data = $this->resource->search($name);

            if (!$data->toArray()) {
                return res_data(0, '暂无搜索内容');
            }
            return res_data(1, 'success', $data);
        }catch (\Exception $e) {
            return res_data(0, '数据库出错: ' . $e->getMessage());
        }
    }


public function search(string $field): object
    {
        return Resource::where('name', 'like', "%{$field}%")->get();

    }


如果name值为中文就会出现上诉问题  postman测试会出现这个问题

**Comment by inhere** [comment]
我在单元测试里测试 是没有问题的呢

**Comment by sunnyos** [comment]
> > 提供一个可复现的演示代码
> 
> /**
> * 搜索某个资源
> * @RequestMapping(route="search/{name}", method={RequestMethod::GET})
> * @param Request $request
> * @param string $name
> * @return array
> */
> public function search(Request $request, string $name)
> {
> try {
> $data = $this->resource->search($name);
> 
> ```
>         if (!$data->toArray()) {
>             return res_data(0, '暂无搜索内容');
>         }
>         return res_data(1, 'success', $data);
>     }catch (\Exception $e) {
>         return res_data(0, '数据库出错: ' . $e->getMessage());
>     }
> }
> ```
> 
> public function search(string $field): object
> {
> return Resource::where('name', 'like', "%{$field}%")->get();
> 
> ```
> }
> ```
> 
> 如果name值为中文就会出现上诉问题 postman测试会出现这个问题

![image](https://user-images.githubusercontent.com/6112421/59001954-354dfa80-8843-11e9-89ed-6bb3dbc37977.png)
这边按照这样操作也是没有问题的
