### ISSUE TITLE
2.0验证器不是必传参数如何定义

### ISSUE THREAD

**Issue by yangjianfeng9527** [swoft-cloud/swoft#683]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes/no
| Swoft version       | 2.0.1
| Swoole version      | 4.3.3
| PHP version         | 7.2
| Runtime environment | Mac

**Details**

验证规则怎么设置像laravel中的required规则，如果传了参数就验证，不传就不验证

```php
/**
     * @IsString(message="格式有误")
     * @Length(min=6, max=12, message="格式有误")
     * @var string
     */
    protected $account = '1';
```

如上代码，我想实现前端传了account参数就进行验证，不传就不验证，直接使用默认值

**Comment by stelin** [comment]
不是必须传递参数，加一个默认值，加了默认值的就可以选的

**Comment by yangjianfeng9527** [comment]
加了默认值，默认值就会走验证，希望有一个注解，定义之后不传就不走任何验证，这样我默认值就可以写null了，比如查询业务，查询条件有多个，都不是必传，如果我定义了默认值，我就不知道前端是传了还是没传（有可能前端传的就是这个默认值），所以这个时候默认设为null是最好的


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 李霖 <notifications@github.com>
发送时间: 2019年6月4日 13:28
收件人: swoft-cloud/swoft <swoft@noreply.github.com>
抄送: yangjianfeng9527 <403565474@qq.com>, Author <author@noreply.github.com>
主题: 回复：[swoft-cloud/swoft] 2.0验证器不是必传参数如何定义 (#683)

**Comment by stelin** [comment]
@yangjianfeng9527 这种场景可以业务解决，不是有默认值么
