### ISSUE TITLE
自定义进程while (true) zm_deactivate_swoole (ERROR 503): Fatal error: Allowed memory size

### ISSUE THREAD

**Issue by JoeXiong** [swoft-cloud/swoft#684]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | 1.0.0
| Swoole version      |  4.3.1
| PHP version         | 7.2.11
| Runtime environment | CentOS 7

**Details**
> swoole.log:
PHP Fatal error:  Allowed memory size of 1077936128 bytes exhausted (tried to allocate 126976 bytes) in /data/release/swoft/app/MessageResponse/Init/DataConsume/KafkaConsumer.php on line 88
[2019-06-03 14:33:32 @9157.0]   ERROR   zm_deactivate_swoole (ERROR 503): Fatal error: Allowed memory size of 1077936128 byt
es exhausted (tried to allocate 126976 bytes) in /data/release/swoft/app/MessageResponse/Ini
t/DataConsume/KafkaConsumer.php on line 88.

```php
/**
 * 自定义进程启动Bean对象进行消费
 * Class KafkaProcess - Custom process
 *
 * @Process(name="kafka", coroutine=false, boot=true, num=1)
 * @package App\Boot
 */
class KafkaProcess implements ProcessInterface
{
    public function run(SwoftProcess $process)
    {
        $pname = \Swoft::$server->getPname();
        $processName = "$pname kafka process";
        $process->name($processName);

        $kafkaBoot = App::getBean('KafkaInit');

        $kafkaBoot->run();//执行kafka消费数据

    }

    public function check(): bool
    {
        return true;
    }
}
```
```php
// 初始化kafka while (true) 进行消费 $consumer = new \RdKafka\KafkaConsumer($conf);
public function run($consumer)
{
        while (true) {
            $message = $consumer->consume(120 * 1000); // swoole.log 报错的具体行数
            if ($message->err != 'RD_KAFKA_RESP_ERR_NO_ERROR') {
                $this->kafkaException->setException($message->err, $message);
            } else {
                //真正处理数据的业务逻辑
                $this->exec($message);
            }

        }
}
```
>猜测原因1： 7.2.11+swoole4.3.1 gc回收内存bug，现按照这个猜测升级了swoole版本，升级到了swoole4.3.4，暂时修改后还未再次出现内存泄露问题

>2019-06-10 18:48:16 swoole4.3.1 升级到swoole4.3.4 再次发生内存泄露问题
PHP Fatal error:  Allowed memory size of 1077936128 bytes exhausted (tried to allocate 40960 bytes) in /data/release/swoft/apps/app/MessageResponse/Init/DataConsume/KafkaConsumer.php on line 89
[2019-06-10 18:48:16 @26042.0]  ERROR   zm_deactivate_swoole (ERRNO 503): Fatal error: Allowed memory size of 1077936128 bytes exhausted (tried to allocate 40960 bytes) in /data/release/swoft/apps/app/MessageResponse/Init/DataConsume/KafkaConsumer.php on line 89

>是否能够主动回收？应该怎么主动回收

>或者有什么方法能够去检查具体的错误？能否能提供点思路

**Comment by JoeXiong** [comment]
pidstat -r -p PHP_PID 1 监控内存使用情况如下：
04:10:57 PM   UID       PID  minflt/s  majflt/s     VSZ    RSS   %MEM  Command
04:10:58 PM   996      7672      0.00      0.00 2441372  33328   0.42  php
04:10:59 PM   996      7672      2.00      0.00 2441372  33328   0.42  php
04:11:00 PM   996      7672     64.00      0.00 2443420  33340   0.42  php
04:11:01 PM   996      7672      7.00      0.00 2443420  33340   0.42  php
04:11:02 PM   996      7672      0.00      0.00 2443420  33340   0.42  php
04:11:03 PM   996      7672      0.00      0.00 2443420  33340   0.42  php
04:11:04 PM   996      7672      0.00      0.00 2443420  33340   0.42  php
04:11:05 PM   996      7672      0.00      0.00 2443420  33340   0.42  php
04:11:06 PM   996      7672     10.00      0.00 2443420  33340   0.42  php
04:11:07 PM   996      7672     10.00      0.00 2443420  33340   0.42  php
04:11:08 PM   996      7672      9.00      0.00 2443420  33340   0.42  php
04:11:09 PM   996      7672      9.00      0.00 2443420  33600   0.42  php
04:11:10 PM   996      7672      0.00      0.00 2443420  33600   0.42  php
04:11:11 PM   996      7672     13.00      0.00 2443420  33600   0.42  php
04:11:12 PM   996      7672     24.00      0.00 2443420  33600   0.42  php
04:11:13 PM   996      7672      0.00      0.00 2443420  33600   0.42  php
04:11:14 PM   996      7672     17.00      0.00 2443420  33600   0.42  php
04:11:15 PM   996      7672      0.00      0.00 2443420  33600   0.42  php
04:11:16 PM   996      7672      0.00      0.00 2443420  33600   0.42  php
04:11:17 PM   996      7672     11.00      0.00 2443420  33600   0.42  php
04:11:18 PM   996      7672     13.00      0.00 2443420  33864   0.42  php
04:11:19 PM   996      7672      0.00      0.00 2443420  33864   0.42  php
04:11:20 PM   996      7672      0.00      0.00 2443420  33864   0.42  php
04:11:21 PM   996      7672      0.00      0.00 2443420  33864   0.42  php
04:11:22 PM   996      7672      0.00      0.00 2443420  33864   0.42  php
04:11:23 PM   996      7672      0.00      0.00 2443420  33864   0.42  php
04:11:24 PM   996      7672      0.00      0.00 2443420  33864   0.42  php
04:11:25 PM   996      7672      0.00      0.00 2443420  33864   0.42  php
04:11:26 PM   996      7672     12.00      0.00 2443420  33864   0.42  php
04:11:27 PM   996      7672      3.00      0.00 2443420  33864   0.42  php
04:11:28 PM   996      7672      5.00      0.00 2443420  33864   0.42  php
04:11:29 PM   996      7672     38.00      0.00 2443420  34128   0.43  php
04:11:30 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:31 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:32 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:33 PM   996      7672      3.00      0.00 2443420  34128   0.43  php
04:11:34 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:35 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:36 PM   996      7672      2.00      0.00 2443420  34128   0.43  php
04:11:37 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:38 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:39 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:40 PM   996      7672     31.00      0.00 2443420  34128   0.43  php
04:11:41 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:42 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:43 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:44 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:45 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:46 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:47 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:48 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:49 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:50 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:51 PM   996      7672     13.00      0.00 2443420  34128   0.43  php
04:11:52 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:53 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:54 PM   996      7672      0.00      0.00 2443420  34128   0.43  php
04:11:55 PM   996      7672     16.00      0.00 2443420  34392   0.43  php
04:11:56 PM   996      7672      1.00      0.00 2443420  34392   0.43  php
04:11:57 PM   996      7672      0.00      0.00 2443420  34392   0.43  php
04:11:58 PM   996      7672      0.00      0.00 2443420  34392   0.43  php
04:11:59 PM   996      7672      0.00      0.00 2443420  34392   0.43  php
04:12:00 PM   996      7672     36.00      0.00 2443420  34392   0.43  php
04:12:01 PM   996      7672      0.00      0.00 2443420  34392   0.43  php
04:12:02 PM   996      7672      1.00      0.00 2443420  34392   0.43  php
04:12:03 PM   996      7672      0.00      0.00 2443420  34392   0.43  php
04:12:04 PM   996      7672      0.00      0.00 2443420  34392   0.43  php
04:12:05 PM   996      7672      0.00      0.00 2443420  34392   0.43  php

> RSS 和 %MEM 不会释放，只会一直增加

**Comment by JoeXiong** [comment]
> 补充完整文件
```php
<?php
/**
 * Date: 2019/4/12
 */

namespace App\MessageResponse\Init\DataConsume;

use Swoft\App;
use Swoft\Bean\Annotation\Bean;
use Swoft\Bean\Annotation\Inject;

/**
 * @Bean()
 * Date: 2019/4/16
 * kafka Consumer消费kafka Producer的数据
 */
class KafkaConsumer
{
    /**
     * Date: 2019/4/17
     * @Inject()
     * @var \App\MessageResponse\Init\Exception\KafkaException
     */
    public $kafkaException;

    /**
     * Date: 2019/4/17
     */
    public $msg;

    /**
     * Date: 2019/4/19
     */
    public $type;

    /**
     * Date: 2019/4/19
     */
    public $table;

    /**
     * Date: 2019/4/19
     * @Inject()
     * @var \App\MessageResponse\Init\DataConsume\TableConsumer\OrderConsumer
     */
    public $order;

    /**
     * Date: 2019/4/19
     * @Inject()
     * @var \App\MessageResponse\Init\DataConsume\TableConsumer\TurnOrderConsumer
     */
    public $turnOrder;

    /**
     * Date: 2019/4/23
     * @Inject()
     * @var \App\MessageResponse\Init\DataConsume\TableConsumer\OrderRemarkConsumer
     */
    public $orderRemark;

    /**
     * Date: 2019/4/23
     * @Inject()
     * @var \App\MessageResponse\Init\DataConsume\TableConsumer\VircallRecordConsumer
     */
    public $vircallRecord;

    /**
     * Date: 2019/4/20
     */
    public $tables = [
        'order',
        'turnOrderApply',
        'orderRemark',
        'vircallRecord',
    ];

    /**
     * Date: 2019/4/19
     * @param $consumer
     * @return void
     */
    public function consumeData($consumer)
    {
        //consumer 一直在消费Topic中的数据
        try {
            while (true) {
                $message = $consumer->consume(120 * 1000);

                if ($message->err != 'RD_KAFKA_RESP_ERR_NO_ERROR') {//kafka异常情况
                    $this->kafkaException->setException($message->err, $message);
                } else {
                    //真正处理数据的业务逻辑
                    $this->exec($message);
                }

            }
        } catch (\Throwable $throwable) {
            $message = sprintf('%s %s %s', $throwable->getMessage(), $throwable->getFile(), $throwable->getLine());
            App::error($message);
            trigger_error($message, E_USER_ERROR);
        }
    }

    /**
     * Date: 2019/4/19
     * @param $message
     * @return void
     */
    public function exec($message)
    {
        $key = json_decode($message->key);//保存了操作的数据库，数据表

        $database = $key->database;//获取数据库名称
        $table = $key->table;//获取表名称

        if ($database != 'shanxiuxia3_product') {//数据库不是需求数据库的情况，直接退出
            return;
        }

        $msg = json_decode($message->payload);//我们自己的消息
        $this->type = $msg->type;//数据操作类型
        $this->msg = $msg;//binlog日志内容

        $table = $this->handleTableName($table);


        $this->table = $table;

        if (in_array($table, $this->tables)) {
            App::info('kafka原数据'.json_encode($this->msg));
            $this->consume();
        }

    }

    /**
     * Date: 2019/4/19
     * @return void
     */
    public function consume()
    {
        //判断订单类型
        switch ($this->type) {
            case 'insert':
                $this->dealData();
                break;
            case 'update':
                $this->dealData();
                break;
            case 'delete':
                // 订单暂时没有删除操作
                break;
            default:
                break;
        }
    }

    /**
     * Date: 2019/4/19
     * @return void
     */
    public function dealData()
    {
        $ts = $this->msg->ts; // binlog 默认插入的时间
        $kafkaType = $this->msg->type; // kafka基础数据动作类型
        $data = $this->msg->data;//kafka拉取到的真实数据
        $old = [];//insert操作时，没有old

        //处理老数据
        if (property_exists($this->msg, 'old')) {
            $old = json_decode(json_encode($this->msg->old), true);
            $old = $this->upperField($old);
        }

        if (!is_array($old)) {
            $old = [];
        }

        $keys = [];
        $values = [];

        foreach ($data as $key => $datum) {
            array_push($keys, $key);
            array_push($values, $datum);
        }

        //处理大写
        $consumeData = array_combine($keys, $values);
        $consumeData = $this->upperField($consumeData);
        $consumeData['oldData'] = $old;
        $consumeData['defaultTime'] = $ts; // 默认时间
        $consumeData['kafkaType'] = $kafkaType; // kafka基础数据动作类型

        switch ($this->table) {
            case 'order':
                $this->order->dealData($consumeData);
                break;
            case 'turnOrderApply':
                $this->turnOrder->dealData($consumeData);
                break;
            case 'orderRemark':
                $this->orderRemark->dealData($consumeData);
                break;
            case 'vircallRecord':
                $this->vircallRecord->dealData($consumeData);
                break;
            default:
                break;
        }
    }

    /**
     * Date: 2019/4/19
     * @param $tableName
     * @return array|string
     */
    private function handleTableName($tableName)
    {
        $name = explode('_', $tableName);

        if (count($name) == 1) {
            return $tableName;
        }

        $res = $name[0];
        for ($i=1; $i<count($name); $i++) {
            $res .= ucfirst($name[$i]);
        }

        return $res;
    }

    /**
     * Date: 2019/4/19
     * @param $old
     * @return array
     */
    public function upperField($old)
    {
        if (empty($old)) {
            return [];
        }

        $res = [];

        foreach ($old as $key => $item) {
            $keyArr = explode('_', $key);
            $count = count($keyArr);
            if ($count == 1) {
                $resKey = $key;
            } else {
                $resKey = $keyArr[0];
                for ($i=1; $i<$count; $i++) {
                    $resKey .= ucfirst($keyArr[$i]);
                }
            }

            $res[$resKey] = $item;
        }

        return $res;
    }


}

```

**Comment by stelin** [comment]
@JoeXiong 2.0 已经正式发布，建议升级到2.0
