### ISSUE TITLE
swoft2.0中间件建议：将UserMiddleware拆分路由解析和路由处理两部分

### ISSUE THREAD

**Issue by hihozhou** [swoft-cloud/swoft#686]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Swoft version       | master（2.x）
| Swoole version      | 4.3.3
| PHP version         | 7.2.17
| Runtime environment | Ubuntu 18.04.

**我的需求**

>1.我定义了一个是否登录的中间件auth（没登录就跳转到登录页面）
2.我定义了http全局中间件auth
3.当请求不存在的路由时候，会进到auth中间件，都会跳转登录页面，正常应该是显示404（所以我这里是判断他路由是否定义了，才进行验证）

**建议**

>可以考虑将swoft框架中`Swoft\Http\Server\Middleware\UserMiddleware`拆分成`路由解析`和`路由处理`两部分，这样可以第一个最先验证路由不存在

![image](https://user-images.githubusercontent.com/12164486/58877950-b81c6b80-8704-11e9-8723-ef508b561db5.png)

![image](https://user-images.githubusercontent.com/12164486/58877976-c36f9700-8704-11e9-972b-8a4311631107.png)

**Comment by sakuraovq** [comment]
good idea
