### ISSUE TITLE
如何判断当前请求是http还是rpc？

### ISSUE THREAD

**Issue by akaQin** [swoft-cloud/swoft#687]
如题

**Comment by inhere** [comment]
http 和 rpc 在不同的地方处理的啊？哪里需要判断？

**Comment by akaQin** [comment]
比如我在logic中抛出一个跟业务相关的异常（BusinessException），http和rpc请求都可能走到这里，但需要不同的Response，所以我想写一个BusinessExceptionHandler，做判断后重新分发给HttpExceptionHandler或RpcExceptionHandler

**Comment by akaQin** [comment]
> http 和 rpc 在不同的地方处理的啊？哪里需要判断？

比如我在logic中抛出一个跟业务相关的异常（BusinessException），http和rpc请求都可能走到这里，但需要不同的Response，所以我想写一个BusinessExceptionHandler，做判断后重新分发给HttpExceptionHandler或RpcExceptionHandler

**Comment by akaQin** [comment]
我的使用场景是http和rpc同时对外提供服务

**Comment by inhere** [comment]
这里也无需区分的，swoft 异常处理里已经区分了，你只需定义对应场景的处理器就行

**Comment by akaQin** [comment]
> 这里也无需区分的，swoft 异常处理里已经区分了，你只需定义对应场景的处理器就行

感觉您没明白我的意思，我换一个问题，该怎么判断我应该抛出HttpExceptiion还是RpcException?

**Comment by inhere** [comment]
😄  即使你是同一个地方抛出的异常 BusinessException，只要你定义了不同场景的异常处理就行。在你这里需要写两个处理器分别针对 http 和 rpc。比如 `HttpBusinessExceptionHandler`  `RpcBusinessExceptionHandler` 在里面返回不同的响应。

参考我新加的 [异常处理文档](https://www.swoft.org/docs/2.x/zh-CN/error/index.html)

**Comment by akaQin** [comment]
> 异常处理文档

明白了，谢谢🙏

**Comment by akaQin** [comment]
明白了，谢谢🙏
