### ISSUE TITLE
控制值使用试图注解@view没有生效，而直接显示数据

### ISSUE THREAD

**Issue by hihozhou** [swoft-cloud/swoft#688]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Swoft version       | master（2.x）
| Swoole version      | 4.3.3
| PHP version         | 7.2.17
| Runtime environment | Ubuntu 18.04.

**Details**

> 控制值使用试图注解@view没有生效，而直接显示数据

https://www.swoft.org/docs/v1/zh-CN/view/usage.html#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B

```php
/**
     * 视图渲染demo - 没有使用布局文件(请访问 /demo/view)
     * @RequestMapping()
     * @View(template="index/index") - 将会渲染 `resources/views/index/index.php` 文件
     */
    public function actionView()
    {
        $data = [
            'name' => 'Swoft',
            'repo' => 'https://github.com/swoft-cloud/swoft',
            'doc' => 'https://doc.swoft.org/',
            'method' => __METHOD__,
        ];

        // 根据请求适应返回类型，如请求视图，则会根据 @View() 注解来返回视图
        // 这里return的值将会传递给视图
        return $data;
    }

```

![image](https://user-images.githubusercontent.com/12164486/58948258-49024e00-87bc-11e9-8b80-a7b490ee0d24.png)

**Comment by inhere** [comment]
2.0 还没有添加 `@View` 的支持。

**Comment by hihozhou** [comment]
@inhere 大佬什么时候支持？急用

**Comment by hihozhou** [comment]
我暂时直接用return view()

**Comment by inhere** [comment]
下个小版本发，已经加上了相关逻辑。
https://github.com/swoft-cloud/swoft-view/commit/1944be2d257902687d641e0a6926d49b186b6244
