### ISSUE TITLE
swoft2.0 devtool如何配置使用

### ISSUE THREAD

**Issue by lzmshow** [swoft-cloud/swoft#690]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> 目前只有1.0的使用方法 2.0的如何使用.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
2.0 devtool 暂时无需配置，还没有添加web方面的功能

**Comment by stelin** [comment]
直接安装devtool 即可使用现有组件，后续会提供更多功能，感谢支持 Swoft
