### ISSUE TITLE
V2.x 版本没有预设提供 docker-compose ?

### ISSUE THREAD

**Issue by adon988** [swoft-cloud/swoft#692]
目前查看 2.x 版本，预设都无 docker-compose 相关设定档，但是官方手册，框架安装有提到Docker-Compose 安装流程？

**Comment by stelin** [comment]
2.x 相关操作还没更新，后续会更新

**Comment by inhere** [comment]
官方 docker 已经可用，docker-compose 下个版本也会提供

**Comment by inhere** [comment]
docker-compose 已经提供
