### ISSUE TITLE
redis注入的方式，连接池是不是有不会释放的问题，用完就超时了。

### ISSUE THREAD

**Issue by vvphp** [swoft-cloud/swoft#702]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 7.3.5
| Swoole version      | 4.2.13
| PHP version         | 2.0.1-beta
| Runtime environment | Docker etc.

  ____                __ _     _____                                            _      ____
 / ___|_      _____  / _| |_  |  ___| __ __ _ _ __ ___   _____      _____  _ __| | __ |___ \  __  __
 \___ \ \ /\ / / _ \| |_| __| | |_ | '__/ _` | '_ ` _ \ / _ \ \ /\ / / _ \| '__| |/ /   __) | \ \/ /
  ___) \ V  V / (_) |  _| |_  |  _|| | | (_| | | | | | |  __/\ V  V / (_) | |  |   <   / __/ _ >  <
 |____/ \_/\_/ \___/|_|  \__| |_|  |_|  \__,_|_| |_| |_|\___| \_/\_/ \___/|_|  |_|\_\ |_____(_)_/\_\

PHP: 7.3.5, Swoft: 2.0.1-beta, Swoole: 4.2.13

**Details**

>
![image](https://user-images.githubusercontent.com/17230924/59320017-50b37c80-8cff-11e9-9905-feb430ef4af6.png)
![image](https://user-images.githubusercontent.com/17230924/59320032-5f019880-8cff-11e9-8cfa-96ea0a277eae.png)
![image](https://user-images.githubusercontent.com/17230924/59320039-65901000-8cff-11e9-8036-e8c41bef0587.png)

```php
// paste output here
2019/06/12-10:18:32 [INFO] Swoft\Event\Manager\EventManager:triggerListeners(324) Registered swoole events:
 start, shutdown, managerStart, managerStop, workerStart, workerStop, workerError, request, task, finish
Server start success (Master PID: 15875, Manager PID: 15876)
redis1:keykey
redis2:keykey

redis1:keykey
redis2:keykey

redis1:keykey
redis2:keykey

redis1:keykey
redis2:keykey

redis1:keykey
```

> Provide minimal script to reproduce the issue

```php
    /**
     * @Inject("redis.pool")
     * @var Pool
     */
    private $redis;

    /**
     * @RequestMapping("/v1/room/redis")
     */
    public function redis(): array
    {
        $key    = 'keykey';
        echo "redis1:".$key.PHP_EOL;
        $result = $this->redis->set($key, 'key');
        $keyVal = $this->redis->get($key);
        //$result = Redis::set($key, 'key');
        //$keyVal = Redis::get($key);
        echo "redis2:".$key.PHP_EOL.PHP_EOL;
        $data = [
            $result,
            $keyVal
        ];
        return $data;
    }
```

[https://www.swoft.org/docs/2.x/zh-CN/redis/usage.html](url)
```php
<?php declare(strict_types=1);

namespace App\Http\Controller;

use Swoft\Redis\Pool;
use Swoft\Bean\Annotation\Mapping\Inject;
use Swoft\Http\Server\Annotation\Mapping\Controller;
use Swoft\Http\Server\Annotation\Mapping\RequestMapping;

/**
 *
 * @Controller("Redis")
 */
class RedisController
{
    /**
     * eg 1
     *
     * @Inject("redis.inc.pool")
     *
     * @var Pool
     */
    private $redisInc;

    /**
     * eg 2
     *
     * @Inject()
     *
     * @var Pool
     */
    private $redis;

    /**
     * @RequestMapping(route="find")
     *
     * @return array
     *
     * @throws Throwable
     */
    public function find(): array
    {
        $this->redis->set('user', ["name"=>"gimi", "age"=>"18"]);

        return $this->redis->get('user');
    }
}  
```

redis注入的方式，连接池是不是有不会释放的问题，用完就超时了。

**Comment by sakuraovq** [comment]
我是压测是 还是直接请求的呢 @vvphp

**Comment by sakuraovq** [comment]
是压测的出的问题 还是直接请求的呢 @vvphp

**Comment by sakuraovq** [comment]
@vvphp  2.0.2 发布 解决了  先用 Redis::xx()
