### ISSUE TITLE
entity 直接调用set方法后，调用toArray方法,返回空数组

### ISSUE THREAD

**Issue by RingRan** [swoft-cloud/swoft#704]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Swoft version       | 2.0.1
| Swoole version      | 4.2.9 (by `php --ri swoole`)
| PHP version         | 7.1.12 (by `php -v`)
| Runtime environment | Docker etc.

**Details**

> entity 直接调用set方法后，调用toArray方法,返回空数组

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
 /* @var User $user */
        $user = User::new();
        $user->setAge(mt_rand(1, 100));
        $user->setUserDesc('desc');

        // Save result
        $result = $user->save();
        var_dump($user->toArray());
```
output

```php
array(0) {
}
``

**Comment by sakuraovq** [comment]
看 changelog 已经修复的了哈 2.0.2 发布
