### ISSUE TITLE
sowft2.0如何配置redis sentinel

### ISSUE THREAD

**Issue by ningge123** [swoft-cloud/swoft#705]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 2.0
| Swoole version      | 4.3.4
| PHP version         | 7.1
| Runtime environment | Ubuntu

**Details**

运维给的redis配置是 `sentinel` 模式，问下swoft redis 怎么配置

**Comment by sakuraovq** [comment]
支持集群模式和 单机模式 哨兵 需要 自己实现=-= 封装下

**Comment by ningge123** [comment]
我引入`predis`抛出这个异常：
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Swoft\Annotation\AnnotationRegister::addAutoLoader() must implement interface Swoft\Annotation\Contract\LoaderInterface, instance of Predis\Autoloader given, called in /home/vagrant/Code/oms-wos-service/vendor/swoft/annotation/src/Resource/AnnotationResource.php on line 183 and defined in /home/vagrant/Code/oms-wos-service/vendor/swoft/annotation/src/AnnotationRegister.php:213

原因是需要实现`LoaderInterface`接口，难道我要改`predis`包里面的`Autoloader.php`文件吗？自动加载写得有问题

**Comment by ningge123** [comment]
我试了一下把`predis`的`Autoloader.php`文件删除然后运行，发现是可以使用，所以发现是`swoft`去扫描`Autoloader.php`,并自动加载，引发上面的错误
