### ISSUE TITLE
用Swoft 提供的静态资源访问的支持，访问文件包含中文会报错

### ISSUE THREAD

**Issue by FromChinaBoy** [swoft-cloud/swoft#710]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | no
| Swoft version       | 2.0.1-beta
| Swoole version      |4.3.3 
| PHP version         | 7.2.8 
| Runtime environment | Mac

**Details**

> Describe what you are trying to achieve and what goes wrong.
### 1、开启静态服务在bean.php
```php
        'setting' => [
            'worker_num' => 4,
            'task_worker_num' => 12,
            'task_enable_coroutine' => true,
            'document_root' => alias('@base/public'), // v4.4.0以下版本, 此处必须为绝对路径
            'enable_static_handler' => true,
        ]
```
### 2、要访问的静态目录
![](http://img.zzhpeng.cn/FulGXdfxsVoggOITWcq7fJMwerRC)

#### 3.1、不包含中文可行
![](http://img.zzhpeng.cn/FqQIcgTXHC6LiNaLnHz8-5XA286I)

#### 3.2、包含中文不行
一直loading

### 4、控制台报错信息
![](http://img.zzhpeng.cn/Fg9p2SiwvBahoyb8ZT7BkHofimQN)

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
直接在swoole试过没？有问题你再打开

**Comment by FromChinaBoy** [comment]
@inhere 刚刚试了swoole开http静态服务是访问不到带中文的资源的

**Comment by inhere** [comment]
ok，静态资源访问 swoft也没处理，是swoole处理的。

**Comment by inhere** [comment]
refer https://github.com/swoole/swoole-src/issues/2676

**Comment by FromChinaBoy** [comment]
@inhere Thx
