### ISSUE TITLE
middleware  $handler->handle($request) 后面代码无法执行

### ISSUE THREAD

**Issue by qijinkui** [swoft-cloud/swoft#713]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```控制器调用了 Model/Dao 层代码，然后控制器调用的中间件  的 $handler->handle($request) 这段代码后面的代码无法执行

**Comment by inhere** [comment]
贴一下demo 代码 和 有没有报错信息

**Comment by qijinkui** [comment]
沒有任何报错信息， 

Middleware(VerifyMiddleware::class) 这个中间件里设置的跨域 用的是手册上的demo

 /**
     *
     * @Middleware(VerifyMiddleware::class)
     *
     * 用户登陆
     * @RequestMapping(route="login")
     * @param Request $request
     * @return array
     * @throws \App\Exception\ServiceException
     * @throws \App\Exception\ValidateException
     */
    public function login(Request $request,Response $response){
        $post = $request->post();
        $this->userLogic->login($post);
        $token = $this->userService->login($post['mobile'],$post['code']);

        //如果注释掉上面的三行代码，就会跨域成功，打开就不行
        return Message::success('success',Message::CODE_SUCCESS,['token'=>$token??'test']);
    }


////////////
$post = $request->post();
$this->userLogic->login($post);
$token = $this->userService->login($post['mobile'],$post['code']);
//////////////////
这三行代码 只是一些entity调用  并 return  没有其他操作，

如下 middleware代码


public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        //验证签名
        $result = $this->checkSign($request);
        //var_dump(11111) 可以正常输出
        $response = $handler->handle($request);
       //var_dump(22222)  这里如果打开那三行代码   就执行不到这 
        if ($result['code'] != 1000) {
            $response = $response->withdata($result);
        }

        return $this->configResponse($response);
    }

    private function configResponse(ResponseInterface $response)
    {
        return $response
            ->withHeader('Access-Control-Allow-Origin', '*')
            ->withHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Accept, Origin, Authorization')
            ->withHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
    }

**Comment by inhere** [comment]
你这代码格式。。。! 😄

**Comment by qijinkui** [comment]
/捂脸
基本就是 控制器调用了  Model下的Logic层，Data和Dao层的话 在中间件   handle 后面就执行不到了

**Comment by stelin** [comment]
@qijinkui 应该是你这三行报错了，你没错误处理，你看下错误日志或try catch
