### ISSUE TITLE
验证器可以不使用注解直接调用吗

### ISSUE THREAD

**Issue by hihozhou** [swoft-cloud/swoft#714]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Swoft version       | master（2.x）
| Swoole version      | 4.3.3
| PHP version         | 7.2.17
| Runtime environment | Ubuntu 18.04.

**Details**

> 由于某些业务问题，我需要在非控制器的其他地方调用验证器验证参数，是否有不通过注解调用验证器验证的方法？

**Comment by stelin** [comment]
@hihozhou 2.0.3 版本会支持。
