### ISSUE TITLE
关于swoft的几点建议

### ISSUE THREAD

**Issue by Yuebanfuxiao** [swoft-cloud/swoft#715]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.x
| Swoole version      | 4.4.0
| PHP version         | 7.2.5
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> 1.强烈建议取消所有的注解方式，路由的集中处理一定是最好的方式。根据长期以来使用laravel的经验，无论是从维护方面还是控制方面，集中处理路由都是最好的方式。

> 2.验证器使用注解的方式真的很尴尬啊，试想，如果一个参数是动态验证的，现有的注解方式真的很糟糕。

> 3.中间件还值得优化，之前也提过这个建议，中间件应该考虑传入自定义参数，不然在现有的中间件下。要实现差异化的中间件就非得要写多个中间件。灵活性还不够，可以参考laravel的中间件。

**Comment by inhere** [comment]
1. swoft 是基于注解的，去掉那就不是swoft了。
2. 现有验证器只是通用的解决方案，特殊的自己在逻辑里处理
3. _中间件应该考虑传入自定义参数_ 自定义参数可以往 request 或者 context 里放。后面的中间件就可以使用，不存在灵活性不够的问题。

**Comment by peixiaochen** [comment]
请问如果使用注解方式的话，后期如何动态维护路由，并进行统一管理呢？

**Comment by inhere** [comment]
要怎么样维护？
路由注册好了都在路由器里面，跟fpm下的也没撒区别。只是用注解标记，框架帮你收集注册而已。

**Comment by peixiaochen** [comment]
比如路由版本控制，

**Comment by qq781548819** [comment]
同求加上基于文件集中管理路由的方式，现在这样维护起来特别麻烦
