### ISSUE TITLE
Swoft2 将会支持http:reload吗

### ISSUE THREAD

**Issue by eaglering** [swoft-cloud/swoft#716]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | ^2.0
| Swoole version      | 4.3.4
| PHP version         | 7.1
| Runtime environment |docker

**Details**

> Swoft2 将会支持http:reload吗？

**Comment by inhere** [comment]
不会，服务修改代码只能restart

**Comment by rainbowMorelhahahah** [comment]
> 不会，服务修改代码只能restart

那么现在reload有什么用
