### ISSUE TITLE
config bean被重复init()，导致在config中定义常量会引发重复定义常量错误。

### ISSUE THREAD

**Issue by minxinqing** [swoft-cloud/swoft#719]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    |no
| Swoft version       | 2.0.1
| Swoole version      | 4.3.4
| PHP version         | 7.1.16
| Runtime environment | Mac

**Details**

> config bean被重复init()，导致在config中定义常量会引发常量重复定义错误。

在config/test.php中定义常量
```php
define('test', true);
```
服务启动报异常
(DEFAULT HANDLER)Exception(ErrorException): Constant test already defined

**Comment by stelin** [comment]
@minxinqing 感谢反馈，我们定位下。
