### ISSUE TITLE
php bin/swoft -h

### ISSUE THREAD

**Issue by duzh** [swoft-cloud/swoft#721]
2019/06/20-07:06:24 [INFO] Swoole\Runtime::enableCoroutine
2019/06/20-07:06:24 [INFO] Swoft\SwoftApplication:__construct(14) Set alias @base=/root/cmdv1
2019/06/20-07:06:24 [INFO] Swoft\SwoftApplication:__construct(14) Set alias @app=@base/app
2019/06/20-07:06:24 [INFO] Swoft\SwoftApplication:__construct(14) Set alias @config=@base/config
2019/06/20-07:06:24 [INFO] Swoft\SwoftApplication:__construct(14) Set alias @runtime=@base/runtime
2019/06/20-07:06:24 [INFO] Project path is /root/cmdv1
2019/06/20-07:06:24 [INFO] Swoft\Processor\ApplicationProcessor:handle(221) Env file(/root/cmdv1/.env) is loaded
PHP Fatal error:  Interface 'Swoft\Db\Contract\DbSelectorInterface' not found in /root/cmdv1/app/Common/DbSelector.php on line 18

**Comment by duzh** [comment]
[root@CMD cmdv1]# php bin/swoft http:start
2019/06/20-06:53:39 [INFO] Swoole\Runtime::enableCoroutine
2019/06/20-06:53:39 [INFO] Swoft\SwoftApplication:__construct(14) Set alias @base=/root/cmdv1
2019/06/20-06:53:39 [INFO] Swoft\SwoftApplication:__construct(14) Set alias @app=@base/app
2019/06/20-06:53:39 [INFO] Swoft\SwoftApplication:__construct(14) Set alias @config=@base/config
2019/06/20-06:53:39 [INFO] Swoft\SwoftApplication:__construct(14) Set alias @runtime=@base/runtime
2019/06/20-06:53:39 [INFO] Project path is /root/cmdv1
2019/06/20-06:53:39 [INFO] Swoft\Processor\ApplicationProcessor:handle(221) Env file(/root/cmdv1/.env) is loaded
PHP Fatal error:  Access level to App\Model\Entity\Count::$attributes must be protected (as in class Swoft\Db\Eloquent\Model) or weaker in /root/cmdv1/app/Model/Entity/Count.php on line 113

**Comment by sakuraovq** [comment]
2.0.2 就可以了哈  明天发版～～～
