### ISSUE TITLE
Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by 18786769297** [swoft-cloud/swoft#722]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 1.0.0
| Swoole version      | 4.3.3 (by `php --ri swoole`)
| PHP version         | 7.2.1 (by `php -v`)
| Runtime environment | Win10 Docker.

**Details**

> 我在上线前做压力测试时出现内存不够用的情况
测试接口: ab -n 5000 -c 500 http://xxxx.com/test
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /home/www/swoft/vendor/swoft/http-server/src/Router/HandlerAdapter.php on line 63
接口里面做了sql连接查询，故重新设置了db连接池参数
 'minActive'   => 180,
 'maxActive'   => 600,
 'maxWait'     => 0,
 'timeout'     => 10,
 'maxIdleTime' => 60,
 'maxWaitTime' => 3,

压测结果没到5000请求就失败了
![image](https://user-images.githubusercontent.com/25738832/59829002-daea8900-936e-11e9-9a64-07ca55709155.png)

**Comment by 18786769297** [comment]
{"msg":"Connection pool waiting queue is full, maxActive=90,maxWait=20,currentCount=106","file":"\/home\/www\/swoft\/vendor\/swoft\/framework\/src\/Pool\/ConnectionPool.php","line":242,"code":0}  
如果连接池设置较小的话,会出现连接池资源被占满

**Comment by stelin** [comment]
@18786769297 建议使用2.0
