### ISSUE TITLE
swoft2.0请问我启用了ws服务，然后post传json的时候验证器过不去

### ISSUE THREAD

**Issue by zuoqiang320** [swoft-cloud/swoft#725]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | 2.0
| Swoole version      | 4.3.4
| PHP version         | 7.1.26
| Runtime environment | Mac

**Details**

我前端用post传递一个json，例如：
![image](https://user-images.githubusercontent.com/12770030/59841067-29575200-9386-11e9-96d6-de8f492df85d.png)
验证器就不给通过
![image](https://user-images.githubusercontent.com/12770030/59841099-3bd18b80-9386-11e9-9a66-6d5c799ced78.png)
请问是不是我的操作不对还是不支持？

**Comment by inhere** [comment]
问题已经修复，等待发 2.0.2
