### ISSUE TITLE
redis  配置报错

### ISSUE THREAD

**Issue by chenjing0521** [swoft-cloud/swoft#726]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/
| Feature request?    | no
| Swoft version       | 2.0.2
| Swoole version      | 4.3.3
| PHP version         | 7.2
| Runtime environment | CentOS 7.

**Details**
```
'redis-2'      => [
    'class'         => RedisDb::class,
    'host'          => '127.0.0.2',
    'port'          => 6378,
    'database'      => 1,
    'retryInterval' => 10,
    'readTimeout'   => 0,
    'timeout'       => 2,
    'option'        => [          
        'prefix'      => 'xxx',
        'serializer' => Redis::SERIALIZER_PHP
    ],
],
```
这个配置中的  **readTimeout** 设置 大于    1    时  rpc请求 报错 等于0时  没有错误

![image](https://user-images.githubusercontent.com/43941983/59847454-14ce8600-9395-11e9-8e96-0ff0bd123bff.png)

```
 'redis.pool'     => [
        'class'   => \Swoft\Redis\Pool::class,
        'redisDb' => \bean('redis'),
        'minActive'   => 1,
        'maxActive'   => 3,
        'maxWait'     => 0,
        'maxWaitTime' => 1,
        'maxIdleTime' => 60,
    ],
```

这个配置中的 **maxWaitTime**   如果设置等于 0   源码中的  
![image](https://user-images.githubusercontent.com/43941983/59853332-39315f00-93a3-11e9-9376-e49918ebdba9.png)
将会被阻塞,阻塞后  应该有风险  但是我菜  我不知道怎么修改  给位大佬 麻烦  看看

**Comment by sakuraovq** [comment]
ok 这个不用担心 我们修复下

**Comment by sakuraovq** [comment]
这个配置中的 maxWaitTime 如果设置等于 0 是其他等待连接释放就可以获取了

**Comment by sakuraovq** [comment]
明天发布噢

**Comment by chenjing0521** [comment]
好的 感谢
