### ISSUE TITLE
docker环境swoft2.x无法启动

### ISSUE THREAD

**Issue by peking2008** [swoft-cloud/swoft#727]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | 2.x
| Swoole version      | 4.3.5
| PHP version         | 7.2.19
| Runtime environment | CentOS 7

**Details**

swoft   | Fatal error: Interface 'Swoft\Db\Contract\DbSelectorInterface' not found in /var/www/swoft/app/Common/DbSelector.php on line 18

swoft   | Fatal error: Access level to App\Model\Entity\Count::$attributes must be protected (as in class Swoft\Db\Eloquent\Model) or weaker in /var/www/swoft/app/Model/Entity/Count.php on line 113

**Comment by inhere** [comment]
这两个问题都已经修复，这两天发版
