### ISSUE TITLE
任务下 taskCo 协程方式调用 mongoDB 导致阻塞

### ISSUE THREAD

**Issue by simplephp** [swoft-cloud/swoft#729]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.2
| Swoole version      |4.3.4
| PHP version         | 7.1.17
| Runtime environment | Ubuntu

**Details**
任务下 taskCo 协程方式调用mongoDB 导致阻塞，任务目前默认必须支持协程，希望有所调整。

> Describe what you are trying to achieve and what goes wrong.

```php
 $result = Swoft\Task\Task::co('MongoTask', 'insert', ['weather', ['a' => 'b']], 1);
```

![微信图片_20190624150137](https://user-images.githubusercontent.com/5026959/59998097-1ba91180-9691-11e9-8763-45e887abc064.png)
![微信图片_20190624150147](https://user-images.githubusercontent.com/5026959/59998098-1c41a800-9691-11e9-90ac-9279d88d01af.png)

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
2.0.4 已发布，已新增此功能
