### ISSUE TITLE
php7.2 PHP Deprecated:  The each() function is deprecated

### ISSUE THREAD

**Issue by masixun71** [swoft-cloud/swoft#73]
PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in /apps/webroot/production/bsf/vendor/swoft/framework/src/Console/CommandParser.php on line 39

**Comment by stelin** [comment]
PHP7.2 函数兼容问题，我们后续兼容下

**Comment by inhere** [comment]
已经修复了， @masixun71 更新看下呢
