### ISSUE TITLE
PointAnnotation切面中如果获取注解信息

### ISSUE THREAD

**Issue by yangjianfeng9527** [swoft-cloud/swoft#733]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes/no
| Swoft version       | 2.0.2
| Swoole version      | 4.3
| PHP version         | 7.2
| Runtime environment | Mac

**Details**

> Describe what you are trying to achieve and what goes wrong.
使用@PointAnnotation定义注解切入点时，在通知方法中如何获取注解信息
```php
/**
 * @Aspect(order=1)
 * @PointAnnotation(include={TestAnnotation::class})
 */
class TestAspect
{
    /**
     * @Around()
     * @param ProceedingJoinPoint $proceedingJoinPoint
     * @return mixed
     */
    public function around(ProceedingJoinPoint $proceedingJoinPoint)
    {
       //在这里我要如何获取TestAnnotation注解对象
        // Before around
        $result = $proceedingJoinPoint->proceed();
        // After around
        return $result;
    }
}
```
我想通过定义注解的属性在切面中做不同的前置和后置逻辑

**Comment by stelin** [comment]
AnnotationRegister::getAnnotations() 方法里面有所有类的注解信息
