### ISSUE TITLE
切面是否可以提供一个方法然后提前终止后续代码或者业务的执行

### ISSUE THREAD

**Issue by codeingist** [swoft-cloud/swoft#743]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.2
| Swoole version      | 4.3.2
| PHP version         | 7.2.19
| Runtime environment | CentOS 7

**Details**

> 切面中是否有提供方法可以停止后续业务的执行？例如我对于一个控制器进行before切面然后进行参数验证然后参数不合法时提前响应请求返回错误信息。这样我控制器中就可以不必关注非主流程业务之外的情况了。也可以利用切面来更加优雅的对业务进行分层

**Comment by stelin** [comment]
@codeingist  里面抛异常是可以终止的，你试试。

**Comment by codeingist** [comment]
> @codeingist 里面抛异常是可以终止的，你试试。

抛出异常等于终止了整个业务流程的执行了，提前响应之类的需求确实可以满足。但是有时候我只想停止当前业务代码的某部分逻辑的执行就没法实现了。

**Comment by stelin** [comment]
before不会影响主流程执行的，你可以使用 around 通知，可以完全控制业务

**Comment by stelin** [comment]
不执行业务都可以的。

**Comment by codeingist** [comment]
> before不会影响主流程执行的，你可以使用 around 通知，可以完全控制业务

大概明白了，谢谢
