### ISSUE TITLE
Call to undefined function go()

### ISSUE THREAD

**Issue by okami-chen** [swoft-cloud/swoft#744]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | 2.0.2
| Swoole version      | 4.3.5
| PHP version      | 7.3.6
| System version      |  Mac Os 14

 (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Fatal error: Uncaught Error: Call to undefined function go() in /www/swoft/vendor/swoft/framework/src/Co.php:71

```php
PHP Fatal error:  Uncaught Error: Call to undefined function go() in /www/swoft/vendor/swoft/framework/src/Co.php:71
Stack trace:
#0 /www/swoft/vendor/swoft/framework/src/Helper/Functions.php(117): Swoft\Co::create(Object(Closure), false)
#1 /www/swoft/vendor/swoft/framework/src/Listener/CoroutineCompleteListener.php(53): sgo(Object(Closure), false)
#2 /www/swoft/vendor/swoft/event/src/Manager/EventManager.php(729): Swoft\Listener\CoroutineCompleteListener->handle(Object(Swoft\Event\Event))
#3 /www/swoft/vendor/swoft/event/src/Manager/EventManager.php(324): Swoft\Event\Manager\EventManager->triggerListeners(Object(Swoft\Event\Listener\ListenerQueue), Object(Swoft\Event\Event), '')
#4 /www/swoft/vendor/swoft/framework/src/Swoft.php(148): Swoft\Event\Manager\EventManager->trigger(Object(Swoft\Event\Event), NULL, Array)
#5 /www/swoft/vendor/swoft/http-server/src/Listener/AfterRequestListener.php(40): Swoft::trigger('swoft.co.comple...')
#6 /www/swoft/vendor/swoft/event/src/Manager/EventManager.php(729): Swoft\Http\Server\Listener in /www/swoft/vendor/swoft/framework/src/Co.php on line 71

Fatal error: Uncaught Error: Call to undefined function go() in /www/swoft/vendor/swoft/framework/src/Co.php:7
```

> Provide minimal script to reproduce the issue

```php

```

**Comment by inhere** [comment]
可能你需要重新装下swoole 这是提示swoole 里的 go 函数不存在

**Comment by okami-chen** [comment]
> 可能你需要重新装下swoole 这是提示swoole 里的 go 函数不存在

重新安装同样错误，pecl install swoole

**Comment by inhere** [comment]
`php --re swoole | grep go` 看下有 go function 没

**Comment by okami-chen** [comment]
> `php --re swoole | grep go` 看下有 go function 没
> 
> 是 swoole 4.3.5 ?

是的，是不是这个版本有变更？

**Comment by gankbat** [comment]
我也在报这个错误.. swool 已经安装了很久了 以前没这个问题

**Comment by okami-chen** [comment]
> `php --re swoole | grep go` 看下有 go function 没
> 
> 是 swoole 4.3.5 ?

Method [ <internal:swoole> public method goaway ] {
