### ISSUE TITLE
头部添加 content-type application/json 导致500错误

### ISSUE THREAD

**Issue by Johnzero** [swoft-cloud/swoft#749]
![image](https://user-images.githubusercontent.com/2416618/60241621-5ce62f00-98e6-11e9-8216-e437c588323a.png)

**Comment by inhere** [comment]
你这内容不像是json啊

**Comment by Johnzero** [comment]
不是json ，应该throw个error 出来吧。现在直接导致报错了

**Comment by inhere** [comment]
body 后面就是你请求的数据体，也不是json呐。

**Comment by stelin** [comment]
content-type 是json, 就要做json解析，但是你内容不是json 提示的解析错误，我们调整下提示错误信息
