### ISSUE TITLE
swoft出现json_decode error: Syntax error

### ISSUE THREAD

**Issue by coltguo** [swoft-cloud/swoft#752]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
提供一些详细信息 或者 复现demo

**Comment by stelin** [comment]
@coltguo 能提供复现代码么

**Comment by inhere** [comment]
先关闭了，出现问题 请发下demo 再打开。

**Comment by manzige** [comment]
# 
## 
### __` `
