### ISSUE TITLE
1.x swoft/devtool依赖报错

### ISSUE THREAD

**Issue by zuojianghua** [swoft-cloud/swoft#755]
swoft/devtool依赖了swoft/data-parser，而https://github.com/swoft-cloud/swoft-data-parser.git没有了

Package operations: 41 installs, 0 updates, 0 removals
  - Installing swoft/data-parser (v1.0.1): Downloading (failed)    Failed to download swoft/data-parser from dist: The "https://api.github.com/repos/swoft-cloud/swoft-data-parser/zipball/356c340f41496ce5df713109e60a07ec9ae1be74" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing swoft/data-parser (v1.0.1): Cloning 356c340f41

  [RuntimeException]
  Failed to clone https://github.com/swoft-cloud/swoft-data-parser.git via https, ssh protocols, aborting.

  - https://github.com/swoft-cloud/swoft-data-parser.git
    Cloning into '/Users/zuojianghua/Code/tars/tars_app/swoftInTars-master/src/vendor/swoft/data-parser'...
    remote: Repository not found.
    fatal: repository 'https://github.com/swoft-cloud/swoft-data-parser.git/' not found

  - git@github.com:swoft-cloud/swoft-data-parser.git
    Cloning into '/Users/zuojianghua/Code/tars/tars_app/swoftInTars-master/src/vendor/swoft/data-parser'...
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

**Comment by inhere** [comment]
ok, 我恢复了这个仓库
