### ISSUE TITLE
在swoft中  引入协程  定时器包  archer  的问题

### ISSUE THREAD

**Issue by chenjing0521** [swoft-cloud/swoft#757]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.2
| Swoole version      | 4.3.5
| PHP version         | 7.2.1
| Runtime environment | CentOS 7

**Details**

具体请看此处 [ issue](https://github.com/swlib/archer/issues/2)

**Comment by stelin** [comment]
@chenjing0521 你能在swoft里面直接复现么，不适用第三方包

**Comment by chenjing0521** [comment]
我试试
