### ISSUE TITLE
migration模块不支持

### ISSUE THREAD

**Issue by crystal9002** [swoft-cloud/swoft#759]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | v.2.0.1
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | v7.1.27
| Runtime environment | Mac

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
migration模块并为完善，只是创建了migration表
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
2.0.3 会支持迁移脚本

**Comment by sakuraovq** [comment]
下下周哈
