### ISSUE TITLE
swoft2.0系列不兼容Swoft1.0 Rpc服务。

### ISSUE THREAD

**Issue by linuxlan** [swoft-cloud/swoft#760]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.1-beta
| Swoole version      | 4.3.3
| PHP version         | 7.2.10
| Runtime environment | Mac

**Details**
在 Swoft 1.0中创建RPCServer，但是在swoft2 调用 的时候 没有任何返回信息，通过对源码的分析发现是 两个版本的Rpc协议不一致引起的

**Comment by 18786769297** [comment]
我也遇到类似的问题,在swoft2.x中调用1.0的rpc服务时会很慢

**Comment by stelin** [comment]
@linuxlan @18786769297 

2.0 已经兼容1.0 RPC 调用，2.0.3 支持，文档地址 https://www.swoft.org/docs/2.x/zh-CN/rpc-client/rpc-1.0.html
