### ISSUE TITLE
特定情况下报错pageEach

### ISSUE THREAD

**Issue by duzh** [swoft-cloud/swoft#763]
\vendor\swoft\websocket-server\src\WebSocketServer.php 278 此方法在执行推送 比如从队列获取数据推送到前端的时候 如果使用的是\server()->sendToAll 方法 此时有可能获取的$fdList数组是Array
(
    [0] => 
)
顾导致此行代码报错.

**Comment by inhere** [comment]
@duzh 

```php
Array
(
[0] =>
)
```

意思是 有key但没有值？

**Comment by duzh** [comment]
是

**Comment by inhere** [comment]
`特定情况` 是怎么触发的？

https://github.com/swoft-cloud/swoft-websocket-server/blob/d0ec3cd3135a1a1a952dba3d7916be9961fb4259/src/WebSocketServer.php#L276-L281

后面是用 swoole 的 `isEstablished` 做了检查的呀

**Comment by inhere** [comment]
有没有复现的demo？ 我先关了，有问题再打开。
