### ISSUE TITLE
手册错别字一个

### ISSUE THREAD

**Issue by dongqibin** [swoft-cloud/swoft#764]
手册地址 : https://www.swoft.org/docs/2.x/zh-CN/validator/index.html
错误文字 : 正常情况都需要对用户输入参数进行校验，此时就会用到验证器。验证器可以验证控制[**其**]中参数
期望改正 : 正常情况都需要对用户输入参数进行校验，此时就会用到验证器。验证器可以验证控制[**器**]中参数

**Comment by inhere** [comment]
@dongqibin  文档错误可以直接点击下面的 Edit 修正，我们会合并的。

**Comment by stelin** [comment]
@dongqibin 我们修改下，感谢反馈！
