### ISSUE TITLE
Swoft\\Db\\Helper\\EntityHelper::listToEntity() must be of the type array, boolean given

### ISSUE THREAD

**Issue by yangtongbing** [swoft-cloud/swoft#770]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 1.0
| Swoole version      | 4.4.0
| PHP version         | 7.1.19
| Runtime environment | Mac

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
Argument 1 passed to Swoft\\Db\\Helper\\EntityHelper::listToEntity() must be of the type array, boolean given, called in /Users/osx/Documents/pprt-parkingpay/parkingpay-server/vendor/swoft/db/src/QueryBuilder.php on line 1506
```

> Provide minimal script to reproduce the issue

```php
/**
     * 测试方法
     * @RequestMapping(route="register/bing_test",method={RequestMethod::POST,RequestMethod::GET})
     */
    public function bing_test(Request $request)
    {
        MainUser::findOne(['mobile'=>$request->input('mobile')], ['fields'=>['id']])
            ->getResult();
    }
```

**Comment by stelin** [comment]
@yangtongbing 描述下你详细信息

**Comment by sakuraovq** [comment]
1.0 的吗

**Comment by yangtongbing** [comment]
我本地环境正常启动项目，findOne结果集不用getResult没有问题，用的话就报出上述错误，很纳闷为什么？各种composer包都安装无误。

**Comment by yangtongbing** [comment]
是swoft1.0的版本，搜了下没有人碰到我类似的问题，公司项目用docker跑的，我也能跑起来，但本地环境始终是个梗

**Comment by sakuraovq** [comment]
建议升级到 2.0

**Comment by yangtongbing** [comment]
> 建议升级到 2.0
升级带来的就是好多修改，公司项目咱们也不敢随意升级的，感觉还是找找这个问题解决比较好。

**Comment by yangtongbing** [comment]
> @yangtongbing 描述下你详细信息

parkingpay-server/vendor/swoft/db/src/DbResult.php  第96行发现不管什么select语句返回的result都是true，导致下面无法进行解析，最终getResult报错，这个问题很头疼。

**Comment by yangtongbing** [comment]
> @yangtongbing 描述下你详细信息

vendor/swoft/db/src/DbResult.php 第96行发现不管什么select语句返回的result都是true，导致下面无法进行解析，最终getResult报错，这个问题很头疼。

**Comment by stelin** [comment]
@yangtongbing 建议升级到2.0 1.0 暂时重大问题才会去修复

**Comment by yangtongbing** [comment]
> @yangtongbing 建议升级到2.0 1.0 暂时重大问题才会去修复

怨我不小心安装了swoole beta版本，坑死，以后会注意，谢谢。

**Comment by datou-leo** [comment]
我也碰到这个问题

**Comment by yangtongbing** [comment]
> 我也碰到这个问题
你php --ri swoole看下是什么版本,如果是较新的版本建议切换下

**Comment by yangtongbing** [comment]
> 我也碰到这个问题

![image](https://user-images.githubusercontent.com/19441443/76831676-bcb0ab80-6862-11ea-92b1-9ddd4da34d52.png)

**Comment by trrtly** [comment]
碰到了同样的问题,跟 swoole 版本有关,安装 swoole 4.3.3 后解决了
