### ISSUE TITLE
使用请求实例导致死循环内存溢出问题

### ISSUE THREAD

**Issue by dongqibin** [swoft-cloud/swoft#772]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2
| Swoole version      | 4.3
| PHP version         | 7.3
| Runtime environment | Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// 在使用请求实例时候.结果报错:错误消息为内存溢出([03-Jul-2019 08:37:57 UTC] PHP Fatal error:  Allowed memory size of 131072000 bytes exhausted (tried to allocate 8192 bytes) in /usr/app/vendor/swoft/bean/src/Container.php on line 343)
```

> Provide minimal script to reproduce the issue

```php
        // 使用方法(代码位于控制器中)
        $class = 'App\\Lib\\Sign\\Cpm';
        $class = BeanFactory::getRequestBean($class, (string) Co::tid());
        return $this->message->success($class);
```

**Comment by stelin** [comment]
已经解决
