### ISSUE TITLE
自定义验证器规则无法使用

### ISSUE THREAD

**Issue by yangjianfeng9527** [swoft-cloud/swoft#777]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | 2.0.2
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

https://www.swoft.org/docs/2.x/zh-CN/validator/customer-rule.html
这个文档中的自定义规则无法使用
RuleInterface也是不存在的

**Comment by stelin** [comment]
@yangjianfeng9527 使用方式不对吧，RuleInterface 这个要2.0.3支持。验证器很多人在使用

**Comment by stelin** [comment]
贴出你使用代码

**Comment by ChangeChe** [comment]
@stelin 我也是照着https://www.swoft.org/docs/2.x/zh-CN/validator/customer-rule.html 这个文档 找不到RuleInterface

**Comment by stelin** [comment]
已修复，更新 2.0.3
