### ISSUE TITLE
The HTTP server have been running!

### ISSUE THREAD

**Issue by longjianghu** [swoft-cloud/swoft#781]
2019/07/06-23:43:34 [INFO] Swoole\Runtime::enableCoroutine
2019/07/06-23:43:34 [INFO] Swoft\SwoftApplication:setSystemAlias(490) Set alias @base=/data
2019/07/06-23:43:34 [INFO] Swoft\SwoftApplication:setSystemAlias(491) Set alias @app=@base/app
2019/07/06-23:43:34 [INFO] Swoft\SwoftApplication:setSystemAlias(492) Set alias @config=@base/config
2019/07/06-23:43:34 [INFO] Swoft\SwoftApplication:setSystemAlias(493) Set alias @runtime=@base/runtime
2019/07/06-23:43:34 [INFO] Project path is /data
2019/07/06-23:43:34 [INFO] Swoft\Processor\EnvProcessor:handle(45) Env file(/data/.env) is loaded
2019/07/06-23:43:34 [INFO] Swoft\Processor\AnnotationProcessor:handle(45) Annotations is scanned(autoloader 23, annotation 248, parser 57)
2019/07/06-23:43:34 [INFO] Swoft\Processor\BeanProcessor:handle(57) config path=/data/config
2019/07/06-23:43:34 [INFO] Swoft\Processor\BeanProcessor:handle(58) config env=
2019/07/06-23:43:34 [INFO] Swoft\Processor\BeanProcessor:handle(62) Bean is initialized(singleton 164, prototype 48, definition 34)
2019/07/06-23:43:34 [INFO] Swoft\Processor\EventProcessor:handle(37) Event manager initialized(32 listener, 3 subscriber)
2019/07/06-23:43:34 [INFO] Swoft\WebSocket\Server\Listener\AppInitCompleteListener:handle(40) WebSocket server route registered(module 2, message command 3)
2019/07/06-23:43:34 [INFO] Swoft\Error\Listener\AppInitCompleteListener:handle(37) Error manager init completed(2 type, 3 handler, 3 exception)
2019/07/06-23:43:34 [INFO] Swoft\Processor\ConsoleProcessor:handle(39) Console command route registered (group 10, command 28)
The HTTP server have been running!(PID: 1)

用docker容器跑的swoft,重启一下容器就直接挂了（删除容器再建也不行），swoole版本4.4.0。

**Comment by inhere** [comment]
4.3+ 试过吗 有这个问题吗？

**Comment by longjianghu** [comment]
我

> 4.3+ 试过吗 有这个问题吗？

我用的4.4.0 ，临时找到一个解决方法。手动删除pid之后即可以启动成功。

**Comment by inhere** [comment]
怎么操作的？ 启动和重启
