### ISSUE TITLE
关于代码的热更新

### ISSUE THREAD

**Issue by longjianghu** [swoft-cloud/swoft#782]
修改代码后，使用docker exec swoft php /data/bin/swoft http:restart 无法查看效果。需要手动删除pid文件再重启才能查看到修改后的代码。这个能否修复一下？

如果环境是开发环境，能否增加一个1.0的代码热更新？

**Comment by stelin** [comment]
@longjianghu  2.0 底层设计是不会提供 类似1.0的热更新，你可以 docker 不用这样启动，换个方式就好
