### ISSUE TITLE
[Swoole 4.4.0] swServer_signal_handler: Fatal Error: manager process exit.

### ISSUE THREAD

**Issue by 98P** [swoft-cloud/swoft#785]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.2
| Swoole version      | 4.4.0
| PHP version         | 7.2.19
| Runtime environment | Ubuntu

**Details**

升级swoole4.4.0版本之后，执行`php bin/swoft http:start`正常启动，按下`Ctrl+C`退出会报以下警告，且无限循环以下内容，导致服务无法退出：

```bash
Stop server by CTRL+C
[2019-07-08 14:04:04 #2161.4]	INFO	Server is shutdown now
[2019-07-08 14:04:04 #2161.4]	WARNING	swServer_signal_handler: Fatal Error: manager process exit. status=0, signal=[Interrupt: 2]
```

降级至swoole4.3.5版本后恢复正常，望大家升级谨慎 TvT

**Comment by inhere** [comment]
当前只支持 swoole 4.3+, swoole 4.4 应该会在 2.0.4 做兼容

**Comment by okami-chen** [comment]
vendor/swoft/stdlib/src/Helper/SystemHelper.php的$process = proc_open($command, $descriptors, $pipes, $cwd);在swoole 4.4.0 + php 7.3.7下有问题，导致http:start 无法启动

**Comment by okami-chen** [comment]
Fatal error: Uncaught Swoole\Error: API must be called in the coroutine in /www/swoft/vendor/swoft/stdlib/src/Helper/SystemHelper.php:72
