### ISSUE TITLE
提示 API must be called in the coroutine

### ISSUE THREAD

**Issue by suhanyujie** [swoft-cloud/swoft#790]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.x
| Swoole version      | 4.4
| PHP version         | 7.3
| Runtime environment | CentOS 7

**Details**
- 启动 http 服务 `php bin/swoft http:start` 提示 fatal error

```other
Uncaught Swoole\Error: API must be called in the coroutine invendor/swoft/stdlib/\src/Helper/SystemHelper.php:72
```

> 通过 composer 方式安装的 swoft `composer create-project swoft/swoft swoft`

**Comment by suhanyujie** [comment]
在 qq 群里问了。通过切换到 swoole 4.3 可以解决。

**Comment by EPsheep** [comment]
swoft2.0.3至2.0.5, ./bin/swoft注释掉
\Swoole\Runtime::enableCoroutine();
这段代码也可以解决

**Comment by suhanyujie** [comment]
> swoft2.0.3至2.0.5, ./bin/swoft注释掉
> \Swoole\Runtime::enableCoroutine();
> 这段代码也可以解决

感觉你这个方法更靠谱点

**Comment by goforwork** [comment]
> > swoft2.0.3至2.0.5, ./bin/swoft注释掉
> > \Swoole\Runtime::enableCoroutine();
> > 这段代码也可以解决
> 
> 感觉你这个方法更靠谱点

可是这样不就关了携程环境吗？
