### ISSUE TITLE
关闭服务失败  

### ISSUE THREAD

**Issue by 823688826** [swoft-cloud/swoft#791]
Stopping ............
Stop the swoft(PID:6365) failed(timeout)!

**Comment by inhere** [comment]
swoole 版本呢

**Comment by 823688826** [comment]
> swoole版本呢

4.3

**Comment by 823688826** [comment]
除了启动命令可以使用   重启和停止命令都失效  是怎么回事？

**Comment by 823688826** [comment]
还有我手动kill掉服务进程  产生了一堆的睡眠进程
![image](https://user-images.githubusercontent.com/26970055/60874139-22777d00-a26a-11e9-85f4-9805caa63649.png)

**Comment by stelin** [comment]
你是不是多次重新启动不同的端口
