### ISSUE TITLE
日志文件格式

### ISSUE THREAD

**Issue by ChangeChe** [swoft-cloud/swoft#798]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.3
| Swoole version      | 4.3.1
| PHP version         | 7.2.16
| Runtime environment | docker

**Details**

> 希望日志文件能按天归档，请问现在有这样的配置吗？

**Comment by stelin** [comment]
@ChangeChe 我们考虑下，加要给按时间分割日志

**Comment by ChangeChe** [comment]
还有一个，使用\Swoft\Log\Helper\Log 记的日志[$level]那块 能不能用大写的。我看现在是小写的是写死的

**Comment by stelin** [comment]
@ChangeChe 2.0.6 我们加上日志按日期或大小切割功能。大小写不一样么，只是一个规则而已。

**Comment by stelin** [comment]
已经新增按日期格式切割日志，2.0.6发布
