### ISSUE TITLE
PointBean 正则

### ISSUE THREAD

**Issue by okami-chen** [swoft-cloud/swoft#801]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> 什么时候能支持 ？

```php
@PointBean(include={App\Controller\*})
```

**Comment by stelin** [comment]
你使用方式不对，App\\Controller\\* 斜杠是转义字符

**Comment by stelin** [comment]
```
App\\Controller\\*::.*
```

**Comment by stelin** [comment]
@okami-chen 2.0.3 已经支持，但是格式要对

**Comment by okami-chen** [comment]
> ```
> App\\Controller\\*::.*
> ```

感谢
