### ISSUE TITLE
应用分层，例如 controller 、service 应该如何设置？

### ISSUE THREAD

**Issue by damaainan** [swoft-cloud/swoft#802]
应用分层，例如MVC架构应该如何设置？

**Comment by stelin** [comment]
@damaainan 每个公司业务不一样，会采用不一样的架构

**Comment by damaainan** [comment]
可能没描述清楚。采用controller 、service 的分层，service 分层应该怎么创建？注解应该采用哪一类？

**Comment by stelin** [comment]
service 和controller是统一级别的，其它按照之前就好

**Comment by damaainan** [comment]
controller的注解是 controller，我要是想加一层 service，并且使用注解，应该怎么加？直接使用 bean ?还是其他的？

**Comment by damaainan** [comment]
希望有人能举例说明一下
![image](https://user-images.githubusercontent.com/11410837/61200615-9efbd700-a714-11e9-873c-569df0ae4e37.png)
能否这样使用？这样使用的话 service 的注解怎么写？

**Comment by inhere** [comment]
在 swoft 里 service 专指 RPC 服务

业务逻辑上分层 可以参考 model 下面的目录 分为 logic, data, dao, entity

**Comment by damaainan** [comment]
使用了 model 目录下的 logic 进行逻辑分层
