### ISSUE TITLE
数据库模型 save() 更新问题

### ISSUE THREAD

**Issue by MrxuanJ** [swoft-cloud/swoft#806]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.3
| Swoole version      | 4.3.5
| PHP version         | 7.2.19
| Runtime environment | CentOS 7

**Details**

> 从 2.0.2 更新 2.0.3 后，数据库模型操作 ->save();  新数据会插入，但是不会更新

```php
return = true;
```

> 是否已经移除实体 save 更新操作？改用 update 了？

```php
$user = User::find(1);
$user->setName('newName');
$user->save();

返回 true 但实际数据库字段 name 还是没修改，如果是

$user = new User();
$user->setName('first');
$user->save();

可插入一条数据
```

**Comment by sakuraovq** [comment]
更新通过 setter 同步有点小问题 感谢您的反馈 , 2.0.4 修复
