### ISSUE TITLE
aop getArgs()提供的不是关联数组,无法实现一些业务

### ISSUE THREAD

**Issue by jlzan1314** [swoft-cloud/swoft#808]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 4.3.5

希望加个新方法,可以获取到参数的map
顺便改下,获取target的原始类名,现在获取需要转换下,后面这个你们自己看吧

**Comment by stelin** [comment]
2.0.4 已发布，已新增此功能
