### ISSUE TITLE
Dockerfile composer 没有设置仓库源

### ISSUE THREAD

**Issue by 957651480** [swoft-cloud/swoft#809]
#composer 安装
RUN php -r"copy('https://getcomposer.org/installer','composer-setup.php');" \
    && php composer-setup.php --install-dir=/usr/bin --filename=composer \
    && composer config -g repo.packagist composer https://mirrors.aliyun.com/composer

阿里云 Composer 全量镜像（推荐）
镜像类型：全量镜像
更新时间：1 分钟
镜像地址：https://mirrors.aliyun.com/composer/
官方地址：https://mirrors.aliyun.com/composer/index....\
镜像说明：阿里云 CDN 加速，更新速度快，推荐使用

安畅网络镜像
镜像类型：全量镜像
更新时间：1 分钟
镜像地址：https://php.cnpkg.org
官方地址：https://php.cnpkg.org/
镜像说明：此 Composer 镜像由安畅网络赞助，目前支持元数据、下载包全量代理。

交通大学镜像
镜像类型：非全量镜像
镜像地址：https://packagist.mirrors.sjtug.sjtu.edu.c...\
官方地址：https://mirrors.sjtug.sjtu.edu.cn/packagis...\
镜像说明：上海交通大学提供的 composer 镜像，稳定、快速、现代的镜像服务，推荐使用。

**Comment by inhere** [comment]
这是通用的镜像，所以不会设置源的。 😄 而且官方镜像是在 docker.hub 构建的，它是在国外。
你自己构建镜像的话可以改下本地文件在构建。
