### ISSUE TITLE
调用同名模型与实际使用模型错误

### ISSUE THREAD

**Issue by shenhai1120** [swoft-cloud/swoft#811]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes/no
| Swoft version       | 2.0
| Swoole version      | 4.3
| PHP version         | 7.3
| Runtime environment | Mac.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
App\Rpc\Service\UserService  
ues App\Model\User 
实际调用的是 App\Model\Entity\User
App\Model\User 改为 User4 调用正常
```

**Comment by inhere** [comment]
描述清楚点啊！！！ 😄

**Comment by shenhai1120** [comment]
> 描述清楚点啊！！！ 😄

在App\Rpc\Service\UserService中只use App\Model\User模型 使用User::new();结果报错实际调用的是App\Model\Entity\User；然后把App\Model\User改成User4 使用User4::new()，然后正常了

**Comment by sakuraovq** [comment]
命名空间指定清楚啊 use 到 具体的实体类啊

**Comment by shenhai1120** [comment]
@我生成了一个user.php模型，在rpc里面只使用了这个模型，运行的时候并没有使用我生成的模型而是使用的App\Model\Entity\User模型，然后我把我生成的模型改成user4.php在运行，然后对了 
@inhere @sakuraovq

**Comment by sakuraovq** [comment]
贴下你复现代码呢 我们看下

**Comment by shenhai1120** [comment]
@sakuraovq 
<?php declare(strict_types=1);


namespace App\Rpc\Service;


use App\Rpc\Lib\UserInterface;
use Exception;
use Swoft\Co;
use Swoft\Rpc\Server\Annotation\Mapping\Service;
use App\Model\User4;
use App\Model\User;

/**
 * Class UserService
 *
 * @since 2.0
 *
 * @Service()
 */
class UserService implements UserInterface
{
    public function create(array $data)
    {
        // $res = User::new($data)->save(); //调用错误
        $res = User4::new($data)->save(); // 正常
        return $res;
    }
}

我的user表新建的没有age字段

错误信息  

2019/07/14-00:55:43 [ERROR] App\Exception\Handler\HttpExceptionHandler:handle(34) Rpc call error!code=0 message= Call to undefined method Swoft\Db\Query\Builder::getAge() At /Applications/XAMPP/xamppfiles/htdocs/tyy-package/swoft/vendor/swoft/stdlib/src/Helper/PhpHelper.php line 51 data={"jsonrpc":"2.0"} pool=user.pool version=1.0

**Comment by inhere** [comment]
@sakuraovq  生成的目录和命名空间错了？

**Comment by sakuraovq** [comment]
@shenhai1120  这个是 demo 的 实体 你删除就好

**Comment by sakuraovq** [comment]
@shenhai1120  你看看  `App\Model\User` 文件里面的内容不就知道了嘛 这个 `User` 是框架的 demo

**Comment by sakuraovq** [comment]
@shenhai1120  你 是用过 `entity` 生成的吗  生成的时候指定了路径吗

**Comment by shenhai1120** [comment]
@sakuraovq  我就是这样生成的，我的用户表是yii2的用户表
php bin/swoft entity:c user --path=@app/Model

**Comment by sakuraovq** [comment]
你没有用实体 就应该吧 entity 那个目录删除啊 demo 留着干嘛

**Comment by sakuraovq** [comment]
可能 demo 影响了 命令空间生成 应该是 对的

**Comment by shenhai1120** [comment]
close #811

**Comment by shenhai1120** [comment]
上手就掉坑里了，哈哈

**Comment by sakuraovq** [comment]
解决了吗 @shenhai1120
