### ISSUE TITLE
模型toArray的建议

### ISSUE THREAD

**Issue by 601157475** [swoft-cloud/swoft#814]
通过get获取的数据列表通过toArray能够转化为数组，如果数据为空null的情况下在调用程序会报错，建议返回空数组。

**Comment by sakuraovq** [comment]
get 返回是一个集合 toArray 应该是没有

**Comment by sakuraovq** [comment]
@601157475 使用的代码 贴出来呢 我看看 是怎么回事

**Comment by 601157475** [comment]
User::where('id','>','1')->first()->toArray();
如下所示  如果first返回值可能是空的，这时会报错
(Error) Call to a member function toArray() on null

**Comment by jlzan1314** [comment]
first 返回本来就可以为空..不能改..你要判断的

**Comment by sakuraovq** [comment]
@601157475  这返回的是实体 本来可能为空 这个不好改的

**Comment by sakuraovq** [comment]
返回实体 比用数组更爽 啊,  响应的时候 框架会自动 `toArray` 所以没关系

**Comment by 601157475** [comment]
好的，我知道了，主要是我写在rpc里面，返回值被定义了array 所以。。。。
