### ISSUE TITLE
框架封装的redis set方法与原生redis扩展的set方法不一致

### ISSUE THREAD

**Issue by codeingist** [swoft-cloud/swoft#816]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       |2.0.3
| Swoole version      | 4.3.5
| PHP version         | 7.2.20
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> swoft框架封装的redis操作的set方法和phpredis扩展的set方法参数不一致。原生的redis扩展set方法第三个参数是可以传入一个数组的框架封装的只能传入一个整形，并且框架中貌似没有提供一个方法来获取redis扩展的对象..

phpredis set方法的相关文档：https://github.com/phpredis/phpredis/#set

> 是否提供一个方法获取phpredis扩展的对象或者说重写一下框架现有的redis操作类做下兼容？

**Comment by sakuraovq** [comment]
我们统一下 原生的 好像可以 第三个参数可以是 array

**Comment by sakuraovq** [comment]
可以用 `rawCommand ` 实现喔 框架不兼容 一个参数多种类型
