### ISSUE TITLE
当错误信息中含有百分号%时，无法使用Log或CLog打印

### ISSUE THREAD

**Issue by smilecc** [swoft-cloud/swoft#817]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.2
| Swoole version      | 4.3.5
| PHP version         | 7.1.27
| Runtime environment | Docker

**Details**

由于CLog与Log中大量使用了sprintf，当错误信息中含有百分号时就会被认为是参数数量错误。

```
sprintf(): Too few arguments At /mnt/d/code/message-service/service-message/vendor/swoft/log/src/Helper/CLog.php line 104
```

例如当用户无法连接数据库，可以遇到如下情况，此时这个错误无论是使用Log还是CLog都是无法被打印出来的。

```php
<?php

CLog::error("Cant connect mysql with 'user'@% , blabla");
```

**Comment by stelin** [comment]
@smilecc 感谢反馈，我们尽快修复！

**Comment by stelin** [comment]
已修复 2.0.4 发布
