### ISSUE TITLE
官方会不会给弄个sentry的插件

### ISSUE THREAD

**Issue by 601157475** [swoft-cloud/swoft#818]
毕竟这是个好东西，好吧我不会弄

**Comment by inhere** [comment]
自己稍微封装下也很快啊

**Comment by chenjing0521** [comment]
正好我要用 ，我想封装一个   ，能否到时候给一下知道 @inhere

**Comment by inhere** [comment]
@chenjing0521  欢迎封装，封装了可以提交到 https://github.com/swoft-cloud/awesome-swoft  让更多人知道了解

**Comment by chenjing0521** [comment]
好的

**Comment by ryanho2009** [comment]
写了一个大家可以试试，有什么问题可以反馈
https://packagist.org/packages/rpr/swoft-sentry

**Comment by 601157475** [comment]
大佬，我学习一下发自我的华为手机-------- 原始邮件 --------主题：Re: [swoft-cloud/swoft] 官方会不会给弄个sentry的插件 (#818)发件人：Ryan 收件人：swoft-cloud/swoft 抄送：601157475 ,Author 写了一个大家可以试试，有什么问题可以反馈

https://packagist.org/packages/rpr/swoft-sentry

**Comment by inhere** [comment]
@ryanho2009 欢迎提交到 https://github.com/swoft-cloud/awesome-swoft 让更多人知道。
还可以在 https://learnku.com/swoft 发下文章介绍下。

**Comment by ryanho2009** [comment]
> @ryanho2009 欢迎提交到 https://github.com/swoft-cloud/awesome-swoft 让更多人知道。
> 还可以在 https://learnku.com/swoft 发下文章介绍下。

好的
