### ISSUE TITLE
验证器无法使用Confirm验证规则

### ISSUE THREAD

**Issue by etoup** [swoft-cloud/swoft#819]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 2.0.3-beta
| Swoole version      | 4.3.5
| PHP version         | 7.2.18
| Runtime environment | Mac/Docker etc.

**Details**

> 缺少文档中@Confirm验证规则

**Comment by stelin** [comment]
@etoup 2.0.4 才会支持，
