### ISSUE TITLE
使用swoft-cli打包路径问题

### ISSUE THREAD

**Issue by shenhai1120** [swoft-cloud/swoft#820]
打包后的phar运行全是以some.phar为根目录，这咋搞还是说我配置没对

$compiler
    // 删除代码注释。打包swoft 应用需要配合 setStripFilter()
    ->stripComments(true)
    ->setShebang(true)
    // 需要打包的文件后缀，内置已经包含了 .php
    ->addSuffix(['.tpl', '.json'])
    // 排除打包目录，排除一些无用的目录，可以有效减少输出文件大小
    ->addExcludeDir([
        'test',
        'doc',
        'docs',
        'tests',
        'Tests',
        'example',
        'runtime',
        'swoole-ide-helper',
        'dist',
    ])
    // 指定添加的文件
    ->addFile([
        'LICENSE',
        'composer.json',
        'README.md',
        'bin/bootstrap.php',
        '.evn',
    ])
    ->setCliIndex('bin/swoft') // 应用入口
;

// 那些目录需要去除注释。Swoft 相关都不能去除注释
$stripDirs = [
    'psr/',
    'nikic/',
    'monolog/',
    'symfony/',
    'toolkit/',
];

$compiler->setStripFilter(function ($file) use ($stripDirs) {
    /** @var \SplFileInfo $file */
    $path = $file->getPathname();

    foreach ($stripDirs as $dir) {
        if (\strpos($path, $dir)) {
            return true;
        }
    }

    return false;
});

**Comment by inhere** [comment]
phar 里运行就是以它自己为根目录

**Comment by shenhai1120** [comment]
打包后直接php some.phar runtime文件夹找不到  我设置成 log_file=> '../runtime/some.log'; 路径还是以some.phar 为根目录，这咋处理

**Comment by inhere** [comment]
下个版本发修复版。你可以先手动设置下(`app/Application`)：

```php

    protected function afterInit(): void
    {
        parent::afterInit();
		
		// 必须写绝对路径，不能使用 __DIR__ 这样的常量
        $this->setRuntimePath('/tmp/runtime');
    }
```
