### ISSUE TITLE
Restart failure

### ISSUE THREAD

**Issue by curtis18** [swoft-cloud/swoft#823]
| Q                   | A
| ------------------- | -----
| Bug report?         |  **yes**/no
| Feature request?    | yes/ **no**
| Swoft version       | 2.0.3
| Swoole version      | 4.3.6 (by `php --ri swoole`)
| PHP version         | 7.2.19 (by `php -v`)
| Runtime environment | Docker Ubuntu

Stop the old server failed when running restart command.
![restart_failure](https://user-images.githubusercontent.com/6743839/61347099-37699700-a88e-11e9-8543-9b9b703b8d67.PNG)

**Comment by kaituosoft** [comment]
我也是的,

**Comment by kaituosoft** [comment]
Swoft version 2.0.4
问题依然存在

**Comment by curtis18** [comment]
@kaituosoft It does not happen anymore, are you using Mac OS?

**Comment by kaituosoft** [comment]
@curtis18 yes

**Comment by stelin** [comment]
Only Mac OS has this problem

**Comment by stelin** [comment]
The problem is solving by Swoole

**Comment by curtis18** [comment]
@kaituosoft you can upgrade Swoole to v4.4.2 to solve the problem. Thanks @stelin
