### ISSUE TITLE
update无法更新json数据

### ISSUE THREAD

**Issue by SuKerd** [swoft-cloud/swoft#827]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.3
| Swoole version      | 4.3.5
| PHP version         | 7.3.5
| Runtime environment | CentOS 7

**Details**

>  执行update更新json数据无法更新

```php
$test = DB::table('personnel_details')
       ->where('id', 20)
       >update(['extend->lj_user_id' => json_encode('dsdfsdf')]);
 var_dump($test); //int(0)
```

> 但是直接执行sql就能执行成功

```php
$test = DB::update("update `personnel_details` set `extend` = json_set(`extend`, '$.\"lj_user_id88\"', \"dsdfsdf\") where `id` = ?",[20]);
 var_dump($test); //int(1)   
```
> 进入swoft\db\src\Connection\Connection.php 498行，update打印后发现
```php
    public function update(string $query, array $bindings = []): int
    {
        //绑定数据多了一个update的值
        var_dump($query);  //string(106) "update `personnel_details` set `extend` = json_set(`extend`, '$."lj_user_id88"', "dsdfsdf") where `id` = ?"
        var_dump($bindings); //array(2) {  [0]=> string(9) ""dsdfsdf"" [1]=>  int(20)}
        return $this->affectingStatement($query, $bindings);
    }
```
> 怎么解决？就用原生？还有一个问题就是如果json字段为null是无法update的
```php
"update `personnel_details` set `extend` = json_set(`extend`, '$."lj_user_id88"', "dsdfsdf") where `id` = 20"//无法更新
"update `personnel_details` set `extend` = json_set('{}', '$."lj_user_id88"', "dsdfsdf") where `id` = 20"//可以更新成功
```

**Comment by sakuraovq** [comment]
ok, i'm looking

**Comment by sakuraovq** [comment]
@SuKerd 已经修复了  2.0.4 下周发布

**Comment by SuKerd** [comment]
> 
> 
> @SuKerd 已经修复了 2.0.4 下周发布

**Comment by SuKerd** [comment]
> 
> 
> @SuKerd 已经修复了 2.0.4 下周发布

那为null的时候呢，这个可以了吗？

**Comment by sakuraovq** [comment]
为 null 的那个有点麻烦

**Comment by sakuraovq** [comment]
为 null 的可以啊

**Comment by sakuraovq** [comment]
我知道为什么了

**Comment by sakuraovq** [comment]
如果 为空 是 "[]" 存储的这样的格式  json_set 就不行  是  "{}" 这的格式就可以 因为数据格式不对称了

**Comment by sakuraovq** [comment]
这个不好搞

**Comment by sakuraovq** [comment]
我这边把 json 默认值改成 `{}` 如果数据库已经是 `{}` json set 无效

**Comment by sakuraovq** [comment]
我这边把 json 默认值改成 `{}` 如果数据库已经是 `[]` json set 无效

**Comment by sakuraovq** [comment]
`model` 可以做  `DB` 这个不好判断 需要自己实现

**Comment by SuKerd** [comment]
> 
> 
> `model` 可以做 `DB` 这个不好判断 需要自己实现

感觉这是mysql的不足了，如果要做这个操作就得先去查询一次，就让我这个强迫症很难受

**Comment by sakuraovq** [comment]
是的 这是 mysql 成面的 做这个判断 要 判断 `null` 的情况和 `[]` 的情况 这个不好判断的

**Comment by SuKerd** [comment]
> 
> 
> 是的 这是 mysql 成面的 做这个判断 要 判断 `null` 的情况和 `[]` 的情况 这个不好判断的

麻烦了，2.0.4下周几发布

**Comment by sakuraovq** [comment]
我模型做下 null 的兼容把   下周嘛具体不清楚哈
