### ISSUE TITLE
swoft2.x ORM问题

### ISSUE THREAD

**Issue by hihozhou** [swoft-cloud/swoft#830]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Swoft version       | 2.0.3
| Swoole version      | 4.3.3
| PHP version         | 7.2
| Runtime environment | Ubuntu

**Details**

> 在调用set方法设置模型时候，由于没有对`$modelAttributes`进行修改，所以在更新操作前检测是否修改方法`isDirty`时候，会检测到没有修改

```php
//model
class User extends Model
{
    /**
     * 
     * @Id()
     * @Column()
     * @var int|null
     */
    private $id;

    /**
     * 
     *
     * @Column()
     * @var string
     */
    private $name;

   /**
     * @param string $name
     *
     * @return void
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

   /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }


}

//调用
$user = User::firstOrFail();
$user->setName('test');//只对类属性修改，并没有对$modelAttributes中的值修改
$user->save();//无效，因为isDirty检测$modelAttributes

```

同样的因为模型继承了实现了ArrayAccess的offsetSet方法，如果直接`$user['name']='test';也是没有修改到`$modelAttributes`方法

## 最后建议就是
`1.使用注解属性，然后定义get和set方法`和 `2.实现ArrayAccess这两种操作模型的逻辑`有点冲突，
因为实现了ArrayAccess那就没有必要属性都表明了，而定义了get和set，属性private又不应可以直接访问对象属性

**Comment by sakuraovq** [comment]
马上修复
