### ISSUE TITLE
執行 php bin/swoft migrate:down 之後，無法再次 migrate:up

### ISSUE THREAD

**Issue by andiechang** [swoft-cloud/swoft#838]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.3
| Swoole version      | 4.3.5 (by `php --ri swoole`)
| PHP version         | 7.2.10 (by `php -v`)
| Runtime environment | Docker

**Details**

> Describe what you are trying to achieve and what goes wrong.

1. 執行 php bin/swoft migrate:down
2. 修改 migration 程式碼
3. 再次執行 php bin/swoft migrate:up
只會出現一行訊息：
```
[SUCCESS] execute ok
```

必須將 migration 資料表裡面已經 rollback 的資料刪除後，才能再次執行 migrate:up

**Comment by sakuraovq** [comment]
Migration scripts Up and Down can only be executed once

**Comment by andiechang** [comment]
> Migration scripts Up and Down can only be executed once

Oh my god.....
That's mean I need to create new migration file to correct some mistake in code....??

Could possible like "Laravel migration"?? Can exceute more than once??

**Comment by sakuraovq** [comment]
I'm sorry My thoughts may be a bit different. We optimize this time.

**Comment by inhere** [comment]
@andiechang OO, you are right!
We will optimize to fix this problem

**Comment by sakuraovq** [comment]
accept

**Comment by sakuraovq** [comment]
composer update
