### ISSUE TITLE
继承父类控制器的成员属性不能在其他控制器使用，这是为什么呢？

### ISSUE THREAD

**Issue by phper08** [swoft-cloud/swoft#840]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 2.0.3
| Swoole version      | 4.4.0 (by `php --ri swoole`)
| PHP version         | 7.3.0 (by `php -v`)
| Runtime environment | Mac

**Details**

https://www.swoft.org/docs/2.x/zh-CN/http-server/controller.html#%E6%B3%A8%E6%84%8F
子类继承父类，为什么不能使用父类的属性？文档里只提到这是错误的，并未说明原因。

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by sakuraovq** [comment]
Annotation does not support inheritance

**Comment by phper08** [comment]
有什么替代方案吗？

**Comment by beckjiang218** [comment]
使用`trait`可以解决吗

**Comment by sakuraovq** [comment]
只是注解不能继承 属性啥的其他不影响啊

**Comment by sunnyos** [comment]
> Q	A
> Bug report?	no
> Feature request?	no
> Swoft version	2.0.3
> Swoole version	4.4.0 (by `php --ri swoole`)
> PHP version	7.3.0 (by `php -v`)
> Runtime environment	Mac
> **Details**
> 
> https://www.swoft.org/docs/2.x/zh-CN/http-server/controller.html#%E6%B3%A8%E6%84%8F
> 子类继承父类，为什么不能使用父类的属性？文档里只提到这是错误的，并未说明原因。
> 
> ```
> // paste output here
> ```
> 
> > Provide minimal script to reproduce the issue
> 
> ```
> // paste code
> ```

因为这样会导致数据污染，在swoft里面controller是单例的，在内存里面只会存在一份，如果你把用户的id存到这里来，然后你别的请求再进来的时候就会把这个值改掉，如果下面有一个控制器会修改用户信息。如你的id是 1  我的id是  3 ，你先执行修改，而在你修改处理其他逻辑时间没有反应过来的时候，我请求了，这时候这个值变成 3 了

**Comment by phper08** [comment]
> 
> 
> > Q	A
> > Bug report?	no
> > Feature request?	no
> > Swoft version	2.0.3
> > Swoole version	4.4.0 (by `php --ri swoole`)
> > PHP version	7.3.0 (by `php -v`)
> > Runtime environment	Mac
> > **Details**
> > https://www.swoft.org/docs/2.x/zh-CN/http-server/controller.html#%E6%B3%A8%E6%84%8F
> > 子类继承父类，为什么不能使用父类的属性？文档里只提到这是错误的，并未说明原因。
> > ```
> > // paste output here
> > ```
> > 
> > 
> > > Provide minimal script to reproduce the issue
> > 
> > 
> > ```
> > // paste code
> > ```
> 
> 因为这样会导致数据污染，在swoft里面controller是单例的，在内存里面只会存在一份，如果你把用户的id存到这里来，然后你别的请求再进来的时候就会把这个值改掉，如果下面有一个控制器会修改用户信息。如你的id是 1 我的id是 3 ，你先执行修改，而在你修改处理其他逻辑时间没有反应过来的时候，我请求了，这时候这个值变成 3 了

controller能用对象池模式吗？

**Comment by sunnyos** [comment]
> controller能用对象池模式吗？

底层的实现就是单例模式，用户没有办法设置controller的模式

**Comment by burugo** [comment]
> > Q	A
> > Bug report?	no
> > Feature request?	no
> > Swoft version	2.0.3
> > Swoole version	4.4.0 (by `php --ri swoole`)
> > PHP version	7.3.0 (by `php -v`)
> > Runtime environment	Mac
> > **Details**
> > https://www.swoft.org/docs/2.x/zh-CN/http-server/controller.html#%E6%B3%A8%E6%84%8F
> > 子类继承父类，为什么不能使用父类的属性？文档里只提到这是错误的，并未说明原因。
> > ```
> > // paste output here
> > ```
> > 
> > 
> > > Provide minimal script to reproduce the issue
> > 
> > 
> > ```
> > // paste code
> > ```
> 
> 因为这样会导致数据污染，在swoft里面controller是单例的，在内存里面只会存在一份，如果你把用户的id存到这里来，然后你别的请求再进来的时候就会把这个值改掉，如果下面有一个控制器会修改用户信息。如你的id是 1 我的id是 3 ，你先执行修改，而在你修改处理其他逻辑时间没有反应过来的时候，我请求了，这时候这个值变成 3 了

这个和继承没关系吧，继承的控制器对象属性值是自己的，并不会共享
