### ISSUE TITLE
日志记录信息完全没用 (Logging Data Useless)

### ISSUE THREAD

**Issue by cirvor** [swoft-cloud/swoft#846]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | v2.0.3
| Swoole version      | 4.3.6
| PHP version         | 7.2.20
| Runtime environment | Mac

**Details**
很简单的复现 调试日志 `Log::debug('this %s log', 'debug');` 故意不添加命名空间
发现记录的日志完全没用

终端显示
> 2019/07/22-09:49:59 [ERROR] App\Exception\Handler\HttpExceptionHandler:handle(34) Class 'App\Http\Controller\****\Log' not found

日志文件记录
> {"level":250,"level_name":"notice","channel":"swoft","datetime":"2019-07-22 09:49","event":"request","tid":2,"cid":3,"traceid":"","spanid":"","parentid":"","cost(ms":4.33,"mem(MB)":20,"uri"\/foo\/bar","pushLog":"","profile":"","counting":""}

如上所述，日志文件中至少要显示出来`Class 'App\Http\Controller\****\Log' not found`的信息吧？
最好加上trace

然后 这个不是error的日志嘛？为什么并没有生成error.log文件呢？

```php
//日志配置
'logger'         => [
        'flushRequest' => false,
        'enable'       => true,
        'json'         => true,
        'handlers'     => [
            'application' => \bean('applicationHandler'),
            'notice'      => \bean('noticeHandler'),
        ],
    ],
    'noticeHandler'      => [
        'class'     => \Swoft\Log\Handler\FileHandler::class,
        'logFile'   => '@runtime/logs/notice.log',
        'formatter' => \bean('lineFormatter'),
        'levels'    => 'notice,info,debug,trace',
    ],
    'applicationHandler' => [
        'class'     => \Swoft\Log\Handler\FileHandler::class,
        'logFile'   => '@runtime/logs/error.log',
        'formatter' => \bean('lineFormatter'),
        'levels'    => 'error,warning',
    ],
```

> Provide minimal script to reproduce the issue

```php
Log::debug('this %s log', 'debug');
```

**Comment by inhere** [comment]
框架不会主动记录日志。需要使用者自己在错误处理器里自己记录

**Comment by cirvor** [comment]
> 框架不会主动记录日志。需要使用者自己在错误处理器里手动记录

就是说哪怕开启了日志记录
框架在使用中出错了也不会记录错误日志？
然后开发者自己去复现错误并排查？

**Comment by inhere** [comment]
默认的异常处理都写好了的，要记录日志 就是加一句代码的事情，很难？ 😄

**Comment by inhere** [comment]
`App\Exception\Handler\HttpExceptionHandler:handle(34)` 就在这个位置，现在只是加了：

https://github.com/swoft-cloud/swoft/blob/ff5da5a3771174f518b6f9ee866da30eace26c65/app/Exception/Handler/HttpExceptionHandler.php#L34

你再加一行 `Log::error()` 就好了
