### ISSUE TITLE
ws:start 启动报错：(CONSOLE)Swoft\Server\Exception\ServerException: Swoole task event listener is not Swoft\Server\Contract\SyncTaskInterface

### ISSUE THREAD

**Issue by zoulongbo** [swoft-cloud/swoft#848]
问题：ws:start启动时报错：
![image](https://user-images.githubusercontent.com/24728778/61726500-52636c00-ada4-11e9-8b2d-4ac77c737e10.png)

解决：找到swoft/vendor/swoft/server/src/SwooleEvent.php类，发现Task监听映射了两个类，SyncTaskInterface::class 与TaskInterface::class，注释SyncTaskInterface::class 后，重启ws:start 完美启动
疑问：请问这里的SyncTaskInterface::class 是什么用途

**Comment by inhere** [comment]
使用同步task任务的
