### ISSUE TITLE
为什么需要强制安装redis扩展?

### ISSUE THREAD

**Issue by cxlblm** [swoft-cloud/swoft#849]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.4
| Swoole version      | 4.4.1
| PHP version         | 7.4.0 
| Runtime environment | Docker etc.

**Details**

> 为什么composer.json必须要依赖redis扩展呢? 这个不应该是交给用户选择的吗? 是否可以提一个PR删除这个依赖呢?

**Comment by inhere** [comment]
swoft 项目是功能最完整的demo，因此是需要所有依赖的。

不能删除，不需要的你可以在本地自己去除。

**Comment by cxlblm** [comment]
> swoft 项目是功能最完整的demo，因此是需要所有依赖的。
> 
> 不能删除，不需要的你可以在本地自己去除依赖再执行install。

说到demo项目, swoft会不会提供一个干净的骨架呢! 现在里面充满了大量的示例代码, 我要使用就需要把这些内容都清理掉.  这对项目开发没有任何意义! 而且demo的功能不应该是在文档里体现的吗?

**Comment by inhere** [comment]
文档里写demo代码，又有人说不能直接运行。。。 这又有啥办法？
