### ISSUE TITLE
阿里云安装超慢！

### ISSUE THREAD

**Issue by Tinywan** [swoft-cloud/swoft#85]

**Comment by huangzhhui** [comment]
请自行配置Composer中国镜像或Docker加速镜像

**Comment by aprchen** [comment]
这个docker 镜像用了个各种加速器还是慢的一逼...疯了

**Comment by daydaygo** [comment]
可以参考项目下的 dockerfile 自行编写, 一些 curl 下载的文件提前下载好使用 Dockerfile 的 COPY 指令.

最后, 请确认自己的docker环境, 自己尝试给 php 官方镜像安装 swoole 试试
