### ISSUE TITLE
Scheduled 注解不存在

### ISSUE THREAD

**Issue by geXingW** [swoft-cloud/swoft#854]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.4-beta
| Swoole version      | 4.4.1
| PHP version         | 7.2.9
| Runtime environment | Ubuntu

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
use Swoft\Task\Bean\Annotation\Scheduled;
```

`use Swoft\Task\Bean\Annotation\Scheduled;`
 注解不存在，如何实现定时任务？

**Comment by inhere** [comment]
2.0 暂时没有定时任务：

- 接下来两个版本可能会出
- 直接使用timer
- github上有同学迁移了 1.0 的到 2.0，可以搜索一下

**Comment by stelin** [comment]
@geXingW 2.0暂时还没支持定时任务，2.0.5 会支持，也就是下一个版本

**Comment by geXingW** [comment]
@stelin @inhere 后续会有 MQ 的支持吗？

**Comment by inhere** [comment]
看后续时间，应该会实现。
现在有自定义进程了，自己实现也很快的。

**Comment by geXingW** [comment]
@inhere 自定义进程的话，还是得实现一套 队列任务 的持久化。不然进程重启了，未执行任务就没了

**Comment by stelin** [comment]
新增秒级定时任务，2.0.5 已经发版
