### ISSUE TITLE
RequestMapping("")传入空字符串不生效

### ISSUE THREAD

**Issue by cxlblm** [swoft-cloud/swoft#855]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.4
| Swoole version      | 4.4.1
| PHP version         | 7.4.0
| Runtime environment | Docker etc.

**Details**

> 现在想基于控制器的路由前缀和方法路由实现一套RESTful风格的路由! 现在遇到一个问题就是, 如果`RequestMapping`的形参不区分null和"",  设置路由的时候回判断如果当前的route为空, 就自动设置路由为当前的控制器方法! 

```php
[ERROR] App\Exception\Handler\HttpExceptionHandler:handle(34) Route not found(path /stations)!
```

> Provide minimal script to reproduce the issue

```php
use App\Annotation\Mapping\GetRequestMapping;
use App\Entity\Station;
use Swoft\Context\Context;
use Swoft\Http\Message\ContentType;
use Swoft\Http\Server\Annotation\Mapping\Controller;
use Swoft\Http\Server\Annotation\Mapping\RequestMapping;

/**
 * @Controller("/stations")
 * Class StationController
 * @package App\Http\Controller
 */
class StationController
{

    /**
     * @RequestMapping("")
     */
    public function index()
    {
        $stations = Station::limit(10)->get();
        return Context::mustGet()->getResponse()->withContentType(ContentType::JSON)->withContent(json_encode($stations));
    }
}

```

**Comment by inhere** [comment]
`RequestMapping("")` 这时生成的路由是 `/stations/index`。

如果你想要 `index()` 的路由映射为 `/stations`，你可以直接写 `RequestMapping("/stations")。

**Comment by cxlblm** [comment]
> `RequestMapping("")` 这时生成的路由是 `/stations/index`。
> 
> 如果你想要 `index()` 的路由映射为 `/stations`，你可以直接写 `RequestMapping("/stations")`。
> 
> 文档上都是说了的啊 😄

文档上是有说明, 不过我觉得应该区分 `@RequestMapping()` `@RequestMapping("")`这个两个方法吧, 后者我是有明确传参的.

**Comment by inhere** [comment]
我们里面是严格类型的，只能是 string。所以默认就是空字符串，你这样写是没有区别的。
