### ISSUE TITLE
监听器Listener  监听swoole request 事件  未生效，好像框架未进行tigger

### ISSUE THREAD

**Issue by chenjing0521** [swoft-cloud/swoft#856]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.4
| Swoole version      | 4.4.1
| PHP version         | 7.2.1
| Runtime environment | CentOS 7

具体问题如题，框架的beforerequest，afterrequest  可用

**Comment by inhere** [comment]
为什么要直接监听 swoole request 呢？你是要自己实现 http 调度逻辑。

**Comment by chenjing0521** [comment]
还是昨天那个问题   重构 后端php代码  其他端不重构   为了兼容路由   /Api/Member/index    可以兼容/Api/member/index  我们的路由现在好像还不能设置 大小写敏感

**Comment by inhere** [comment]
可以这样，你重写 `Swoft\Http\Server\Swoole\RequestListener`，可以先对swoole的`$request` 稍作处理：

```php
$request->server['request_uri'] = strtolower($request->server['request_uri']);
```

就可以了，

在 `app/bean.php` 里覆盖默认的处理：

```php

        'httpServer'      => [
            'on' => [
                SwooleEvent::REQUEST => bean(MyRequestListener::class)
            ]
        ],
```

**Comment by chenjing0521** [comment]
好的 谢谢   我监听了 BeforeHttprequest
