### ISSUE TITLE
执行 php bin/swoft http:restart 会重启失败

### ISSUE THREAD

**Issue by summerKK** [swoft-cloud/swoft#858]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | x.y.z
| Swoole version      | 4.4.1 (by `php --ri swoole`)
| PHP version         | 7.2.20 (by `php -v`)
| Runtime environment | Docker.

**Details**

> Describe what you are trying to achieve and what goes wrong.
执行 php bin/swoft http:restart 会重启失败
![image](https://user-images.githubusercontent.com/19187969/61937340-3a1c6880-afc1-11e9-8477-04cc0306f1de.png)
- 我看了一下代码是因为没有杀掉旧的进程,因为swoft.pid的masterId为1,所以没有杀掉进程
- vendor/swoft/http-server/src/Command/HttpServerCommand.php
```php
    /**
     * Restart the http server
     *
     * @CommandMapping(usage="{fullCommand} [-d|--daemon]",)
     * @CommandOption("daemon", short="d", desc="Run server on the background")
     *
     * @throws ReflectionException
     * @throws ContainerException
     * @example
     *  {fullCommand}
     *  {fullCommand} -d
     */
    public function restart(): void
    {
        $server = $this->createServer();

        // Check if it has started
        if ($server->isRunning()) {
            $success = $server->stop();

            if (!$success) {
                output()->error('Stop the old server failed!');
                return;
            }
        }

        output()->writef('<success>Server HTTP restart success !</success>');
        $server->startWithDaemonize();
    }
```
- vendor/swoft/server/src/Server.php
```php
    /**
     * Check if the server is running
     *
     * @return bool
     */
    public function isRunning(): bool
    {
        $pidFile = alias($this->pidFile);

        // Is pid file exist ?
        if (file_exists($pidFile)) {
            // Get pid file content and parse the content
            $pidFile = file_get_contents($pidFile);

            // Parse and record PIDs
            [$masterPID, $managerPID] = explode(',', $pidFile);
            // Format type
            $masterPID  = (int)$masterPID;
            $managerPID = (int)$managerPID;

            $this->pidMap['masterPid']  = $masterPID;
            $this->pidMap['managerPid'] = $managerPID;

            // Notice: skip pid 1, resolve start server on docker.
            return $masterPID > 1 && Process::kill($masterPID, 0);
        }

        return false;
    }
```
![image](https://user-images.githubusercontent.com/19187969/61937488-8ff11080-afc1-11e9-936f-4ca9f055d5ea.png)

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by inhere** [comment]
swoft server 作为docker的第一个进程时，不要执行restart 是不可能成功的。 
你还不如直接restart docker. 
pid 为 1 是收到docker监控的，这个进程挂了，容器也就挂了。

**Comment by inhere** [comment]
你要使用 restart 那你就改下 docker-compose 覆盖掉默认的 start server 命令，手动到容器里去启动server，这时server不是第一个进程，是可以执行restart的。

**Comment by summerKK** [comment]
> 你要使用 restart 那你就改下 docker-compose 覆盖掉默认的 start server 命令，手动到容器里去启动server，这时server不是第一个进程，是可以执行restart的。

2.0有热更新功能吗?我之前也是重启docker,但是感觉每次重启都要等很久.

**Comment by inhere** [comment]
https://swoft.org/docs/2.x/zh-CN/tool/swoftcli/hot-restart.html

**Comment by summerKK** [comment]
> https://swoft.org/docs/2.x/zh-CN/tool/swoftcli/hot-restart.html

谢谢大佬

**Comment by rainbowMorelhahahah** [comment]
> https://swoft.org/docs/2.x/zh-CN/tool/swoftcli/hot-restart.html

404了

**Comment by inhere** [comment]
新文档地址变了。

这里还有一份老文档：

http://swoft.io/docs/2.x/zh-CN/tool/swoftcli/hot-restart.html
