### ISSUE TITLE
Dockerfile build时候报依赖版本的错误 ，应该更新dockerfile的from 7.1

### ISSUE THREAD

**Issue by bijingshihaizi** [swoft-cloud/swoft#859]
Dockerfile中的

FROM php:7.1

如果有之前php7.1镜像缓存的会build成功 ，没有的会报依赖版本错误的问题
 我用更改成旧版本的php:7.1.24

**Comment by inhere** [comment]
没有 `FROM php:7.1` 这句啊。 

现在是 `FROM php:7.2` 的了， 你是 1.0 ？

**Comment by bijingshihaizi** [comment]
是的 ，没有用到7.2 ，但是我测试好像向上不兼容




------------------ 原始邮件 ------------------
发件人: "Inhere"<notifications@github.com>; 
发送时间: 2019年7月29日(星期一) 下午5:01
收件人: "swoft-cloud/swoft"<swoft@noreply.github.com>; 
抄送: "有你陪着我"<1225448773@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [swoft-cloud/swoft] Dockerfile build时候报依赖版本的错误 ，应该更新dockerfile的from 7.1 (#859)




没有 FROM php:7.1 这句啊。
 
现在是 FROM php:7.2 的了， 你是 1.0 ？

**Comment by inhere** [comment]
哦 不会吧 报啥错误？

**Comment by bijingshihaizi** [comment]
我用的不是master，我是1.x分支拉的dockerfile，还是from7.1 
报的错误我没全记住 ，我只记得有个libssl的依赖版本需要降，但是降低了后还会和curl的发生冲突





------------------ 原始邮件 ------------------
发件人: "Inhere"<notifications@github.com>; 
发送时间: 2019年7月29日(星期一) 下午5:05
收件人: "swoft-cloud/swoft"<swoft@noreply.github.com>; 
抄送: "有你陪着我"<1225448773@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [swoft-cloud/swoft] Dockerfile build时候报依赖版本的错误 ，应该更新dockerfile的from 7.1 (#859)




哦 不会吧 报啥错误？

**Comment by inhere** [comment]
哦，你用的swoft 1.0 ?

**Comment by bijingshihaizi** [comment]
4.0.3 




------------------ 原始邮件 ------------------
发件人: "Inhere"<notifications@github.com>; 
发送时间: 2019年7月29日(星期一) 下午5:13
收件人: "swoft-cloud/swoft"<swoft@noreply.github.com>; 
抄送: "有你陪着我"<1225448773@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [swoft-cloud/swoft] Dockerfile build时候报依赖版本的错误 ，应该更新dockerfile的from 7.1 (#859)




哦，你用的swoft 1.0 ?

**Comment by inhere** [comment]
推荐升级到 `swoft 2.0` 更加稳定。
