### ISSUE TITLE
getResult（classname）returns directly an instance of the called class even if the result is empty.

### ISSUE THREAD

**Issue by eaglering** [swoft-cloud/swoft#86]
![69 n0 m4 qp_ abmjnv0exs](https://user-images.githubusercontent.com/13248249/35423533-251b36d2-0289-11e8-8721-df07b44c41b6.png)
getResult（class）returns directly an instance of the called class even if the result is empty.

**Comment by huangzhhui** [comment]
I think the method should always return an same object, strong typing is more maintainable

**Comment by stelin** [comment]
When query is empty, the getResult will return null
