### ISSUE TITLE
win7环境下使用 cygwin安装swoft错误

### ISSUE THREAD

**Issue by yykpf** [swoft-cloud/swoft#865]
错误问题：
`$ php bin/swoft -h
2019/07/31-11:55:45 [INFO] Swoft\SwoftApplication:setSystemAlias(485) Set alias @base=/cygdrive/d/Tool/phpStudy/WWW/swoft
2019/07/31-11:55:45 [INFO] Swoft\SwoftApplication:setSystemAlias(486) Set alias @app=@base/app
2019/07/31-11:55:45 [INFO] Swoft\SwoftApplication:setSystemAlias(487) Set alias @config=@base/config
2019/07/31-11:55:45 [INFO] Swoft\SwoftApplication:setSystemAlias(488) Set alias @runtime=@base/runtime
2019/07/31-11:55:45 [INFO] Project path is /cygdrive/d/Tool/phpStudy/WWW/swoft
2019/07/31-11:55:45 [INFO] Swoft\Processor\EnvProcessor:handle(52) Env file(/cygdrive/d/Tool/phpStudy/WWW/swoft/.env) is loaded
2019/07/31-11:55:52 [INFO] Swoft\Processor\AnnotationProcessor:handle(45) Annotations is scanned(autoloader 31, annotation 428, parser 90)
PHP Parse error:  syntax error, unexpected '.10758325' (T_DNUMBER), expecting '{' in /tmp/UserInterface_IGNORE_5d41114817c476.10758325.php on line 5
`
使用命令：
`php bin/swoft -h`
相应返回错误信息：
`2019/07/31-11:55:52 [INFO] Swoft\Processor\AnnotationProcessor:handle(45) Annotations is scanned(autoloader 31, annotation 428, parser 90)
PHP Parse error:  syntax error, unexpected '.10758325' (T_DNUMBER), expecting '{' in /tmp/UserInterface_IGNORE_5d41114817c476.10758325.php on line 5
`
错误代码展示：
`
<?php
 declare (strict_types=1);
namespace App\Rpc\Lib;

class UserInterface_IGNORE_5d41114817c476.10758325 implements \App\Rpc\Lib\UserInterface
{
    use \Swoft\Rpc\Client\Concern\ServiceTrait;
    public function getOriginalClassName() : string
    {
        return 'App\\Rpc\\Lib\\UserInterface';
    }
......
`
环境：
php:
`PHP 7.1.16 (cli) (built: Apr 10 2018 18:09:30) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
`
swoole: 
    4.4.1
扩展：
![image](https://user-images.githubusercontent.com/14089155/62185318-79b5cc80-b394-11e9-9a5a-6ca89e02ea54.png)

**Comment by stelin** [comment]
@yykpf 已修复 2.0.5 一起发布

**Comment by inhere** [comment]
`2.0.5` 已经发布。
