### ISSUE TITLE
Swoft自带的数据库模型中 getter 和 setter 的意义在哪里

### ISSUE THREAD

**Issue by be1ief** [swoft-cloud/swoft#868]
今天我尝试使用swoft的时候，我发现一个很没有意义的设计，setter实际上并没有发挥它应有的作用。我尝试观测setter时候我发现，模型在加载的时候，就会去调用这个setter完成entity的初始化。但是这样真的有意义吗？我认为作为setter，它应当是用于简化开发者工作，完成某些赋值时的数据转换。而不是通过调用setter去完成entity的初始化，这样的设计会使得setter局限性很大，而且并没什么实际卵用。应用场景很窄，连个时间转换的任务都不能胜任。另外我还要说，既然基于PHP7，强类型的约束下更显得setter没啥用了。。。

补图：
![QQ截图20190731211206](https://user-images.githubusercontent.com/53355510/62214626-0635ae80-b3d8-11e9-9ce2-317a33ff91c3.png)

一张图说明所有问题

另外我要吐槽的是。。。其他地方学Java思想学的挺好，这个地方一学一个Bug....

**Comment by sunnyos** [comment]
在使用实体操作得时候可以通过get和set方法获取和设置值，里面的数据类型跟数据库对应
