### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by amorZhu** [swoft-cloud/swoft#870]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | latest
| Swoole version      | no
| PHP version         | PHP 7.3.7-2+ubuntu18.04.1+deb.sury.org+1
| Runtime environment | No

**Details**
通过文档使用`docker-compose`执行了安装，还没有使用。在`composer install`时报错。
报错信息如下：
```shell
vagrant@homestead:~/php/swoft$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package swoft/process ~2.0.0 exists as swoft/process[v1.0.4, v1.0.1, v1.0.0, dev-master, v1.0.2, 1.x-dev, v1.0.3, dev-bak] but these are rejected by your constraint.
```

**Comment by inhere** [comment]
你看下是不是源有问题呢？ 2.0.4 早就发了。可以试下清除 composer cache  或者用 aliyun 的源。

https://packagist.org/packages/swoft/process

**Comment by amorZhu** [comment]
我用的华为云镜像源，我测试一下阿里镜像源。

**Comment by amorZhu** [comment]
切换了镜像源好了。。。实测，华为云镜像源的问题。
```shell
composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
composer clear-cache
composer install
```
