### ISSUE TITLE
2.0.4-beta sum返回数据抹零，分组count数据错误

### ISSUE THREAD

**Issue by ijisong** [swoft-cloud/swoft#873]
1，模型调用sum方法返回总和，返回结果为int类型，实际上还有小数部分
->sum('money')
2，模型groupBy之后get获取记录十几条，但是groupBy之后count数据对不上
->groupBy('uid')->get(['uid']);
->groupBy('uid')->count();

**Comment by sakuraovq** [comment]
分组了 count 返回是数组吧
 这应该用 selectRaw 实现吧

**Comment by sakuraovq** [comment]
你希望 groupBy 之后 count 返回 数组 ?

**Comment by sakuraovq** [comment]
@ijisong i

**Comment by ijisong** [comment]
看文档理解错误了，谢谢指教

**Comment by sakuraovq** [comment]
@ijisong i  这样的查询 可以使用 selectRaw  然后在 `get`  

我看能不能兼容下 分组统计

**Comment by sakuraovq** [comment]
这种 用 `selectRaw` 最好
