### ISSUE TITLE
2.x crontab 无法使用

### ISSUE THREAD

**Issue by shiqwang** [swoft-cloud/swoft#876]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.4
| Swoole version      | 4.4.2
| PHP version         | 7.2
| Runtime environment |  Docker

**Details**

> 用官方的docker装的环境，composer create 的项目，但是提示没有crontab这个类，我在把swoft-cloud/crontab用composer安装了一下，也无法使用 …… 不解 @_@

**Comment by inhere** [comment]
等 2.0.5 发布

**Comment by AridanJohn** [comment]
2.0.5
[Semantical Error] The annotation "@Swoft\Crontab\Annotaion\Mapping\Scheduled" in class App\Crontab\CronTask does not exist, or could not be auto-loaded. in /var/www/swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54

**Comment by stelin** [comment]
2.0.5 已经发布了
