### ISSUE TITLE
为什么WsModule::onOpen()中没有记录Session信息

### ISSUE THREAD

**Issue by be1ief** [swoft-cloud/swoft#877]
今天有一个场景：需要在websocket客户端连接上之后向客户端发送一些消息并且保存一些状态，我想通过Session::mustGet()获取到当前的session对象，但是我发现好像在onOpen阶段，Session对象还没有建立Coroutine::tid()到$fd的关系，所以我想知道有没有办法解决这个问题或者有没有其他的解决方案。只要能够实现在当前connection会话中保存状态就可以了

**Comment by inhere** [comment]
我看了 open 也是在协程环境里。 可以直接使用 `Session::mustGet()`

**Comment by inhere** [comment]
我关闭了，有问题。 你提供一个demo，在打开。
