### ISSUE TITLE
RPC Client 调用报错

### ISSUE THREAD

**Issue by duzh** [swoft-cloud/swoft#883]
**Details**
在命令行调用 具体实现
/**
     * @Reference(pool="udp.pool")
     *
     * @var Udp20001Interface
     */
    private $udp20001Service;

 $this->udp20001Service->push('TMachineInfo',json_encode($chanData));
> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
PHP Fatal error:  Uncaught TypeError: Return value of context() must implement interface Swoft\Context\ContextInterface, null returned in /root/cmdv1/vendor/swoft/framework/src/Helper/Functions.php:129
Stack trace:
#0 /root/cmdv1/vendor/swoft/rpc-client/src/Extender.php(27): context()
#1 /root/cmdv1/vendor/swoft/rpc-client/src/Concern/ServiceTrait.php(52): Swoft\Rpc\Client\Extender->getExt()
#2 /tmp/Udp20001Interface_IGNORE_5d48ebd3677ba.php(26): App\Rpc\Lib\Udp20001Interface_IGNORE_5d48ebd3677ba->__proxyCall('App\\Rpc\\Lib\\Udp...', 'push', Array)
#3 /root/cmdv1/app/Console/Command/UdpCommand.php(127): App\Rpc\Lib\Udp20001Interface_IGNORE_5d48ebd3677ba->push('TMachineInfo', '{"time":1565060...')
#4 {main}
  thrown in /root/cmdv1/vendor/swoft/framework/src/Helper/Functions.php on line 129
[2019-08-06 02:54:11 $28731.0]	WARNING	swManager_check_exit_status: worker#0[pid=28733] abnormal exit, status=255, signal=0

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
@duzh 你要提供一个可以复现的demo例子，现在看来是你使用的地方没有上下文，或不在上下文中

**Comment by duzh** [comment]
> 
> 
> @duzh 你要提供一个可以复现的demo例子，现在看来是你使用的地方没有上下文，或不在上下文中

恩 我这边是在自建的命令里执行的 
`<?php declare(strict_types=1);


namespace App\Console\Command;

use App\Common\RpcClient;
use App\Rpc\Lib\Udp20001Interface;
use Swoft\Console\Annotation\Mapping\Command;
use Swoft\Console\Annotation\Mapping\CommandMapping;
use function input;
use function output;
use function sprintf;
use Swoft\Redis\Redis;
use Exception;
use Swoft\Exception\SwoftException;
use Swoft\Rpc\Client\Annotation\Mapping\Reference;
/**
 * Class UdpCommand
 *
 * @since 2.0
 *
 * @Command(name="udp",coroutine=false)
 */
class UdpCommand
{
    /**
     * @Reference(pool="udp.pool")
     *
     * @var Udp20001Interface
     */
    private $udp20001Service;
    /**
     * @CommandMapping(name="get")
     */
    public function get()
    { 
        ...
        $this->udp20001Service->push('TSwitchNet',json_encode($chanData));
     }
} `
大概就是这么一个调用方式 目前使用外部调用可以实现没有报错 使用以上方式 按文档方式实现就报错

**Comment by stelin** [comment]
@duzh 

@command(name="udp",coroutine=false) 这里错误了，这里必须是 coroutine=true, 必须协程环境。
