### ISSUE TITLE
如何给rpc请求添加链路跟踪

### ISSUE THREAD

**Issue by yangjianfeng9527** [swoft-cloud/swoft#884]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

如题，如何给rpc请求添加链路跟踪

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by sakuraovq** [comment]
traceid  和 spanid 了解下

**Comment by stelin** [comment]
spanid parentid traceid 还有，rpc ext扩展信息了解下

**Comment by dengkangfa** [comment]
> spanid parentid traceid还有，rpc ext扩展信息了解下

rpc client ext扩展信息怎么传，bean配置注入实现了ExtenderInterface的类？

**Comment by stelin** [comment]
嗯，是的注入实现的interface, 返回一个数组参数，你可以从下文环境中拿到你需要的参数(context()->getXxxx)
