### ISSUE TITLE
2.0.5 Scheduled注解不存在，无法启动

### ISSUE THREAD

**Issue by AridanJohn** [swoft-cloud/swoft#885]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.5
| Swoole version      | 4.4.2
| PHP version         | 7.2.6
| Runtime environment | CentOS 7/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
Fatal error: Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@Swoft\Crontab\Annotaion\Mapping\Scheduled" in class App\Crontab\CronTask does not exist, or could not be auto-loaded. in /var/www/swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by sakuraovq** [comment]
2.0.5 支持了
