### ISSUE TITLE
纵观整个框架，貌似没有顶级命名空间的支持？

### ISSUE THREAD

**Issue by jmt33** [swoft-cloud/swoft#89]
大多数必须使用 use，类似：

use Swoft\App;
App::trace("this is child trace" . Coroutine::id());

------

而不能直接的：App::trace("this is child trace" . Coroutine::id()); 不需要进行 use 引用。

**Comment by inhere** [comment]
正在整理 后面会提供一个 \Swoft::class 作为定级的类 他是继承自 Swoft\App 的

**Comment by stelin** [comment]
已经新增swoft.php 顶级命名空间，使用前更新代码
