### ISSUE TITLE
自动写入时间戳 问题

### ISSUE THREAD

**Issue by Johnzero** [swoft-cloud/swoft#891]
| Swoft version       | 2.0.4-beta
1.问题一 使用devtoole 生成Entity，对于timestamp类型定义为int类型
![image](https://user-images.githubusercontent.com/2416618/62606091-04b33b80-b92e-11e9-8160-08ecb94f622f.png)
![image](https://user-images.githubusercontent.com/2416618/62606111-0f6dd080-b92e-11e9-96e2-5f8470853578.png)

2.对于时间戳 支持 数据库 int 和 timestamp 类型, 底层会自动根据实体的属性  CREATED_AT 和 UPDATED_AT 这个两个字段定义的 @var 来判断. 用户无需操心生成时间戳格式，使用过程中@var无效，一直是int时间戳入库。

3。public $modelTimestamps = false;  无效，设置成false还是在写入CREATED_AT
![image](https://user-images.githubusercontent.com/2416618/62606258-6c698680-b92e-11e9-9c86-4c2e06953b6b.png)

**Comment by sakuraovq** [comment]
@Johnzero

**Comment by sakuraovq** [comment]
@Johnzero 
- timestamp 类型生成为 string 类型
- 自动写入的是 判断是常量有没有定义 不需要写入定义常量干嘛 这个修复下
- $modelDetaFormat 属性只对 string 类型的有效 int 只能写入当前时间戳
