### ISSUE TITLE
定时任务 crontab，使用 Log::profileStart() 無效

### ISSUE THREAD

**Issue by andiechang** [swoft-cloud/swoft#892]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.5
| Swoole version      | 4.4.1 (by `php --ri swoole`)
| PHP version         | 7.2.10 (by `php -v`)
| Runtime environment | Docker

**Details**

> Describe what you are trying to achieve and what goes wrong.

聲明一個定時任務，並在代碼中加入
```php
Log::profileStart('tagName');
Log::profileEnd('tagName');
```
但是在 notice.log 裡面並不會記錄 profile；
其他的 Log 可以正常記錄。

> Provide minimal script to reproduce the issue

```php
<?php declare(strict_types=1);

namespace App\Crontab;

use Swoft\Crontab\Annotaion\Mapping\Cron;
use Swoft\Crontab\Annotaion\Mapping\Scheduled;
use Swoft\Log\Helper\Log;

/**
 * Class CronTask
 *
 * @since 2.0
 *
 * @Scheduled()
 */
class CronTask
{
    /**
     * @Cron("0/10 * * * * *")
     */
    public function secondTask()
    {
        Log::profileStart('secondTask');

        Log::info('secondTask Start');
        printf("second task run: %s ", date('Y-m-d H:i:s', time()));
        
        Log::profileEnd('secondTask');
    }
}
```

**Comment by stelin** [comment]
感谢反馈，我跟踪下。

**Comment by stelin** [comment]
@andiechang 问题已经修复 2.0.6 发布

**Comment by stelin** [comment]
问题已修复，请更新到 2.0.6
