### ISSUE TITLE
Redis连接重连失败

### ISSUE THREAD

**Issue by alawnchen** [swoft-cloud/swoft#893]
![Jietu20190811-124229@2x](https://user-images.githubusercontent.com/1811463/62829852-90321280-bc35-11e9-997a-a7737f6d103d.jpg)

在逻辑层里面实例化Cache时候，连续调用方法就会出现类似“Redis command reconnect error(Method(delete) is not supported!)”的提示，烦请指教一下

$cache = new \App\Extend\Cache();
$cache->set( 'city', 'shanghai' );
$cache->delete( 'city' );

**Comment by sakuraovq** [comment]
使用 del 就好了~

**Comment by sakuraovq** [comment]
使用 del() 就好了~

**Comment by alawnchen** [comment]
@sakuraovq 多谢，马虎了，没有看Swoft\Redis\Redis类
