### ISSUE TITLE
官方会把phpexcel添加到组件里吗？

### ISSUE THREAD

**Issue by 5202m** [swoft-cloud/swoft#894]
如题，会把phpexcel添加到组件里吗？

**Comment by inhere** [comment]
不会。官方只会做一些通用的，需求人多的。 

phpexcel 这种特殊的库，都是用户自己弄。 不然官方忙的过来吗？ 😄

**Comment by stelin** [comment]
这种库其实就是生产一个文件，文件操作缓存协程的就好
