### ISSUE TITLE
2.x   Swoft\Stdlib\Helper\SystemHelper 文件缺失，composer过程中会生成该文件，但是执行完之后文件就消失了

### ISSUE THREAD

**Issue by kai-xx** [swoft-cloud/swoft#895]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by kai-xx** [comment]
http://gitlab.jhongnet.com:8888/zhangke/swoft-vendor/blob/d89755e8e59e43df418918117bb94c209186d2b6/swoft/component/src/stdlib/src/Helper/SystemHelper.php

手动创建后可以正常运行

**Comment by stelin** [comment]
这个问题是系统把这个文件删除了，比如杀毒软件

**Comment by kai-xx** [comment]
还真是这情况，win10自带的安全就给过滤掉了……

李霖 <notifications@github.com> 于2019年8月13日周二 下午8:17写道：

**Comment by stelin** [comment]
@kai-xx 我们细查下为什么会被删除

**Comment by inhere** [comment]
已修复，待 2.0.6 发布
