### ISSUE TITLE
关于mac系统的问题

### ISSUE THREAD

**Issue by aprchen** [swoft-cloud/swoft#90]
mac 系统不支持设置进程名称,希望设置进程名的时候做个兼容判断

**Comment by aprchen** [comment]
![image](https://user-images.githubusercontent.com/13740363/35470752-523357ec-038a-11e8-9b25-1b936226da46.png)
php 7.13, swoole 2.07, 控制器配置前缀无效
![image](https://user-images.githubusercontent.com/13740363/35470784-bfb9a19a-038a-11e8-846e-858e8ebad022.png)

**Comment by inhere** [comment]
哦 这里是对的 

`@RequestMapping()` 里 route 如果以 `/` 开始 会认为你要加个绝对路径的路由 
就不会在加上前面的 前缀了

**Comment by inhere** [comment]
是有一点不直观 
但是更灵活一些 比如你想给action定义一个与前缀完全无关的 路由path 时
默认的话 就只有写写一个跟前缀一样的 path
