### ISSUE TITLE
有连接断开后，fdList 里面有 false，swoole webSocket server->isEstablished(int $fd)

### ISSUE THREAD

**Issue by vvphp** [swoft-cloud/swoft#902]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.5-beta
| Swoole version      | 4.4.3-alpha
| PHP version         | 7.3.7
| Runtime environment | Docker etc.

**Details**

```php
server()->sendToAll('Recv:'.$data);
```

有连接断开后，fdList 里面有 false，swoole webSocket server->isEstablished(int $fd)
后面试了几次，没有复现。

![image](https://user-images.githubusercontent.com/17230924/63154952-420d7c80-c044-11e9-8b9e-af751262456c.png)

![image](https://user-images.githubusercontent.com/17230924/63154976-4f2a6b80-c044-11e9-8e59-f3ba3e174617.png)

![image](https://user-images.githubusercontent.com/17230924/63155002-5d788780-c044-11e9-8084-40c1fa09c825.png)

**Comment by inhere** [comment]
ok, 下个版本发布时，加上非空检查。
