### ISSUE TITLE
win10下docker-compose up运行报错

### ISSUE THREAD

**Issue by ctfang** [swoft-cloud/swoft#903]
swoft 版本 v2.0.5
win10下使用git bash执行docker-compose up
报错 

$ docker-compose up

In file .\.env: environment variable name 'APP_DEBUG ' may not contains whitespace.

修改_.env_ 文件 去除 `APP_DEBUG = 1 ` =号前面的空格后，正常安装

**Comment by inhere** [comment]
下个版本调整下格式
