### ISSUE TITLE
mysql8.0 NOWAIT以及SKIP LOCKED特性支持

### ISSUE THREAD

**Issue by a952135763** [swoft-cloud/swoft#906]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.05
| Swoole version      | 4.4.1
| PHP version         | 7.2.20
| Runtime environment | Win10 Dev Docker

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
想要支持 Mysql8.0的新特性
SKIP LOCKED 和 NOWAIT

DB::table('users')->where('votes', '>', 100)->lockForUpdate(nowait)->get();
DB::table('users')->where('votes', '>', 100)->lockForUpdate(skip locked)->get();
lockForUpdate 方法传入参数 这样更方便
```

> Provide minimal script to reproduce the issue

```php
没有代码..
```

**Comment by sakuraovq** [comment]
好滴

**Comment by sakuraovq** [comment]
DB::table('user')
            ->lock('nowait')
            ->toSql(); lock 方法原始是支持的

**Comment by a952135763** [comment]
没注意到lock方法
DB::table('user')
->lock('for update nowait')
->toSql();
这就是我想要的 谢谢了
