### ISSUE TITLE
rpc调用异常问题

### ISSUE THREAD

**Issue by zghsh123** [swoft-cloud/swoft#909]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
前面携带Rpc call error!code=500 message=asdsadas data={"asdasd123":"asdsa123","jsonrpc":"2.0"} pool=alisms.pool version=2.0
> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
@zghsh123 详细描述下你的问题，以及如何复现
