### ISSUE TITLE
sgo第二个参数  与Context::getWaitGroup()->wait()的问题

### ISSUE THREAD

**Issue by chenjing0521** [swoft-cloud/swoft#913]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.5
| Swoole version      | 4.4.4 (by `php --ri swoole`)
| PHP version         | 7.2.1 (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> sgo() 的第二个参数是用来控制等待返回的,  Context::getWaitGroup()->wait();  框架会自动调用,下面这段代码在http服务  api中执行  如果我不手动Context::getWaitGroup()->wait();  $user中是没有
un_read_msg  这个索引的,我也看了源码  好像是在销毁的时候调用的Context::getWaitGroup()->wait();

```php
       //未读消息数量
        sgo(function () use (&$user){
            /** 获取logic @var  $logic MsgReceiverLogic */
            $logic = \Swoft::getBean('MsgReceiverLogic');
            $user['un_read_msg'] = $logic->getReadMsgCount($user['uid']);
        },true);

        Context::getWaitGroup()->wait();
        return $user;
```

**Comment by chenjing0521** [comment]
而 这样 调用在正常的api请求中 手动Context::getWaitGroup()->wait()没问题 但是如果放到 定时器去执行  会有意外的执行结果

**Comment by stelin** [comment]
@chenjing0521 感谢反馈，我们复现下

**Comment by chenjing0521** [comment]
**测试代码**
```php
/**
 * Class TestController
 * @Controller(prefix="/Test")
 */
class TestController
{

    /**
     * @RequestMapping(route="test",method={RequestMethod::POST})
     */
    public function test(Request $request,Response $response)
    {
        $user = [];
        //未读消息数量
        sgo(function () use (&$user){
            Co::sleep(0.5);
            $user['un_read_msg'] = 10 ;
        },true);

//        Context::getWaitGroup()->wait();
        return $response->withData($user);
    }
```
![image](https://user-images.githubusercontent.com/43941983/64402326-1ca1ea80-d0a7-11e9-9fb4-305351db2759.png)

```php
/**
 * Class TestController
 * @Controller(prefix="/Test")
 */
class TestController
{

    /**
     * @RequestMapping(route="test",method={RequestMethod::POST})
     */
    public function test(Request $request,Response $response)
    {
        $user = [];
        //未读消息数量
        sgo(function () use (&$user){
            Co::sleep(0.5);
            $user['un_read_msg'] = 10 ;
        },true);

        Context::getWaitGroup()->wait();
        return $response->withData($user);
    }
```
![image](https://user-images.githubusercontent.com/43941983/64402368-3fcc9a00-d0a7-11e9-9525-452f342e92d7.png)

这里如果我不手动调   Context::getWaitGroup()->wait(); 就会等待不到结果,我记得官方是不建议自己调取   Context::getWaitGroup()->wait();


但是如果我  手动调取Context::getWaitGroup()->wait();     了这个方法    , 定时器就会出现等待不了的情况,只能用原生的waitgroup

**Comment by stelin** [comment]
这个问题2.0.6已经修复了，定时器的bug

**Comment by chenjing0521** [comment]
那手动调用Context::getWaitGroup()->wait(); 这个问题呢

**Comment by chenjing0521** [comment]
即时不在定时器中 也要手动调用Context::getWaitGroup()->wait();

**Comment by stelin** [comment]
这个可以不用手动调用，请求执行完成，自动做了处理，直接使用`sgo`就好

**Comment by chenjing0521** [comment]
https://github.com/swoft-cloud/swoft/issues/913#issuecomment-528710415

大佬不知道看了我这段测试代码没有,不手动调用   un_read_msg中没数据

**Comment by chenjing0521** [comment]
还是说  作者 您修复了?

**Comment by stelin** [comment]
sgo 一直就不需要手动调用wait, 框架底层做了实现
