### ISSUE TITLE
当post一个空字符串过来的时候，input()方法设置了默认值，但获取的还是空字符

### ISSUE THREAD

**Issue by xjr1022** [swoft-cloud/swoft#916]
| Q        | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.5
| Swoole version      | 4.4.3
| PHP version         | 7.2
| Runtime environment | Mac

**Details**
获取响应数据设置默认值有bug，我通过post请求发送xx为空字符串，按理说$result应该为30，结果竟然是空字符串

```php
    public function test(Request $request,Response $response):Response
    {
        $result = $request->input('xx',30)
        return $response->withData([
             $result
        ]);
    }
```
**Details**
看了下源码，应该是？？的锅，空字符串不为null
```php
public function input(string $key = '', $default = null)
    {
        $parsedBody = $this->getParsedBody();
        $parsedBody = is_array($parsedBody) ? $parsedBody : [];
        $inputs     = array_merge($parsedBody, $this->getQueryParams());

        if (!$key) {
            return $inputs;
        }
        return $inputs[$key] ?? $default;
    }
```

> Provide minimal script to reproduce the issue

```php
 public function test(Request $request,Response $response):Response
    {
        $result = $request->input('xx',30)
        return $response->withData([
             $result
        ]);
    }
```

**Comment by stelin** [comment]
@xjr1022 感谢返反馈，我们复查下

**Comment by inhere** [comment]
这里是没有问题的

这里只是按key取数据，提交的有对应key，就取里面的。不会做是否为空的检查。

**Comment by xjr1022** [comment]
> 这里是没有问题的
> 
> 这里只是按key取数据，提交的有对应key，就取里面的。不会做是否为空的检查。
这个很多框架都不是这么处理的，包括yii2 tp 之类的，比如数据分页，我只要第一页数据，前端可以给我穿空字符串

**Comment by inhere** [comment]
你是看错了吧。 yii 也是用isset 检查的，所以有key存在也是会返回对应的值，不会使用你的默认值的。

https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L589-L619

**Comment by xjr1022** [comment]
> 你是看错了吧。 yii 也是用isset 检查的，所以有key存在也是会返回对应的值，不会使用你的默认值的。
> 
> https://github.com/yiisoft/yii2/blob/90d46298addda275b5ad5afb4e399b768083b5e6/framework/web/Request.php#L589-L619

好吧，那就是记成TP的input了，刚看了下laravel的源码，也是isset，那就是使用习惯的问题了，这个issue可以关闭了
