### ISSUE TITLE
RequestMapping添加method参数提示问题

### ISSUE THREAD

**Issue by longjianghu** [swoft-cloud/swoft#918]
RequestMapping("index",method={RequestMethod::POST})

添加了 method 之后是限定只能 POST 访问系统提示路由不存在（这个路由是没有问题的，只是访问方法不正确），要么更改一个提示要么提示明确一点吧：

Route not found(path /task/index)! At /data/vendor/swoft/http-server/src/Middleware/DefaultMiddleware.php line 57

**Comment by inhere** [comment]
自己配置

https://swoft.org/docs/2.x/zh-CN/http-server/route.html#%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E

**Comment by okool** [comment]
请问handleMethodNotAllowed 这个是在/vendor/里面配置么?/vendor目录是不提交版本库的.
"Route not found" 是异常么?怎么截获到.

**Comment by inhere** [comment]
都是抛出的对应异常，在 app/bean.php 配置即可以覆盖默认的：

https://swoft.org/docs/2.x/zh-CN/http-server/route.html#%E8%B7%AF%E7%94%B1%E5%99%A8%E9%85%8D%E7%BD%AE
