### ISSUE TITLE
使用迁移工具生成表，添加表字段注释中文显示乱码

### ISSUE THREAD

**Issue by han0918** [swoft-cloud/swoft#920]
![image](https://user-images.githubusercontent.com/28640176/63635564-76adb380-c696-11e9-9f0b-5100d5d90149.png)
![image](https://user-images.githubusercontent.com/28640176/63635573-7f05ee80-c696-11e9-90d3-661b9e09626e.png)

**Comment by sakuraovq** [comment]
先看文档 说了 需要先配置 charset

**Comment by sakuraovq** [comment]
需要先配置 charset
```php
        'charset'  => 'utf8mb4',

```
