### ISSUE TITLE
\Swoft\Timer::after 未透传参数给回调函数

### ISSUE THREAD

**Issue by zhao05141237** [swoft-cloud/swoft#922]
| Q                   | A
| ------------------- | -----
| Swoft version        | 2.0.5-beta
| Swoole version    |4.4.4
| PHP version      | 7.3.6
| Runtime environment | Mac

**Details**

> \Swoft\Timer::after 未传递给回调函数

```php
public function after(): array
    {
        $paramOne = 1;
        $paramTwo = 1;
        Timer::after(3 * 1000, function ($paramOne, $paramTwo) {
            CLog::info('param' . $paramOne);
            CLog::info($paramTwo);
            $this->addUser($paramOne);
        }, $paramOne, $paramTwo);

        return ['after'];
    }
```

>报错如下

```php
4 [ERROR] Timer after error！Too few arguments to function App\Http\Controller\TimerController::App\Http\Controller\{closure}(), 1 passed in swoft/vendor/swoft/stdlib/src/Helper/PhpHelper.php on line 48 and exactly 2 expected swoft/app/Http/Controller/TimerController.php 37

```
\Swoft\Timer代码如下
```php
public static function after(int $msec, $callback, ...$params): int
    {
        $items = self::getLogItems();
        return SwooleTimer::after($msec, function () use ($callback, $items) {

            try {
                // Before
                Swoft::trigger(SwoftEvent::TIMER_AFTER_BEFORE);

                // Init Context
                self::initItems($items);

                // Callback
                PhpHelper::call($callback, 1);

                // After
                Swoft::trigger(SwoftEvent::TIMER_AFTER_AFTER);
            } catch (Throwable $e) {
                Error::log('Timer after error！%s %s %d', $e->getMessage(), $e->getFile(), $e->getLine());
            }
        }, ... $params);
    }

```
```php
 PhpHelper::call($callback, 1); //这里面并没有透传param参数 给after
```

**Comment by pekoe0210** [comment]
定时任务这里，我也遇到传参数的问题，我把任务的逻辑写到逻辑层，在任务里面直接调用逻辑层的方法，不报错了，具体哪里出的问题，现在还没有找出来

**Comment by stelin** [comment]
@pekoe0210 感谢反馈，我修复下

**Comment by sunnyos** [comment]
> Q	A
> Swoft version	2.0.5-beta
> Swoole version	4.4.4
> PHP version	7.3.6
> Runtime environment	Mac
> **Details**
> 
> > \Swoft\Timer::after 未传递给回调函数
> 
> ```
> public function after(): array
>     {
>         $paramOne = 1;
>         $paramTwo = 1;
>         Timer::after(3 * 1000, function ($paramOne, $paramTwo) {
>             CLog::info('param' . $paramOne);
>             CLog::info($paramTwo);
>             $this->addUser($paramOne);
>         }, $paramOne, $paramTwo);
> 
>         return ['after'];
>     }
> ```
> 
> > 报错如下
> 
> ```
> 4 [ERROR] Timer after error！Too few arguments to function App\Http\Controller\TimerController::App\Http\Controller\{closure}(), 1 passed in swoft/vendor/swoft/stdlib/src/Helper/PhpHelper.php on line 48 and exactly 2 expected swoft/app/Http/Controller/TimerController.php 37
> ```
> 
> \Swoft\Timer代码如下
> 
> ```
> public static function after(int $msec, $callback, ...$params): int
>     {
>         $items = self::getLogItems();
>         return SwooleTimer::after($msec, function () use ($callback, $items) {
> 
>             try {
>                 // Before
>                 Swoft::trigger(SwoftEvent::TIMER_AFTER_BEFORE);
> 
>                 // Init Context
>                 self::initItems($items);
> 
>                 // Callback
>                 PhpHelper::call($callback, 1);
> 
>                 // After
>                 Swoft::trigger(SwoftEvent::TIMER_AFTER_AFTER);
>             } catch (Throwable $e) {
>                 Error::log('Timer after error！%s %s %d', $e->getMessage(), $e->getFile(), $e->getLine());
>             }
>         }, ... $params);
>     }
> ```
> 
> ```
>  PhpHelper::call($callback, 1); //这里面并没有透传param参数 给after
> ```

已经修复，等下一个版本发布
