### ISSUE TITLE
swoft-2.0.4安装devtool,访问报错

### ISSUE THREAD

**Issue by Smurfs-xxl** [swoft-cloud/swoft#925]
{"code":0,"error":"(Swoft\\Http\\Server\\Exception\\NotFoundRouteException) Route not found(path \/__devtool)!","file":"At \/home\/xxl\/swoft-2.0.4\/vendor\/swoft\/http-server\/src\/Middleware\/DefaultMiddleware.php line 57","trace":"#0 \/home\/xxl\/swoft-2.0.4\/vendor\/swoft\/http-server\/src\/RequestHandler.php(75): Swoft\\Http\\Server\\Middleware\\DefaultMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#1 \/home\/xxl\/swoft-2.0.4\/vendor\/swoft\/http-server\/src\/Middleware\/UserMiddleware.php(44): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#2 \/home\/xxl\/swoft-2.0.4\/vendor\/swoft\/http-server\/src\/RequestHandler.php(75): Swoft\\Http\\Server\\Middleware\\UserMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#3 \/home\/xxl\/swoft-2.0.4\/vendor\/swoft\/view\/src\/Middleware\/ViewMiddleware.php(41): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#4 \/home\/xxl\/swoft-2.0.4\/vendor\/swoft\/http-server\/src\/RequestHandler.php(75): Swoft\\View\\Middleware\\ViewMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#5 \/home\/xxl\/swoft-2.0.4\/vendor\/swoft\/http-server\/src\/HttpDispatcher.php(77): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#6 \/home\/xxl\/swoft-2.0.4\/vendor\/swoft\/http-server\/src\/Swoole\/RequestListener.php(38): Swoft\\Http\\Server\\HttpDispatcher->dispatch(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Message\\Response))\n#7 {main}"}

**Comment by Smurfs-xxl** [comment]
2.0.X的版本，我试过几个，都是访问devtool出错。

**Comment by Smurfs-xxl** [comment]
2.0.5 访问devtool报错

{"code":0,"error":"(Swoft\\Http\\Server\\Exception\\NotFoundRouteException) Route not found(path \/__devtool)!","file":"At \/home\/xxl\/swoft-2.0.5\/vendor\/swoft\/http-server\/src\/Middleware\/DefaultMiddleware.php line 57","trace":"#0 \/home\/xxl\/swoft-2.0.5\/vendor\/swoft\/http-server\/src\/RequestHandler.php(75): Swoft\\Http\\Server\\Middleware\\DefaultMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#1 \/home\/xxl\/swoft-2.0.5\/vendor\/swoft\/http-server\/src\/Middleware\/ValidatorMiddleware.php(44): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#2 \/home\/xxl\/swoft-2.0.5\/vendor\/swoft\/http-server\/src\/RequestHandler.php(75): Swoft\\Http\\Server\\Middleware\\ValidatorMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#3 \/home\/xxl\/swoft-2.0.5\/vendor\/swoft\/http-server\/src\/Middleware\/UserMiddleware.php(44): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#4 \/home\/xxl\/swoft-2.0.5\/vendor\/swoft\/http-server\/src\/RequestHandler.php(75): Swoft\\Http\\Server\\Middleware\\UserMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#5 \/home\/xxl\/swoft-2.0.5\/vendor\/swoft\/view\/src\/Middleware\/ViewMiddleware.php(41): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#6 \/home\/xxl\/swoft-2.0.5\/vendor\/swoft\/http-server\/src\/RequestHandler.php(75): Swoft\\View\\Middleware\\ViewMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#7 \/home\/xxl\/swoft-2.0.5\/app\/Http\/Middleware\/FavIconMiddleware.php(35): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#8 \/home\/xxl\/swoft-2.0.5\/vendor\/swoft\/http-server\/src\/RequestHandler.php(75): App\\Http\\Middleware\\FavIconMiddleware->process(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Server\\RequestHandler))\n#9 \/home\/xxl\/swoft-2.0.5\/vendor\/swoft\/http-server\/src\/HttpDispatcher.php(77): Swoft\\Http\\Server\\RequestHandler->handle(Object(Swoft\\Http\\Message\\Request))\n#10 \/home\/xxl\/swoft-2.0.5\/vendor\/swoft\/http-server\/src\/Swoole\/RequestListener.php(38): Swoft\\Http\\Server\\HttpDispatcher->dispatch(Object(Swoft\\Http\\Message\\Request), Object(Swoft\\Http\\Message\\Response))\n#11 {main}"}

**Comment by stelin** [comment]
2.0 devtool 现在只迁移了部分功能，其它正在迁移

**Comment by Smurfs-xxl** [comment]
> 2.0 devtool 现在只迁移了部分功能，其它正在迁移

收到。swoft有没有微服务的demo？
