### ISSUE TITLE
Fatal error: Class 'Swoft\Stdlib\Helper\SystemHelper' not found in /var/www/swoft/vendor/swoft/stdlib/src/Helper/Sys.php on line 10

### ISSUE THREAD

**Issue by YZWLEO** [swoft-cloud/swoft#926]
/var/www/swoft# php bin/swoft -h
2019/08/28-10:12:48 [INFO] Swoft\SwoftApplication:setSystemAlias(485) Set alias @base=/var/www/swoft
2019/08/28-10:12:48 [INFO] Swoft\SwoftApplication:setSystemAlias(486) Set alias @app=@base/app
2019/08/28-10:12:48 [INFO] Swoft\SwoftApplication:setSystemAlias(487) Set alias @config=@base/config
2019/08/28-10:12:48 [INFO] Swoft\SwoftApplication:setSystemAlias(488) Set alias @runtime=@base/runtime
2019/08/28-10:12:48 [INFO] Project path is /var/www/swoft
2019/08/28-10:12:48 [INFO] Swoft\Processor\EnvProcessor:handle(52) Env file(/var/www/swoft/.env) is loaded
2019/08/28-10:12:59 [INFO] Swoft\Processor\AnnotationProcessor:handle(45) Annotations is scanned(autoloader 32, annotation 444, parser 92)

Fatal error: Class 'Swoft\Stdlib\Helper\SystemHelper' not found in /var/www/swoft/vendor/swoft/stdlib/src/Helper/Sys.php on line 10
root@11a050e68264:/var/www/swoft# Fatal error: Class 'Swoft\Stdlib\Helper\SystemHelper' not found in /var/www/swoft/vendor/swoft/stdlib/src/Helper/Sys.php on line 10

**Comment by inhere** [comment]
refer https://github.com/swoft-cloud/swoft/issues/895

已修复，待 2.0.6 发布
