### ISSUE TITLE
2.0.5版本数据库更新操作

### ISSUE THREAD

**Issue by etoup** [swoft-cloud/swoft#928]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.5
| Swoole version      | 4.4.3
| PHP version         | 7.2.18
| Runtime environment |Mac/Docker etc.

**Details**

> 在2.0.4版本的下面操作测试正常，升级到2.0.5版本后报错

```php
$result = Devices::find($data['id'])->update($data);
```

> 报错：update null

**Comment by stelin** [comment]
@etoup 你贴下完整代码，看错误是你使用问题。

**Comment by stelin** [comment]
应该是你 Devices::find($data['id'])没查到数据

**Comment by sakuraovq** [comment]
Devices::modifyById($data['id'], $data)  可以这样

**Comment by etoup** [comment]
> 改成下面代码就好了：

```php
$result = Devices::where('id', $data['id'])->update($data);
```

**Comment by etoup** [comment]
好的，我试试上面代码，谢谢

**Comment by sakuraovq** [comment]
```php

modifyById(int $id, array $values) 
```

**Comment by etoup** [comment]
好的，我之前有个issue（#910）2.0.5版本sum返回整型的问题，请帮忙看看，谢谢

**Comment by stelin** [comment]
2.0.5 我们没法复现

**Comment by stelin** [comment]
你确定下你版本

**Comment by etoup** [comment]
好的，谢谢
