### ISSUE TITLE
为啥使用redis的sMember获取到的内容是false？

### ISSUE THREAD

**Issue by chang1314** [swoft-cloud/swoft#934]
$key   = 'key';

        $this->redis->zAdd($key, [
            'add1'    => 11.1,
            'score2' => 11.1,
            'score3' => 11.21
        ]);

        $get = $this->redis->sMember($key);
        return [$get];

key是对的  
集合也存进去了
为啥sMember方法获取到的就是false呢

**Comment by sakuraovq** [comment]
0 0 你的 key 已经存在了 集合是保持唯一的

**Comment by chang1314** [comment]
> 0 0 你的 key 已经存在了 集合是保持唯一的
唯一是不错，那如何取出集合的数据呢
