### ISSUE TITLE
启动定时器后，内存溢出。

### ISSUE THREAD

**Issue by cmliangchu** [swoft-cloud/swoft#936]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.5
| Swoole version      | 4.4.3 (by `php --ri swoole`)
| PHP version         | 7.2.0 (by `php -v`)
| Runtime environment | CentOS 7

**Details**

> 使用定时器后，内存溢出。（定时器内不做任何事情，只是打印当前使用内存，内存就一直在涨，最后爆了）

```php
public function FansMsgPush()
{
CLog::info(memory_get_usage());
}
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by xjr1022** [comment]
我重新从用composer下载了swoft，什么代码都没改动，也没有添加任何其他代码，只添加一行
```php
CLog::info(memory_get_usage());
```
直接开启定时器，然后内存一直在增长，目前就观察额五分钟，这五分里面，内存一直在增长

**Comment by stelin** [comment]
感谢反馈，我们查下

**Comment by stelin** [comment]
2.0.6 会修改该问题，确认是一个bug

**Comment by stelin** [comment]
问题已修复，请更新到 2.0.6
