### ISSUE TITLE
2.0.5 生成 controller 错误

### ISSUE THREAD

**Issue by damaainan** [swoft-cloud/swoft#937]
2.0.5 生成 controller
command 'controller:create' is not exists

**Comment by damaainan** [comment]
为什么这个命令 `php bin/swoft gen:controller`  不能执行了

**Comment by inhere** [comment]
devtool 暂时没有内置生成， swoftcli 里有这个命名。

**Comment by damaainan** [comment]
看了一下代码，没看到相关的命令

**Comment by stelin** [comment]
后续版会支持
