### ISSUE TITLE
没有初始化完成事件 SwoftEvent::APP_INIT_COMPLETE 基本没用

### ISSUE THREAD

**Issue by ctfang** [swoft-cloud/swoft#938]
没有初始化完成事件（SwoftEvent::APP_INIT_COMPLETE不能调用数据库）
场景：
启动后，业务初始化，启动业务缓存等，
检查api维护开关等

**Comment by stelin** [comment]
这个事件是框架初始化完成事件，事件里面是没有协程支持的，所以不能执行协程IO操作，下一个版本，我考虑下，让该事件支持协程以及可以支持其它IO操作

**Comment by stelin** [comment]
其实不需要这个事件支持协程，你直接使用swoft内置的 `srun` 函数开启协程，就可以执行数据这些操作
