### ISSUE TITLE
调试sql事件

### ISSUE THREAD

**Issue by ctfang** [swoft-cloud/swoft#939]
事件 DbEvent::SQL_RAN 不能打印失败sql,只打印了成功的sql,调试不方便，
需要有执行sql前事件

**Comment by sakuraovq** [comment]
有 selecting  类似的模型事件具体看下文档

**Comment by stelin** [comment]
https://www.swoft.org/docs/2.x/zh-CN/db/model.html#%E4%BA%8B%E4%BB%B6
