### ISSUE TITLE
swoole_set_process_name is not supported on MacOS

### ISSUE THREAD

**Issue by igo9go** [swoft-cloud/swoft#94]
`PHP Warning:  swoole_process::name(): swoole_set_process_name is not supported on MacOS`

这个警告能否做一下判断，在MacOS下不执行swoole_set_process_name

**Comment by huangzhhui** [comment]
我觉得作为一个框架不应该自作主张的去做不设置的操作，而是用户代码判断，因为如果框架处理的话这个对用户就不透明了，那么用户在想要对这个Process进行操作的时候发现找不到，甚至会误以为这个Process没有启动，但实际上是启动了的

**Comment by inhere** [comment]
框架内部调用 会做相应判断， mac 不调用此方法。

会在接下来的更新中修复合并 :)

**Comment by stelin** [comment]
已经修复了，更新代码。
