### ISSUE TITLE
Redis当zAdd纯数字字符串value时，zRem不能通过字符串类型的参数删除value。

### ISSUE THREAD

**Issue by zxl409774878** [swoft-cloud/swoft#942]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.5-beta
| Swoole version      | 4.4.2
| PHP version         | 7.3.7
| Runtime environment | Win10 WSL Debian 9.7
| Redis version | 5.0.3

**Details**

当zAdd的value为纯数字的字符串时，zRem不能通过字符串类型的参数删除value。

```php
public function index() {
    $result[] = Redis::zAdd('test', [
        2018 => 5,
        '2019' => 10,
    ]);
    $result[] = Redis::zRange('test', 0, -1, true);
    $result[] = Redis::zRem('test', '2019');
    $result[] = Redis::zRem('test', 2019);
    return $result;
}
```
返回
```json
[1,{"2018":5,"2019":10},0,1]
```
Redis内实际存储value为
```
i:2019;
```

**Comment by stelin** [comment]
感谢反馈，我们复查下

**Comment by sakuraovq** [comment]
好的 我们看看

**Comment by sakuraovq** [comment]
@zxl409774878  这是 redis 序列化的问题 这样可以关闭序列化哈 默认的连接池是开启了序列化
