### ISSUE TITLE
执行数据迁移回滚的问题

### ISSUE THREAD

**Issue by longjianghu** [swoft-cloud/swoft#944]
up 的时候默认使用了迁移文件的连接池，down 的时候是不是也应该使用？现在需要手动传参（不使用默认值情况下）。

**Comment by sakuraovq** [comment]
你在迁移文件里面配置下 默认的 pool 就可以了  默认都是 db.pool

**Comment by sakuraovq** [comment]
查询回滚 只会从默认的 db.pool 查询  需要指定就 传 pool 参数就可以了
