### ISSUE TITLE
http服务器执行reload命令，显示relaod success，但服务器直接就挂了

### ISSUE THREAD

**Issue by xjr1022** [swoft-cloud/swoft#946]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.5
| Swoole version      | 4.4.3
| PHP version         | 7.3
| Runtime environment | Mac

**Details**
http服务器以后台形式运行，此时执行 http:reload，终端也打印了reload success ，但此时发送请求就发现服务器无响应，才发现程序直接挂了
![3C84FB514189F40B00BA14883E2B0BE0.png](https://i.loli.net/2019/09/04/XZ1EjDP8OrzMNa4.png)
![0E7D2E3176F6EE6CF9B11438458FDAE5.png](https://i.loli.net/2019/09/04/MuD3V1qjZsOlpNb.png)
![BA8FFFBA39FE5C8CE07FA5865ABB1712.png](https://i.loli.net/2019/09/04/C4NxFgYnztqJ3l8.png)
![8C9B1881B5B17C2E63D64EBFF5C9A27C.png](https://i.loli.net/2019/09/04/IlC4OSE3JsexdRm.png)

**Comment by inhere** [comment]
试了下 mac 下有这个问题，Linux 下是可以的。swoole底层的问题

**Comment by xjr1022** [comment]
> 试了下 mac 下有这个问题，Linux 下是可以的。swoole底层的问题

好的，我还以为linux也有这个问题，辛苦了，谢谢了
