### ISSUE TITLE
redis set 如何原子设置 nx + px ?

### ISSUE THREAD

**Issue by maimake** [swoft-cloud/swoft#948]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       |  2.0.5-beta
| Swoole version      |4.4.5 (by `php --ri swoole`)
| PHP version         | 7.2.19 (by `php -v`)
| Runtime environment | Docker etc.

**Details**

> `Redis::set()` 如何原子设置 NX 和 PX选项 ?
> http://www.redis.cn/commands/set.html

> Provide minimal script to reproduce the issue

```php
Redis::set('key', 'value', ['NX', 'PX' => 1000]);
```
报错
```
Argument 3 passed to Swoft\Redis\Connection\Connection::set() must be of the type integer or null, array given, called in /var/www/swoft/vendor/swoft/redis/src/Redis.php
```

**Comment by stelin** [comment]
@maimake 

调用Redis::setnx()

**Comment by sakuraovq** [comment]
@maimake  同时设置 nx + px 只有原生的 set 方法支持 swoft 的 set 不支持这样

**Comment by sakuraovq** [comment]
同时设置 nx + px 只有原生的 set 方法支持 swoft 的 set 不支持这样 
需要使用  Redis::call(function($redis){  ...}) 方法解决

**Comment by stelin** [comment]
还有一种方式，使用redis事物操作以及lua脚本
