### ISSUE TITLE
手动安装 启动报错

### ISSUE THREAD

**Issue by UncleZh** [swoft-cloud/swoft#949]
swoft 2.0 
php 7.2
swoole  4.4.5

git克隆项目 然后composer install      运行php bin/swoft http:start 报错如下

![image](https://user-images.githubusercontent.com/26923608/64271556-16f5b900-cf70-11e9-970b-5ecf97f3c7ae.png)

**Comment by stelin** [comment]
@UncleZh 你删除定时任务测试文件或安装定时任务组件

**Comment by stelin** [comment]
https://www.swoft.org/docs/2.x/zh-CN/task/crontab.html
