### ISSUE TITLE
Swoole\Coroutine\Redis 可否加入默认前缀设置？

### ISSUE THREAD

**Issue by jmt33** [swoft-cloud/swoft#95]
Swoole\Coroutine\Redis 不可以加入默认前缀，严重影响编码体验。
例如：
$redis->setOption(Redis::OPT_PREFIX, 'myAppName:'); 
这种写法，完全不支持。

**Comment by stelin** [comment]
后面新增一个配置项，可以配置前缀

**Comment by huangzhhui** [comment]
PR [Support redis key prefix](https://github.com/swoft-cloud/swoft-redis/pull/2)
swoft/redis v1.0.4 版本已支持 prefix 功能
