### ISSUE TITLE
docker-compose up 卡死在MySQL

### ISSUE THREAD

**Issue by semi-aurora** [swoft-cloud/swoft#950]
![QQ图片20190905100515](https://user-images.githubusercontent.com/30685220/64306259-bf356d00-cfc4-11e9-9524-1652b2c916d5.png)

**Comment by inhere** [comment]
确定是卡住了吗？compose 配置是怎么样的

**Comment by inhere** [comment]
确定是卡住了吗？compose 配置是怎么样的

**Comment by mi-autumn** [comment]
解决了.我环境得问题

**Comment by semi-aurora** [comment]
解决了.我自己环境问题.
