### ISSUE TITLE
关于aop返回类型零值为后为null的问题

### ISSUE THREAD

**Issue by Aaron-PHP** [swoft-cloud/swoft#951]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | x.y.z
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

> AOP afterReturn 的时候　，如果函数返回该类型零值，getJoinPoint之后会变为null.

```php
    before Aop , output : false
    after Aop , output : null
```

> Provide minimal script to reproduce the issue

```php
    /**
     * New join point
     *
     * @param Throwable|null $catch
     * @param mixed          $return
     *
     * @return JoinPoint
     */
    private function getJoinPoint(Throwable $catch = null, $return = null): JoinPoint
    {
        $joinPoint = new JoinPoint($this->className, $this->target, $this->methodName, $this->args, $this->argsMap);
        if ($catch) {
            $joinPoint->setCatch($catch);
        }
        var_dump($return);

        if ($return) {
            $joinPoint->setReturn($return);
        }
        var_dump($joinPoint->getReturn());

        return $joinPoint;
    } 
```
vendor/swoft/aop/src/AspectHandler.php

**Comment by stelin** [comment]
感谢反馈，我们修复下

**Comment by stelin** [comment]
已修复 2.0.6 一起发布

**Comment by stelin** [comment]
已修复在 2.0.6，版本已经发布
