### ISSUE TITLE
DbExpectation 的code不是PDOExpectation的code，无法根据具体异常处理业务

### ISSUE THREAD

**Issue by airect** [swoft-cloud/swoft#952]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.5
| Swoole version      | 4.4.3 (by `php --ri swoole`)
| PHP version         | 7.1.23 (by `php -v`)
| Runtime environment | Mac

**Details**
目前db只有DbExpectation，code为0，无法根据code区分db异常类型，如 23000 主键重复
建议DbExpectation 使用PDOExpectation的code。

```php
// Connection.php  line 713
// Throw exception
throw new DbException($e->getMessage(), (int)$e->getCode());
```

**Comment by stelin** [comment]
感谢反馈，我们做下调整，把错误异常code一起抛出来

**Comment by sakuraovq** [comment]
好的 这个确实是有必要的 感谢您的建议 我们优化下

**Comment by chenjing0521** [comment]
> 好的 这个确实是有必要的 感谢您的建议 我们优化下

还有一个问题, 执行错误语句的时候很难发现,错误在哪.因为toSql   拿不到完整的sql,只有部分,而demo的那个事件是 执行后的sql   执行出错的sql是打印不出来的  ,  能不能把执行抛出异常的sql打印出来或者通过事件获取到

**Comment by sakuraovq** [comment]
这个是个不错的问题 我把这个 sql 放在错误信息里面吧 这个确实方便调试哈可以的

**Comment by chenjing0521** [comment]
麻烦了

**Comment by stelin** [comment]
sql 放在错误信息 不要放到错误信息里面，有风险，写到debug日志

**Comment by stelin** [comment]
已修复，请更新至2.0.6
