### ISSUE TITLE
关于安装遇到报redis不存在的问题

### ISSUE THREAD

**Issue by linkimfly** [swoft-cloud/swoft#953]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | no
| Swoft version       | 2.0.6
| Swoole version      | 4.4.5
| PHP version         | 7.2.21
| Runtime environment | Mac

**Details**

> 安装总是会报redis扩展不存在，但问题是我redis确实启用了，而且我也下过源码编译安装，也用pecl也试过重新安装也还是会报这个错 

![image](https://user-images.githubusercontent.com/30326966/64482065-cd7dc600-d21c-11e9-8e2a-97764247e08c.png)
![image](https://user-images.githubusercontent.com/30326966/64482230-3ca8e980-d220-11e9-90d2-e52c9e062c58.png)

![image](https://user-images.githubusercontent.com/30326966/64482212-c4422880-d21f-11e9-940d-bd2bb565b827.png)

**Comment by sakuraovq** [comment]
== 还有这种操作 你先改下 composer 呢

**Comment by linkimfly** [comment]
改了composer是可以了
