### ISSUE TITLE
insert没有事件监听

### ISSUE THREAD

**Issue by dongqibin** [swoft-cloud/swoft#955]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.5
| Swoole version      | 4.4
| PHP version         | 7.3
| Runtime environment | CentOS 7

**Details**

> 模型事件有creating跟created.批量插入的话只能使用insert方法.而insert没有事件.怎么办啊?这算是个bug吗?.

**Comment by sakuraovq** [comment]
@dongqibin 只有模型的方法支持用 save 方法吧

**Comment by dongqibin** [comment]
我现在想监听sql的运行情况.其中包括批量插入.有什么解决方案吗?

**Comment by sakuraovq** [comment]
监听 `swoft.db.ran`  事件 哈哈 这个暂时没有 用 model 的 `save` 方法就可以解决了 insert 是builder 做的不是模型的范畴
