### ISSUE TITLE
websocket无法随http启动

### ISSUE THREAD

**Issue by 233cy** [swoft-cloud/swoft#956]
![image](https://user-images.githubusercontent.com/29916783/64593148-23e73200-d3e0-11e9-84d5-3a097fe80a53.png)
![image](https://user-images.githubusercontent.com/29916783/64593203-3cefe300-d3e0-11e9-89c4-0e14c0e3a8b4.png)
以下是报错内容。
![image](https://user-images.githubusercontent.com/29916783/64593260-5a24b180-d3e0-11e9-9b35-64c6ab3598fd.png)
只要加了ws服务就无法启动。

**Comment by inhere** [comment]
请查看 websocket server 文档，如何同时启动http 和 ws

**Comment by 233cy** [comment]
好的已解决，在请教个问题，自定义进程里是不是无法给websocket群发消息呢

**Comment by 233cy** [comment]
> 请查看 websocket server 文档，如何同时启动http 和 ws

·····

**Comment by stelin** [comment]
暂时没法群发消息，你需要通过其它方式通信或者http请求。

**Comment by fingerred** [comment]
> 好的已解决，在请教个问题，自定义进程里是不是无法给websocket群发消息呢



> ![image](https://user-images.githubusercontent.com/29916783/64593148-23e73200-d3e0-11e9-84d5-3a097fe80a53.png)
> ![image](https://user-images.githubusercontent.com/29916783/64593203-3cefe300-d3e0-11e9-89c4-0e14c0e3a8b4.png)
> 以下是报错内容。
> ![image](https://user-images.githubusercontent.com/29916783/64593260-5a24b180-d3e0-11e9-9b35-64c6ab3598fd.png)
> 只要加了ws服务就无法启动。

我也是遇到这个问题，给的文档只能在启动ws时支持http。没说在启动http时支持ws服务。
