### ISSUE TITLE
json_decode error: Syntax error At 错误

### ISSUE THREAD

**Issue by 233cy** [swoft-cloud/swoft#958]
直接composer最新2.0.5版本，访问RPC，路径：http://127.0.0.1:18307/rpc/getList直接就报错了已经：json_decode error: Syntax error At /mnt/d/www/devops/server/vendor/swoft/stdlib/src/Helper/JsonHelper.php line 35

**Comment by 233cy** [comment]
@inhere

**Comment by stelin** [comment]
你返回的数据json_decode出错，有复现代码么

**Comment by stelin** [comment]
已经复现，高版本swoole会有问题，我们修复下

**Comment by stelin** [comment]
@233cy 你试下最新版的 swoole 4.4.6 +swoft 2.0.6

**Comment by stelin** [comment]
@233cy 更新至 Swoole 4.4.7 问题已经修复
