### ISSUE TITLE
RedisController->testDefer 例子运行报错

### ISSUE THREAD

**Issue by eaglering** [swoft-cloud/swoft#96]
![tt y l a x fz j dq 7](https://user-images.githubusercontent.com/13248249/35664913-ddb9b144-075e-11e8-9ca5-327f3999bfa5.png)
![o07ot 5fmr ijt7i378 5nl](https://user-images.githubusercontent.com/13248249/35664922-e32fa6d8-075e-11e8-9b15-7d6537911379.png)

**Comment by huangzhhui** [comment]
更新 Swoole 至最新的 master 版本或等待 Swoole 发布下一个版本可修复此问题
