### ISSUE TITLE
2.0.5版本的数据库的自增方法循环使用超过十次会阻塞进程

### ISSUE THREAD

**Issue by xjr1022** [swoft-cloud/swoft#961]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | x2.0.5
| Swoole version      | 4.4.3
| PHP version         | 7.2
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**

2.0.5版本的数据库的自增方法循环使用超过十次会阻塞进程，此时http请求就会卡主
```php
  $arr = [61,34,44,42,41,56,55,7,55,11];
        foreach ($arr as $v){
            UsersIncome::where(['uid'=>$v,'month'=>'201909'])->increment('estimate_income',$v);
        }
      return $response->withData([

        ]);
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by xjr1022** [comment]
看到2.0.6的更新日志显示好像修复了这个问题，

**Comment by xjr1022** [comment]
> 看到2.0.6的更新日志显示好像修复了这个问题，

把2.0.6的connection文件夹替换了下，还是不行，看来修复的不是这个问题

**Comment by xjr1022** [comment]
> ```
>      public function raw($value)	    public function raw($value): Expression
>     {	    {
>         return $this->getConnection()->raw($value);	        return Expression::new($value);
>     }
> ```
> 
> 相互替换下

好滴，谢谢你了，辛苦了😋

**Comment by sakuraovq** [comment]
@xjr1022 swoft 正式发布啦
