### ISSUE TITLE
自动更新时间戳的问题

### ISSUE THREAD

**Issue by wvfeng** [swoft-cloud/swoft#963]
实体类中时间戳字段定义如下：
```
    /**
     * 创建时间
     *
     * @Column()
     * @var int
     */
    private $created_at = 0;

    /**
     * 修改时间
     *
     * @Column()
     * @var int
     */
    private $updated_at = 0;
```
实体字段填充会调用`setCreated_at`方法，取值会调用`getCreated_at`方法，
但是自动插入时间却会调用`setCreatedAt`方法
所以导致实体类内必须同时定义`setCreated_at`、`setCreatedAt`两种设置时间戳的方法才能正常使用，如果只定义`setCreated_at`数据查询时字段赋值正确，但是数据更新时不会更新，如果只定义`setCreatedAt`则更新时正常，查询时不会赋值
`updated_at`这个字段也有一样的问题

**Comment by wvfeng** [comment]
@inhere 后续测试发现了一个BUG，如果在`getCreated_at`和`getUpdated_at`格式化时间，数据保存的时候会出现把格式化的字段取证保存，如下图：
![image](https://user-images.githubusercontent.com/33809027/64695694-4dcb5200-d4cf-11e9-8bb8-1384fdada077.png)

**Comment by sakuraovq** [comment]
第二个不算问题吧 _(:з」∠)_

**Comment by wvfeng** [comment]
算不算个问题，要看怎么去想了，如果说在setter中设置相应的反向转义，那最终的结果也有可能是对的，例如：
```
/**
     * @return string
     */
    public function getCreated_at(): string
    {
        return date('Y-m-d H:i:s', $this->created_at);
    }

    /**
     * @param string $created_at
     */
    public function setCreated_at(string $created_at): void
    {
        $this->created_at = strtotime($created_at);
    }
```
但是这样的话解决不了不可逆操作的问题，例如：
```
/**
     * @return string
     */
    public function getCreated_at(): string
    {
        return date('Y-m-d', $this->created_at);
    }

    /**
     * @param string $created_at
     */
    public function setCreated_at(string $created_at): void
    {
        $this->created_at = strtotime($created_at);
    }
```
这样操作就会导致实际数据失真，并且，我本来的想法并不是希望创建时间发生改变，只是希望在取出时进行转义
