### ISSUE TITLE
定时任务派发异步任务finish事件触发错误

### ISSUE THREAD

**Issue by JayenLee** [swoft-cloud/swoft#965]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes/no
| Feature request?    | yes/no
| Swoft version       | 2.0.5
| Swoole version      | x.y.z (by `php --ri swoole`)
| PHP version         | x.y.z (by `php -v`)
| Runtime environment | Win10/Mac/CentOS 7/Ubuntu/Docker etc.

**Details**
定时任务里面想派发一个异步任务给task进程去执行，这个异步任务执行了，但是worker进程的finish 没办法监听到，会报WARNING	swTaskWorker_finish: task->finish() can only be used in the worker process，是不是定时任务派发任务，还是在task进程里面执行？

> Describe what you are trying to achieve and what goes wrong.

```php
   /**
     * @Cron("* * * * * *")
     */
    public function secondTask()
    {
        var_dump('aaaaa');
        CLog::info("second task run: %s ", date('Y-m-d H:i:s', time()));
        Task::async('tests','list',[1,'ddddd']);
        Task::async('test','lists',[1,'ddddd']);
        return time().'2222';
    }


```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
定时任务不支持这种方式投递任务

**Comment by stelin** [comment]
你直接用协程就好了为啥要去投递任务，完全没必要使用任务

**Comment by JayenLee** [comment]
定时任务处理一些很大的数据量处理，需要翻页拉取数据，我是希望能够把每个页的数据丢到任务里面去处理，这样减少处理时间。

**Comment by inhere** [comment]
你多开几个协程就行了啊

**Comment by zoulux** [comment]
还是建议定时任务中可以投递任务，laravel 框架中是可以的
