### ISSUE TITLE
压力测试数据库连接查询抛出警告

### ISSUE THREAD

**Issue by eaglering** [swoft-cloud/swoft#97]
运行代码：
```
$result1 = Mobiles::query()->select('*')->where('mobile', '1571155')->limit(1)->getDefer();
$result = $this->redis->set('test1', 1);
var_dump($result);
var_dump($result1->getResult());
```
执行测试：
`ab -n 10 -c 10 http://192.168.1.199:8098/mok/test`

抛出警告：
PHP Warning:  Swoole\Coroutine\MySQL::query(): mysql client has already been bound to another coroutine. in /dir/project/vendor/swoft/framework/src/Db/Mysql/MysqlConnect.php on line 55

**Comment by stelin** [comment]
已解决，更新版本，要求最新swoole版本
