### ISSUE TITLE
Bug:异常抛出问题

### ISSUE THREAD

**Issue by wvfeng** [swoft-cloud/swoft#970]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.5
| Swoole version      | 4.4.3
| PHP version         | 7.2

**Details**
![image](https://user-images.githubusercontent.com/33809027/64956117-703ce100-d8bc-11e9-84c3-0cdb1decf786.png)
文档中说明不会抛出的异常(`Swoft\Bean\Exception\ContainerException`)还在抛出

**Comment by stelin** [comment]
什么情况下抛出的

**Comment by stelin** [comment]
是真实运行抛出的么

**Comment by wvfeng** [comment]
不是真实抛出，而是提示抛出，例如使用`config`等全局函数时，如果不处理`ContainerException`或者再次往外抛出，那么编辑器会提示有异常未处理，如图：
![image](https://user-images.githubusercontent.com/33809027/65016321-88f9d500-d956-11e9-8e66-f46119720e67.png)
处理或者抛出后则正常：
![image](https://user-images.githubusercontent.com/33809027/65016359-a6c73a00-d956-11e9-90ff-c73517daf88e.png)

**Comment by inhere** [comment]
有部分方法 或者 函数没有移除到。2.0.6 再清理一些
