### ISSUE TITLE
PHP Fatal error:  Uncaught Swoft\Exception\SwoftException: context information has been lost of the coID  这个错误可以抛出到异常 

### ISSUE THREAD

**Issue by chenjing0521** [swoft-cloud/swoft#973]
这个错误每次都要到  vendor\swoft\log\src\Logger.php  中的addRecord  去打印$message参数,希望以后可以直接抛出

![image](https://user-images.githubusercontent.com/43941983/65053075-fb41d800-d99d-11e9-86a6-3e36a56248c0.png)

![image](https://user-images.githubusercontent.com/43941983/65053113-08f75d80-d99e-11e9-9a5a-60825ced77c3.png)

**Comment by stelin** [comment]
2.0.6 已经修复这个问题了，很快发版
