### ISSUE TITLE
建议：Rpc client 调用Rpc server端抛出Exception，自定义或者debug只显示抛出文字

### ISSUE THREAD

**Issue by FromChinaBoy** [swoft-cloud/swoft#975]
| Q                   | A
| ------------------- | -----
| Bug report?         | no
| Feature request?    | yes
| Swoft version       | 2.0.4-beta
| Swoole version      | 4.4.1 (by `php --ri swoole`)
| PHP version         | 7.2.8 (by `php -v`)
| Runtime environment | Mac

**Describe the bug**
![FnN7qj3MxRMZflqq7M6swqbShiqp](http://img.zzhpeng.cn/FnN7qj3MxRMZflqq7M6swqbShiqp)

暂时我这边会这样处理。。。
![FnpAE1IJG_uzKHRtopI1guD5LiMs](http://img.zzhpeng.cn/FnpAE1IJG_uzKHRtopI1guD5LiMs)

**Expected behavior**

**Screenshots**

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
// paste code
```

**Comment by stelin** [comment]
感谢反馈，我们优化下。

**Comment by stelin** [comment]
已修复 2.0.6
