### ISSUE TITLE
请问有没有使用协程封装好的elasticsearch client

### ISSUE THREAD

**Issue by sushaowei** [swoft-cloud/swoft#978]
请问有没有使用协程封装好的elasticsearch client

使用elasticsearch官方包会阻塞的吧

**Comment by huangzhhui** [comment]
@sushaowei 可以使用 https://github.com/hyperf-cloud/elasticsearch ，独立的一个组件，可以直接在 Swoft 上使用的，通过命令 `composer require hyperf/elasticsearch` 安装即可

**Comment by stelin** [comment]
@sushaowei 我们后续会支持。
