### ISSUE TITLE
Http 响应对象文件下载设置自定义响应头失败

### ISSUE THREAD

**Issue by yggo** [swoft-cloud/swoft#991]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | yes
| Swoft version       | 2.0.6
| Swoole version      | 4.4.5
| PHP version         | 7.3.9
| Runtime environment | CentOS Linux release 7.6.1810 (Core)

**Describe the bug**
```
Http 响应对象文件下载时设置自定义响应头失败
```

**Expected behavior**
```
可以正常输出自定义响应头
```

**Screenshots**

**Details**

> Describe what you are trying to achieve and what goes wrong.

```php
// paste output here
```

> Provide minimal script to reproduce the issue

```php
控制器类
return $response
            ->withHeader('Cache-Control', 'max-age=0')
            ->file(\alias('@runtime/1.apk'), "application/vnd.android.package-archive");
```

**Comment by ctfang** [comment]
临时解决

        $routes = Exec::bean(Postmen::class)->down();

        $json = json_encode($routes, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);

        return Context::get()
            ->getResponse()
            ->withContent($json)
            ->withHeader('Content-Type', "application/octet-stream")
            ->withHeader('Content-Disposition', 'attachment; filename=admin-api.json');
