### ISSUE TITLE
验证器能否实现存在则验证，不存在使用默认值

### ISSUE THREAD

**Issue by joewongex** [swoft-cloud/swoft#992]
业务里面经常有这样的场景：如果一个字段存在，则使用验证器验证它，如果不存在，则自动填充属性里面填写的默认值，**并且不去校验这个默认值**，但是目前2.x版本中的验证器似乎不能实现这样的需求。

**Comment by stelin** [comment]
你定义一个默认值，如果参数不存在，获取到的就是默认值
