### ISSUE TITLE
redis不支持georadius

### ISSUE THREAD

**Issue by ijisong** [swoft-cloud/swoft#993]
Redis command reconnect error(Method(GEORADIUS) is not supported!) At /root/apiv2/vendor/swoft/redis/src/Connection/Connection.php line 395

**Comment by stelin** [comment]
感谢反馈2.0.7 支持下

**Comment by sakuraovq** [comment]
感谢反馈2.0.7 支持下

**Comment by sakuraovq** [comment]
可以先使用 call 方法代替喔
