### ISSUE TITLE
不支持PHP7.3

### ISSUE THREAD

**Issue by id0612** [swoft-cloud/swoft#995]
暂时先通过3个问题说明与PHP7.3不兼容，建议给予支持，并尽量支持到PHP7.4，后续如有发现会尽量持续更新。（以下测试参考文档手动安装之后直接运行即可重现，无其它干扰，附件为依赖包信息）

问题1：
![image](https://user-images.githubusercontent.com/2449459/65414947-4e48de80-de27-11e9-940f-c866779d3a1e.png)

建议新版本删除：#!/usr/bin/env php，启用时已经指定了php命令，此行多余，还涉及到declare(strict_types=1)在新版本PHP中的约定。

问题2：(解决问题一之后方可重现)
![image](https://user-images.githubusercontent.com/2449459/65415120-ac75c180-de27-11e9-9078-8d41277a1df4.png)
经验证，在PHP7.2中无此问题（其它环境完全相同），在PHP7.3中，swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/Annotation/Target.php会被多次加载。

建议使用include_once加载文件

问题3：（尝试将vendor/composer/ClassLoader.php 444行改为include_once加载后）
![image](https://user-images.githubusercontent.com/2449459/65415355-2b6afa00-de28-11e9-9e32-b05a9c0a8f6c.png)
在PHP7.2中同样无此问题，且出现错误信息的打印需要等到接近10秒。

[composer_info.txt](https://github.com/swoft-cloud/swoft/files/3641501/composer_info.txt)

**Comment by inhere** [comment]
😄  不会吧，我本地开发机 php 7.3 刚出来就升级了。开发使用都没有问题啊！

**Comment by inhere** [comment]
你的系统信息呢？swoft、swoole版本是多少

**Comment by id0612** [comment]
**PHP 7.3.9** (cli) (built: Aug 30 2019 10:43:30) ( ZTS DEBUG )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
**Version => 4.4.6**
Built => Sep 23 2019 12:52:32
coroutine => enabled
debug => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1  11 Sep 2018
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

swoft,当前 master，2.0.1 2.0.5 2.0.6我都试过，问题同样。依赖包中有详细信息。

**Comment by inhere** [comment]
操作系统呢？

**Comment by id0612** [comment]
同一份代码，相同版本的扩展，php7.2运行就没问题。

Ubuntu 18.04.3 LTS \n \l

运行于Win10的WSL环境

**Comment by id0612** [comment]
附PHP编译命令，测试的两个版本都是如此。

./configure --prefix=/opt/php --with-config-file-path=/opt/php/etc --with-config-file-scan-dir=/opt/php/etc/conf.d \
--with-mysqli --with-pdo-mysql \
--with-gd --with-jpeg-dir --with-png-dir --with-freetype-dir \
--with-zlib --with-zlib-dir \
--with-openssl \
--with-curl \
--enable-mbstring \
--enable-fpm \
--enable-inline-optimization \
--enable-zip \
--enable-sockets \
--enable-pcntl --enable-maintainer-zts --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-shmop \
--enable-debug \
--without-pear

**Comment by id0612** [comment]
见鬼，头蒙了，我干嘛去修改：vendor/composer/ClassLoader.php，哈哈。不过问题2还是存在

继续验证是否与WSL有关，因为你们都说没遇到这个问题。

**Comment by id0612** [comment]
最新结果：在实体机运行的Ubuntu 18.04中，同样的方式编译PHP7.3，运行正常。但在WSL+PHP7.3环境中，require_once未发挥作用，导致文件重复加载，WSL+PHP7.2也正常，运行结果见附件。

![image](https://user-images.githubusercontent.com/2449459/65485153-9de4e400-ded3-11e9-9ebb-640ed3ea64d4.png)
[PHP7.2执行结果.txt](https://github.com/swoft-cloud/swoft/files/3645467/PHP7.2.txt)
[PHP7.3执行结果.txt](https://github.com/swoft-cloud/swoft/files/3645468/PHP7.3.txt)


相同环境及当前swoft根目录中验证 require_once 的作用，却是有效的，如图所示：
![image](https://user-images.githubusercontent.com/2449459/65485328-24012a80-ded4-11e9-8797-5189405dc8fc.png)

运行环境：Win10启用WSL，安装 Ubuntu（18.04），通过之前提供的编译命令安装PHP 7.3.9

**Comment by id0612** [comment]
另一个测试，在同样的位置，引用一个普通的文件，比如之前提到的bb.php，运行结果，多次引用同样只打印一次时间戳，但如果引用的框架中已经加载的其它文件，都会被重复加载。如图所示。
![image](https://user-images.githubusercontent.com/2449459/65485953-c968ce00-ded5-11e9-99c1-9e01f1b5f9a6.png)
![image](https://user-images.githubusercontent.com/2449459/65486224-7e9b8600-ded6-11e9-8e88-ec7db59ac8af.png)

运行结果：
![image](https://user-images.githubusercontent.com/2449459/65486377-dafea580-ded6-11e9-9ec3-7db7ddc13dc1.png)
