### ISSUE TITLE
Bug: 实体类Getters中使用其他实体类启动报错

### ISSUE THREAD

**Issue by wvfeng** [swoft-cloud/swoft#996]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.6
| Swoole version      | 4.4.5
| PHP version         | 7.2.20
| Runtime environment | Ubuntu 19.04

**Describe the bug**
实体类Getters中使用其他实体类启动报错

**Expected behavior**
希望可以在实体类Getters使用其他实体类

**Screenshots**
![image](https://user-images.githubusercontent.com/33809027/65418191-7be55600-de2e-11e9-95aa-61b19100a197.png)

```php
    /**
     * @return string
     */
    public function getMaterial(): ?string
    {
        return Resource::find($this->material)->getPath();
    }
```

**Comment by sakuraovq** [comment]
这个不是 实体报的错  需要改下 入口文件 看升级公告吧

**Comment by inhere** [comment]
你是在启动的哪个环节操作了数据库？

**Comment by wvfeng** [comment]
@sakuraovq 你说的升级公告具体是指的哪个？文档中没有发现，还有关于入口文件一共就十几行代码，已经对比了我的和最新的是一致的。
@inhere 启动的环节没有操作数据库，所以为什么会出现这个问题我也很奇怪，我猜测和数据库的事件监听有关，一会试试删掉事件监听还有没有问题

**Comment by wvfeng** [comment]
@inhere 经过测试发现和数据库事件监听没有关系，这个问题应该发生在更早的时候，我猜测是BeanProcessor初始化Bean的时候发生的，因为我手动把这个Getters改为私有方法后出现了这个情况：
![image](https://user-images.githubusercontent.com/33809027/65566348-1657ad80-df85-11e9-97ab-b7a3c2ce5219.png)

**Comment by sakuraovq** [comment]
getter 和 setter 必须是公开的 属性是私有
