### ISSUE TITLE
http-server停止超时

### ISSUE THREAD

**Issue by ChangeChe** [swoft-cloud/swoft#998]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.5
| Swoole version      | v4.4.3
| PHP version         | 7.2.16
| Runtime environment | Docker

**Describe the bug**
使用http:start -d, 或者http:restart后，服务能正常启动，但是调用http:stop或者再次调用http:restart后, 会提示停止超时
```
Stopping ................................
Stop the swoft-http(PID:28352) failed(timeout:30s)!
[ERROR] Stop the old server failed!
```
但是此时通过ps去查看进程，会发现服务已经被关闭了的。。。

**Comment by inhere** [comment]
你升级下swoole版本再试试呢？

**Comment by ChangeChe** [comment]
使用4.4.6的swoole, 也是相同的结果，如果你那边不能重现的话，可能是自身环境的问题吧

**Comment by inhere** [comment]
docker 里面是什么系统环境？
你写个简单的demo http-server试试呢？

**Comment by ChangeChe** [comment]
系统：Linux 871a4e7355f8 4.14.104-boot2docker #1 SMP Thu Feb 28 20:58:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
查了下，原来的master进程变成了僵尸进程

**Comment by Uestczhouxin** [comment]
> 查验了下，是本地docker环境的问题。

您好，请问下docker什么环节导致的呢，我也遇到这个问题了

**Comment by cooooommon** [comment]
你好，现在v2.0.9现在依然存在这个问题，环境是lnmp,centos 7.2
