### ISSUE TITLE
数据库操作当selectRaw中有别名出现，并以别名排序时，报错。

### ISSUE THREAD

**Issue by RingRan** [swoft-cloud/swoft#999]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | 2.0.3
| Swoole version      | 4.3.5 (by `php --ri swoole`)
| PHP version         | 7.2.20 (by `php -v`)
| Runtime environment | Docker etc.

**Describe the bug**
数据库操作当selectRaw中有别名出现，并以别名排序时，报字段不存在错误。

**Expected behavior**
不应该报错，或者count时，不应该出现order by

**Details**

```php
$paginate = User::query()
                ->select('age as age2', 'count(*) as countNumber')
                ->where('id', '>', 1)
                ->groupBy('age')
                ->orderBy('countNumber')
                ->count();
```

输出的sql语句：
```mysql
select count(*) as aggregate from `user` where `id` > ? group by `age` order by `countNumber` asc6s
```

**Comment by sakuraovq** [comment]
这样使用是有问题的

**Comment by sakuraovq** [comment]
```php
$paginate = User::query()
                ->selectRaw('age as age2', 'count(*) as countNumber')
                ->where('id', '>', 1)
                ->groupBy('age')
                ->orderBy('countNumber')
                ->get();
```
改成这样的
